<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Into the Unknown - Simulating a Bionomial Test</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Into the Unknown</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">Stephen Barrie</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml" rel="" target=""><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Stephen137" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/sjbarrie" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Simulating a Bionomial Test</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#summarizing-the-sample" id="toc-summarizing-the-sample" class="nav-link active" data-scroll-target="#summarizing-the-sample">Summarizing the Sample</a></li>
  <li><a href="#simulating-randomness" id="toc-simulating-randomness" class="nav-link" data-scroll-target="#simulating-randomness">Simulating Randomness</a></li>
  <li><a href="#simulating-the-null-distribution-i" id="toc-simulating-the-null-distribution-i" class="nav-link" data-scroll-target="#simulating-the-null-distribution-i">Simulating the Null Distribution I</a></li>
  <li><a href="#simulating-the-null-distribution-ii" id="toc-simulating-the-null-distribution-ii" class="nav-link" data-scroll-target="#simulating-the-null-distribution-ii">Simulating the Null Distribution II</a></li>
  <li><a href="#inspecting-the-null-distribution" id="toc-inspecting-the-null-distribution" class="nav-link" data-scroll-target="#inspecting-the-null-distribution">Inspecting the Null Distribution</a></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals">Confidence Intervals</a></li>
  <li><a href="#calculating-a-one-sided-p-value" id="toc-calculating-a-one-sided-p-value" class="nav-link" data-scroll-target="#calculating-a-one-sided-p-value">Calculating a One-Sided P-Value</a></li>
  <li><a href="#calculating-a-two-sided-p-value" id="toc-calculating-a-two-sided-p-value" class="nav-link" data-scroll-target="#calculating-a-two-sided-p-value">Calculating a Two-Sided P-Value</a></li>
  <li><a href="#writing-a-binomial-test-function" id="toc-writing-a-binomial-test-function" class="nav-link" data-scroll-target="#writing-a-binomial-test-function">Writing a Binomial Test Function</a></li>
  <li><a href="#binomial-testing-with-scipy" id="toc-binomial-testing-with-scipy" class="nav-link" data-scroll-target="#binomial-testing-with-scipy">Binomial Testing with SciPy</a></li>
  <li><a href="#review" id="toc-review" class="nav-link" data-scroll-target="#review">Review</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_1samp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this lesson, we will walk through a simulation of a binomial hypothesis test in Python. Binomial tests are useful for comparing the frequency of some outcome in a sample to the expected probability of that outcome. For example, if we expect 90% of ticketed passengers to show up for their flight but only 80 of 100 ticketed passengers actually show up, we could use a binomial test to understand whether 80 is significantly different from 90.</p>
<p>Binomial tests are similar to one-sample t-tests in that they test a sample statistic against some population-level expectation. The difference is that:</p>
<ul>
<li>binomial tests are used for <code>binary categorical data</code> to compare a sample <code>frequency</code> to an expected population-level probability</li>
<li>one-sample t-tests are used for <code>quantitative</code> data to compare a sample <code>mean</code> to an expected population mean.</li>
</ul>
<p>In Python, as in many other programming languages used for statistical computing, there are a number of libraries and functions that allow a data scientist to run a hypothesis test in a single line of code. However, a data scientist will be much more likely to spot and fix potential errors and interpret results correctly if they have a conceptual understanding of how these functions work. To that end, this lesson will help you build your own conceptual understanding!</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>monthly_report <span class="op">=</span> pd.read_csv(<span class="st">'data/monthly_report.csv'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>monthly_report.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">timestamp</th>
<th data-quarto-table-cell-role="th">purchase</th>
<th data-quarto-table-cell-role="th">item</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>17/01/2020 17:23</td>
<td>y</td>
<td>cue cards - love actually</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>25/01/2020 17:09</td>
<td>n</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>25/01/2020 05:22</td>
<td>n</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>18/01/2020 04:33</td>
<td>y</td>
<td>t-rex - jurassic park</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>24/01/2020 17:24</td>
<td>n</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<section id="summarizing-the-sample" class="level3">
<h3 class="anchored" data-anchor-id="summarizing-the-sample">Summarizing the Sample</h3>
<p>The marketing department at Live-it-LIVE reports that, during this time of year, about 10% of visitors to Live-it-LIVE.com make a purchase.</p>
<p>The monthly report shows every visitor to the site and whether or not they made a purchase. The checkout page had a small bug this month, so the business department wants to know whether the purchase rate dipped below expectation. They’ve asked us to investigate this question.</p>
<p>In order to run a hypothesis test to address this, we’ll first need to know two things from the data:</p>
<ul>
<li>The number of people who visited the website</li>
<li>The number of people who made a purchase on the website</li>
</ul>
<p>Assuming each row of our dataset represents a unique site visitor, we can calculate the number of people who visited the website by finding the number of rows in the data frame. We can then find the number who made a purchase by using a conditional statement to add up the total number of rows where a purchase was made.</p>
<p>For example, suppose that the dataset candy contains a column named chocolate with ‘yes’ recorded for every candy that has chocolate in it and ‘no’ otherwise. The following code calculates the sample size (the number of candies) and the number of those candies that contain chocolate:</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">## sample size (number of rows): </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="bu">len</span>(monthly_report)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sample_size)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>500</code></pre>
</div>
</div>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">## number purchases: </span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>num_purchased <span class="op">=</span> np.<span class="bu">sum</span>(monthly_report.purchase <span class="op">==</span> <span class="st">'y'</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(num_purchased)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>41</code></pre>
</div>
</div>
</section>
<section id="simulating-randomness" class="level3">
<h3 class="anchored" data-anchor-id="simulating-randomness">Simulating Randomness</h3>
<p>In the last exercise, we calculated that there were 500 site visitors to live-it-LIVE.com this month and 41 of them made a purchase. In comparison, if each of the 500 visitors had a 10% chance of making a purchase, we would expect around 50 of those visitors to buy something. Is 41 different enough from 50 that we should question whether this months’ site visitors really had a 10% chance of making a purchase?</p>
<p>To conceptualize why our expectation (50) and observation (41) might not be equal — EVEN IF there was no dip in the purchase probability — let’s turn to a common probability example: flipping a fair coin. We can simulate a coin flip in Python using the <code>numpy.random.choice()</code> function:</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>flip <span class="op">=</span> np.random.choice([<span class="st">'heads'</span>, <span class="st">'tails'</span>], size<span class="op">=</span><span class="dv">1</span>, p<span class="op">=</span>[<span class="fl">0.5</span>, <span class="fl">0.5</span>])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(flip) </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co">## output is either ['heads'] or ['tails']</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['heads']</code></pre>
</div>
</div>
<p>If we run this code (or flip a real coin) a few times, we’ll find that — just like we can’t know ahead of time whether any single visitor to Live-it-LIVE.com will make a purchase — we can’t predict the outcome of any individual coin flip.</p>
<p>If we flip a fair coin 10 times in a row, we expect about 5 of those coins to come up heads (50%). We can simulate this in python by changing the size parameter of <code>numpy.random.choice()</code>:</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>flip <span class="op">=</span> np.random.choice([<span class="st">'heads'</span>, <span class="st">'tails'</span>], size<span class="op">=</span><span class="dv">10</span>, p<span class="op">=</span>[<span class="fl">0.5</span>, <span class="fl">0.5</span>])</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(flip)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['heads' 'tails' 'heads' 'heads' 'tails' 'heads' 'heads' 'tails' 'tails'
 'heads']</code></pre>
</div>
</div>
<p>If you try this yourself, it’s perfectly reasonable that you’ll get only four heads, or maybe six or seven! Because this is a <code>random</code> process, we can’t guarantee that exactly half of our coin flips will come up heads. Similarly, even if each Live-it-LIVE visitor has a 10% chance of making a purchase, that doesn’t mean we expect exactly 10% to do so in any given sample.</p>
<blockquote class="blockquote">
<p>Q1. use the random.choice() function from NumPy to simulate a single visitor to Live-it-LIVE.com, who has a 10% chance of making a purchase (p=0.1). Save the outcome as a variable named <code>one_visitor</code> and print it. If the visitor made a purchase, the value of one_visitor should be [‘y’]; if they did not make a purchase, it should be [‘n’] (just like in the original data!).</p>
</blockquote>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>one_visitor <span class="op">=</span> np.random.choice([<span class="st">'y'</span>, <span class="st">'n'</span>], size<span class="op">=</span><span class="dv">1</span>, p<span class="op">=</span>[<span class="fl">0.1</span>, <span class="fl">0.9</span>])</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(one_visitor) </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co">## output is either ['y'] or ['n']</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['n']</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q2. ow, create a new list named <code>simulated_monthly_visitors</code>, which contains the randomly-generated outcomes for 500 visitors to Live-it-LIVE.com (still with a 10% chance of a purchase). Print <code>simulated_monthly_visitors</code> out. Do you see any visitors in this list who made a purchase?</p>
</blockquote>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>simulated_monthly_visitors <span class="op">=</span> np.random.choice([<span class="st">'y'</span>, <span class="st">'n'</span>], size<span class="op">=</span><span class="dv">500</span>, p<span class="op">=</span>[<span class="fl">0.1</span>, <span class="fl">0.9</span>])</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(simulated_monthly_visitors) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>['n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'y' 'n' 'n' 'y' 'y' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'n' 'y'
 'n' 'n' 'y' 'y' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'y'
 'y' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'y' 'y' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n'
 'n' 'y' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'y' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'y' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'y' 'n' 'n' 'y' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n'
 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'n' 'y' 'n' 'y' 'n']</code></pre>
</div>
</div>
</section>
<section id="simulating-the-null-distribution-i" class="level3">
<h3 class="anchored" data-anchor-id="simulating-the-null-distribution-i">Simulating the Null Distribution I</h3>
<p>The first step in running a hypothesis test is to form a null hypothesis. For the question of whether the purchase rate at Live-it-LIVE.com was different from 10% this month, the null hypothesis describes a world in which the true probability of a visitor making a purchase was exactly 10%, but by random chance, we observed that only 41 visitors (8.2%) made a purchase.</p>
<p>Let’s return to the coin flip example from the previous exercise. We can simulate 10 coin flips and print out the number of those flips that came up heads using the following code:</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>flips <span class="op">=</span> np.random.choice([<span class="st">'heads'</span>, <span class="st">'tails'</span>], size<span class="op">=</span><span class="dv">10</span>, p<span class="op">=</span>[<span class="fl">0.5</span>, <span class="fl">0.5</span>])</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>num_heads <span class="op">=</span> np.<span class="bu">sum</span>(flips <span class="op">==</span> <span class="st">'heads'</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(num_heads)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>4</code></pre>
</div>
</div>
<p>If we run this code a few times, we’ll likely see different results each time. This will give us get a sense for the range in the number of heads that could occur by random chance, even if the coin is fair. We’re more likely to see numbers like four, five, or six, but maybe we’ll see something more extreme every once in a while — ten heads in a row, or even zero!</p>
<blockquote class="blockquote">
<p>Q3. Calculate the number of those simulated visitors who made a purchase. Save the result as <code>num_purchased</code> and print it out.</p>
</blockquote>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>simulated_monthly_visitors <span class="op">=</span> np.random.choice([<span class="st">'y'</span>, <span class="st">'n'</span>], size<span class="op">=</span><span class="dv">500</span>, p<span class="op">=</span>[<span class="fl">0.1</span>, <span class="fl">0.9</span>])</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>num_purchased <span class="op">=</span> np.<span class="bu">sum</span>(simulated_monthly_visitors <span class="op">==</span> <span class="st">'y'</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(num_purchased)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>44</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q4. Inspect the value of <code>num_purchased</code> from the previous instruction. Is it close to 50 (which is what we would expect for a purchase probability of 10%)? Less than? Greater than? Now try pressing “Run” a few more times and see what other values of num_purchased you observe. What’s the farthest number from 50 that you observe after pressing “Run” 5 times?</p>
</blockquote>
<p>The first number observed was 52, which is close to 50. The next values were 41, 36, 52, and 44.</p>
</section>
<section id="simulating-the-null-distribution-ii" class="level3">
<h3 class="anchored" data-anchor-id="simulating-the-null-distribution-ii">Simulating the Null Distribution II</h3>
<p>In the last exercise, we simulated a random sample of 500 visitors, where each visitor had a 10% chance of making a purchase. When we pressed “Run” a few times, we saw that the number of purchases varied from sample to sample, but was around 50.</p>
<p>Similarly, we simulated a single random sample of 10 coin flips, where each flip had a 50% chance of coming up heads. We saw that the number of simulated heads was not necessarily 5, but somewhere around 5.</p>
<p>By running the same simulated experiment many times, we can get a sense for how much a particular outcome (like the number of purchases, or heads) varies by random chance. Consider the following code:</p>
<div class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>outcomes <span class="op">=</span> []</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10000</span>): </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    flips <span class="op">=</span> np.random.choice([<span class="st">'heads'</span>, <span class="st">'tails'</span>], size<span class="op">=</span><span class="dv">10</span>, p<span class="op">=</span>[<span class="fl">0.5</span>, <span class="fl">0.5</span>])</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    num_heads <span class="op">=</span> np.<span class="bu">sum</span>(flips <span class="op">==</span> <span class="st">'heads'</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    outcomes.append(num_heads)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(outcomes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[6, 5, 4, 5, 6, 5, 9, 3, 4, 6, 7, 7, 5, 7, 4, 6, 6, 7, 5, 3, 6, 5, 4, 7, 5, 2, 7, 6, 3, 7, 7, 5, 6, 5, 3, 4, 2, 6, 4, 6, 5, 6, 1, 4, 4, 4, 3, 6, 2, 3, 4, 5, 8, 5, 6, 2, 7, 3, 7, 4, 5, 5, 2, 4, 6, 4, 6, 4, 8, 6, 4, 5, 7, 4, 4, 6, 4, 5, 9, 4, 3, 4, 5, 5, 3, 8, 6, 8, 6, 6, 3, 5, 5, 5, 4, 3, 5, 4, 6, 7, 5, 3, 5, 7, 6, 5, 6, 7, 6, 3, 4, 4, 5, 5, 4, 5, 6, 5, 6, 5, 4, 8, 4, 3, 5, 6, 4, 7, 5, 6, 5, 6, 4, 6, 6, 5, 9, 6, 4, 2, 3, 2, 5, 6, 4, 4, 2, 4, 5, 6, 3, 5, 6, 7, 7, 6, 3, 5, 6, 6, 5, 6, 6, 7, 1, 8, 7, 5, 7, 8, 5, 6, 6, 6, 5, 6, 4, 5, 4, 4, 8, 8, 4, 5, 4, 5, 4, 6, 2, 6, 7, 6, 6, 7, 7, 5, 5, 6, 3, 6, 4, 6, 4, 4, 5, 3, 5, 5, 4, 5, 5, 8, 7, 5, 6, 7, 2, 3, 5, 4, 4, 4, 5, 6, 4, 5, 7, 7, 6, 3, 4, 5, 6, 5, 7, 7, 6, 5, 3, 4, 8, 2, 4, 4, 4, 7, 4, 6, 5, 3, 6, 5, 6, 6, 5, 6, 5, 4, 5, 7, 5, 3, 4, 3, 3, 3, 4, 5, 4, 4, 1, 5, 4, 4, 0, 5, 4, 4, 6, 6, 6, 6, 4, 4, 5, 4, 5, 6, 6, 7, 7, 6, 5, 5, 4, 5, 5, 5, 5, 7, 5, 6, 3, 5, 4, 4, 4, 6, 4, 7, 3, 5, 6, 4, 7, 6, 5, 7, 6, 4, 4, 3, 5, 6, 4, 4, 5, 4, 5, 5, 5, 4, 8, 6, 6, 7, 5, 5, 6, 5, 7, 6, 5, 6, 7, 7, 6, 6, 7, 6, 3, 6, 5, 5, 2, 3, 2, 6, 4, 5, 7, 2, 5, 6, 5, 5, 5, 3, 4, 8, 6, 9, 6, 4, 5, 6, 5, 3, 1, 4, 7, 5, 6, 3, 2, 6, 3, 3, 3, 8, 5, 5, 4, 8, 6, 2, 4, 7, 3, 5, 6, 5, 4, 5, 4, 2, 6, 4, 5, 6, 5, 3, 6, 6, 7, 5, 4, 7, 5, 7, 6, 6, 5, 5, 4, 4, 5, 9, 6, 5, 2, 5, 7, 3, 3, 6, 5, 5, 6, 7, 5, 3, 6, 7, 5, 4, 5, 6, 5, 5, 6, 6, 7, 5, 6, 4, 4, 4, 6, 7, 6, 3, 2, 4, 5, 4, 5, 5, 5, 7, 5, 4, 3, 2, 6, 3, 5, 5, 6, 5, 4, 6, 4, 4, 5, 4, 4, 2, 3, 6, 6, 4, 4, 4, 6, 8, 6, 6, 7, 5, 3, 3, 3, 2, 3, 7, 7, 5, 5, 6, 8, 7, 5, 6, 7, 4, 3, 3, 3, 4, 4, 3, 6, 5, 6, 6, 4, 6, 4, 5, 6, 9, 5, 7, 4, 3, 8, 6, 6, 2, 8, 6, 3, 5, 3, 3, 3, 5, 7, 6, 6, 7, 3, 5, 5, 2, 4, 5, 6, 6, 4, 4, 6, 6, 4, 4, 5, 5, 6, 7, 5, 6, 7, 5, 3, 6, 4, 4, 7, 3, 4, 7, 5, 6, 8, 5, 5, 8, 4, 6, 8, 6, 4, 6, 5, 3, 6, 4, 4, 4, 6, 6, 4, 8, 3, 6, 8, 5, 5, 5, 6, 4, 5, 4, 3, 6, 6, 6, 3, 6, 5, 3, 4, 5, 6, 4, 4, 6, 3, 5, 3, 5, 4, 4, 7, 4, 7, 7, 6, 5, 5, 7, 5, 5, 5, 5, 8, 4, 5, 9, 6, 3, 3, 6, 6, 4, 3, 6, 4, 4, 1, 6, 2, 7, 5, 4, 7, 6, 5, 5, 3, 8, 7, 4, 6, 6, 5, 6, 7, 6, 6, 3, 5, 4, 6, 3, 5, 6, 5, 5, 6, 4, 5, 3, 7, 5, 4, 6, 5, 7, 5, 4, 6, 5, 5, 5, 6, 5, 3, 7, 3, 5, 4, 5, 4, 7, 1, 5, 5, 8, 4, 4, 7, 6, 3, 4, 3, 6, 7, 7, 4, 6, 6, 5, 3, 7, 7, 5, 3, 4, 1, 5, 5, 2, 5, 4, 6, 4, 3, 6, 5, 4, 7, 5, 5, 3, 6, 7, 6, 8, 6, 5, 5, 6, 7, 5, 4, 7, 5, 2, 6, 3, 4, 4, 4, 5, 3, 6, 4, 4, 4, 3, 5, 2, 4, 5, 6, 4, 4, 7, 5, 3, 2, 5, 4, 7, 5, 6, 4, 7, 6, 7, 8, 5, 4, 4, 3, 3, 6, 2, 5, 4, 3, 6, 5, 7, 2, 3, 3, 5, 4, 4, 5, 4, 6, 6, 3, 5, 3, 3, 6, 6, 7, 4, 4, 2, 5, 5, 6, 5, 3, 7, 6, 4, 6, 5, 5, 6, 4, 5, 3, 6, 3, 5, 4, 4, 4, 4, 6, 3, 3, 4, 4, 4, 9, 6, 5, 4, 4, 6, 6, 6, 5, 6, 4, 5, 3, 4, 6, 4, 5, 3, 6, 5, 5, 5, 5, 8, 6, 4, 5, 5, 6, 6, 6, 4, 4, 8, 5, 5, 4, 3, 7, 6, 5, 5, 8, 7, 6, 5, 5, 7, 3, 2, 5, 6, 3, 8, 4, 1, 4, 5, 7, 5, 8, 8, 3, 5, 3, 4, 4, 2, 5, 6, 3, 3, 6, 4, 5, 6, 4, 6, 7, 6, 5, 4, 5, 5, 5, 3, 6, 2, 3, 7, 4, 4, 6, 3, 3, 6, 4, 4, 8, 4, 5, 3, 3, 6, 6, 7, 5, 8, 2, 4, 6, 6, 3, 5, 4, 6, 7, 5, 3, 5, 6, 6, 6, 5, 3, 6, 4, 6, 5, 6, 6, 6, 5, 3, 5, 2, 8, 6, 4, 4, 4, 9, 7, 5, 6, 3, 4, 5, 7, 4, 5, 6, 4, 5, 5, 6, 3, 6, 1, 2, 5, 2, 7, 7, 5, 3, 5, 3, 4, 7, 5, 5, 3, 6, 5, 6, 5, 4, 5, 4, 5, 3, 7, 4, 7, 3, 7, 5, 6, 5, 3, 3, 4, 6, 3, 5, 4, 5, 7, 4, 4, 3, 5, 8, 9, 4, 5, 6, 3, 5, 4, 7, 6, 6, 7, 6, 4, 6, 6, 3, 6, 4, 5, 3, 6, 3, 3, 3, 3, 8, 3, 2, 3, 2, 7, 5, 5, 4, 3, 4, 4, 4, 8, 5, 4, 3, 5, 5, 6, 7, 7, 5, 1, 6, 4, 5, 5, 8, 5, 5, 2, 5, 5, 8, 4, 6, 3, 5, 7, 4, 5, 2, 4, 6, 3, 5, 4, 5, 6, 3, 4, 6, 4, 6, 3, 3, 6, 6, 4, 4, 3, 2, 3, 4, 6, 3, 5, 5, 6, 4, 5, 4, 5, 4, 2, 5, 5, 4, 6, 6, 6, 6, 3, 7, 5, 4, 3, 6, 6, 4, 8, 7, 2, 5, 5, 5, 6, 6, 4, 6, 6, 5, 3, 2, 7, 5, 3, 3, 6, 5, 4, 7, 7, 5, 3, 3, 4, 4, 4, 3, 7, 3, 7, 5, 8, 4, 4, 4, 3, 2, 5, 6, 6, 4, 4, 6, 4, 6, 7, 5, 7, 8, 5, 4, 5, 5, 4, 4, 6, 4, 7, 4, 6, 4, 5, 3, 7, 6, 5, 4, 5, 5, 6, 4, 4, 5, 4, 6, 6, 4, 3, 6, 7, 3, 6, 5, 3, 2, 3, 5, 5, 3, 3, 2, 7, 4, 5, 5, 6, 3, 5, 6, 7, 7, 5, 4, 6, 4, 7, 9, 6, 5, 5, 6, 7, 2, 7, 4, 6, 5, 7, 5, 6, 9, 4, 5, 3, 4, 4, 6, 8, 5, 3, 4, 3, 5, 4, 5, 4, 3, 6, 3, 5, 2, 6, 1, 4, 4, 3, 5, 4, 5, 7, 5, 5, 5, 6, 6, 5, 4, 5, 4, 9, 6, 5, 3, 7, 4, 6, 6, 6, 5, 6, 6, 3, 6, 6, 2, 4, 6, 4, 5, 7, 4, 2, 3, 5, 7, 2, 4, 4, 4, 4, 7, 6, 5, 2, 8, 7, 5, 4, 4, 3, 5, 6, 5, 4, 7, 5, 7, 6, 3, 8, 4, 6, 5, 5, 5, 3, 5, 5, 5, 3, 7, 6, 3, 6, 5, 5, 6, 3, 6, 7, 7, 4, 6, 4, 5, 6, 5, 4, 6, 5, 5, 5, 5, 4, 5, 5, 6, 5, 5, 5, 4, 8, 5, 5, 7, 7, 5, 4, 5, 6, 6, 5, 8, 5, 6, 2, 8, 4, 4, 3, 5, 5, 5, 6, 2, 4, 9, 6, 7, 3, 4, 5, 5, 6, 4, 1, 5, 7, 4, 5, 4, 6, 8, 6, 5, 4, 5, 7, 3, 5, 7, 6, 5, 6, 2, 5, 8, 7, 6, 6, 5, 2, 7, 3, 7, 6, 5, 5, 6, 3, 4, 6, 7, 7, 5, 5, 4, 7, 8, 5, 5, 5, 6, 7, 4, 5, 3, 6, 5, 5, 6, 8, 3, 5, 6, 4, 4, 5, 5, 5, 3, 5, 2, 6, 1, 4, 6, 5, 6, 2, 6, 5, 7, 5, 6, 7, 4, 5, 6, 4, 7, 5, 3, 6, 5, 6, 6, 5, 8, 6, 7, 4, 7, 5, 4, 6, 5, 5, 6, 4, 2, 4, 8, 6, 5, 7, 5, 7, 6, 5, 4, 6, 2, 6, 4, 7, 4, 4, 5, 3, 6, 5, 6, 5, 5, 4, 5, 3, 2, 4, 4, 6, 5, 5, 5, 6, 7, 3, 5, 5, 3, 5, 7, 5, 6, 7, 5, 6, 6, 5, 4, 5, 2, 6, 3, 3, 2, 4, 4, 3, 6, 7, 6, 6, 5, 5, 7, 4, 3, 3, 5, 4, 5, 4, 4, 4, 5, 4, 3, 3, 6, 5, 4, 3, 6, 5, 6, 7, 7, 5, 5, 6, 3, 6, 6, 5, 2, 3, 6, 7, 4, 5, 5, 6, 7, 4, 7, 6, 6, 4, 4, 3, 5, 5, 6, 3, 6, 6, 3, 2, 5, 2, 3, 7, 4, 5, 7, 7, 6, 5, 8, 4, 5, 3, 5, 5, 3, 4, 7, 6, 1, 5, 6, 6, 8, 1, 8, 5, 5, 7, 4, 6, 5, 4, 5, 5, 7, 8, 6, 4, 4, 6, 5, 7, 7, 6, 8, 6, 6, 3, 2, 5, 5, 4, 6, 9, 2, 5, 3, 4, 6, 3, 4, 8, 5, 6, 6, 6, 4, 6, 5, 7, 3, 5, 6, 4, 7, 5, 7, 6, 5, 4, 5, 5, 5, 4, 5, 2, 5, 7, 4, 6, 4, 4, 5, 6, 5, 6, 3, 7, 5, 5, 3, 4, 7, 3, 5, 7, 8, 5, 5, 5, 6, 5, 6, 6, 4, 6, 8, 3, 6, 5, 1, 5, 6, 4, 8, 2, 5, 5, 5, 4, 4, 7, 5, 7, 6, 4, 7, 3, 2, 4, 4, 4, 5, 6, 6, 7, 3, 2, 6, 3, 4, 4, 2, 3, 5, 5, 6, 4, 7, 1, 3, 6, 6, 4, 6, 5, 4, 3, 5, 3, 8, 5, 3, 6, 4, 7, 7, 8, 2, 5, 5, 4, 6, 3, 5, 2, 4, 8, 5, 7, 4, 6, 5, 4, 5, 4, 6, 3, 6, 3, 4, 5, 7, 3, 4, 4, 3, 5, 6, 2, 8, 4, 5, 8, 3, 7, 5, 6, 5, 7, 7, 6, 5, 5, 4, 3, 3, 4, 6, 3, 4, 6, 5, 5, 5, 6, 5, 3, 4, 7, 3, 4, 6, 4, 2, 6, 5, 4, 5, 5, 4, 7, 5, 5, 5, 3, 5, 6, 3, 7, 7, 7, 7, 5, 7, 6, 5, 4, 6, 3, 7, 4, 3, 4, 7, 6, 5, 4, 7, 3, 3, 3, 5, 6, 5, 7, 6, 6, 6, 3, 7, 6, 5, 6, 6, 6, 4, 4, 7, 7, 4, 4, 3, 5, 7, 6, 5, 2, 7, 5, 9, 5, 6, 7, 5, 6, 7, 8, 4, 6, 7, 4, 8, 7, 5, 5, 8, 4, 6, 3, 5, 5, 5, 6, 5, 4, 2, 6, 3, 5, 6, 4, 1, 6, 4, 3, 5, 4, 3, 4, 6, 5, 8, 3, 5, 9, 3, 5, 7, 7, 4, 6, 4, 6, 5, 5, 5, 4, 5, 6, 8, 6, 4, 5, 6, 4, 2, 2, 2, 6, 5, 7, 6, 4, 5, 4, 5, 4, 4, 6, 6, 3, 3, 5, 7, 4, 7, 6, 4, 4, 7, 7, 2, 5, 4, 5, 6, 3, 5, 4, 2, 3, 3, 4, 7, 3, 7, 1, 5, 5, 7, 7, 5, 3, 4, 5, 6, 6, 7, 4, 4, 4, 4, 4, 5, 6, 7, 6, 4, 6, 7, 7, 6, 6, 2, 6, 7, 8, 7, 8, 4, 3, 4, 4, 4, 5, 6, 5, 6, 6, 4, 4, 7, 3, 7, 5, 5, 5, 7, 4, 4, 5, 4, 2, 8, 9, 4, 4, 3, 0, 3, 4, 4, 8, 6, 4, 8, 4, 3, 4, 8, 5, 5, 5, 10, 4, 3, 2, 4, 6, 7, 6, 5, 6, 5, 5, 5, 4, 8, 4, 7, 5, 4, 8, 8, 4, 5, 5, 5, 5, 7, 5, 6, 5, 5, 4, 4, 7, 7, 3, 5, 1, 5, 3, 3, 3, 4, 7, 6, 8, 3, 6, 7, 4, 6, 4, 7, 4, 6, 6, 5, 7, 2, 5, 3, 3, 4, 4, 6, 4, 7, 7, 5, 4, 4, 7, 6, 2, 2, 3, 3, 5, 6, 5, 4, 7, 6, 6, 4, 5, 6, 6, 5, 5, 7, 6, 4, 6, 4, 3, 5, 4, 8, 4, 5, 5, 8, 9, 4, 4, 6, 5, 4, 5, 5, 5, 6, 4, 2, 5, 5, 7, 4, 5, 3, 6, 6, 5, 5, 8, 6, 4, 4, 4, 3, 6, 4, 6, 4, 5, 3, 5, 3, 5, 6, 4, 5, 4, 4, 4, 3, 7, 5, 6, 7, 5, 5, 7, 4, 4, 3, 3, 2, 6, 5, 8, 3, 5, 6, 5, 7, 4, 4, 6, 6, 3, 7, 4, 4, 5, 2, 6, 7, 7, 4, 1, 6, 6, 2, 6, 5, 4, 5, 5, 5, 5, 5, 3, 7, 3, 5, 3, 2, 4, 7, 7, 7, 5, 6, 3, 4, 4, 6, 5, 6, 7, 8, 4, 3, 4, 6, 5, 7, 4, 5, 5, 6, 6, 6, 8, 4, 4, 7, 6, 4, 7, 4, 5, 7, 5, 6, 7, 4, 6, 4, 8, 5, 3, 5, 4, 7, 5, 7, 6, 4, 7, 3, 4, 5, 5, 5, 7, 2, 3, 5, 7, 5, 6, 6, 4, 4, 3, 5, 4, 2, 7, 7, 6, 8, 7, 5, 4, 7, 6, 6, 4, 8, 2, 7, 7, 3, 6, 7, 3, 5, 7, 6, 7, 6, 5, 4, 5, 6, 6, 6, 2, 4, 1, 5, 5, 3, 5, 4, 3, 6, 7, 3, 5, 4, 6, 8, 6, 6, 7, 5, 6, 5, 6, 7, 6, 5, 8, 6, 6, 5, 6, 4, 4, 5, 7, 5, 4, 7, 4, 3, 6, 5, 5, 6, 3, 7, 6, 5, 5, 6, 4, 5, 8, 7, 6, 4, 4, 5, 6, 5, 5, 4, 6, 7, 7, 6, 4, 1, 6, 3, 4, 5, 4, 4, 4, 7, 6, 4, 7, 8, 4, 6, 5, 1, 7, 2, 7, 2, 4, 6, 3, 5, 5, 5, 5, 5, 3, 6, 5, 5, 7, 7, 4, 3, 5, 3, 6, 6, 4, 8, 7, 7, 6, 5, 5, 4, 7, 4, 5, 6, 4, 4, 6, 3, 5, 4, 5, 6, 4, 5, 7, 5, 6, 4, 5, 6, 4, 4, 5, 6, 4, 4, 7, 3, 6, 5, 4, 7, 4, 7, 7, 5, 5, 5, 3, 8, 5, 6, 6, 5, 5, 2, 4, 8, 4, 6, 4, 4, 3, 6, 3, 5, 8, 4, 3, 3, 5, 5, 7, 5, 6, 6, 6, 4, 8, 4, 4, 4, 5, 3, 1, 3, 5, 7, 9, 4, 8, 6, 3, 1, 3, 5, 6, 3, 5, 8, 6, 3, 7, 9, 3, 4, 5, 0, 5, 5, 5, 5, 4, 7, 4, 6, 7, 2, 4, 4, 4, 7, 6, 4, 5, 3, 4, 6, 8, 6, 4, 3, 6, 6, 7, 7, 5, 4, 7, 7, 7, 5, 5, 6, 5, 5, 2, 4, 7, 4, 3, 3, 3, 3, 5, 7, 5, 2, 6, 8, 5, 5, 5, 7, 5, 5, 4, 5, 5, 5, 4, 4, 5, 3, 7, 7, 6, 2, 4, 8, 6, 7, 7, 5, 6, 6, 7, 4, 6, 4, 4, 5, 3, 8, 7, 5, 4, 3, 5, 4, 5, 7, 6, 6, 4, 2, 6, 4, 4, 5, 5, 4, 5, 4, 4, 4, 5, 6, 6, 4, 2, 7, 5, 5, 5, 3, 4, 7, 4, 5, 5, 7, 4, 5, 4, 7, 4, 4, 5, 5, 7, 5, 3, 6, 5, 7, 4, 6, 6, 4, 5, 7, 8, 2, 5, 4, 4, 4, 6, 7, 4, 5, 4, 4, 7, 5, 2, 5, 6, 3, 5, 4, 6, 4, 5, 5, 1, 6, 4, 3, 6, 9, 3, 5, 6, 8, 5, 4, 4, 6, 7, 6, 4, 6, 7, 7, 9, 4, 6, 2, 2, 5, 6, 3, 7, 2, 8, 5, 6, 4, 4, 6, 9, 6, 4, 3, 5, 6, 5, 5, 4, 2, 3, 5, 5, 6, 2, 4, 7, 4, 5, 5, 5, 5, 3, 6, 5, 7, 3, 7, 4, 6, 5, 4, 3, 4, 5, 5, 5, 3, 5, 3, 5, 4, 3, 5, 4, 4, 4, 6, 3, 5, 7, 5, 6, 4, 8, 4, 8, 6, 6, 4, 6, 5, 5, 5, 6, 5, 4, 4, 2, 6, 2, 4, 4, 7, 3, 4, 3, 7, 4, 7, 7, 5, 4, 7, 4, 6, 8, 4, 6, 5, 3, 5, 6, 6, 5, 6, 5, 6, 4, 6, 5, 1, 8, 8, 3, 3, 7, 1, 5, 5, 3, 6, 6, 2, 4, 4, 5, 6, 5, 4, 6, 5, 5, 4, 6, 5, 5, 7, 4, 6, 8, 7, 8, 5, 5, 6, 6, 3, 6, 5, 7, 5, 5, 5, 4, 6, 8, 7, 7, 4, 6, 4, 6, 4, 4, 6, 4, 5, 3, 5, 5, 4, 4, 3, 5, 4, 3, 5, 5, 2, 6, 3, 3, 4, 4, 4, 7, 4, 6, 4, 4, 7, 8, 7, 4, 3, 6, 6, 5, 5, 6, 7, 6, 6, 5, 7, 4, 6, 4, 5, 7, 4, 5, 6, 4, 5, 3, 6, 4, 6, 8, 4, 5, 6, 5, 7, 4, 1, 3, 4, 3, 5, 5, 4, 7, 4, 5, 4, 2, 10, 4, 5, 7, 5, 4, 5, 5, 1, 7, 5, 4, 6, 5, 3, 4, 5, 5, 3, 4, 7, 6, 4, 6, 6, 4, 5, 7, 5, 5, 4, 6, 6, 4, 3, 5, 5, 9, 8, 6, 1, 7, 3, 3, 5, 7, 4, 5, 6, 3, 4, 5, 3, 5, 7, 6, 6, 5, 7, 3, 7, 4, 3, 5, 6, 4, 4, 6, 5, 7, 7, 5, 7, 4, 4, 7, 5, 7, 7, 5, 7, 5, 4, 5, 6, 6, 5, 5, 4, 7, 5, 4, 4, 4, 6, 5, 5, 7, 7, 2, 5, 4, 5, 8, 6, 7, 3, 2, 4, 6, 6, 5, 5, 7, 4, 5, 2, 5, 2, 5, 4, 4, 6, 5, 4, 3, 6, 4, 5, 6, 4, 8, 5, 5, 2, 5, 4, 5, 5, 5, 6, 3, 5, 6, 3, 4, 5, 3, 2, 6, 4, 3, 4, 6, 3, 8, 3, 7, 6, 6, 6, 4, 2, 4, 4, 5, 10, 6, 7, 4, 6, 5, 5, 6, 4, 4, 3, 5, 5, 6, 7, 3, 6, 5, 5, 4, 5, 4, 5, 5, 6, 5, 4, 4, 8, 4, 7, 7, 4, 4, 5, 6, 3, 4, 5, 3, 7, 7, 3, 6, 4, 5, 4, 5, 3, 4, 3, 7, 4, 7, 4, 5, 3, 6, 3, 8, 6, 7, 5, 4, 3, 3, 7, 1, 5, 10, 4, 7, 5, 4, 6, 5, 4, 5, 4, 5, 6, 4, 6, 6, 4, 7, 2, 3, 9, 8, 6, 6, 6, 7, 5, 4, 5, 3, 4, 2, 4, 3, 6, 5, 5, 2, 4, 7, 4, 4, 4, 6, 4, 6, 4, 6, 7, 4, 4, 5, 4, 6, 6, 5, 6, 7, 8, 4, 6, 3, 7, 5, 3, 7, 5, 7, 8, 7, 3, 5, 5, 6, 5, 7, 6, 5, 4, 7, 5, 4, 6, 7, 6, 3, 5, 3, 0, 4, 4, 1, 3, 4, 7, 2, 4, 4, 5, 7, 6, 3, 6, 4, 6, 8, 6, 4, 3, 9, 5, 8, 5, 5, 5, 3, 8, 4, 3, 3, 2, 6, 5, 4, 4, 5, 5, 5, 6, 3, 6, 4, 6, 5, 6, 3, 3, 5, 3, 6, 4, 3, 4, 4, 1, 2, 6, 7, 3, 4, 6, 7, 2, 5, 3, 5, 3, 4, 6, 6, 5, 4, 5, 6, 5, 6, 3, 4, 6, 7, 1, 5, 7, 5, 5, 7, 3, 2, 3, 3, 6, 5, 7, 6, 5, 7, 2, 4, 6, 3, 2, 7, 5, 6, 5, 4, 7, 2, 6, 5, 4, 6, 6, 3, 6, 4, 3, 1, 4, 6, 7, 3, 5, 4, 3, 2, 5, 6, 7, 5, 4, 4, 4, 6, 5, 4, 6, 6, 3, 6, 4, 6, 3, 3, 7, 5, 2, 6, 3, 6, 3, 4, 5, 6, 2, 5, 5, 7, 3, 6, 5, 5, 5, 5, 5, 5, 4, 4, 9, 6, 5, 3, 6, 3, 4, 7, 6, 8, 4, 5, 5, 6, 9, 7, 6, 3, 7, 6, 7, 7, 8, 5, 4, 7, 7, 6, 5, 5, 8, 5, 5, 2, 6, 6, 4, 2, 7, 4, 7, 5, 5, 7, 5, 2, 5, 5, 8, 6, 8, 7, 3, 6, 6, 4, 6, 5, 6, 7, 6, 8, 2, 3, 4, 5, 5, 6, 4, 2, 3, 6, 7, 5, 4, 6, 5, 8, 4, 5, 9, 7, 5, 7, 7, 4, 4, 6, 4, 5, 7, 4, 5, 6, 4, 7, 7, 8, 3, 5, 5, 6, 8, 6, 3, 6, 4, 4, 3, 3, 5, 6, 4, 5, 3, 3, 2, 4, 5, 4, 6, 3, 2, 5, 5, 5, 1, 7, 4, 6, 9, 3, 7, 3, 5, 5, 6, 6, 4, 6, 7, 6, 5, 7, 1, 3, 4, 2, 10, 3, 2, 4, 6, 5, 5, 4, 7, 3, 6, 3, 6, 3, 2, 5, 5, 8, 6, 6, 6, 7, 5, 4, 5, 5, 3, 5, 3, 4, 6, 4, 5, 7, 3, 4, 6, 7, 3, 3, 7, 6, 9, 5, 4, 6, 6, 4, 5, 3, 4, 4, 6, 2, 6, 1, 5, 4, 5, 4, 6, 6, 5, 7, 6, 3, 6, 6, 7, 6, 6, 4, 5, 6, 6, 3, 8, 5, 4, 6, 6, 4, 4, 3, 5, 5, 3, 4, 4, 3, 6, 5, 6, 8, 5, 7, 5, 3, 5, 7, 4, 3, 5, 2, 3, 5, 6, 5, 3, 4, 4, 8, 8, 5, 5, 3, 4, 5, 4, 2, 4, 6, 4, 4, 3, 4, 6, 4, 6, 2, 5, 6, 7, 5, 3, 3, 4, 5, 6, 4, 6, 8, 5, 8, 2, 3, 5, 4, 7, 4, 2, 3, 5, 6, 8, 4, 4, 5, 6, 5, 2, 3, 6, 6, 5, 7, 7, 4, 5, 8, 4, 3, 6, 5, 7, 8, 4, 8, 7, 4, 3, 3, 7, 6, 6, 4, 9, 5, 7, 5, 3, 5, 6, 5, 2, 2, 7, 5, 5, 5, 9, 4, 3, 4, 1, 5, 3, 7, 8, 6, 4, 3, 5, 6, 3, 6, 7, 6, 3, 7, 2, 5, 2, 7, 4, 4, 6, 7, 2, 4, 6, 5, 5, 6, 4, 7, 6, 8, 4, 7, 3, 7, 6, 6, 6, 4, 6, 2, 2, 4, 4, 3, 5, 7, 6, 5, 4, 9, 4, 7, 3, 5, 7, 2, 5, 3, 3, 5, 5, 6, 6, 7, 6, 7, 5, 5, 7, 8, 5, 4, 4, 5, 5, 6, 7, 5, 5, 5, 6, 5, 6, 5, 5, 5, 3, 3, 7, 5, 7, 6, 7, 5, 4, 4, 6, 3, 4, 6, 5, 5, 6, 6, 6, 4, 5, 5, 4, 2, 6, 7, 5, 4, 5, 6, 6, 3, 5, 6, 7, 4, 5, 6, 4, 7, 4, 5, 7, 6, 8, 5, 5, 8, 6, 5, 6, 4, 5, 4, 5, 8, 6, 6, 4, 2, 5, 6, 7, 7, 5, 3, 4, 4, 6, 4, 4, 5, 4, 6, 4, 3, 6, 5, 4, 5, 4, 3, 6, 4, 5, 7, 4, 6, 3, 4, 5, 5, 5, 4, 5, 6, 2, 4, 2, 6, 5, 5, 5, 3, 7, 4, 7, 3, 7, 1, 4, 8, 6, 3, 4, 5, 7, 3, 4, 5, 2, 5, 9, 6, 3, 5, 5, 2, 5, 7, 3, 6, 5, 7, 5, 3, 5, 7, 2, 5, 7, 3, 4, 6, 5, 2, 3, 5, 8, 6, 3, 2, 6, 3, 4, 3, 5, 3, 5, 5, 6, 3, 5, 4, 4, 5, 5, 3, 7, 4, 6, 6, 7, 4, 7, 5, 7, 5, 7, 3, 5, 6, 7, 4, 2, 7, 3, 4, 7, 5, 6, 6, 5, 2, 6, 3, 5, 3, 4, 2, 6, 3, 8, 6, 4, 3, 5, 4, 7, 7, 7, 4, 7, 5, 4, 6, 6, 8, 5, 4, 8, 4, 4, 3, 8, 3, 4, 0, 6, 5, 5, 4, 4, 4, 5, 7, 3, 8, 6, 2, 3, 5, 7, 2, 3, 6, 3, 6, 4, 7, 5, 3, 5, 6, 6, 3, 6, 9, 4, 4, 7, 5, 2, 5, 3, 6, 6, 7, 5, 4, 6, 7, 4, 5, 6, 5, 6, 5, 7, 5, 6, 4, 4, 6, 8, 3, 5, 4, 2, 5, 4, 5, 6, 7, 3, 7, 8, 6, 6, 7, 7, 6, 3, 5, 3, 3, 6, 4, 4, 2, 2, 5, 7, 4, 5, 3, 5, 3, 5, 3, 4, 5, 4, 4, 8, 4, 6, 5, 5, 3, 6, 8, 4, 3, 6, 6, 4, 5, 4, 5, 4, 4, 6, 4, 4, 6, 4, 5, 6, 4, 6, 6, 6, 4, 5, 2, 7, 7, 4, 3, 7, 5, 4, 6, 7, 4, 6, 5, 5, 4, 6, 6, 5, 5, 3, 4, 4, 6, 5, 1, 7, 5, 8, 6, 6, 5, 5, 5, 5, 5, 7, 4, 3, 7, 7, 7, 6, 4, 6, 4, 6, 6, 5, 7, 7, 4, 3, 4, 4, 7, 6, 5, 5, 8, 4, 5, 6, 9, 2, 2, 4, 5, 5, 7, 4, 8, 5, 5, 3, 3, 7, 5, 8, 6, 5, 4, 2, 4, 6, 6, 4, 6, 6, 5, 6, 4, 4, 4, 4, 2, 3, 3, 6, 2, 7, 7, 4, 6, 2, 4, 6, 4, 5, 6, 5, 4, 5, 3, 3, 8, 4, 4, 4, 5, 3, 7, 7, 7, 5, 3, 4, 3, 7, 4, 4, 2, 3, 2, 5, 6, 5, 5, 6, 7, 6, 5, 6, 4, 5, 4, 3, 4, 5, 4, 5, 5, 7, 6, 2, 9, 7, 4, 5, 8, 7, 5, 4, 3, 5, 3, 5, 4, 4, 4, 7, 7, 5, 2, 4, 4, 5, 6, 8, 5, 8, 4, 7, 6, 3, 5, 4, 6, 7, 3, 6, 7, 6, 5, 4, 6, 3, 2, 7, 6, 7, 6, 6, 6, 5, 5, 6, 5, 7, 4, 6, 5, 4, 5, 5, 5, 7, 4, 4, 5, 5, 2, 5, 4, 3, 5, 6, 4, 4, 6, 4, 6, 7, 5, 5, 5, 6, 5, 6, 7, 4, 5, 3, 5, 4, 6, 5, 3, 7, 5, 5, 3, 4, 5, 5, 5, 4, 6, 4, 3, 5, 2, 7, 7, 7, 5, 6, 4, 3, 4, 3, 4, 7, 6, 6, 6, 6, 5, 5, 3, 5, 4, 7, 4, 3, 5, 5, 5, 5, 3, 5, 2, 7, 6, 4, 4, 3, 5, 5, 5, 4, 5, 2, 6, 2, 6, 4, 5, 3, 7, 4, 5, 7, 7, 4, 6, 3, 4, 5, 7, 4, 2, 4, 7, 5, 3, 4, 6, 7, 4, 3, 4, 3, 4, 4, 2, 7, 4, 3, 3, 5, 2, 8, 6, 6, 7, 5, 5, 6, 6, 4, 6, 7, 5, 3, 6, 4, 6, 4, 3, 5, 3, 4, 8, 4, 3, 5, 3, 7, 3, 2, 3, 4, 5, 4, 7, 7, 4, 5, 6, 5, 5, 4, 5, 7, 8, 5, 7, 7, 7, 6, 4, 2, 3, 2, 3, 4, 2, 4, 6, 5, 5, 4, 6, 3, 4, 7, 4, 4, 3, 6, 3, 5, 5, 5, 7, 4, 5, 6, 5, 7, 3, 3, 5, 6, 7, 8, 4, 6, 6, 5, 5, 6, 3, 5, 7, 3, 5, 7, 5, 6, 7, 7, 6, 6, 8, 4, 8, 3, 5, 5, 7, 6, 9, 9, 5, 5, 3, 4, 7, 4, 5, 4, 6, 1, 7, 3, 6, 6, 6, 6, 5, 5, 6, 6, 4, 3, 7, 5, 6, 6, 4, 4, 7, 4, 6, 3, 6, 1, 6, 4, 5, 6, 4, 6, 7, 5, 6, 2, 4, 3, 6, 4, 4, 4, 4, 4, 5, 5, 4, 7, 3, 6, 7, 7, 4, 5, 6, 4, 5, 7, 4, 3, 2, 6, 2, 6, 6, 6, 4, 7, 5, 7, 6, 5, 3, 6, 4, 3, 4, 8, 5, 6, 6, 5, 5, 3, 6, 7, 5, 2, 7, 6, 5, 5, 3, 5, 7, 4, 9, 6, 5, 1, 5, 5, 5, 4, 5, 4, 4, 4, 6, 3, 3, 6, 8, 4, 7, 5, 5, 5, 8, 6, 3, 5, 4, 6, 5, 6, 4, 5, 6, 6, 8, 5, 3, 6, 5, 7, 8, 4, 5, 7, 3, 4, 3, 1, 5, 5, 7, 6, 8, 3, 5, 5, 5, 4, 7, 7, 3, 5, 5, 7, 5, 5, 5, 2, 3, 1, 6, 6, 8, 3, 4, 5, 5, 5, 7, 6, 5, 7, 5, 2, 8, 6, 5, 5, 4, 7, 3, 5, 2, 6, 4, 5, 5, 5, 8, 5, 7, 3, 4, 2, 5, 6, 6, 9, 4, 5, 4, 4, 5, 3, 8, 3, 6, 8, 5, 7, 5, 5, 3, 5, 2, 5, 6, 6, 6, 6, 2, 5, 4, 6, 4, 3, 6, 6, 7, 3, 6, 1, 4, 9, 4, 3, 4, 6, 8, 3, 7, 5, 7, 6, 7, 6, 4, 7, 3, 4, 6, 4, 4, 4, 4, 4, 5, 5, 3, 5, 4, 4, 4, 6, 5, 2, 5, 4, 3, 6, 4, 5, 6, 6, 5, 5, 4, 0, 4, 8, 4, 5, 5, 4, 4, 6, 6, 7, 5, 3, 2, 2, 6, 7, 5, 4, 3, 7, 5, 5, 6, 6, 5, 6, 5, 7, 5, 6, 5, 8, 4, 6, 8, 5, 3, 6, 3, 6, 3, 6, 5, 7, 6, 7, 2, 7, 5, 4, 3, 5, 5, 1, 8, 3, 7, 6, 4, 5, 4, 2, 7, 7, 4, 5, 7, 5, 3, 7, 6, 2, 7, 7, 5, 2, 4, 5, 8, 5, 4, 6, 5, 7, 6, 5, 1, 5, 7, 5, 4, 4, 2, 6, 7, 3, 7, 1, 7, 5, 3, 4, 2, 4, 5, 8, 6, 4, 5, 5, 6, 3, 4, 2, 5, 9, 6, 5, 7, 4, 6, 5, 7, 7, 6, 5, 5, 3, 4, 7, 3, 4, 4, 5, 7, 7, 4, 5, 4, 4, 6, 3, 4, 7, 7, 3, 6, 6, 3, 5, 5, 4, 5, 4, 6, 3, 7, 5, 4, 4, 5, 5, 5, 3, 4, 7, 4, 3, 4, 5, 4, 8, 4, 8, 3, 4, 6, 5, 6, 9, 6, 5, 5, 5, 3, 7, 2, 5, 4, 4, 5, 6, 7, 5, 8, 6, 8, 5, 5, 1, 6, 5, 4, 5, 4, 6, 5, 5, 5, 9, 6, 4, 5, 5, 4, 3, 4, 6, 4, 2, 5, 7, 7, 6, 6, 7, 5, 4, 4, 5, 3, 7, 5, 7, 4, 2, 6, 6, 8, 7, 4, 6, 7, 4, 5, 6, 3, 5, 5, 7, 4, 2, 7, 4, 6, 6, 8, 4, 3, 5, 6, 4, 6, 5, 3, 4, 4, 6, 7, 6, 4, 5, 4, 3, 3, 3, 5, 5, 9, 4, 4, 5, 5, 1, 6, 6, 4, 3, 6, 5, 5, 3, 3, 7, 7, 7, 4, 3, 5, 7, 3, 4, 4, 5, 6, 3, 5, 5, 3, 5, 5, 4, 6, 5, 4, 7, 6, 7, 7, 6, 9, 5, 9, 6, 3, 6, 3, 8, 4, 6, 5, 5, 4, 9, 6, 7, 7, 4, 5, 4, 5, 6, 7, 4, 3, 3, 7, 6, 7, 6, 5, 5, 10, 4, 6, 8, 7, 4, 5, 4, 4, 7, 5, 5, 3, 7, 4, 5, 8, 4, 4, 4, 5, 6, 8, 4, 3, 3, 5, 4, 6, 4, 6, 5, 6, 4, 1, 2, 5, 3, 8, 3, 3, 5, 6, 2, 5, 4, 5, 7, 4, 5, 8, 3, 7, 6, 5, 6, 4, 5, 4, 5, 6, 7, 2, 2, 3, 4, 6, 7, 8, 5, 3, 5, 5, 7, 5, 4, 7, 3, 5, 5, 6, 7, 8, 6, 4, 6, 4, 5, 4, 4, 9, 3, 4, 6, 4, 5, 6, 2, 7, 6, 7, 3, 7, 3, 5, 8, 6, 4, 6, 4, 6, 5, 6, 3, 4, 5, 5, 4, 6, 4, 5, 4, 5, 7, 4, 4, 5, 2, 6, 8, 5, 4, 5, 6, 4, 4, 2, 5, 3, 4, 6, 4, 6, 7, 4, 4, 7, 6, 7, 2, 5, 6, 4, 5, 5, 4, 6, 5, 5, 9, 5, 3, 5, 5, 4, 3, 3, 3, 7, 6, 5, 9, 8, 3, 2, 5, 5, 5, 4, 4, 7, 7, 4, 4, 5, 7, 6, 5, 8, 5, 4, 6, 8, 4, 4, 5, 7, 6, 6, 2, 5, 7, 4, 6, 5, 5, 5, 4, 5, 6, 6, 5, 7, 5, 4, 6, 4, 5, 4, 3, 4, 5, 5, 6, 3, 4, 6, 4, 5, 4, 4, 4, 5, 5, 6, 8, 2, 5, 5, 7, 4, 4, 3, 2, 8, 4, 6, 6, 5, 6, 3, 4, 3, 3, 6, 4, 4, 7, 5, 7, 3, 6, 4, 5, 3, 3, 2, 4, 4, 5, 3, 5, 5, 9, 4, 6, 5, 3, 5, 3, 6, 6, 5, 8, 4, 8, 5, 5, 4, 4, 3, 4, 5, 6, 7, 6, 7, 4, 7, 6, 5, 4, 4, 6, 4, 8, 6, 4, 5, 5, 3, 7, 5, 5, 6, 5, 6, 3, 4, 5, 3, 4, 7, 4, 2, 4, 6, 6, 7, 8, 6, 6, 4, 7, 3, 5, 6, 4, 5, 3, 5, 7, 3, 9, 4, 3, 5, 9, 8, 4, 6, 2, 4, 4, 7, 5, 6, 4, 6, 7, 7, 4, 4, 7, 5, 6, 7, 5, 5, 4, 4, 6, 6, 6, 4, 5, 4, 4, 7, 5, 6, 7, 6, 5, 3, 5, 3, 5, 6, 5, 4, 0, 6, 3, 6, 2, 6, 7, 5, 4, 3, 6, 6, 6, 3, 7, 5, 7, 5, 4, 4, 5, 6, 5, 8, 6, 3, 7, 4, 6, 5, 4, 7, 4, 4, 5, 4, 5, 5, 6, 6, 4, 8, 5, 6, 4, 3, 5, 6, 6, 7, 5, 4, 7, 6, 6, 2, 2, 5, 4, 4, 2, 7, 7, 3, 4, 3, 5, 3, 5, 2, 3, 7, 4, 5, 4, 2, 4, 4, 7, 5, 6, 1, 5, 4, 6, 7, 3, 4, 6, 5, 3, 2, 5, 7, 3, 7, 5, 6, 6, 3, 4, 5, 7, 3, 6, 5, 3, 4, 5, 4, 3, 4, 4, 4, 4, 6, 5, 6, 7, 6, 8, 3, 6, 6, 5, 3, 7, 4, 4, 4, 5, 5, 5, 5, 5, 5, 4, 4, 4, 7, 6, 4, 4, 7, 5, 6, 7, 6, 5, 6, 3, 5, 7, 4, 2, 5, 2, 6, 3, 8, 5, 6, 6, 5, 7, 7, 5, 5, 3, 5, 7, 4, 5, 6, 7, 3, 4, 3, 4, 7, 5, 4, 3, 4, 5, 6, 6, 5, 6, 5, 5, 4, 4, 3, 5, 8, 5, 6, 6, 7, 4, 3, 7, 4, 8, 5, 6, 3, 5, 4, 2, 5, 7, 8, 2, 6, 3, 3, 5, 7, 5, 9, 8, 5, 3, 2, 4, 4, 7, 4, 4, 3, 6, 5, 7, 3, 6, 3, 5, 6, 4, 3, 3, 5, 7, 4, 4, 6, 4, 2, 3, 4, 6, 5, 5, 4, 5, 6, 5, 6, 2, 3, 5, 6, 6, 7, 3, 7, 3, 6, 5, 7, 4, 5, 5, 2, 4, 6, 6, 4, 5, 3, 4, 3, 5, 4, 8, 7, 7, 6, 6, 3, 7, 9, 6, 4, 3, 5, 3, 3, 8, 4, 7, 7, 5, 4, 7, 4, 4, 6, 3, 7, 6, 5, 5, 8, 6, 7, 2, 6, 4, 4, 5, 3, 5, 6, 5, 10, 5, 2, 7, 7, 5, 5, 6, 5, 5, 5, 7, 5, 7, 5, 5, 1, 5, 5, 7, 5, 7, 5, 5, 6, 2, 5, 2, 6, 5, 2, 4, 5, 4, 5, 7, 4, 5, 8, 4, 7, 4, 6, 5, 6, 7, 4, 6, 4, 5, 4, 3, 5, 5, 1, 6, 4, 6, 4, 4, 5, 7, 6, 4, 5, 6, 4, 6, 7, 4, 6, 4, 3, 7, 5, 6, 4, 5, 5, 3, 4, 3, 5, 5, 7, 6, 3, 6, 7, 7, 5, 7, 8, 5, 4, 4, 4, 6, 7, 4, 5, 4, 5, 4, 6, 6, 6, 3, 6, 3, 8, 3, 6, 3, 7, 6, 7, 5, 5, 4, 2, 2, 7, 8, 4, 6, 2, 4, 8, 4, 7, 6, 2, 6, 7, 6, 3, 4, 5, 7, 3, 4, 3, 6, 5, 7, 6, 4, 5, 4, 6, 5, 6, 5, 5, 8, 4, 6, 8, 8, 6, 5, 4, 5, 4, 5, 6, 7, 4, 5, 5, 4, 7, 4, 4, 6, 5, 7, 7, 0, 6, 6, 1, 5, 8, 2, 3, 6, 6, 4, 6, 5, 5, 5, 3, 4, 6, 5, 9, 5, 8, 7, 4, 4, 1, 4, 7, 4, 6, 6, 7, 5, 5, 5, 4, 5, 6, 5, 3, 1, 2, 4, 3, 5, 7, 4, 6, 6, 3, 5, 5, 8, 4, 6, 6, 6, 5, 5, 5, 7, 5, 2, 4, 4, 6, 6, 6, 6, 5, 0, 5, 8, 4, 9, 5, 5, 5, 7, 4, 5, 5, 6, 3, 4, 6, 4, 4, 2, 4, 8, 6, 5, 6, 6, 7, 5, 8, 7, 5, 6, 4, 4, 4, 4, 4, 6, 5, 4, 4, 3, 5, 5, 4, 6, 5, 7, 4, 6, 7, 4, 3, 3, 5, 4, 6, 5, 4, 3, 3, 4, 6, 6, 8, 5, 5, 6, 5, 8, 6, 3, 7, 5, 4, 5, 6, 6, 7, 5, 9, 4, 6, 4, 6, 4, 5, 8, 5, 2, 4, 1, 4, 5, 4, 3, 5, 8, 6, 5, 7, 5, 7, 5, 4, 6, 3, 5, 5, 7, 4, 6, 3, 5, 3, 5, 8, 5, 4, 5, 5, 8, 4, 8, 6, 4, 3, 4, 4, 3, 2, 5, 4, 8, 4, 2, 4, 4, 4, 4, 1, 5, 3, 6, 3, 4, 3, 4, 7, 4, 5, 5, 5, 4, 7, 5, 5, 4, 6, 3, 7, 5, 5, 4, 2, 2, 3, 6, 4, 4, 5, 6, 3, 6, 6, 5, 3, 2, 6, 6, 5, 3, 4, 5, 3, 6, 4, 5, 5, 7, 5, 6, 5, 4, 6, 5, 4, 8, 4, 2, 4, 6, 6, 4, 7, 4, 4, 3, 6, 3, 8, 5, 5, 6, 8, 4, 6, 7, 6, 4, 6, 4, 5, 4, 4, 5, 4, 4, 6, 5, 4, 3, 5, 8, 2, 4, 8, 4, 4, 6, 3, 4, 6, 6, 4, 4, 5, 6, 5, 7, 4, 7, 5, 7, 6, 3, 5, 4, 7, 3, 0, 8, 1, 7, 4, 4, 6, 6, 7, 6, 6, 6, 4, 5, 7, 4, 6, 3, 6, 3, 6, 4, 7, 6, 4, 6, 7, 5, 6, 3, 7, 5, 2, 5, 5, 3, 4, 2, 4, 4, 4, 3, 3, 3, 3, 3, 3, 4, 8, 4, 5, 3, 2, 5, 2, 8, 6, 5, 3, 5, 7, 7, 4, 6, 6, 6, 7, 7, 6, 4, 6, 4, 6, 5, 3, 3, 5, 7, 3, 5, 5, 3, 5, 7, 5, 6, 6, 6, 4, 5, 6, 6, 4, 6, 4, 3, 3, 5, 6, 4, 5, 6, 4, 5, 8, 5, 7, 9, 5, 4, 6, 6, 2, 5, 2, 7, 6, 7, 3, 3, 5, 4, 2, 2, 4, 5, 3, 5, 5, 2, 7, 5, 5, 5, 3, 5, 7, 7, 6, 5, 5, 6, 4, 6, 5, 3, 5, 4, 6, 7, 7, 6, 4, 6, 8, 6, 5, 3, 8, 3, 7, 6, 5, 5, 5, 5, 4, 5, 4, 4, 3, 6, 6, 4, 3, 7, 6, 6, 6, 5, 5, 5, 5, 6, 5, 9, 6, 6, 6, 5, 1, 7, 3, 2, 6, 7, 5, 5, 6, 3, 5, 2, 4, 5, 6, 8, 4, 3, 6, 4, 5, 3, 5, 8, 5, 7, 5, 2, 5, 5, 7, 4, 4, 2, 4, 2, 4, 2, 7, 6, 5, 5, 6, 4, 6, 8, 6, 4, 3, 5, 7, 7, 6, 4, 5, 5, 6, 6, 6, 4, 5, 5, 6, 8, 2, 6, 4, 3, 6, 6, 7, 4, 5, 4, 6, 6, 7, 6, 5, 4, 7, 8, 4, 4, 5, 7, 6, 5, 3, 7, 5, 5, 5, 5, 6, 4, 6, 4, 6, 5, 4, 6, 6, 4, 6, 5, 2, 5, 3, 5, 6, 4, 5, 7, 4, 6, 6, 6, 7, 4, 3, 4, 5, 6, 3, 4, 6, 5, 7, 6, 3, 8, 5, 4, 6, 2, 7, 5, 2, 3, 5, 5, 6, 8, 7, 3, 6, 7, 5, 7, 6, 6, 4, 6, 6, 5, 5, 4, 4, 3, 4, 7, 3, 5, 3, 2, 3, 5, 6, 4, 2, 1, 4, 3, 5, 7, 5, 5, 5, 6, 3, 7, 3, 4, 3, 5, 6, 7, 7, 8, 8, 3, 8, 9, 6, 4, 3, 6, 5, 7, 7, 6, 6, 4, 5, 8, 4, 4, 5, 3, 7, 3, 7, 3, 5, 6, 5, 7, 7, 5, 4, 5, 3, 4, 5, 5, 7, 3, 2, 9, 6, 4, 6, 4, 3, 6, 5, 8, 5, 4, 6, 7, 6, 5, 7, 7, 6, 5, 6, 6, 8, 6, 3, 2, 5, 8, 6, 5, 2, 4, 7, 6, 7, 5, 4, 5, 4, 4, 3, 7, 5, 3, 7, 7, 3, 4, 6, 7, 5, 7, 7, 8, 4, 4, 5, 6, 5, 3, 7, 4, 3, 6, 5, 6, 4, 3, 3, 8, 5, 3, 5, 7, 3, 6, 5, 3, 1, 7, 10, 5, 5, 4, 5, 4, 3, 5, 5, 2, 5, 7, 3, 5, 3, 3, 8, 3, 8, 5, 5, 7, 6, 6, 7, 5, 5, 7, 6, 2, 5, 3, 6, 5, 6, 6, 3, 6, 5, 5, 4, 6, 4, 5, 6, 8, 3, 5, 2, 4, 6, 10, 3, 9, 4, 4, 8, 5, 5, 4, 6, 4, 4, 5, 3, 3, 4, 4, 5, 7, 4, 5, 7, 6, 4, 9, 7, 3, 3, 2, 9, 5, 7, 7, 4, 7, 5, 3, 7, 3, 6, 8, 5, 5, 3, 1, 6, 4, 6, 2, 7, 7, 6, 6, 7, 5, 6, 6, 5, 4, 3, 6, 7, 6, 5, 4, 4, 5, 3, 6, 7, 5, 7, 3, 6, 4, 4, 6, 5, 7, 4, 8, 5, 5, 3, 4, 5, 5, 4, 6, 6, 6, 7, 7, 4, 5, 5, 4, 3, 6, 4, 5, 2, 4, 4, 8, 6, 7, 7, 7, 7, 4, 7, 5, 6, 5, 7, 4, 5, 4, 4, 4, 3, 7, 7, 5, 7, 4, 8, 5, 2, 4, 6, 2, 6, 5, 3, 5, 5, 5, 5, 4, 6, 2, 6, 5, 6, 6, 3, 7, 1, 5, 6, 6, 5, 5, 3, 2, 6, 6, 5, 3, 3, 6, 4, 5, 4, 6, 2, 3, 5, 4, 7, 3, 7, 7, 6, 1, 6, 7, 4, 7, 4, 4, 7, 4, 9, 8, 4, 4, 6, 3, 5, 5, 5, 6, 7, 5, 7, 1, 5, 3, 5, 6, 6, 3, 7, 8, 6, 5, 2, 3, 4, 6, 4, 5, 5, 3, 5, 5, 7, 5, 4, 5, 3, 7, 3, 5, 6, 6, 5, 7, 4, 5, 8, 4, 2, 4, 5, 6, 7, 5, 3, 7, 5, 5, 5, 6, 6, 3, 8, 3, 3, 4, 5, 5, 2, 4, 5, 7, 4, 5, 4, 4, 5, 7, 5, 4, 5, 6, 5, 6, 5, 3, 6, 4, 5, 4, 6, 5, 6, 4, 2, 7, 6, 5, 6, 5, 3, 5, 5, 1, 7, 3, 5, 6, 6, 4, 7, 5, 3, 5, 6, 5, 7, 4, 5, 2, 1, 8, 4, 4, 6, 2, 5, 5, 4, 5, 4, 7, 4, 6, 2, 5, 5, 6, 6, 6, 3, 5, 6, 5, 4, 6, 4, 5, 5, 6, 2, 2, 7, 6, 5, 4, 6, 6, 6, 4, 3, 3, 6, 7, 5, 6, 7, 3, 7, 4, 5, 6, 4, 6, 5, 6, 4, 3, 3, 7, 7, 3, 7, 6, 4, 3, 7, 5, 7, 4, 6, 5, 4, 5, 2, 7, 4, 4, 5, 3, 7, 6, 4, 3, 6, 3, 4, 5, 3, 2, 5, 3, 3, 5, 6, 5, 5, 8, 4, 8, 7, 6, 5, 3, 5, 5, 2, 7, 4, 6, 5, 7, 4, 3, 4, 3, 5, 3, 6, 6, 4, 4, 6, 5, 7, 5, 7, 6, 5, 7, 5, 4, 4, 3, 6, 4, 6, 5, 5, 6, 4, 6, 4, 6, 6, 5, 7, 2, 6, 6, 4, 2, 6, 3, 4, 5, 6, 4, 6, 6, 5, 6, 4, 6, 3, 5, 6, 4, 7, 5, 6, 2, 5, 3, 2, 6, 6, 5, 8, 6, 5, 6, 6, 8, 4, 7, 5, 2, 7, 4, 7, 3, 5, 5, 5, 5, 3, 6, 5, 4, 6, 5, 5, 8, 1, 5, 6, 6, 5, 2, 6, 3, 8, 2, 2, 2, 6, 4, 4, 5, 2, 6, 7, 4, 6, 5, 6, 4, 5, 5, 6, 6, 0, 5, 7, 4, 6, 2, 6, 2, 1, 6, 4, 5, 5, 4, 7, 4, 7, 3, 5, 4, 4, 4, 4, 4, 4, 7, 6, 3, 4, 4, 3, 6, 3, 4, 2, 6, 2, 5, 3, 5, 4, 5, 5, 4, 4, 5, 5, 4, 5, 9, 6, 5, 5, 3, 4, 3, 6, 6, 8, 6, 4, 5, 3, 1, 6, 4, 2, 2, 7, 3, 4, 7, 5, 2, 5, 5, 7, 4, 5, 5, 6, 6, 4, 4, 2, 5, 5, 4, 4, 3, 4, 3, 7, 3, 3, 5, 4, 3, 6, 4, 6, 6, 7, 6, 5, 5, 7, 6, 4, 5, 5, 6, 5, 6, 7, 4, 3, 4, 5, 3, 4, 5, 5, 5, 6, 5, 4, 6, 5, 4, 5, 8, 3, 7, 3, 5, 3, 8, 5, 3, 5, 6, 6, 4, 9, 5, 4, 6, 2, 8, 2, 4, 6, 3, 5, 4, 4, 3, 6, 6, 4, 4, 5, 2, 4, 2, 2, 7, 6, 7, 9, 6, 3, 3, 6, 5, 4, 7, 7, 7, 4, 4, 7, 7, 8, 4, 5, 2, 4, 3, 4, 6, 4, 6, 8, 6, 6, 5, 1, 4, 4, 3, 6, 5, 6, 2, 7, 6, 6, 5, 6, 4, 5, 4, 3, 5, 2, 3, 5, 5, 5, 5, 6, 4, 2, 7, 6, 5, 3, 5, 4, 5, 0, 2, 5, 5, 4, 5, 5, 7, 4, 5, 8, 5, 4, 4, 5, 3, 3, 3, 7, 7, 3, 2, 5, 6, 5, 5, 5, 3, 5, 6, 5, 8, 4, 4, 7, 7, 5, 7, 7, 6, 7, 3, 6, 6, 2, 6, 6, 4, 3, 5, 4, 7, 7, 1, 6, 5, 5, 5, 4, 7, 6, 4, 4, 2, 5, 2, 2, 4, 4, 6, 4, 4, 10, 4, 6, 3, 8, 4, 4, 5, 6, 5, 4, 5, 8, 4, 7, 4, 5, 4, 5, 5, 4, 5, 6, 9, 2, 4, 6, 6, 2, 3, 4, 5, 3, 5, 5, 7, 6, 6, 6, 2, 4, 5, 7, 6, 5, 4, 6, 5, 5, 5, 3, 4, 4, 6, 4, 7, 7, 1, 5, 6, 6, 5, 6, 6, 3, 6, 4, 4, 7, 8, 3, 6, 5, 8, 5, 4, 6, 7, 5, 7, 8, 5, 8, 4, 4, 6, 6, 4, 6, 3, 6, 6, 7, 5, 3, 5, 5, 5, 2, 6, 8, 5, 5, 6, 3, 3, 5, 5, 5, 6, 4, 5, 5, 5, 6, 2, 6, 5, 3, 5, 3, 5, 4, 3, 6, 4, 5, 4, 3, 4, 5, 5, 4, 3, 2, 7, 4, 4, 4, 6, 8, 3, 5, 5, 5, 5, 3, 3, 3, 5, 5, 4, 6, 5, 6, 5, 6, 2, 5, 6, 5, 5, 4, 4, 6, 4, 3, 7, 2, 5, 8, 6, 3, 7, 5, 6, 6, 6, 5, 7, 6, 4, 3, 5, 4, 5, 5, 6, 3, 3, 4, 6, 4, 4, 5, 6, 1, 5, 3, 5, 7, 7, 6, 6, 4, 5, 5, 7, 3, 4, 5, 8, 6, 4, 4, 5, 7, 5, 6, 6, 7, 9, 5, 3, 6, 4, 6, 5, 5, 4, 4, 5, 3, 6, 7, 6, 5, 5, 5, 1, 4, 6, 5, 6, 4, 5, 4, 4, 5, 9, 5, 3, 4, 6, 4, 6, 4, 5, 2, 6, 5, 8, 5, 6, 4, 4, 3, 7, 5, 4, 7, 7, 7, 6, 4, 5, 3, 5, 3, 3, 4, 3, 7, 7, 5, 9, 7, 5, 5, 4, 4, 4, 4, 4, 7, 7, 5, 4, 4, 4, 5, 8, 6, 5, 8, 6, 4, 4, 3, 4, 3, 5, 4, 4, 6, 4, 3, 6, 5, 9, 3, 4, 6, 4, 4, 4, 3, 5, 5, 8, 6, 5, 7, 3, 5, 7, 6, 6, 7, 3, 6, 5, 6, 4, 7, 5, 6, 4, 5, 4, 7, 4, 5, 7, 7, 5, 7, 4, 3, 6, 3, 6, 3, 6, 6, 5, 6, 5, 5, 6, 3, 6, 4, 6, 10, 7, 7, 4, 7, 3, 4, 5, 8, 6, 6, 6, 5, 5, 6, 8, 6, 4, 4, 9, 5, 1, 5, 5, 5, 5, 4, 5, 4, 2, 7, 6, 5, 5, 3, 6, 5, 6, 7, 5, 5, 6, 6, 5, 6, 3, 5, 9, 8, 4, 2, 6, 6, 3, 7, 2, 6, 4, 8, 7, 5, 5, 7, 8, 4, 4, 4, 5, 1, 6, 5, 5, 5, 7, 7, 6, 5, 7, 5, 5, 5, 4, 8, 4, 4, 3, 3, 5, 5, 5, 3, 8, 4, 6, 5, 5, 4, 4, 7, 6, 5, 4, 4, 2, 5, 7, 7, 5, 2, 5, 3, 7, 5, 6, 7, 6, 7, 4, 5, 6, 4, 5, 5, 2, 5, 5, 5, 4, 4, 8, 4, 8, 1, 8, 5, 5, 8, 3, 10, 5, 5, 3, 5, 6, 3, 5, 6, 5, 8, 6, 5, 5, 4, 5, 3, 5, 8, 5, 4, 7, 9, 7, 3, 7, 4, 4, 5, 4, 5, 7, 5, 3, 4, 3, 1, 5, 5, 6, 4, 3, 2, 7, 5, 6, 6, 4, 5, 2, 5, 4, 4, 8, 5, 7, 7, 4, 5, 4, 4, 9, 6, 4, 6, 4, 6, 3, 5, 7, 6, 5, 3, 6, 4, 6, 6, 4, 6, 7, 3, 3, 5, 7, 2, 6, 6, 5, 6, 6, 5, 4, 8, 6, 5, 4, 7, 4, 2, 4, 6, 8, 7, 6, 4, 4, 6, 3, 6, 5, 3, 3, 6, 6, 5, 7, 7, 5, 5, 5, 8, 5, 5, 7, 6, 3, 7, 2, 4, 6, 3, 6, 7, 7, 3, 6, 6, 4, 4, 3, 4, 4, 5, 4, 7, 3, 4, 5, 7, 8, 7, 5, 5, 4, 6, 7, 6, 5, 5, 5, 5, 7, 4, 4, 5, 4, 4, 4, 6, 7, 4, 7, 6, 5, 4, 7, 5, 6, 6, 4, 3, 2, 6, 7, 3, 6, 3, 3, 5, 3, 8, 4, 6, 3, 5, 6, 1, 6, 6, 8, 6, 7, 6, 7, 7, 4, 3, 4, 5, 4, 6, 6, 5, 4, 5, 6, 6, 7, 8, 4, 7, 4, 5, 4, 6, 8, 6, 4, 6, 7, 5, 4, 8, 3, 7, 4, 7, 4, 5, 4, 6, 4, 4, 3, 6, 6, 5, 3, 6, 6, 5, 3, 4, 4, 3, 6, 6, 2, 7, 5, 5, 4, 3, 7, 3, 6, 6, 9, 6, 4, 4, 4, 6, 3, 4, 3, 5, 7, 2, 6, 4, 3, 6, 7, 3, 3, 4, 3, 7, 4, 5, 7, 4, 5, 5, 6, 5, 5, 7, 6, 2, 2, 6, 5, 5, 4, 5, 1, 4, 4, 4, 5, 6, 4, 6, 2, 5, 4, 7, 6, 7, 5, 4, 2, 3, 5, 4, 5, 6, 3, 2, 4, 4, 3, 4, 5, 5, 7, 2, 3, 4, 3, 5, 4, 2, 5, 7, 4, 4, 4, 7, 4, 7, 6, 5, 3, 4, 5, 6, 7, 5, 4, 3, 5, 1, 9, 9, 4, 6, 4, 6, 1, 5, 4, 6, 6, 5, 5, 6, 6, 8, 6, 5, 5, 6, 7, 6, 3, 4, 6, 4, 6, 4, 3, 6, 5, 9, 5, 3, 4, 7, 5, 4, 4, 6, 5, 4, 3, 7, 6, 7, 4, 3, 4, 3, 4, 4, 5, 5, 6, 7, 4, 5, 5, 4, 4, 4, 5, 6, 3, 4, 3, 3, 6, 7, 4, 5, 7, 4, 7, 4, 4, 3, 4, 4, 4, 4, 3, 7, 4, 5, 7, 6, 5, 7, 5, 3, 6, 5, 5, 7, 5, 4, 5, 4, 6, 4, 5, 6, 7, 5, 4, 5, 4, 6, 4, 4, 3, 7, 5, 6, 4, 8, 5, 6, 4, 5, 5, 4, 4, 3, 8, 4, 7, 6, 5, 5, 7, 6, 3, 6, 4, 7, 7, 4, 4, 7, 6, 4, 1, 4, 3, 4, 6, 4, 6, 2, 8, 8, 6, 7, 5, 3, 6, 3, 3, 4, 4, 5, 6, 5, 6, 4, 4, 4, 4, 4, 5, 5, 2, 4, 4, 4, 6, 7, 8, 4, 2, 7, 3, 5, 5, 5, 5, 4, 6, 4, 4, 3, 4, 5, 5, 2, 5, 6, 5, 2, 5, 4, 7, 4, 8, 4, 7, 3, 6, 5, 5, 8, 5, 2, 6, 7, 5, 8, 1, 5, 6, 3, 5, 5, 6, 3, 5, 6, 4, 2, 6, 4, 1, 6, 5, 7, 5, 4, 2, 7, 5, 4, 7, 2, 4, 5, 2, 3, 5, 4, 6, 3, 2, 2, 4, 6, 7, 5, 5, 6, 5, 6, 5, 6, 7, 5, 2, 2, 6, 6, 4, 3, 5, 5, 6, 6, 5, 6, 6, 4, 4, 5, 5, 4, 3, 6, 3, 3, 5, 4, 4, 4, 5, 5, 3, 4, 4, 2, 4, 5, 5, 5, 7, 4, 7, 5, 6, 5, 5, 5, 6, 6, 6, 4, 1, 4, 6, 5, 7, 4, 4, 5, 4, 6, 2, 5, 5, 7, 4, 7, 5, 5, 4, 6, 3, 7, 6, 6, 4, 6, 4, 6, 4, 7, 7, 3, 6, 5, 3, 4, 5, 6, 4, 6, 6, 5, 4, 7, 8, 4, 5, 6, 4, 3, 4, 6, 5, 4, 8, 8, 9, 6, 4, 4, 5, 4, 4, 5, 5, 7, 6, 3, 4, 5, 4, 5, 2, 2, 4, 4, 4, 3, 4, 5, 6, 8, 6, 8, 7, 4, 7, 8, 4, 6, 5, 6, 5, 6, 5, 7, 6, 5, 5, 9, 6, 6, 3, 6, 5, 6, 4, 7, 6, 6, 2, 5, 5, 5, 7, 6, 7, 5, 9, 6, 5, 5, 5, 2, 1, 5, 7, 2, 4, 5, 4, 5, 4, 7, 5, 5, 4, 5, 6, 6, 4, 4, 7, 5, 7, 8, 6, 5, 5, 3, 3, 8, 5, 2, 6, 7, 5, 6, 4, 7, 6, 4, 5, 4, 5, 5, 7, 5, 3, 4, 5, 3, 4, 5, 6, 3, 4, 5, 5, 4, 6, 6, 7, 8, 6, 4, 3, 6, 4, 5, 4, 7, 7, 4, 3, 6, 6, 7, 5, 3, 3, 6, 5, 5, 4, 5, 7, 6, 5, 5, 5, 4, 4, 4, 3, 6, 4, 7, 8, 5, 6, 5, 3, 7, 4, 4, 7, 6, 3, 3, 5, 5, 5, 6, 3, 6, 5, 3, 4, 8, 4, 2, 3, 5, 1, 7, 3, 5, 5, 4, 5, 4, 5, 3, 4, 3, 6, 4, 7, 6, 6, 6, 5, 5, 4, 5, 6, 5, 4, 6, 6, 2, 6, 6, 3, 8, 3, 6, 4, 4, 7, 5, 7, 5, 5, 7, 5, 3, 6, 5, 6, 5, 7, 5, 2, 4, 5, 1, 4, 4, 5, 4, 6, 7, 5, 5, 5, 3, 5, 4, 5, 4, 6, 4, 7, 5, 2, 7, 5, 6, 4, 1, 6, 5, 5, 4, 5, 3, 4, 4, 4, 4, 5, 4, 5, 4, 4, 3, 7, 5, 7, 6, 3, 5, 4, 4, 4, 5, 3, 4, 6, 3, 6, 8, 5, 5, 8, 5, 4, 5, 6, 8, 7, 5, 5, 5, 6, 3, 4, 6, 7, 2, 5, 5, 4, 4, 8, 4, 6, 4, 8, 4, 5, 6, 6, 6, 5, 5, 6, 7, 5, 5, 6, 2, 4, 3, 6, 6, 4, 2, 4, 3, 5, 3, 4, 4, 5, 7, 5, 6, 4, 6, 7, 6, 3, 5, 5, 6, 3, 3, 3, 5, 6, 4, 6, 7, 7, 6, 6, 5, 6, 3, 2, 3, 6, 4, 7, 4, 4, 4, 4, 3, 3, 3, 6, 4, 6, 5, 4, 5, 6, 6, 3, 3, 5, 4, 5, 6, 2, 3, 4, 5, 6, 5, 6, 5, 4, 8, 9, 3, 4, 4, 7, 5, 6, 7, 3, 6, 8, 5, 5, 7, 2, 4, 6, 5, 7, 4, 6, 4, 4, 5, 3, 4, 3, 5, 7, 4, 6, 3, 4, 5, 4, 7, 7, 4, 3, 6, 4, 2, 8, 6, 5, 7, 6, 6, 2, 3, 5, 6, 3, 6, 3, 5, 4, 5, 6, 5, 3, 3, 7, 6, 8, 2, 3, 3, 5, 6, 5, 2, 4, 6, 2, 4, 3, 5, 3, 4, 3, 5, 5, 7, 5, 6, 4, 4, 3, 7, 4, 4, 4, 4, 5, 7, 5, 7, 4, 3, 7, 2, 5, 5, 5, 7, 6, 4, 6, 6, 5, 6, 8, 5, 4, 7, 5, 4, 5, 3, 4, 6, 7, 3, 5, 6, 8, 5, 6, 5, 4, 7, 4, 6, 3, 3, 3, 4, 7, 2, 7, 3, 6, 4, 7, 2, 6, 6, 5, 4, 4, 1, 4, 4, 7, 2, 3, 3, 7, 5, 2, 5, 5, 6, 3, 2, 6, 8, 4, 4, 5, 3, 4, 4, 3, 5, 4, 3, 6, 7, 2, 7, 6, 1, 6, 7, 7, 4, 4, 6, 5, 6, 6]</code></pre>
</div>
</div>
<p>In this code chunk, we’ve done the following:</p>
<ul>
<li>initialized an empty list named outcomes to store the number of ‘heads’ from simulated samples of coin flips</li>
<li>set up a for-loop to repeat the steps below 10000 times:</li>
<li>flip a fair coin 10 times</li>
<li>calculate the number of those 10 flips that came up heads</li>
<li>append that number onto outcomes</li>
</ul>
<p>Note that 10000 is an arbitrarily chosen large number — it’s big enough that it will yield almost all possible outcomes of our experiment, and small enough that the simulation still runs quickly. From inspecting the output, we can see that the number of ‘heads’ varied between 0 and 10:</p>
<div class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>min_heads <span class="op">=</span> np.<span class="bu">min</span>(outcomes) </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(min_heads) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0</code></pre>
</div>
</div>
<div class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>max_heads <span class="op">=</span> np.<span class="bu">max</span>(outcomes)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(max_heads) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>10</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q5. Run an experiment where we simulate a sample of 500 visitors, each with a 10% chance of making a purchase, and record the number of purchases for that imaginary sample — then repeat that experiment 10,000 times</p>
</blockquote>
<div class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>null_outcomes <span class="op">=</span> []</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co">#start for loop here:</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10000</span>): </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  simulated_monthly_visitors <span class="op">=</span> np.random.choice([<span class="st">'y'</span>, <span class="st">'n'</span>], size<span class="op">=</span><span class="dv">500</span>, p<span class="op">=</span>[<span class="fl">0.1</span>, <span class="fl">0.9</span>])</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  num_purchased <span class="op">=</span> np.<span class="bu">sum</span>(simulated_monthly_visitors <span class="op">==</span> <span class="st">'y'</span>)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  null_outcomes.append(num_purchased)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Q6. Outside of your loop, save the minimum and maximum values in null_outcomes as <code>null_min</code> and <code>null_max</code> respectively, then print them out. How much does the number of purchases seem to be varying by random chance? Run your code a couple of times to see how variable these numbers are.</p>
</blockquote>
<div class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>null_min <span class="op">=</span> np.<span class="bu">min</span>(null_outcomes)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(null_min)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>26</code></pre>
</div>
</div>
<div class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>null_max <span class="op">=</span> np.<span class="bu">max</span>(null_outcomes)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(null_max)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>76</code></pre>
</div>
</div>
</section>
<section id="inspecting-the-null-distribution" class="level3">
<h3 class="anchored" data-anchor-id="inspecting-the-null-distribution">Inspecting the Null Distribution</h3>
<p>In the previous exercise, we simulated 10000 different samples of 500 visitors, where each visitor had a 10% chance of making a purchase, and calculated the number of purchases per sample. Upon further inspection, we saw that those numbers ranged from around 25 to 75. This is useful information, but we can learn even more from inspecting the full distribution.</p>
<p>For example, recall our 10000 coin flip experiments: for each experiment, we flipped a fair coin 10 times and recorded the number of heads in a list named outcomes. We can plot a histogram of outcomes using <code>matplotlib.pyplot.hist()</code>. We can also add a vertical line at any x-value using <code>matplotlib.pyplot.axvline()</code>:</p>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>plt.hist(outcomes)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">2</span>, color <span class="op">=</span> <span class="st">'r'</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Binomial_Test_files/figure-html/cell-18-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>This histogram shows us that, over 10000 experiments, we observed as few as 0 and as many as 10 heads out of 10 flips. However, we were most likely to observe around 4-6 heads. It would be unlikely to observe only 2 heads (where the vertical red line is).</p>
<blockquote class="blockquote">
<p>Q6. Plot a histogram for our null outcomes</p>
</blockquote>
<div class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>plt.hist(null_outcomes)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plt.axvline(2, color = 'r')</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Binomial_Test_files/figure-html/cell-19-output-1.png" class="img-fluid"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Q7. In the month we’re investigating, we calculated that there were 41 purchases. Add a vertical line to your histogram at 41. Make this line red using color = ‘r’ so that you can see it.</p>
</blockquote>
<div class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>plt.hist(null_outcomes)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>plt.axvline(<span class="dv">41</span>, color <span class="op">=</span> <span class="st">'r'</span>)  <span class="co">#add a vertical red line at 41</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Binomial_Test_files/figure-html/cell-20-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>41 purchases is somewhat likely to occur based on this null distribution. It’s not in the middle of the distribution, where there’s the most density, but it’s also not way out in the tails (which would mean it is very unlikely).</p>
</section>
<section id="confidence-intervals" class="level3">
<h3 class="anchored" data-anchor-id="confidence-intervals">Confidence Intervals</h3>
<p>So far, we’ve inspected the null distribution and calculated the minimum and maximum values. While the number of purchases in each simulated sample ranged roughly from 25 to 75 by random chance, upon further inspection of the distribution, we saw that those extreme values happened very rarely.</p>
<p>By reporting an interval covering 95% of the values instead of the full range, we can say something like: “we are 95% confident that, if each visitor has a 10% chance of making a purchase, a random sample of 500 visitors will make between 37 and 63 purchases.” We can use the <code>np.percentile()</code> function to calculate this 95% interval as follows:</p>
<div class="cell" data-execution_count="53">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>np.percentile(null_outcomes, [<span class="fl">2.5</span>,<span class="fl">97.5</span>]) <span class="co"># 2.5% data lies below 2.5th percentile and 2.5% data lies above 97.5th percentile</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># A total of 5% is outwith our range, leaving us with a 95% confidence interval</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="53">
<pre><code>array([37., 63.])</code></pre>
</div>
</div>
<p>We calculated the 2.5th and 97.5th percentiles so that exactly 5% of the data falls outside those percentiles (2.5% above the 97.5th percentile, and 2.5% below the 2.5th percentile). This leaves us with a range covering 95% of the data.</p>
<p>If our observed statistic falls outside this interval, then we can conclude it is unlikely that the null hypothesis is true. In this example, because 41 falls within the 95% interval (37 - 63), it is still reasonably likely that we observed a lower purchase rate by random chance, even though the null hypothesis was true.</p>
<blockquote class="blockquote">
<p>Q8. Calculate an interval covering the middle 90% of the values in null_outcomes. Save the output in a variable named <code>null_90CI</code> and print it out. Is the observed value of 41 purchases inside or outside this interval?</p>
</blockquote>
<div class="cell" data-execution_count="55">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>null_90CI <span class="op">=</span> np.percentile(null_outcomes, [<span class="dv">5</span>, <span class="dv">95</span>]) <span class="co"># 5% data lies below 5th percentile and 5% data lies above 95th percentile</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co"># A total of 10% is outwith our range, leaving us with a 90% confidence interval</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(null_90CI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[39. 61.]</code></pre>
</div>
</div>
<p>The observed value of 41 purchases is inside the 90% confidence interval (39 to 61) and so it is still reasonably likely that we observed a lower purchase rate by random chance, even though the null hypothesis was true..</p>
</section>
<section id="calculating-a-one-sided-p-value" class="level3">
<h3 class="anchored" data-anchor-id="calculating-a-one-sided-p-value">Calculating a One-Sided P-Value</h3>
<p><em>P-value</em> calculations and interpretations depend on the <code>alternative hypothesis</code> of a test, a description of the difference from expectation that we are interested in.</p>
<p>For example, let’s return to the 10-coin-flip example from earlier. Suppose that we flipped a coin 10 times and observed only 2 heads. We might run a hypothesis test with the following null and alternative hypotheses:</p>
<ul>
<li>Null: the probability of heads is 0.5</li>
<li>Alternative: the probability of heads is less than 0.5</li>
</ul>
<p>This hypothesis test asks the question: IF the probability of heads is 0.5, what’s the probability of observing 2 or fewer heads among a single sample of 10 coin flips?</p>
<p>Earlier, we used a for-loop to repeatedly (10000 times!) flip a fair coin 10 times, and store the number of heads (for each set of 10 flips) in a list named outcomes. The probability of observing 2 or fewer heads among 10 coin flips is approximately equal to the proportion of those 10000 experiments where we observed 0, 1, or 2 heads:</p>
<div class="cell" data-execution_count="57">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>outcomes <span class="op">=</span> np.array(outcomes)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> np.<span class="bu">sum</span>(outcomes <span class="op">&lt;=</span> <span class="dv">2</span>)<span class="op">/</span><span class="bu">len</span>(outcomes) </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(p_value) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.0552</code></pre>
</div>
</div>
<p>This calculation is equivalent to calculating the proportion of this histogram that is colored in red:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Binomial_Test_files/figure-html/213b3d7c-8174-4176-8a71-019d00c9f32a-1-a66514b0-9b7d-40c2-87e1-735a3cb1f181.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">image.png</figcaption>
</figure>
</div>
<p>We estimated that the probability of observing 2 or fewer heads is about 0.059 (5.9%). This probability (0.059) is referred to as a <code>one-sided p-value</code>.</p>
<blockquote class="blockquote">
<p>Q9. Calculate the proportion of values in <code>null_outcomes</code> that are less than or equal to 41 (the observed number of purchases that we calculated earlier). Save this number as a variable named <code>p_value</code> and print it out.</p>
</blockquote>
<div class="cell" data-execution_count="63">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>null_outcomes <span class="op">=</span> np.array(null_outcomes)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> np.<span class="bu">sum</span>(null_outcomes <span class="op">&lt;=</span> <span class="dv">41</span>)<span class="op">/</span><span class="bu">len</span>(null_outcomes) </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(p_value) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.1014</code></pre>
</div>
</div>
</section>
<section id="calculating-a-two-sided-p-value" class="level3">
<h3 class="anchored" data-anchor-id="calculating-a-two-sided-p-value">Calculating a Two-Sided P-Value</h3>
<p>In the previous exercise, we calculated a one-sided p-value. In this exercise, we’ll estimate a p-value for a 2-sided test, which is the default setting for many functions in Python (and other languages, like R!).</p>
<p>In our 10-coin-flip experiment, remember that we observed 2 heads, which is 3 less than the expected value of 5 (50% of 10) if the null hypothesis is true. The two sided test focuses on the number of heads being three different from expectation, rather than just less than. The hypothesis test now asks the following question:</p>
<p>Suppose that the true probability of heads is 50%. What is the probability of observing either two or fewer heads OR eight or more heads? (Note that two and eight are both three away from five). The calculation now estimates the proportion of the null histogram that is colored in red:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Binomial_Test_files/figure-html/609d0b24-a0be-4861-8f79-d1b8c59b4f12-1-8515bc2b-e547-4742-8c34-70a623e59fb2.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">image.png</figcaption>
</figure>
</div>
<p>This proportion can be calculated in Python as follows. Note that the | symbol is similar to ‘or’, but works for comparing multiple values at once.</p>
<div class="cell" data-execution_count="64">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>outcomes <span class="op">=</span> np.array(outcomes)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> np.<span class="bu">sum</span>((outcomes <span class="op">&lt;=</span> <span class="dv">2</span>) <span class="op">|</span> (outcomes <span class="op">&gt;=</span> <span class="dv">8</span>))<span class="op">/</span><span class="bu">len</span>(outcomes)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(p_value) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.1042</code></pre>
</div>
</div>
<p>We end up with a p-value that is twice as large as the one-sided p-value.</p>
<blockquote class="blockquote">
<p>Q10. Use null_outcomes to calculate the p-value for a two-sided test. In other words, calculate the proportion of values in null_outcomes that are less than or equal to 41 (the number of purchases we observed in our sample, which is 9 fewer than 50) OR greater than or equal to 59 (which is 9 purchases more than 50). Save this number as a variable named p_value and print it out.</p>
</blockquote>
<div class="cell" data-execution_count="66">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> np.<span class="bu">sum</span>((null_outcomes <span class="op">&lt;=</span> <span class="dv">41</span>) <span class="op">|</span> (null_outcomes <span class="op">&gt;=</span> <span class="dv">59</span>))<span class="op">/</span><span class="bu">len</span>(null_outcomes)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(p_value) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.2012</code></pre>
</div>
</div>
</section>
<section id="writing-a-binomial-test-function" class="level3">
<h3 class="anchored" data-anchor-id="writing-a-binomial-test-function">Writing a Binomial Test Function</h3>
<p>The following function named <code>simulation_binomial_test()</code> takes in any values for the following:</p>
<ul>
<li>The observed sample statistic (eg., 41 purchases)</li>
<li>The sample size (eg., 500 visitors)</li>
<li>The null probability of success (eg., 0.10 probability of a purchase)</li>
</ul>
<p>The function should return a p-value for a one-sided test where the alternative hypothesis is that the true probability of success is LESS THAN the null.</p>
<div class="cell" data-execution_count="67">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> binom_test</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> simulation_binomial_test(observed_successes, n, p): <span class="co"># observed sample statistic, sample size, null prob of success</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#initialize null_outcomes</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  null_outcomes <span class="op">=</span> []</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#generate the simulated null distribution</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10000</span>):</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>    simulated_monthly_visitors <span class="op">=</span> np.random.choice([<span class="st">'y'</span>, <span class="st">'n'</span>], size<span class="op">=</span>n, p<span class="op">=</span>[p, <span class="dv">1</span> <span class="op">-</span> p])</span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>    num_purchased <span class="op">=</span> np.<span class="bu">sum</span>(simulated_monthly_visitors <span class="op">==</span> <span class="st">'y'</span>)</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>    null_outcomes.append(num_purchased)</span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a>  <span class="co">#calculate a 1-sided p-value</span></span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a>  null_outcomes <span class="op">=</span> np.array(null_outcomes)</span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a>  p_value <span class="op">=</span> np.<span class="bu">sum</span>(null_outcomes <span class="op">&lt;=</span> observed_successes)<span class="op">/</span><span class="bu">len</span>(null_outcomes) </span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb45-19"><a href="#cb45-19" aria-hidden="true" tabindex="-1"></a>  <span class="co">#return the p-value</span></span>
<span id="cb45-20"><a href="#cb45-20" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> p_value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="68">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Test your function below by uncommenting the code below. You should see that your simulation function gives you a very similar answer to the binom_test function from scipy:</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>p_value1 <span class="op">=</span> simulation_binomial_test(<span class="dv">45</span>, <span class="dv">500</span>, <span class="fl">.1</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"simulation p-value: "</span>, p_value1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>simulation p-value:  0.2564</code></pre>
</div>
</div>
<div class="cell" data-execution_count="69">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>p_value2 <span class="op">=</span> binom_test(<span class="dv">45</span>, <span class="dv">500</span>, <span class="fl">.1</span>, alternative <span class="op">=</span> <span class="st">'less'</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"binom_test p-value: "</span>, p_value2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>binom_test p-value:  0.254689260562342</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_747/436983038.py:1: DeprecationWarning: 'binom_test' is deprecated in favour of 'binomtest' from version 1.7.0 and will be removed in Scipy 1.12.0.
  p_value2 = binom_test(45, 500, .1, alternative = 'less')</code></pre>
</div>
</div>
</section>
<section id="binomial-testing-with-scipy" class="level3">
<h3 class="anchored" data-anchor-id="binomial-testing-with-scipy">Binomial Testing with SciPy</h3>
<p>More formally, the binomial distribution describes the number of expected “successes” in an experiment with some number of “trials”. In the example you just worked through, the experiment consisted of 500 people visiting Live-it-LIVE.com. For each of those trials (visitors), we expected a 10% chance of a purchase (success), but observed only 41 successes (less than 10%).</p>
<p>SciPy has a function called binom_test(), which performs a binomial test for you. The default alternative hypothesis for the binom_test() function is two-sided, but this can be changed using the alternative parameter (eg., alternative = ‘less’ will run a one-sided lower tail test).</p>
<p>binom_test() requires three inputs, the number of observed successes, the number of total trials, and an expected probability of success. For example, with 10 flips of a fair coin (trials), the expected probability of heads is 0.5. Let’s imagine we get 2 heads (observed successes) in 10 flips. Is the coin weighted? The function call for this binomial test would look like:</p>
<div class="cell" data-execution_count="73">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> binomtest</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> binomtest(<span class="dv">2</span>, n<span class="op">=</span><span class="dv">10</span>, p<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(p_value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>BinomTestResult(k=2, n=10, alternative='two-sided', statistic=0.2, pvalue=0.109375)</code></pre>
</div>
</div>
<p>This tells us that IF the true probability of heads is 0.5, the probability of observing 2 or fewer heads OR 8 or more heads is 0.109 (10.9%).</p>
<blockquote class="blockquote">
<p>Q10. Use the <code>binomtest</code> function to run the same binomial test that you just simulated: A two-sided test for whether the observed 41 purchases among 500 visitors to Live-it-LIVE.com is far enough from the expected 10% purchase rate to convince you that the purchase rate was different from expectation this week. Save the p-value as <code>p_value_2sided</code> and print it out. Is this p-value similar to what you calculated via simulation?</p>
</blockquote>
<div class="cell" data-execution_count="75">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>p_value_2sided <span class="op">=</span> binomtest(<span class="dv">41</span>, n<span class="op">=</span><span class="dv">500</span>, p<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(p_value_2sided)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>BinomTestResult(k=41, n=500, alternative='two-sided', statistic=0.082, pvalue=0.20456397700682577)</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q11. Run the same hypothesis test as in step 1, but now as a one-sided test where the alternative hypothesis is that the probability of a visitor making a purchase was less than 10% (0.1).</p>
</blockquote>
<div class="cell" data-execution_count="77">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>p_value_1sided <span class="op">=</span> binomtest(<span class="dv">41</span>, n<span class="op">=</span><span class="dv">500</span>, p<span class="op">=</span><span class="fl">0.1</span>, alternative <span class="op">=</span> <span class="st">'less'</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(p_value_1sided)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>BinomTestResult(k=41, n=500, alternative='less', statistic=0.082, pvalue=0.10011352697567102)</code></pre>
</div>
</div>
</section>
<section id="review" class="level3">
<h3 class="anchored" data-anchor-id="review">Review</h3>
<p>You now know how to run a binomial hypothesis test using a SciPy function — or by simulating it yourself! This will serve you well as a data scientist because it will enable you to investigate what’s going on if pre-written functions return surprising results. You also now have a conceptual understanding of how a binomial test works and what questions it aims to answer. To summarize, here are some of the things you’ve learned about hypothesis tests in general:</p>
<p>All hypothesis tests start with a null and alternative hypothesis</p>
<p>Outcomes of a hypothesis test that might be reported include:</p>
<ul>
<li>confidence intervals</li>
<li>p-values</li>
</ul>
<p>A hypothesis test can be simulated by:</p>
<ul>
<li>taking repeated random samples where the null hypothesis is assumed to be true</li>
<li>using those simulated samples to generate a null distribution</li>
<li>comparing an observed sample statistic to that null distribution</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> binom_test</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> simulation_binomial_test(observed_successes, n, p, alternative_hypothesis):</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#initialize null_outcomes</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>  null_outcomes <span class="op">=</span> []</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#generate the simulated null distribution</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10000</span>):</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>    simulated_monthly_visitors <span class="op">=</span> np.random.choice([<span class="st">'y'</span>, <span class="st">'n'</span>], size<span class="op">=</span>n, p<span class="op">=</span>[p, <span class="dv">1</span><span class="op">-</span>p])</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>    num_purchased <span class="op">=</span> np.<span class="bu">sum</span>(simulated_monthly_visitors <span class="op">==</span> <span class="st">'y'</span>)</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>    null_outcomes.append(num_purchased)</span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>  null_outcomes <span class="op">=</span> np.array(null_outcomes)</span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> alternative_hypothesis <span class="op">==</span> <span class="st">'less'</span>:</span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>    p_value <span class="op">=</span> np.<span class="bu">sum</span>(null_outcomes <span class="op">&lt;=</span> observed_successes)<span class="op">/</span><span class="bu">len</span>(null_outcomes) </span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a>  <span class="cf">elif</span> alternative_hypothesis <span class="op">==</span> <span class="st">'greater'</span>:</span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a>    p_value <span class="op">=</span> np.<span class="bu">sum</span>(null_outcomes <span class="op">&gt;=</span> observed_successes)<span class="op">/</span><span class="bu">len</span>(null_outcomes)</span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span>:</span>
<span id="cb57-22"><a href="#cb57-22" aria-hidden="true" tabindex="-1"></a>    difference <span class="op">=</span> np.<span class="bu">abs</span>(p<span class="op">*</span>n <span class="op">-</span> observed_successes)</span>
<span id="cb57-23"><a href="#cb57-23" aria-hidden="true" tabindex="-1"></a>    upper <span class="op">=</span> p<span class="op">*</span>n <span class="op">+</span> difference</span>
<span id="cb57-24"><a href="#cb57-24" aria-hidden="true" tabindex="-1"></a>    lower <span class="op">=</span> p<span class="op">*</span>n <span class="op">-</span> difference</span>
<span id="cb57-25"><a href="#cb57-25" aria-hidden="true" tabindex="-1"></a>    p_value <span class="op">=</span> np.<span class="bu">sum</span>((null_outcomes <span class="op">&gt;=</span> upper) <span class="op">|</span> (null_outcomes <span class="op">&lt;=</span> lower))<span class="op">/</span><span class="bu">len</span>(null_outcomes)</span>
<span id="cb57-26"><a href="#cb57-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb57-27"><a href="#cb57-27" aria-hidden="true" tabindex="-1"></a>  <span class="co">#return the p-value</span></span>
<span id="cb57-28"><a href="#cb57-28" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> p_value</span>
<span id="cb57-29"><a href="#cb57-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-30"><a href="#cb57-30" aria-hidden="true" tabindex="-1"></a><span class="co">#Test your function:</span></span>
<span id="cb57-31"><a href="#cb57-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'lower tail one-sided test:'</span>)</span>
<span id="cb57-32"><a href="#cb57-32" aria-hidden="true" tabindex="-1"></a>p_value1 <span class="op">=</span> simulation_binomial_test(<span class="dv">45</span>, <span class="dv">500</span>, <span class="fl">.1</span>, alternative_hypothesis <span class="op">=</span> <span class="st">'less'</span>)</span>
<span id="cb57-33"><a href="#cb57-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"simulation p-value: "</span>, p_value1)</span>
<span id="cb57-34"><a href="#cb57-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-35"><a href="#cb57-35" aria-hidden="true" tabindex="-1"></a>p_value2 <span class="op">=</span> binom_test(<span class="dv">45</span>, <span class="dv">500</span>, <span class="fl">.1</span>, alternative <span class="op">=</span> <span class="st">'less'</span>)</span>
<span id="cb57-36"><a href="#cb57-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"binom_test p-value: "</span>, p_value2)</span>
<span id="cb57-37"><a href="#cb57-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-38"><a href="#cb57-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'upper tail one-sided test:'</span>)</span>
<span id="cb57-39"><a href="#cb57-39" aria-hidden="true" tabindex="-1"></a>p_value1 <span class="op">=</span> simulation_binomial_test(<span class="dv">53</span>, <span class="dv">500</span>, <span class="fl">.1</span>, alternative_hypothesis <span class="op">=</span> <span class="st">'greater'</span>)</span>
<span id="cb57-40"><a href="#cb57-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"simulation p-value: "</span>, p_value1)</span>
<span id="cb57-41"><a href="#cb57-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-42"><a href="#cb57-42" aria-hidden="true" tabindex="-1"></a>p_value2 <span class="op">=</span> binom_test(<span class="dv">53</span>, <span class="dv">500</span>, <span class="fl">.1</span>, alternative <span class="op">=</span> <span class="st">'greater'</span>)</span>
<span id="cb57-43"><a href="#cb57-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"binom_test p-value: "</span>, p_value2)</span>
<span id="cb57-44"><a href="#cb57-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-45"><a href="#cb57-45" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'two-sided test:'</span>)</span>
<span id="cb57-46"><a href="#cb57-46" aria-hidden="true" tabindex="-1"></a>p_value1 <span class="op">=</span> simulation_binomial_test(<span class="dv">42</span>, <span class="dv">500</span>, <span class="fl">.1</span>, alternative_hypothesis <span class="op">=</span> <span class="st">'not_equal'</span>)</span>
<span id="cb57-47"><a href="#cb57-47" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"simulation p-value: "</span>, p_value1)</span>
<span id="cb57-48"><a href="#cb57-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-49"><a href="#cb57-49" aria-hidden="true" tabindex="-1"></a>p_value2 <span class="op">=</span> binom_test(<span class="dv">42</span>, <span class="dv">500</span>, <span class="fl">.1</span>)</span>
<span id="cb57-50"><a href="#cb57-50" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"binom_test p-value: "</span>, p_value2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>