<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Into the Unknown - Movie Statistics Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Into the Unknown</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">Stephen Barrie</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml" rel="" target=""><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Stephen137" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/sjbarrie" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Movie Statistics Project</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#motivation" id="toc-motivation" class="nav-link" data-scroll-target="#motivation">Motivation</a></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset">Dataset</a></li>
  <li><a href="#imdb-score" id="toc-imdb-score" class="nav-link" data-scroll-target="#imdb-score">IMDb Score</a></li>
  <li><a href="#genre" id="toc-genre" class="nav-link" data-scroll-target="#genre">Genre</a></li>
  <li><a href="#runtime" id="toc-runtime" class="nav-link" data-scroll-target="#runtime">Runtime</a></li>
  <li><a href="#relationships" id="toc-relationships" class="nav-link" data-scroll-target="#relationships">Relationships</a></li>
  <li><a href="#runtime-and-imdb-score" id="toc-runtime-and-imdb-score" class="nav-link" data-scroll-target="#runtime-and-imdb-score">Runtime and IMDb Score</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>Explore Netflix data with your new understanding of summary statistics!</p>
<section id="overview" class="level3">
<h3 class="anchored" data-anchor-id="overview">Overview</h3>
<p>In this project, we will practice using summary statistics from real data.</p>
<p>We will:</p>
<ul>
<li>interpret summary statistics in context</li>
<li>make choices about which summary statistics are appropriate based on the situation</li>
<li>answer free-response questions and compare your answers to a sample solution available after you submit your answer</li>
<li>answer toggle questions that can be clicked on to toggle an explanation or solution</li>
<li>explore some really interesting data!</li>
</ul>
<p>As an added bonus, some toggle prompts are labeled “Just for Fun” and don’t have to be answered. These prompts provide extra interesting details about the data for your enjoyment!</p>
</section>
<section id="motivation" class="level3">
<h3 class="anchored" data-anchor-id="motivation">Motivation</h3>
<p>You just got a very cool job in the film industry! Your first assignment is to do some research on the content produced by streaming services in the last few years. You’re putting together information for a report on the kinds of films being produced as well as any patterns that might be worth exploring further.</p>
</section>
<section id="dataset" class="level3">
<h3 class="anchored" data-anchor-id="dataset">Dataset</h3>
<p>You decide to start your research by exploring some data about films and documentaries produced by Netflix. The dataset you’ll be using is a modified version of one found on the website <a href="https://www.kaggle.com/luiscorter/netflix-original-films-imdb-scores">Kaggle</a>. Your dataset includes 503 films with the following variables:</p>
<ul>
<li><code>title</code>: title of the film</li>
<li><code>genre</code>: genre of the film</li>
<li><code>language</code>: primary language of the film</li>
<li><code>year</code>: year the film premiered</li>
<li><code>runtime</code>: length of the film in minutes</li>
<li><code>score</code>: film rating of 1 to 10 (worst to best) from the website IMDb</li>
</ul>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>netflix <span class="op">=</span> pd.read_csv(<span class="st">'data/NetflixOriginals.csv'</span>,  encoding<span class="op">=</span><span class="st">'ISO-8859-1'</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>netflix.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Title</th>
<th data-quarto-table-cell-role="th">Genre</th>
<th data-quarto-table-cell-role="th">Premiere</th>
<th data-quarto-table-cell-role="th">Runtime</th>
<th data-quarto-table-cell-role="th">IMDB Score</th>
<th data-quarto-table-cell-role="th">Language</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Enter the Anime</td>
<td>Documentary</td>
<td>August 5, 2019</td>
<td>58</td>
<td>2.5</td>
<td>English/Japanese</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Dark Forces</td>
<td>Thriller</td>
<td>August 21, 2020</td>
<td>81</td>
<td>2.6</td>
<td>Spanish</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>The App</td>
<td>Science fiction/Drama</td>
<td>December 26, 2019</td>
<td>79</td>
<td>2.6</td>
<td>Italian</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>The Open House</td>
<td>Horror thriller</td>
<td>January 19, 2018</td>
<td>94</td>
<td>3.2</td>
<td>English</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Kaali Khuhi</td>
<td>Mystery</td>
<td>October 30, 2020</td>
<td>90</td>
<td>3.4</td>
<td>Hindi</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Some of the films have multiple languages e.g.&nbsp;from above English/Japanese. Let’s create a new category <code>Multiple</code>. We can do this by creating a custom function which will return <code>Multiple</code> for any fields in the <code>Language</code> column that contain the delimiter <code>/</code> :</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to check if a value contains '/'</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> categorize_language(value):</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="st">'/'</span> <span class="kw">in</span> value:</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">'Multiple'</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Applying the function to create a new 'Category' column</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>netflix[<span class="st">'Language_Category'</span>] <span class="op">=</span> netflix[<span class="st">'Language'</span>].<span class="bu">apply</span>(categorize_language)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>netflix.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Title</th>
<th data-quarto-table-cell-role="th">Genre</th>
<th data-quarto-table-cell-role="th">Premiere</th>
<th data-quarto-table-cell-role="th">Runtime</th>
<th data-quarto-table-cell-role="th">IMDB Score</th>
<th data-quarto-table-cell-role="th">Language</th>
<th data-quarto-table-cell-role="th">Language_Category</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Enter the Anime</td>
<td>Documentary</td>
<td>August 5, 2019</td>
<td>58</td>
<td>2.5</td>
<td>English/Japanese</td>
<td>Multiple</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Dark Forces</td>
<td>Thriller</td>
<td>August 21, 2020</td>
<td>81</td>
<td>2.6</td>
<td>Spanish</td>
<td>Spanish</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>The App</td>
<td>Science fiction/Drama</td>
<td>December 26, 2019</td>
<td>79</td>
<td>2.6</td>
<td>Italian</td>
<td>Italian</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>The Open House</td>
<td>Horror thriller</td>
<td>January 19, 2018</td>
<td>94</td>
<td>3.2</td>
<td>English</td>
<td>English</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Kaali Khuhi</td>
<td>Mystery</td>
<td>October 30, 2020</td>
<td>90</td>
<td>3.4</td>
<td>Hindi</td>
<td>Hindi</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<blockquote class="blockquote">
<p>Q. There are clearly a lot of films that have English as their primary language. Of the 584 films, what proportion have English as their primary language?</p>
</blockquote>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>no_movies <span class="op">=</span> <span class="bu">len</span>(netflix)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>no_movies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>584</code></pre>
</div>
</div>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>language_counts <span class="op">=</span> netflix[<span class="st">'Language_Category'</span>].value_counts()</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>language_counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>English       401
Hindi          33
Spanish        31
Multiple       23
French         20
Italian        14
Portuguese     12
Indonesian      9
Korean          6
Japanese        6
Turkish         5
German          5
Dutch           3
Polish          3
Marathi         3
Filipino        2
Thai            2
Malay           1
Norwegian       1
Swedish         1
Georgian        1
Bengali         1
Tamil           1
Name: Language_Category, dtype: int64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the count for 'English' category</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>english_count <span class="op">=</span> language_counts.get(<span class="st">'English'</span>, <span class="dv">0</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>english_count</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>401</code></pre>
</div>
</div>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'The proportion of the </span><span class="sc">{</span>no_movies<span class="sc">}</span><span class="ss"> films that have English as their primary language is </span><span class="sc">{</span>english_count <span class="op">/</span> no_movies <span class="op">*</span> <span class="dv">100</span> <span class="sc">:.2f}</span><span class="ss">%.'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The proportion of the 584 films that have English as their primary language is 68.66%.</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q. What is the ratio of English-language films to films in a single language that is NOT English?</p>
</blockquote>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the count for 'Multiple' category</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>multiple_count <span class="op">=</span> language_counts.get(<span class="st">'Multiple'</span>, <span class="dv">0</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>multiple_count</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>23</code></pre>
</div>
</div>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>other_single_language <span class="op">=</span> no_movies <span class="op">-</span> english_count <span class="op">-</span> multiple_count</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>other_single_language</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>160</code></pre>
</div>
</div>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'The ratio of the </span><span class="sc">{</span>english_count<span class="sc">}</span><span class="ss"> English language films to the </span><span class="sc">{</span>other_single_language<span class="sc">}</span><span class="ss"> films in a single language that is NOT English is </span><span class="sc">{</span>english_count <span class="op">/</span> other_single_language <span class="sc">:.2f}</span><span class="ss">:1.'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The ratio of the 401 English language films to the 160 films in a single language that is NOT English is 2.51:1.</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q. About 4% of the films have multiple primary languages. Find out which genres tend to have this interesting feature.</p>
</blockquote>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>multiple <span class="op">=</span> netflix.query(<span class="st">'Language_Category == "Multiple"'</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>multiple.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Title</th>
<th data-quarto-table-cell-role="th">Genre</th>
<th data-quarto-table-cell-role="th">Premiere</th>
<th data-quarto-table-cell-role="th">Runtime</th>
<th data-quarto-table-cell-role="th">IMDB Score</th>
<th data-quarto-table-cell-role="th">Language</th>
<th data-quarto-table-cell-role="th">Language_Category</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Enter the Anime</td>
<td>Documentary</td>
<td>August 5, 2019</td>
<td>58</td>
<td>2.5</td>
<td>English/Japanese</td>
<td>Multiple</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">30</td>
<td>After Maria</td>
<td>Documentary</td>
<td>May 24, 2019</td>
<td>37</td>
<td>4.6</td>
<td>English/Spanish</td>
<td>Multiple</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">126</td>
<td>Bomb Scared</td>
<td>Black comedy</td>
<td>October 12, 2017</td>
<td>89</td>
<td>5.6</td>
<td>Spanish/Basque</td>
<td>Multiple</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">263</td>
<td>A Tale of Two Kitchens</td>
<td>Documentary</td>
<td>May 22, 2019</td>
<td>30</td>
<td>6.3</td>
<td>English/Spanish</td>
<td>Multiple</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">287</td>
<td>The Outsider</td>
<td>Crime drama</td>
<td>March 9, 2018</td>
<td>120</td>
<td>6.3</td>
<td>English/Japanese</td>
<td>Multiple</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>multiple.Genre.value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>Documentary         17
Drama                2
Black comedy         1
Crime drama          1
Action-adventure     1
War drama            1
Name: Genre, dtype: int64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>genre_counts <span class="op">=</span> netflix[<span class="st">'Genre'</span>].value_counts()</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>genre_counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>Documentary                             159
Drama                                    77
Comedy                                   49
Romantic comedy                          39
Thriller                                 33
                                       ... 
Romantic comedy-drama                     1
Heist film/Thriller                       1
Musical/Western/Fantasy                   1
Horror anthology                          1
Animation/Christmas/Comedy/Adventure      1
Name: Genre, Length: 115, dtype: int64</code></pre>
</div>
</div>
</section>
<section id="imdb-score" class="level3">
<h3 class="anchored" data-anchor-id="imdb-score">IMDb Score</h3>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>netflix[<span class="st">'IMDB Score'</span>].describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>count    584.000000
mean       6.271747
std        0.979256
min        2.500000
25%        5.700000
50%        6.350000
75%        7.000000
max        9.000000
Name: IMDB Score, dtype: float64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>netflix[<span class="st">'IMDB Score'</span>].hist()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>&lt;AxesSubplot: &gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Movie_Stats_Project_files/figure-html/cell-17-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>The distribution of IMDb scores is mostly symmetrical in a bell shape, indicating a normal distribution. There are a couple of very low scores, but they are not far from the rest of the distribution, so they may not be extreme enough to be considered outliers. Since the distribution is fairly symmetrical, we can rely on the mean of 6.3 to give us a good idea of what a typical IMDb rating is. With a standard deviation of 1, we know there is some variation in scores, but most scores fall between 4 and 8 on the 1-10 scale.</p>
<blockquote class="blockquote">
<p>Q. Find out which films got the highest and lowest IMDb scores!</p>
</blockquote>
<p>We can sort the IMDb scores in descending order :</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>highest_score <span class="op">=</span> netflix[<span class="st">'IMDB Score'</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>highest_score</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>583    9.0
582    8.6
581    8.5
580    8.4
579    8.4
      ... 
4      3.4
3      3.2
2      2.6
1      2.6
0      2.5
Name: IMDB Score, Length: 584, dtype: float64</code></pre>
</div>
</div>
<p>We can then use <code>.iloc</code> to grab row 583 with the highest score of 9.0 :</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(netflix.iloc[<span class="dv">583</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Title                David Attenborough: A Life on Our Planet
Genre                                             Documentary
Premiere                                      October 4, 2020
Runtime                                                    83
IMDB Score                                                9.0
Language                                              English
Language_Category                                     English
Name: 583, dtype: object</code></pre>
</div>
</div>
<p>We can sort the IMDb scores in ascending order (by default):</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>lowest_score <span class="op">=</span> netflix[<span class="st">'IMDB Score'</span>].sort_values()</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>lowest_score</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<pre><code>0      2.5
1      2.6
2      2.6
3      3.2
4      3.4
      ... 
579    8.4
580    8.4
581    8.5
582    8.6
583    9.0
Name: IMDB Score, Length: 584, dtype: float64</code></pre>
</div>
</div>
<p>We can then use <code>.iloc</code> to grab rows 0 with the lowest score of 2.5 :</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(netflix.iloc[<span class="dv">0</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Title                 Enter the Anime
Genre                     Documentary
Premiere               August 5, 2019
Runtime                            58
IMDB Score                        2.5
Language             English/Japanese
Language_Category            Multiple
Name: 0, dtype: object</code></pre>
</div>
</div>
</section>
<section id="genre" class="level3">
<h3 class="anchored" data-anchor-id="genre">Genre</h3>
<p>Genre is a categorical variable — this variable gives information about a quality of the films that is non-numeric. We can describe categorical variables using frequencies, proportions, and ratios.</p>
<p>Our colleague might create a table showing the different genre categories, the count of films in each category (frequency), and the percentage of the total this count represents (proportion). Our colleague might also compare counts of genres to one another using ratios.</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>genre_counts <span class="op">=</span> netflix[<span class="st">'Genre'</span>].value_counts()</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>genre_counts</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>Documentary                             159
Drama                                    77
Comedy                                   49
Romantic comedy                          39
Thriller                                 33
                                       ... 
Romantic comedy-drama                     1
Heist film/Thriller                       1
Musical/Western/Fantasy                   1
Horror anthology                          1
Animation/Christmas/Comedy/Adventure      1
Name: Genre, Length: 115, dtype: int64</code></pre>
</div>
</div>
</section>
<section id="runtime" class="level3">
<h3 class="anchored" data-anchor-id="runtime">Runtime</h3>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>netflix.Runtime.hist()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>&lt;AxesSubplot: &gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Movie_Stats_Project_files/figure-html/cell-23-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>netflix.Runtime.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>count    584.000000
mean      93.577055
std       27.761683
min        4.000000
25%       86.000000
50%       97.000000
75%      108.000000
max      209.000000
Name: Runtime, dtype: float64</code></pre>
</div>
</div>
<p>There are two aspects of this distribution plot that might lead to concern about using the mean and standard deviation:</p>
<ul>
<li>The distribution is left-skewed — it has a long tail of low values on the left side. These values might influence the mean to be lower.</li>
<li>There is a single high value of just above 200 minutes. This value might be an outlier that influences the mean to be higher.</li>
</ul>
<p>The mean describes a typical runtime as in the low 90s. The standard deviation describes the distribution as having wide variability, with runtimes an average of almost 30 minutes different than the mean. These measurements are not wrong, but they don’t help us do a good job of summarizing what we’re seeing in the distribution.</p>
<p>We could use statistics that are more robust to outliers and skewness, such as the median and interquartile range (IQR). The median is the middle (50%) value i.e.&nbsp;97mins (and the IQR is the range of the middle 50% of the data (75% - 25%) i.e.&nbsp;(108 - 86) = 22 mins.</p>
<p>The median describes a higher runtime as most typical. The low IQR indicates that half the values aren’t very far from the center value. These descriptions better match the large number of values near 100 that we see in the distribution plot.</p>
<p>Since the mean is less than the median, it seems like the left-skew is more influential on the mean than the high potential outlier is.</p>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>netflix.Runtime.sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>561    209
328    155
581    153
247    151
284    151
      ... 
498     11
66      10
325      9
417      7
40       4
Name: Runtime, Length: 584, dtype: int64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>netflix.iloc[<span class="dv">561</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>Title                     The Irishman
Genre                      Crime drama
Premiere             November 27, 2019
Runtime                            209
IMDB Score                         7.8
Language                       English
Language_Category              English
Name: 561, dtype: object</code></pre>
</div>
</div>
</section>
<section id="relationships" class="level3">
<h3 class="anchored" data-anchor-id="relationships">Relationships</h3>
<p>Next, you want to explore some relationships between variables. Aggregating data across genres and languages may give you some insights.</p>
<section id="scores-by-genre" class="level4">
<h4 class="anchored" data-anchor-id="scores-by-genre">Scores by Genre</h4>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by 'Genre' and calculate mean and standard deviation</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  The reset_index() is used to make the grouped data a DataFrame instead of a Series</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>score_genre <span class="op">=</span> netflix.groupby(<span class="st">'Genre'</span>)[<span class="st">'IMDB Score'</span>].agg([<span class="st">'mean'</span>, <span class="st">'std'</span>]).reset_index()</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the grouped data back to the original DataFrame</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>netflix <span class="op">=</span> pd.merge(netflix, score_genre, on<span class="op">=</span><span class="st">'Genre'</span>, how<span class="op">=</span><span class="st">'left'</span>, suffixes<span class="op">=</span>(<span class="st">''</span>, <span class="st">'_grouped'</span>))</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the updated DataFrame</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>netflix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Title</th>
<th data-quarto-table-cell-role="th">Genre</th>
<th data-quarto-table-cell-role="th">Premiere</th>
<th data-quarto-table-cell-role="th">Runtime</th>
<th data-quarto-table-cell-role="th">IMDB Score</th>
<th data-quarto-table-cell-role="th">Language</th>
<th data-quarto-table-cell-role="th">Language_Category</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Enter the Anime</td>
<td>Documentary</td>
<td>August 5, 2019</td>
<td>58</td>
<td>2.5</td>
<td>English/Japanese</td>
<td>Multiple</td>
<td>6.936478</td>
<td>0.843172</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Dark Forces</td>
<td>Thriller</td>
<td>August 21, 2020</td>
<td>81</td>
<td>2.6</td>
<td>Spanish</td>
<td>Spanish</td>
<td>5.563636</td>
<td>0.925276</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>The App</td>
<td>Science fiction/Drama</td>
<td>December 26, 2019</td>
<td>79</td>
<td>2.6</td>
<td>Italian</td>
<td>Italian</td>
<td>4.533333</td>
<td>1.855622</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>The Open House</td>
<td>Horror thriller</td>
<td>January 19, 2018</td>
<td>94</td>
<td>3.2</td>
<td>English</td>
<td>English</td>
<td>4.700000</td>
<td>1.670329</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Kaali Khuhi</td>
<td>Mystery</td>
<td>October 30, 2020</td>
<td>90</td>
<td>3.4</td>
<td>Hindi</td>
<td>Hindi</td>
<td>4.650000</td>
<td>1.767767</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">579</td>
<td>Taylor Swift: Reputation Stadium Tour</td>
<td>Concert Film</td>
<td>December 31, 2018</td>
<td>125</td>
<td>8.4</td>
<td>English</td>
<td>English</td>
<td>7.633333</td>
<td>0.744759</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">580</td>
<td>Winter on Fire: Ukraine's Fight for Freedom</td>
<td>Documentary</td>
<td>October 9, 2015</td>
<td>91</td>
<td>8.4</td>
<td>English/Ukranian/Russian</td>
<td>Multiple</td>
<td>6.936478</td>
<td>0.843172</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">581</td>
<td>Springsteen on Broadway</td>
<td>One-man show</td>
<td>December 16, 2018</td>
<td>153</td>
<td>8.5</td>
<td>English</td>
<td>English</td>
<td>7.133333</td>
<td>1.350309</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">582</td>
<td>Emicida: AmarElo - It's All For Yesterday</td>
<td>Documentary</td>
<td>December 8, 2020</td>
<td>89</td>
<td>8.6</td>
<td>Portuguese</td>
<td>Portuguese</td>
<td>6.936478</td>
<td>0.843172</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">583</td>
<td>David Attenborough: A Life on Our Planet</td>
<td>Documentary</td>
<td>October 4, 2020</td>
<td>83</td>
<td>9.0</td>
<td>English</td>
<td>English</td>
<td>6.936478</td>
<td>0.843172</td>
</tr>
</tbody>
</table>

<p>584 rows × 9 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(score_genre)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Genre      mean       std
0              Action  5.414286  1.112697
1       Action comedy  5.420000  0.791833
2     Action thriller  6.400000       NaN
3    Action-adventure  7.300000       NaN
4     Action-thriller  6.133333  1.026320
..                ...       ...       ...
110               War  6.750000  0.636396
111         War drama  7.100000  0.848528
112        War-Comedy  6.000000       NaN
113           Western  6.066667  1.250333
114      Zombie/Heist  5.900000       NaN

[115 rows x 3 columns]</code></pre>
</div>
</div>
<p>Most of the mean and standard deviation pairs are not far from the overall mean and standard deviation of all IMDb scores (6.3 and 1.0). However, there are a couple of patterns that stand out.</p>
<ul>
<li>The “Romance/Romantic Comedy” genre has the lowest standard deviation at 0.6. This may indicate this genre was pretty consistent in getting scores close to the mean of 5.9.</li>
<li>The “Action/Sci-Fi” and “Comedy” genres had similar mean scores to “Romance/Romantic Comedy” but a wider spread of scores.</li>
<li>The “Documentary” genre had the highest mean IMDb score. Since its standard deviation isn’t particularly large, this may indicate Netflix documentaries tended to rate well fairly consistently.</li>
</ul>
</section>
<section id="runtime-by-language" class="level4">
<h4 class="anchored" data-anchor-id="runtime-by-language">Runtime by Language</h4>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by 'Genre' and calculate mean and standard deviation</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  The reset_index() is used to make the grouped data a DataFrame instead of a Series</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>runtime_lang <span class="op">=</span> netflix.groupby(<span class="st">'Language_Category'</span>)[<span class="st">'Runtime'</span>].agg([<span class="st">'mean'</span>, <span class="st">'std'</span>]).reset_index()</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the grouped data back to the original DataFrame</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>netflix <span class="op">=</span> pd.merge(netflix, runtime_lang, on<span class="op">=</span><span class="st">'Language_Category'</span>, how<span class="op">=</span><span class="st">'left'</span>, suffixes<span class="op">=</span>(<span class="st">''</span>, <span class="st">'_grouped'</span>))</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the updated DataFrame</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>netflix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Title</th>
<th data-quarto-table-cell-role="th">Genre</th>
<th data-quarto-table-cell-role="th">Premiere</th>
<th data-quarto-table-cell-role="th">Runtime</th>
<th data-quarto-table-cell-role="th">IMDB Score</th>
<th data-quarto-table-cell-role="th">Language</th>
<th data-quarto-table-cell-role="th">Language_Category</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
<th data-quarto-table-cell-role="th">mean_grouped</th>
<th data-quarto-table-cell-role="th">std_grouped</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Enter the Anime</td>
<td>Documentary</td>
<td>August 5, 2019</td>
<td>58</td>
<td>2.5</td>
<td>English/Japanese</td>
<td>Multiple</td>
<td>6.936478</td>
<td>0.843172</td>
<td>76.391304</td>
<td>36.869227</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Dark Forces</td>
<td>Thriller</td>
<td>August 21, 2020</td>
<td>81</td>
<td>2.6</td>
<td>Spanish</td>
<td>Spanish</td>
<td>5.563636</td>
<td>0.925276</td>
<td>93.387097</td>
<td>24.556978</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>The App</td>
<td>Science fiction/Drama</td>
<td>December 26, 2019</td>
<td>79</td>
<td>2.6</td>
<td>Italian</td>
<td>Italian</td>
<td>4.533333</td>
<td>1.855622</td>
<td>98.357143</td>
<td>9.328263</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>The Open House</td>
<td>Horror thriller</td>
<td>January 19, 2018</td>
<td>94</td>
<td>3.2</td>
<td>English</td>
<td>English</td>
<td>4.700000</td>
<td>1.670329</td>
<td>91.817955</td>
<td>28.506566</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Kaali Khuhi</td>
<td>Mystery</td>
<td>October 30, 2020</td>
<td>90</td>
<td>3.4</td>
<td>Hindi</td>
<td>Hindi</td>
<td>4.650000</td>
<td>1.767767</td>
<td>115.787879</td>
<td>16.999554</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">579</td>
<td>Taylor Swift: Reputation Stadium Tour</td>
<td>Concert Film</td>
<td>December 31, 2018</td>
<td>125</td>
<td>8.4</td>
<td>English</td>
<td>English</td>
<td>7.633333</td>
<td>0.744759</td>
<td>91.817955</td>
<td>28.506566</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">580</td>
<td>Winter on Fire: Ukraine's Fight for Freedom</td>
<td>Documentary</td>
<td>October 9, 2015</td>
<td>91</td>
<td>8.4</td>
<td>English/Ukranian/Russian</td>
<td>Multiple</td>
<td>6.936478</td>
<td>0.843172</td>
<td>76.391304</td>
<td>36.869227</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">581</td>
<td>Springsteen on Broadway</td>
<td>One-man show</td>
<td>December 16, 2018</td>
<td>153</td>
<td>8.5</td>
<td>English</td>
<td>English</td>
<td>7.133333</td>
<td>1.350309</td>
<td>91.817955</td>
<td>28.506566</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">582</td>
<td>Emicida: AmarElo - It's All For Yesterday</td>
<td>Documentary</td>
<td>December 8, 2020</td>
<td>89</td>
<td>8.6</td>
<td>Portuguese</td>
<td>Portuguese</td>
<td>6.936478</td>
<td>0.843172</td>
<td>91.250000</td>
<td>22.947073</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">583</td>
<td>David Attenborough: A Life on Our Planet</td>
<td>Documentary</td>
<td>October 4, 2020</td>
<td>83</td>
<td>9.0</td>
<td>English</td>
<td>English</td>
<td>6.936478</td>
<td>0.843172</td>
<td>91.817955</td>
<td>28.506566</td>
</tr>
</tbody>
</table>

<p>584 rows × 11 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>runtime_lang</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Language_Category</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Bengali</td>
<td>41.000000</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Dutch</td>
<td>99.666667</td>
<td>5.507571</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>English</td>
<td>91.817955</td>
<td>28.506566</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Filipino</td>
<td>99.500000</td>
<td>7.778175</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>French</td>
<td>92.700000</td>
<td>12.498842</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Georgian</td>
<td>23.000000</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>German</td>
<td>99.600000</td>
<td>9.396808</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>Hindi</td>
<td>115.787879</td>
<td>16.999554</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>Indonesian</td>
<td>103.777778</td>
<td>12.255384</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>Italian</td>
<td>98.357143</td>
<td>9.328263</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>Japanese</td>
<td>99.333333</td>
<td>48.272836</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>Korean</td>
<td>115.833333</td>
<td>22.631100</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>Malay</td>
<td>101.000000</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>Marathi</td>
<td>121.666667</td>
<td>8.736895</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>Multiple</td>
<td>76.391304</td>
<td>36.869227</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>Norwegian</td>
<td>86.000000</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>Polish</td>
<td>98.666667</td>
<td>6.658328</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">17</td>
<td>Portuguese</td>
<td>91.250000</td>
<td>22.947073</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">18</td>
<td>Spanish</td>
<td>93.387097</td>
<td>24.556978</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">19</td>
<td>Swedish</td>
<td>86.000000</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">20</td>
<td>Tamil</td>
<td>101.000000</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">21</td>
<td>Thai</td>
<td>101.000000</td>
<td>22.627417</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">22</td>
<td>Turkish</td>
<td>101.800000</td>
<td>10.592450</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>There are some interesting differences among the means and standard deviations in the table.</p>
<ul>
<li><p>English, Spanish, French, and “other single” films all have around the same average runtime. However, French films have about half the standard deviation of the others. There is a lot less variability in French film runtimes.</p></li>
<li><p>Marathi films have the highest mean runtime at 122 minutes. The low standard deviation of 9 minutes indicates that Marathi films in our dataset are consistently a relatively long runtime.</p></li>
</ul>
</section>
</section>
<section id="runtime-and-imdb-score" class="level3">
<h3 class="anchored" data-anchor-id="runtime-and-imdb-score">Runtime and IMDb Score</h3>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>netflix.plot.scatter(x<span class="op">=</span><span class="st">'Runtime'</span>, y<span class="op">=</span><span class="st">'IMDB Score'</span>, c<span class="op">=</span><span class="st">'blue'</span>, marker<span class="op">=</span><span class="st">'o'</span>, edgecolors<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Set plot labels and title</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'IMDb score by runtime'</span>)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Runtime in minutes'</span>)</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'IMDb score'</span>)</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the plot</span></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Movie_Stats_Project_files/figure-html/cell-31-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation coefficient</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>correlation_coefficient <span class="op">=</span> netflix[<span class="st">'Runtime'</span>].corr(netflix[<span class="st">'IMDB Score'</span>])</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the result</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Correlation coefficient between Runtime and IMDb score: </span><span class="sc">{</span>correlation_coefficient<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Correlation coefficient between Runtime and IMDb score: -0.04089629142078858</code></pre>
</div>
</div>
<p>The correlation coefficient indicates a negative relationship, but the value is so close to zero that we should conclude there’s really no linear relationship between the variables.</p>
<p>The plot does not show any linear relationship between the two variables. The plot mainly shows a cloud of points that aren’t close to the shape of a line. Lower runtimes aren’t associated with particularly low or high IMDb scores. Higher runtimes aren’t associated with particularly low or high IMDb scores.</p>
<p>Most of the films have runtimes between 50 and 150 minutes with varying IMDb scores between about 6.0 and 8.0 across those runtimes in no particular pattern.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>