<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Into the Unknown - STATISTICAL THINKING</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Into the Unknown</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">Stephen Barrie</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml" rel="" target=""><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Stephen137" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/sjbarrie" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">STATISTICAL THINKING</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#describing-categorical-variables" id="toc-describing-categorical-variables" class="nav-link" data-scroll-target="#describing-categorical-variables">Describing Categorical Variables</a></li>
  <li><a href="#describing-numeric-variables" id="toc-describing-numeric-variables" class="nav-link" data-scroll-target="#describing-numeric-variables">Describing Numeric Variables</a></li>
  <li><a href="#mean-and-standard-deviation" id="toc-mean-and-standard-deviation" class="nav-link" data-scroll-target="#mean-and-standard-deviation">Mean and Standard Deviation</a></li>
  <li><a href="#skewed-distributions" id="toc-skewed-distributions" class="nav-link" data-scroll-target="#skewed-distributions">Skewed Distributions</a></li>
  <li><a href="#median-and-iqr" id="toc-median-and-iqr" class="nav-link" data-scroll-target="#median-and-iqr">Median and IQR</a></li>
  <li><a href="#outliers-and-robust-measures" id="toc-outliers-and-robust-measures" class="nav-link" data-scroll-target="#outliers-and-robust-measures">Outliers and Robust Measures</a></li>
  <li><a href="#aggregate-data" id="toc-aggregate-data" class="nav-link" data-scroll-target="#aggregate-data">Aggregate Data</a></li>
  <li><a href="#variable-relationships" id="toc-variable-relationships" class="nav-link" data-scroll-target="#variable-relationships">Variable Relationships</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>Let’s imagine we are working for the city government of the fictional city of Melody Metropolis. The mayor of Melody Metropolis wants to know more about the musicians who currently live in the city. The learning environment shows a dataset we have on musicians living in the city as of last year. How would you describe this dataset? See if you can answer any of the following questions:</p>
<ul>
<li>What does a typical musician’s income look like?</li>
<li>Is there a wide range of musician ages?</li>
<li>What proportion of the musicians in the dataset play guitar?</li>
</ul>
<p>We can try to make generalizations by looking over the rows and columns, but it’s difficult to answer these questions precisely. We need some kind of “data vocabulary” that can help us measure and describe the variables in the dataset. <em>Summary statistics</em> can be used for exactly this purpose!</p>
<p>With a basic understanding of summary statistics, we can communicate and understand a lot more specific information about the musicians in the city. But learning statistics is often associated with a lot of negativity:</p>
<ul>
<li>Memorization of lots of math formulas</li>
<li>Long calculations done by hand</li>
<li>Confusing or meaningless interpretations</li>
</ul>
<p>None of these struggles need to be part of learning to use statistics. In this lesson, we’ll gain a conceptual understanding of how summary statistics can easily help us communicate and interpret our dataset.</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>musician <span class="op">=</span> pd.read_csv(<span class="st">'data/music.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>musician.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 958 entries, 0 to 957
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   age         958 non-null    int64 
 1   income      958 non-null    int64 
 2   title       958 non-null    object
 3   experience  958 non-null    int64 
 4   instrument  958 non-null    object
 5   band        958 non-null    int64 
dtypes: int64(4), object(2)
memory usage: 45.0+ KB</code></pre>
</div>
</div>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>musician.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">income</th>
<th data-quarto-table-cell-role="th">title</th>
<th data-quarto-table-cell-role="th">experience</th>
<th data-quarto-table-cell-role="th">instrument</th>
<th data-quarto-table-cell-role="th">band</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>40</td>
<td>40840</td>
<td>performer</td>
<td>13</td>
<td>guitar</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>54</td>
<td>21689</td>
<td>composer</td>
<td>11</td>
<td>voice</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>37</td>
<td>43153</td>
<td>composer</td>
<td>28</td>
<td>piano</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>47</td>
<td>58113</td>
<td>composer</td>
<td>31</td>
<td>violin</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>52</td>
<td>24518</td>
<td>producer</td>
<td>13</td>
<td>guitar</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="describing-categorical-variables" class="level3">
<h3 class="anchored" data-anchor-id="describing-categorical-variables">Describing Categorical Variables</h3>
<p>To start our summary for the mayor, let’s describe some of the categorical variables in the musician dataset — those variables that contain qualitative information on the city’s musicians. First, let’s look at information about the title variable, which tells us the job title each musician holds.</p>
<p>The following table shows:</p>
<ul>
<li>frequency: the count of musicians for each job title</li>
<li>proportion: the frequency divided by the total number of musicians</li>
<li>percentage: the proportion converted from a decimal to a percentage</li>
</ul>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>musician.astype(<span class="st">'object'</span>).describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">income</th>
<th data-quarto-table-cell-role="th">title</th>
<th data-quarto-table-cell-role="th">experience</th>
<th data-quarto-table-cell-role="th">instrument</th>
<th data-quarto-table-cell-role="th">band</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>958</td>
<td>958</td>
<td>958</td>
<td>958</td>
<td>958</td>
<td>958</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">unique</td>
<td>48</td>
<td>947</td>
<td>5</td>
<td>48</td>
<td>6</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">top</td>
<td>39</td>
<td>35558</td>
<td>performer</td>
<td>14</td>
<td>guitar</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">freq</td>
<td>46</td>
<td>2</td>
<td>333</td>
<td>46</td>
<td>278</td>
<td>619</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="describing-numeric-variables" class="level3">
<h3 class="anchored" data-anchor-id="describing-numeric-variables">Describing Numeric Variables</h3>
<p>Now that we’ve learned about some of the categorical variables in our musician dataset, it’s time to explore some numeric variables — those with quantitative data. There are a lot of ways we can describe the distribution of a numeric variable. A distribution is a function that shows all possible values of a variable and how frequently each value occurs. This may sound pretty technical, but visualizing the distribution can make it easy to understand.</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>musician.age.hist()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>&lt;AxesSubplot: &gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Statistical_Thinking_files/figure-html/cell-7-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>The distribution of musician ages is plotted with age on the x-axis and frequency on the y-axis. From this plot, we can see:</p>
<ul>
<li>Ages range from about 15 to 70</li>
<li>There are few musicians under 30 or over 50 years old</li>
<li>There are a lot of musicians between the ages of 30 and 50</li>
</ul>
<p>This distribution might be considered bell-shaped or hill-shaped and symmetrical. This is actually a very common pattern and is called a <code>normal distribution</code>.</p>
<p>Viewing a plot or knowing a variable is normally distributed gives us some general information, but still nothing specific. We need exact measurements to describe where the center of the distribution is and how wide the values are spread away from that center. There are several sets of statistics we may use for these measurements, and we will need to know when to use which combination.</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>musician.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">income</th>
<th data-quarto-table-cell-role="th">experience</th>
<th data-quarto-table-cell-role="th">band</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>958.000000</td>
<td>958.000000</td>
<td>958.000000</td>
<td>958.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>40.588727</td>
<td>35546.394572</td>
<td>18.575157</td>
<td>0.646138</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>9.324632</td>
<td>11956.462117</td>
<td>9.814587</td>
<td>0.478417</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>18.000000</td>
<td>12728.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>34.000000</td>
<td>25942.500000</td>
<td>11.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>40.000000</td>
<td>33568.000000</td>
<td>17.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>47.000000</td>
<td>43084.250000</td>
<td>27.000000</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>66.000000</td>
<td>83158.000000</td>
<td>51.000000</td>
<td>1.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="mean-and-standard-deviation" class="level3">
<h3 class="anchored" data-anchor-id="mean-and-standard-deviation">Mean and Standard Deviation</h3>
<p>Let’s return to our visualization of the distribution of musician ages.</p>
<ul>
<li>What would you say is the typical age of a musician in Melody Metropolis?</li>
<li>Are most musicians about this age, or are there lots of musicians of many different ages?</li>
</ul>
<p>To answer these questions more specifically, we should take some measurements of our variable.</p>
<ul>
<li><p>The mean, also called the average, describes the center of a numeric distribution by adding all values and dividing by the count.</p></li>
<li><p>The standard deviation describes the spread of values in a numeric distribution relative to the mean. It is calculated by finding the average squared distance from each data point to the mean and square-rooting the result.</p></li>
</ul>
<p>The mean age of musicians is 40.6 years and the standard deviation is about 9.3 years. We might interpret this standard deviation as moderate variability in age. Had the standard deviation been 1 year, we might say there’s hardly any variability in age.</p>
<p>The mean and standard deviation are common choices, especially for normal distributions. Their mathematical formulas have special properties that make them easy to use in other contexts, such as statistical testing. However, the mean and standard deviation are not always the best measurements to describe a distribution.</p>
</section>
<section id="skewed-distributions" class="level3">
<h3 class="anchored" data-anchor-id="skewed-distributions">Skewed Distributions</h3>
<p>As we’re moving through the numeric variables in our musician dataset, we come across some interesting details when we inspect the income variable.</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>musician.income.hist()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>&lt;AxesSubplot: &gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Statistical_Thinking_files/figure-html/cell-9-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>We notice that the shape of the distribution is different than the shape of the age distribution. There are quite a few musicians with higher incomes that are creating a longer tail on the right side. We also notice that the mean indicates that the typical income is 35,546. This value seems a little high since most of the incomes seem to be between 15,000 and 40,000.</p>
<p>What we have learned is that the income distribution is <code>skewed</code>. A skewed distribution is asymmetrical with a steep change in frequency on one side and a flatter, trailing change in frequency on the other. Specifically, the income distribution is right-skewed (also called positively-skewed) because the tail is on the right side.</p>
<p>So why does the mean seem wrong? Remember, the mean is the sum of all the values in the dataset divided by the total count. That sum is made very large by all the higher incomes in that right tail. This makes the mean a greater number than we would like it be. When the data are skewed, the mean may not be the best measure of a typical observation.</p>
<p>There are a number of ways to deal with this issue. We will handle the problem with the income data by taking some alternative measurements.</p>
<p>Another numeric variable from the musician dataset is years of experience working in the field of music. This plot shows what the experience distribution might look like if it is right-skewed like the income distribution is.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Statistical_Thinking_files/figure-html/d769bbc7-aa5d-43ea-8573-4a09a7c4893d-1-1c9214e7-d970-465a-bc10-3f3dbaa700cf.JPG" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">right_skew.JPG</figcaption>
</figure>
</div>
<p>This plot shows what the experience distribution might look like if it is left-skewed.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Statistical_Thinking_files/figure-html/d769bbc7-aa5d-43ea-8573-4a09a7c4893d-2-3c8fd736-dada-4aa4-bacc-70fed96f4c6e.JPG" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">left_skew.JPG</figcaption>
</figure>
</div>
<p>Think about which distribution seems most likely to be true for musicians in Melody Metropolis.</p>
</section>
<section id="median-and-iqr" class="level3">
<h3 class="anchored" data-anchor-id="median-and-iqr">Median and IQR</h3>
<p>Let’s find an alternative measure to the mean. We want to find a value that represents the typical musician income, but we don’t want to use the actual values in the computation because the data are skewed.</p>
<p>One method would be to find the middle value when all values are arranged from smallest to largest. This value is called the <code>median</code>, but it’s also referred to as the 50th percentile or the second quartile (Q2).</p>
<p>Let’s look at some simple data where the median (Q2) is 13. Half the data points are less than 13, and half are greater than 13.</p>
<p>These data span 22 values, ranging from 6 to 28. We could use this as our measure of spread, but what if the highest number wasn’t 28 but 280? The median would still be 13, but now the range is 274 (280-6), which doesn’t tell us a lot about the bulk of the data.</p>
<p>A better measurement might be the <code>interquartile range (IQR)</code>. A quartile is simply a marker for a quarter (25%) of the data.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Statistical_Thinking_files/figure-html/92f33e58-ebed-412a-97e2-f8104de2389a-1-10ac8a23-fab3-455b-b5b5-ec08e0ec6202.JPG" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">iqr.JPG</figcaption>
</figure>
</div>
<ul>
<li>The first quartile marks 25% (Q1 = 10).</li>
<li>The second quartile marks 50% (Q2 = 13 — the median)</li>
<li>The third quartile marks 75% (Q3 = 22)</li>
</ul>
<p>The IQR is the difference between Q3 and Q1 (22-10 = 12), marking the range for just the middle 50% of the data.</p>
<p>Let’s find out how the median and IQR work out for our income data.</p>
<p>This looks better — the median of 33,568 is lower than the mean of 35,546 and seems more typical.</p>
</section>
<section id="outliers-and-robust-measures" class="level3">
<h3 class="anchored" data-anchor-id="outliers-and-robust-measures">Outliers and Robust Measures</h3>
<p>For our income data, the difference between the mean (35,546) and median (33,568) was only about 2,000. You may be wondering: Is the difference ever larger?</p>
<p>Let’s imagine some very famous celebrity musicians have all decided to move to Melody Metropolis. We know celebrities make much more money than the typical musician in our dataset. Say we added three new incomes to the distribution:</p>
<ul>
<li><code>$48 million:</code> Paul McCartney, British musician of the Beatles</li>
<li><code>$57 million:</code> BTS, South Korean K-pop band</li>
<li><code>$81 million:</code> Beyoncé, American singer-songwriter</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Statistical_Thinking_files/figure-html/9846a93a-4948-44ce-8299-a46133f114ee-1-01733612-9a04-4d64-a83f-f5fab3bac270.JPG" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">histogram_revised.JPG</figcaption>
</figure>
</div>
<p>The median appears almost unaffected by the addition of these three gigantic incomes: the median moves from 32,978 to 33,011. However, the mean makes a drastic change from 34,795 to 228,235. The mean is now well beyond even the maximum in the original distribution. An income of 228,235 is definitely not a great measure of the center of our income distribution.</p>
<p>These celebrity incomes are examples of outliers, extreme values that are distant from the rest of the distribution. Just as with skewness, outliers tend to more heavily influence the mean than the median. This same pattern occurs with measures of spread: the standard deviation is more influenced by outliers and skewness than the interquartile range (IQR).</p>
<p>Because the median and IQR are NOT heavily influenced by extreme values, we say they are <code>robust</code>. Robust statistics are often a better choice to measure the center and spread of a distribution that is skewed or has outliers.</p>
</section>
<section id="aggregate-data" class="level3">
<h3 class="anchored" data-anchor-id="aggregate-data">Aggregate Data</h3>
<p>One measure that we haven’t covered that is usually talked about alongside the mean and median is the mode. The mode is defined as the value with the highest frequency, but we can also think of the mode as the value where the peak of the distribution occurs. While not great for computations, the mode can help us identify interesting features in a variable.</p>
<p>For instance, there might be more than one mode, such as in our distribution of years of experience. In the following plot, we can see there’s one peak near the 10-year mark and another near the 30-year mark. We would call this distribution <em>bimodal</em> because it has two modes.</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>musician.experience.hist()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>&lt;AxesSubplot: &gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Statistical_Thinking_files/figure-html/cell-10-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>Sometimes bimodal distributions occur when there are differences across categories of another variable. Given that the city seems to have a lot of young people in bands, let’s see if this pattern is reflected when we find the mean of each category of the band variable.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Statistical_Thinking_files/figure-html/d03dae6f-8728-4785-b643-4a198da535f7-1-1a5b34e5-5178-42b4-a567-4578b6537f91.JPG" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">agg_stats.JPG</figcaption>
</figure>
</div>
<p>These means are very different and very close to the locations of the modes in our plot. This indicates that there may be some differences in experience level between these two groups that are showing up in our distribution plots as two peaks.</p>
<p>By making this separation and then summarizing with the mean, we have <code>aggregated</code> our data. In this case, we have aggregated by summarizing a numeric variable (experience) across each value of a categorical variable (band).</p>
<p>Do you see any other interesting patterns?</p>
</section>
<section id="variable-relationships" class="level3">
<h3 class="anchored" data-anchor-id="variable-relationships">Variable Relationships</h3>
<p>Aggregating data is a way of exploring variable relationships. We specifically looked at relationships between a numeric variable and a categorical variable, but we should also examine relationships between two numeric variables.</p>
<p>For example, we might wonder: Does musician income vary with years of experience? To start, we can take a look at a <code>scatter plot</code> with experience on the x-axis and income on the y-axis. Each point in the plot represents a musician, and the coordinates of that point are the musician’s experience (x) and income (y).</p>
<div class="cell" data-execution_count="77">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>musician.plot.scatter(x<span class="op">=</span><span class="st">'experience'</span>, y<span class="op">=</span><span class="st">'income'</span>, c<span class="op">=</span><span class="st">'blue'</span>, marker<span class="op">=</span><span class="st">'o'</span>, edgecolors<span class="op">=</span><span class="st">'black'</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Set plot labels and title</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Income by experience'</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Experience in years'</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Income in USD'</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the plot</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="Statistical_Thinking_files/figure-html/cell-11-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>The cloud of points in the plot has a pattern. The points move from the lower left to the upper right part of the plot. In other words, lower levels of experience tend to be associated with lower incomes, and higher levels of experience tend to be associated with higher incomes. The points don’t form a perfect line though — there is some variation.</p>
<p>We can describe this relationship more precisely by measuring the <code>correlation coefficient</code>. This number ranges from -1 to +1 and tells us two things about a linear relationship:</p>
<ul>
<li><p><code>Direction:</code> A positive coefficient means that higher values in one variable are associated with higher values in the other. A negative coefficient means higher values in one variable are associated with lower values of the other.</p></li>
<li><p><code>Strength:</code> The farther the coefficient is from 0, the stronger the relationship and the more the points in a scatter plot look like a line.</p></li>
</ul>
<div class="cell" data-execution_count="79">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>correlation_matrix <span class="op">=</span> musician.corr()</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>correlation_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_249/863198317.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = musician.corr()</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="79">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">income</th>
<th data-quarto-table-cell-role="th">experience</th>
<th data-quarto-table-cell-role="th">band</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">age</td>
<td>1.000000</td>
<td>0.012138</td>
<td>0.030573</td>
<td>-0.014856</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">income</td>
<td>0.012138</td>
<td>1.000000</td>
<td>0.736082</td>
<td>-0.370822</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">experience</td>
<td>0.030573</td>
<td>0.736082</td>
<td>1.000000</td>
<td>-0.574383</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">band</td>
<td>-0.014856</td>
<td>-0.370822</td>
<td>-0.574383</td>
<td>1.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The correlation coefficient for income and experience is 0.74 — the relationship is positive and moderately strong.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>