<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Stephen Barrie">
<meta name="dcterms.date" content="2023-01-19">

<title>Into the Unknown - Financial Forecasting in Python</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Into the Unknown</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">Stephen Barrie</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"><i class="bi bi-rss" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Stephen137"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/sjbarrie"><i class="bi bi-linkedin" role="img">
</i> 
 </a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Financial Forecasting in Python</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Forecasting</div>
                <div class="quarto-category">DataCamp</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Stephen Barrie </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 19, 2023</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#income-statements" id="toc-income-statements" class="nav-link active" data-scroll-target="#income-statements">1. Income statements</a>
  <ul class="collapse">
  <li><a href="#tesla-motors-inc." id="toc-tesla-motors-inc." class="nav-link" data-scroll-target="#tesla-motors-inc.">1.1 Tesla Motors Inc.</a></li>
  <li><a href="#forecasting-revenue-for-tesla" id="toc-forecasting-revenue-for-tesla" class="nav-link" data-scroll-target="#forecasting-revenue-for-tesla">1.2 Forecasting revenue for Tesla</a></li>
  </ul></li>
  <li><a href="#balance-sheet-and-forecast-ratios" id="toc-balance-sheet-and-forecast-ratios" class="nav-link" data-scroll-target="#balance-sheet-and-forecast-ratios">2. Balance Sheet and forecast ratios</a>
  <ul class="collapse">
  <li><a href="#calculating-accounts-receivable-debtors" id="toc-calculating-accounts-receivable-debtors" class="nav-link" data-scroll-target="#calculating-accounts-receivable-debtors">2.1 Calculating accounts receivable (debtors)</a></li>
  <li><a href="#bad-debts" id="toc-bad-debts" class="nav-link" data-scroll-target="#bad-debts">2.2 Bad debts</a></li>
  <li><a href="#calculating-accounts-payable-creditors" id="toc-calculating-accounts-payable-creditors" class="nav-link" data-scroll-target="#calculating-accounts-payable-creditors">2.3 Calculating accounts payable (creditors)</a></li>
  <li><a href="#debtor-days-ratio" id="toc-debtor-days-ratio" class="nav-link" data-scroll-target="#debtor-days-ratio">2.4 Debtor days ratio</a></li>
  <li><a href="#days-payable-outstanding" id="toc-days-payable-outstanding" class="nav-link" data-scroll-target="#days-payable-outstanding">2.5 Days payable outstanding</a></li>
  <li><a href="#days-in-inventory" id="toc-days-in-inventory" class="nav-link" data-scroll-target="#days-in-inventory">2.6 Days in inventory</a></li>
  <li><a href="#asset-turnover" id="toc-asset-turnover" class="nav-link" data-scroll-target="#asset-turnover">2.7 Asset Turnover</a></li>
  </ul></li>
  <li><a href="#balance-sheet" id="toc-balance-sheet" class="nav-link" data-scroll-target="#balance-sheet">3. Balance Sheet</a>
  <ul class="collapse">
  <li><a href="#calculating-balance-sheet-ratios-for-ford" id="toc-calculating-balance-sheet-ratios-for-ford" class="nav-link" data-scroll-target="#calculating-balance-sheet-ratios-for-ford">3.1 Calculating Balance Sheet ratios for Ford</a></li>
  <li><a href="#forecasting-the-balance-sheet-for-ford" id="toc-forecasting-the-balance-sheet-for-ford" class="nav-link" data-scroll-target="#forecasting-the-balance-sheet-for-ford">3.2 Forecasting the Balance Sheet for Ford</a></li>
  </ul></li>
  <li><a href="#financial-periods-and-how-to-work-with-them" id="toc-financial-periods-and-how-to-work-with-them" class="nav-link" data-scroll-target="#financial-periods-and-how-to-work-with-them">4. Financial periods and how to work with them</a>
  <ul class="collapse">
  <li><a href="#converting-quarters-into-months" id="toc-converting-quarters-into-months" class="nav-link" data-scroll-target="#converting-quarters-into-months">4.1 Converting quarters into months</a></li>
  <li><a href="#merging-months-into-quarters" id="toc-merging-months-into-quarters" class="nav-link" data-scroll-target="#merging-months-into-quarters">4.2 Merging months into quarters</a></li>
  <li><a href="#the-datetime-library" id="toc-the-datetime-library" class="nav-link" data-scroll-target="#the-datetime-library">4.3 The datetime library</a></li>
  <li><a href="#converting-date-formats---explicit" id="toc-converting-date-formats---explicit" class="nav-link" data-scroll-target="#converting-date-formats---explicit">4.4 Converting date formats - explicit</a></li>
  </ul></li>
  <li><a href="#tips-and-tricks-when-working-with-datasets" id="toc-tips-and-tricks-when-working-with-datasets" class="nav-link" data-scroll-target="#tips-and-tricks-when-working-with-datasets">5. Tips and tricks when working with datasets</a>
  <ul class="collapse">
  <li><a href="#working-with-datasets---month-totals" id="toc-working-with-datasets---month-totals" class="nav-link" data-scroll-target="#working-with-datasets---month-totals">5.1 Working with datasets - month totals</a></li>
  <li><a href="#working-with-datasets---combining-datasets" id="toc-working-with-datasets---combining-datasets" class="nav-link" data-scroll-target="#working-with-datasets---combining-datasets">5.2 Working with datasets - combining datasets</a></li>
  <li><a href="#exporting-data" id="toc-exporting-data" class="nav-link" data-scroll-target="#exporting-data">5.3 Exporting data</a></li>
  </ul></li>
  <li><a href="#assumptions-and-variances-in-forecasts" id="toc-assumptions-and-variances-in-forecasts" class="nav-link" data-scroll-target="#assumptions-and-variances-in-forecasts">6. Assumptions and variances in forecasts</a>
  <ul class="collapse">
  <li><a href="#building-sensitive-forecast-models" id="toc-building-sensitive-forecast-models" class="nav-link" data-scroll-target="#building-sensitive-forecast-models">6.1 Building sensitive forecast models</a></li>
  <li><a href="#weighted-probability" id="toc-weighted-probability" class="nav-link" data-scroll-target="#weighted-probability">6.2 Weighted probability</a></li>
  <li><a href="#market-sentiment" id="toc-market-sentiment" class="nav-link" data-scroll-target="#market-sentiment">6.3 Market sentiment</a></li>
  <li><a href="#dependencies-and-sensitivity" id="toc-dependencies-and-sensitivity" class="nav-link" data-scroll-target="#dependencies-and-sensitivity">6.4 Dependencies and sensitivity</a></li>
  <li><a href="#assigning-dependencies-for-sales-and-cogs" id="toc-assigning-dependencies-for-sales-and-cogs" class="nav-link" data-scroll-target="#assigning-dependencies-for-sales-and-cogs">6.5 Assigning dependencies for sales and COGS</a></li>
  <li><a href="#building-a-sensitivity-analysis-for-gross-profit" id="toc-building-a-sensitivity-analysis-for-gross-profit" class="nav-link" data-scroll-target="#building-a-sensitivity-analysis-for-gross-profit">6.6 Building a sensitivity analysis for gross profit</a></li>
  <li><a href="#assigning-dependencies-for-expenses" id="toc-assigning-dependencies-for-expenses" class="nav-link" data-scroll-target="#assigning-dependencies-for-expenses">6.7 Assigning dependencies for expenses</a></li>
  <li><a href="#build-a-sensitivity-analysis-for-the-net-profit" id="toc-build-a-sensitivity-analysis-for-the-net-profit" class="nav-link" data-scroll-target="#build-a-sensitivity-analysis-for-the-net-profit">6.8 Build a sensitivity analysis for the net profit</a></li>
  <li><a href="#working-with-variances-in-the-forecast" id="toc-working-with-variances-in-the-forecast" class="nav-link" data-scroll-target="#working-with-variances-in-the-forecast">6.9 Working with variances in the forecast</a></li>
  <li><a href="#building-a-gap-analysis-between-forecasts" id="toc-building-a-gap-analysis-between-forecasts" class="nav-link" data-scroll-target="#building-a-gap-analysis-between-forecasts">6.10 Building a gap analysis between forecasts</a></li>
  <li><a href="#setting-dependencies-for-netflix" id="toc-setting-dependencies-for-netflix" class="nav-link" data-scroll-target="#setting-dependencies-for-netflix">6.11 Setting dependencies for Netflix</a></li>
  <li><a href="#calculating-an-alternative-forecast-for-netflix" id="toc-calculating-an-alternative-forecast-for-netflix" class="nav-link" data-scroll-target="#calculating-an-alternative-forecast-for-netflix">6.12 Calculating an alternative forecast for Netflix</a></li>
  </ul></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways">Key takeaways</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p>In <strong>Financial Forecasting in Python</strong>, we will step into the role of CFO and learn how to advise a board of directors on key metrics while building a financial forecast, the basics of income statements and Balance Sheets, and cleaning messy financial data. During this blog we will examine real-life datasets from Netflix, Tesla, and Ford, using the <code>pandas</code> package. Following this blog we will be able to calculate financial metrics, work with assumptions and variances, and build our own forecast in Python.</p>
<section id="income-statements" class="level2">
<h2 class="anchored" data-anchor-id="income-statements">1. Income statements</h2>
<section id="tesla-motors-inc." class="level3">
<h3 class="anchored" data-anchor-id="tesla-motors-inc.">1.1 Tesla Motors Inc.</h3>
<p>In this example we have chosen to download the latest Income Statemet from Tesla Motors Inc.&nbsp;as a csv file. Let’s have a look at our raw data:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/5835c733-56e4-4d0f-b089-9939502a13fe.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">tesla_raw.JPG</figcaption><p></p>
</figure>
</div>
<p>Tesla has a financial year end of 31 December and we have the results for the financial years 2017 to 2021, as well as an additional column headed <code>TTM</code> which stands for <code>trailing twelve months</code> which is the most recent 12 months of data available. We will be using this column together with the historical information to produce a forecast for the 2022 financial year. .</p>
<p>There are some problems with the data. We need to ensure the data is in the desire format and eliminate any headers we don’t want to use. This could be done manually of course but this would require editing the file every time we have new data. Much better to make use of Python, in particular the <code>pandas</code> library.</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get required packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load in our financials</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>income_statement <span class="op">=</span> pd.read_csv(<span class="st">'Data/Income Statement_Annual_As Originally Reported.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s focus our atttention on four key <code>metrics</code> - ‘Gross Profit’, ‘Total Revenue, ’Operating expenses’, and ‘Net Income’. To do this we’ll create a filtered income statement to only show these rows. The filtering code uses the following pattern.</p>
<pre><code>dataframe[dataframe.columnname.isin(list_of_categories)]</code></pre>
<div class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose some interesting metrics</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>interesting_metrics <span class="op">=</span> [<span class="st">'Total Revenue'</span>, <span class="st">'Operating Expenses'</span>, <span class="st">'Gross Profit'</span>, <span class="st">'Net Income'</span>]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for rows containing these metrics</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>filtered_income_statement <span class="op">=</span> income_statement[income_statement.metric.isin(interesting_metrics)]</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># See the result</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>filtered_income_statement</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="36">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>metric</th>
      <th>2017</th>
      <th>2018</th>
      <th>2019</th>
      <th>2020</th>
      <th>2021</th>
      <th>TTM</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Gross Profit</td>
      <td>2222.0</td>
      <td>4042.0</td>
      <td>4069.0</td>
      <td>6630.0</td>
      <td>13606.0</td>
      <td>19923.0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Total Revenue</td>
      <td>11759.0</td>
      <td>21461.0</td>
      <td>24578.0</td>
      <td>31536.0</td>
      <td>53823.0</td>
      <td>74863.0</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Operating Expenses</td>
      <td>-3855.0</td>
      <td>-4295.0</td>
      <td>-3989.0</td>
      <td>-4636.0</td>
      <td>-7110.0</td>
      <td>-7413.0</td>
    </tr>
    <tr>
      <th>19</th>
      <td>Net Income</td>
      <td>-2241.0</td>
      <td>-1063.0</td>
      <td>-775.0</td>
      <td>862.0</td>
      <td>5644.0</td>
      <td>11223.0</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
<section id="forecasting-revenue-for-tesla" class="level3">
<h3 class="anchored" data-anchor-id="forecasting-revenue-for-tesla">1.2 Forecasting revenue for Tesla</h3>
<p>Let’s now append a new column with 2022 Forecast data, which we will assign the header “Forecast”. For this exercise, we would like to set the filtered_income_statement to only show the row ‘Revenue’.</p>
<p>Remember, the TTM column is the most recent 12-month value that we will use for the 2022 forecast. Thus far, we have the following information for 2022:</p>
<p>Total revenues for the 9 months to 30 September 2022 are 57,144 USD millions, up 58% on the 9 months to September 2021, so let’s ignore any seasonality and make a very crude estimate of revenue for 2022 for illustrative purposes of say 80,000 USD millions:</p>
<div class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>revenue_metric <span class="op">=</span> [<span class="st">'Total Revenue'</span>]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for rows containing the revenue metric</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>filtered_income_statement <span class="op">=</span> income_statement[income_statement.metric.isin(revenue_metric)]</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the number of columns in filtered_income_statement</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>n_cols <span class="op">=</span> <span class="bu">len</span>(filtered_income_statement.columns)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Insert a column in the correct position containing the column 'Forecast'</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>filtered_income_statement.insert(n_cols, <span class="st">'Forecast'</span>, <span class="dv">80000</span>) </span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>filtered_income_statement</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="42">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>metric</th>
      <th>2017</th>
      <th>2018</th>
      <th>2019</th>
      <th>2020</th>
      <th>2021</th>
      <th>TTM</th>
      <th>Forecast</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>Total Revenue</td>
      <td>11759.0</td>
      <td>21461.0</td>
      <td>24578.0</td>
      <td>31536.0</td>
      <td>53823.0</td>
      <td>74863.0</td>
      <td>80000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Excellent, we successfully built a new table to include the 2022 forecast from a raw dataset.</p>
</section>
</section>
<section id="balance-sheet-and-forecast-ratios" class="level2">
<h2 class="anchored" data-anchor-id="balance-sheet-and-forecast-ratios">2. Balance Sheet and forecast ratios</h2>
<section id="calculating-accounts-receivable-debtors" class="level3">
<h3 class="anchored" data-anchor-id="calculating-accounts-receivable-debtors">2.1 Calculating accounts receivable (debtors)</h3>
<p>When we sell something on credit, the credit portion is in the balance sheet under ‘Accounts Receivable’ or ‘Debtors’. For example, if credit sales are made in January with a 60-day payback period, they would be recorded in our ‘Debtors’ account in January, but only be paid (released) in March, and so on.</p>
<p>In this exercise, we will create the following lists:</p>
<ul>
<li>The credit sales in the month <code>credits</code>, which in this exercise is 60% of the sale value.</li>
<li>The total accounts receivable <code>debtors</code>, to be calculated as the credits for the current month, plus the credits of the month before, minus the credits of two months before (as we assume the credits from 2 months ago or 60 days, will be repaid by then).</li>
</ul>
<p>We have set an index for the variable <code>month</code>. The <code>month</code> value is set at 0.</p>
<div class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the list for sales, and empty lists for debtors and credits</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>month <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>sales <span class="op">=</span> [<span class="dv">500</span>, <span class="dv">350</span>, <span class="dv">700</span>]</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>debtors <span class="op">=</span> [] </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>credits <span class="op">=</span> []</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the statement to append the calculated figures to the debtors and credits lists</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> mvalue <span class="kw">in</span> sales: </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    credits.append(mvalue <span class="op">*</span> <span class="fl">0.6</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> month <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>        debtors.append(credits[month] <span class="op">+</span> credits[month<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>        debtors.append(credits[month]) </span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    month <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the result</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The ‘Debtors’ are </span><span class="sc">{}</span><span class="st">."</span>.<span class="bu">format</span>(debtors))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The ‘Debtors’ are [300.0, 510.0, 630.0].</code></pre>
</div>
</div>
</section>
<section id="bad-debts" class="level3">
<h3 class="anchored" data-anchor-id="bad-debts">2.2 Bad debts</h3>
<p>When offering credit terms to customers, there is always a risk that the customer does not pay their debt. In the finance world, this is known as “bad debts”.</p>
<p>As we have already recorded sales, we need to record the loss of sales now, as we never received the payment.</p>
<p>This affects both the income statement and the balance sheet. In the income statement, we record a negative value in the sales for the month we write off the debt. In the balance sheet, we need to reduce our debtor’s asset.</p>
<p>The following variables have been defined for January: <code>debtors_jan = 1500</code></p>
<p>In February, we received news that a customer has gone into liquidation. This customer currently owes 500 USD.</p>
<p>We expect to recover 70% of this amount; the rest has to be written off as bad debts.</p>
<div class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>debtors_jan <span class="op">=</span> <span class="dv">1500</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the bad debts for February</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>bad_debts_feb <span class="op">=</span> <span class="dv">500</span> <span class="op">*</span> <span class="fl">0.3</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the feb debtors amount</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>debtors_feb <span class="op">=</span> (debtors_jan<span class="op">-</span> bad_debts_feb)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the debtors for January and the bad debts and the debtors for February</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The debtors are </span><span class="sc">{}</span><span class="st"> in January, </span><span class="sc">{}</span><span class="st"> in February. February's bad debts are </span><span class="sc">{}</span><span class="st"> USD."</span>.<span class="bu">format</span>(debtors_jan, debtors_feb, bad_debts_feb))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The debtors are 1500 in January, 1350.0 in February. February's bad debts are 150.0 USD.</code></pre>
</div>
</div>
<p>You can see that our debtors amount is reduced by the amount of bad debts.</p>
</section>
<section id="calculating-accounts-payable-creditors" class="level3">
<h3 class="anchored" data-anchor-id="calculating-accounts-payable-creditors">2.3 Calculating accounts payable (creditors)</h3>
<p>Now we will look at a scenario where we are the ones being granted credit. This means that we can buy something, but only have to pay for this amount later.</p>
<p>In this exercise, T-Z needs to buy nuts and bolts to produce 1000 units in January and 1200 units in February. The cost of nuts and bolts per unit is 0.25 USD. The credit terms are 50% cash upfront and 50% in 30 days.</p>
<p>Therefore, the creditors’ value, in this case, would be paid the month directly after. This means that the creditors’ value would only reflect the current month’s credit purchases.</p>
<div class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the cost per unit</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>unit_cost <span class="op">=</span> <span class="fl">0.25</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the list for production units and empty list for creditors</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>production <span class="op">=</span> [<span class="dv">1000</span>,<span class="dv">1200</span>]</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>creditors <span class="op">=</span> []</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the accounts payable for January and February</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> mvalue <span class="kw">in</span> production: </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    creditors.append(mvalue <span class="op">*</span> unit_cost <span class="op">*</span> <span class="fl">0.5</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the creditors balance for January and February</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The creditors balance for January and February are </span><span class="sc">{}</span><span class="st"> and </span><span class="sc">{}</span><span class="st"> USD."</span>.<span class="bu">format</span>(creditors[<span class="dv">0</span>], creditors[<span class="dv">1</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The creditors balance for January and February are 125.0 and 150.0 USD.</code></pre>
</div>
</div>
<p>As we can see, the Balance Sheet shows us what our real cash situation looks like, as just because we made a sale does not mean money in the bank, and incurring an expense also does not mean we have to pay it right away!</p>
</section>
<section id="debtor-days-ratio" class="level3">
<h3 class="anchored" data-anchor-id="debtor-days-ratio">2.4 Debtor days ratio</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/cf709952-3233-4304-a146-4a8a9c464373.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">debtors_days_ratio.JPG</figcaption><p></p>
</figure>
</div>
<p>The first ratio we will look at is debtor days. This ratio looks at how many days it takes to receive our money from our debtors. It is usually calculated over a period of 1 financial year.</p>
<p>The following information is available to you:</p>
<ul>
<li>Sales for the year: 12,500 USD</li>
<li>Ending Debtors balance: 650</li>
</ul>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the variables</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>debtors_end <span class="op">=</span> <span class="dv">650</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>sales_tot <span class="op">=</span> <span class="dv">12500</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the debtor days variable</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>ddays_ratio <span class="op">=</span> (debtors_end<span class="op">/</span>sales_tot) <span class="op">*</span> <span class="dv">365</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the result</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The debtor days ratio is </span><span class="sc">{}</span><span class="st">."</span>.<span class="bu">format</span>(ddays_ratio))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The debtor days ratio is 18.98.</code></pre>
</div>
</div>
</section>
<section id="days-payable-outstanding" class="level3">
<h3 class="anchored" data-anchor-id="days-payable-outstanding">2.5 Days payable outstanding</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/93e97b27-ed58-4484-822a-fcd31bdf35be.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">creditors_days_ratio.JPG</figcaption><p></p>
</figure>
</div>
<p>We will now have a look at our accounts payable, or creditors, and a ratio called the Days Payable Outstanding (DPO).</p>
<p>This ratio is an efficiency ratio that measures the average number of days a company takes to pay its suppliers.</p>
<p>T-Z wants to know its days payable outstanding and has asked you to calculate it.</p>
<div class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the variables</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>cogs_tot <span class="op">=</span> <span class="dv">4000</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>creditors_end <span class="op">=</span> <span class="dv">650</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the days payable outstanding</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>dpo <span class="op">=</span> (creditors_end<span class="op">/</span>cogs_tot)<span class="op">*</span><span class="dv">365</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the days payable outstanding</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The days payable outstanding is </span><span class="sc">{}</span><span class="st">."</span>.<span class="bu">format</span>(dpo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The days payable outstanding is 59.3125.</code></pre>
</div>
</div>
</section>
<section id="days-in-inventory" class="level3">
<h3 class="anchored" data-anchor-id="days-in-inventory">2.6 Days in inventory</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/3d8b2a0a-dd5f-4357-8a29-11653949b71d.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">days_in_inventory.JPG</figcaption><p></p>
</figure>
</div>
<p>In this exercise, we will calculate the time it takes for a company to turn inventory into sales (days in inventory or DII ratio) based on the following information:</p>
<div class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>cogs_total <span class="op">=</span> <span class="dv">4000</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>av_inv <span class="op">=</span> <span class="dv">1900</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>sales_tot <span class="op">=</span> <span class="dv">10000</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>ob_assets <span class="op">=</span> <span class="dv">2000</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>cb_assets <span class="op">=</span> <span class="dv">7000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="53">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the dii ratio </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>dii_ratio <span class="op">=</span> (av_inv<span class="op">/</span>cogs_tot)<span class="op">*</span><span class="dv">365</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the result</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The DII ratio is </span><span class="sc">{}</span><span class="st">."</span>.<span class="bu">format</span>(dii_ratio))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The DII ratio is 173.375.</code></pre>
</div>
</div>
</section>
<section id="asset-turnover" class="level3">
<h3 class="anchored" data-anchor-id="asset-turnover">2.7 Asset Turnover</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/5bd1ef99-6bcf-4c89-9977-3aeee7d4f888.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">asset_turnover.JPG</figcaption><p></p>
</figure>
</div>
<p>In this exercise, we will calculate the efficiency of a company’s assets by seeing how the company uses its assets to generate sales (asset turnover ratio):</p>
<div class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the Average Assets</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>av_assets <span class="op">=</span> (ob_assets <span class="op">+</span> cb_assets)<span class="op">/</span><span class="dv">2</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the Asset Turnover Ratio</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>at_ratio <span class="op">=</span> sales_tot<span class="op">/</span>av_assets</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the Asset Turnover Ratio</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The asset turnover ratio is </span><span class="sc">{}</span><span class="st">."</span>.<span class="bu">format</span>(at_ratio))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The asset turnover ratio is 2.2222222222222223.</code></pre>
</div>
</div>
<p>Let’s test our understanding of Balance Sheet ratios:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/aa6a673d-c16f-4f62-9b24-a8639abecd22.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">understanding_ratios.JPG</figcaption><p></p>
</figure>
</div>
</section>
</section>
<section id="balance-sheet" class="level2">
<h2 class="anchored" data-anchor-id="balance-sheet">3. Balance Sheet</h2>
<section id="calculating-balance-sheet-ratios-for-ford" class="level3">
<h3 class="anchored" data-anchor-id="calculating-balance-sheet-ratios-for-ford">3.1 Calculating Balance Sheet ratios for Ford</h3>
<p>Now we will look at a real life example, Ford Inc, a company producing motor vehicles. We will first upload a dataset: <code>balance_sheet</code> with the data for Ford Inc’s Balance Sheet as at 31 December 2017. The sales and cost of sales figures have been provided for 2017 within the <code>Key_Figures_Memo</code> dataset.</p>
<p>We are only interested in one line on the balance sheet, the <code>Receivables</code> (another name for Debtors), and therefore need to create a filter for this. In this exercise, we will use <em>boolean indexing</em> to filter our dataset for Receivables in the <code>metric</code> column. We will first specify our metric of interest (<code>'Receivables'</code>), and then check whether the column of interest has this value in each row. This will generate a boolean series of <code>True</code> and <code>False</code> values. With this series, we can then filter our existing dataset.</p>
<p>Once we have filtered our dataset, we can retrieve the receivables values from the most recent time period and calculate the debtor days ratio.</p>
<div class="cell" data-execution_count="68">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read in the Ford Balance Sheet data</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>balance_sheet <span class="op">=</span> pd.read_csv(<span class="st">'Data/F-Balance-Sheet.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="70">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the filter metric for Receivables</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>receivables_metric <span class="op">=</span> [<span class="st">'Receivables'</span>]</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a boolean series with your metric</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>receivables_filter <span class="op">=</span> balance_sheet.metric.isin(receivables_metric)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the series to filter the dataset</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>filtered_balance_sheet <span class="op">=</span> balance_sheet[receivables_filter]</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>filtered_balance_sheet </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="70">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>metric</th>
      <th>2013-12</th>
      <th>2014-12</th>
      <th>2015-12</th>
      <th>2016-12</th>
      <th>2017-12</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>6</th>
      <td>Receivables</td>
      <td>87309.0</td>
      <td>92819.0</td>
      <td>101975.0</td>
      <td>57368.0</td>
      <td>62809.0</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="72">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bring in values for Sales and Cost of Sales</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>sales<span class="op">=</span><span class="dv">156776</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>cogs<span class="op">=</span><span class="dv">131332</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="73">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># From previous step</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>receivables_metric <span class="op">=</span> [<span class="st">'Receivables'</span>]</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>receivables_filter <span class="op">=</span> balance_sheet.metric.isin(receivables_metric)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>filtered_balance_sheet <span class="op">=</span> balance_sheet[receivables_filter]</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the zeroth value from the last time period (2017-12)</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>debtors_end <span class="op">=</span> filtered_balance_sheet[<span class="st">'2017-12'</span>].iloc[<span class="dv">0</span>]</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the debtor days ratio</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>ddays <span class="op">=</span> (debtors_end<span class="op">/</span>sales) <span class="op">*</span> <span class="dv">365</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the debtor days ratio</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The debtor day ratio is </span><span class="sc">{:.0f}</span><span class="st">. A higher debtors days ratio means it takes longer to collect cash from debtors."</span>.<span class="bu">format</span>(ddays))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The debtor day ratio is 146. A higher debtors days ratio means it takes longer to collect cash from debtors.</code></pre>
</div>
</div>
<p>Next, we will learn how to append this information into our forecast.</p>
</section>
<section id="forecasting-the-balance-sheet-for-ford" class="level3">
<h3 class="anchored" data-anchor-id="forecasting-the-balance-sheet-for-ford">3.2 Forecasting the Balance Sheet for Ford</h3>
<p>Now that we have the ratios for Ford, the management wishes to improve them for the 2018 financial year.</p>
<p>There is one ratio in particular that management would like to be improved – the <code>debtor days</code> ratio, which is currently sitting at 146 days, while better than Nissan (244 days), is still much higher than Toyota, the industry leader (31 days).</p>
<p>Management would like to bring the debtor days down to below 100 days.</p>
<div class="cell" data-execution_count="74">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set target debtor days</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>ddays <span class="op">=</span> <span class="dv">99</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Sales are expected to increase by 10%. Calculate these forecasted sales, <code>f_sales</code> from the existing <code>sales</code> :</p>
<div class="cell" data-execution_count="76">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the forecasted sales </span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>f_sales <span class="op">=</span> sales <span class="op">*</span> <span class="fl">1.10</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>f_sales</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="76">
<pre><code>172453.6</code></pre>
</div>
</div>
<p>We can rearrange the debtor days formula to calculate the closing balance of debtors needed to achieve 99 debtor days :</p>
<div class="cell" data-execution_count="77">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Solve for the forecasted debtors' ending balance</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>f_debtors_end <span class="op">=</span> f_sales <span class="op">*</span> ddays<span class="op">/</span> <span class="dv">365</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"If sales rise by 10% and the debtor days decrease to </span><span class="sc">{:.0f}</span><span class="st"> then the forecasted closing balance for debtors will be </span><span class="sc">{:.0f}</span><span class="st">."</span>.<span class="bu">format</span>(ddays, f_debtors_end))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>If sales rise by 10% and the debtor days decrease to 99 then the forecasted closing balance for debtors will be 46775.</code></pre>
</div>
</div>
<p>Let’s now append a column to include the forecasted debtors:</p>
<div class="cell" data-execution_count="78">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the number of columns in the filtered balance sheet</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>n_cols <span class="op">=</span> <span class="bu">len</span>(filtered_balance_sheet.columns)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Append a Forecast column of the forecasted debtors' end balance</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>filtered_balance_sheet.insert(n_cols, <span class="st">'Forecast'</span>, f_debtors_end)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co"># See the result</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>filtered_balance_sheet</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="78">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>metric</th>
      <th>2013-12</th>
      <th>2014-12</th>
      <th>2015-12</th>
      <th>2016-12</th>
      <th>2017-12</th>
      <th>Forecast</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>6</th>
      <td>Receivables</td>
      <td>87309.0</td>
      <td>92819.0</td>
      <td>101975.0</td>
      <td>57368.0</td>
      <td>62809.0</td>
      <td>46775.086027</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
</section>
<section id="financial-periods-and-how-to-work-with-them" class="level2">
<h2 class="anchored" data-anchor-id="financial-periods-and-how-to-work-with-them">4. Financial periods and how to work with them</h2>
<section id="converting-quarters-into-months" class="level3">
<h3 class="anchored" data-anchor-id="converting-quarters-into-months">4.1 Converting quarters into months</h3>
<p>A company has a challenge in separating data into months. It has received the following data:</p>
<ul>
<li>Quarter 1 = 700</li>
<li>Quarter 2 = 650</li>
</ul>
<p>The split across the months within each quarter is equal. Our goal is to separate this data into a list format containing the amounts per month for the first two quarters.</p>
<div class="cell" data-execution_count="79">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a list for quarters and initialize an empty list qrtlist</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>quarters <span class="op">=</span> [<span class="dv">700</span>, <span class="dv">650</span>]</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>qrtlist <span class="op">=</span> []</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a for loop to split the quarters into months and add to qrtlist</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> qrt <span class="kw">in</span> quarters:</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a> month <span class="op">=</span> <span class="bu">round</span>(qrt <span class="op">/</span> <span class="dv">3</span>, <span class="dv">2</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a> qrtlist <span class="op">=</span> qrtlist <span class="op">+</span> [month, month, month]</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the result</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The values per month for the first two quarters are </span><span class="sc">{}</span><span class="st">."</span>.<span class="bu">format</span>(qrtlist))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The values per month for the first two quarters are [233.33, 233.33, 233.33, 216.67, 216.67, 216.67].</code></pre>
</div>
</div>
</section>
<section id="merging-months-into-quarters" class="level3">
<h3 class="anchored" data-anchor-id="merging-months-into-quarters">4.2 Merging months into quarters</h3>
<p>Now we saw what to do when we wanted to split quarters into months for more detailed monthly information. But what happens when the opposite is true and we wish to combine data into fewer columns? This is typical when dealing with historical data, when monthly details may not be necessary, or when we need a highly consolidated version of the data for a report.</p>
<p>The key here is to create an index, and then only add to the quarter total <code>quarter</code> in cycles of 3, or until the length of the list. We can do this with the following code:</p>
<pre><code>if index % 3 == 0 or index == len(months):</code></pre>
<p>This code checks whether the index divided by three yields a remainder of 0, or if the index is at the end of the list months. Thus, in a loop it will execute the specified code every three months or when it reaches the end of the list.</p>
<p>The monthly sales are already provided in the code as months, containing the sales from the first two quarters, as well as the first month of Q3. Our task is to generate a new list called quarters that contains the quarterly totals from the first three months (which includes the partial total of Q3).</p>
<div class="cell" data-execution_count="80">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a months list, as well as an index, and set the quarter to 0</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>months <span class="op">=</span> [<span class="dv">100</span>, <span class="dv">100</span>, <span class="dv">150</span>, <span class="dv">250</span>, <span class="dv">300</span>, <span class="dv">10</span>, <span class="dv">20</span>]</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>quarter <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>quarters <span class="op">=</span> []</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>index <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create for loop for quarter, print result, and increment the index</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> sales <span class="kw">in</span> months:</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    quarter <span class="op">+=</span> sales</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> index <span class="op">%</span> <span class="dv">3</span> <span class="op">==</span> <span class="dv">0</span> <span class="kw">or</span> index <span class="op">==</span> <span class="bu">len</span>(months):</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>        quarters.append(quarter)</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>        quarter <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>    index <span class="op">=</span> index <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The quarter totals are Q1: </span><span class="sc">{}</span><span class="st">, Q2: </span><span class="sc">{}</span><span class="st">, Q3: </span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(quarters[<span class="dv">0</span>], quarters[<span class="dv">1</span>], quarters[<span class="dv">2</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The quarter totals are Q1: 350, Q2: 560, Q3: 20</code></pre>
</div>
</div>
<p>Let’s have a look at a library that can help us more when working with dates.</p>
</section>
<section id="the-datetime-library" class="level3">
<h3 class="anchored" data-anchor-id="the-datetime-library">4.3 The datetime library</h3>
<p>Sales area A in Europe and Sales area B in Australia have different date formats.</p>
<ul>
<li>Sale A: 4000 on 14/02/2018</li>
<li>Sale B: 3000 on 2 March 2018</li>
</ul>
<p>If we want to consolidate or compare sales periods, we need to convert to the same date format. We can easily do this by using the datetime library and the datetime.strptime(date_string, format) method, using the following directives:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/0b6b67bc-e665-430c-80eb-a8a0f3ebb1bb.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">date_time.JPG</figcaption><p></p>
</figure>
</div>
<div class="cell" data-execution_count="81">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import the datetime python library</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> datetime <span class="im">import</span> datetime</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a dt_object to convert the first date and print the month result</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>dt_object1 <span class="op">=</span> datetime.strptime(<span class="st">'14/02/2018'</span>, <span class="st">'</span><span class="sc">%d</span><span class="st">/%m/%Y'</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dt_object1)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a dt_object to convert the second date and print the month result</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>dt_object2 <span class="op">=</span> datetime.strptime(<span class="st">'2 March 2018'</span>, <span class="st">'</span><span class="sc">%d</span><span class="st"> %B %Y'</span>)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dt_object2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2018-02-14 00:00:00
2018-03-02 00:00:00</code></pre>
</div>
</div>
</section>
<section id="converting-date-formats---explicit" class="level3">
<h3 class="anchored" data-anchor-id="converting-date-formats---explicit">4.4 Converting date formats - explicit</h3>
<p>Let’s revisut one of the dates from the previous exercise.</p>
<ul>
<li>Sale A: 4000 on 14/02/2018</li>
</ul>
<p>We used the <code>datetime</code> library to identify the day <code>d</code>, month <code>m</code>, and year <code>y</code> which could help us to identify data from datasets with different date formats. However, what about a scenario where we want to convert date formats into a specific format?</p>
<p>In this exercise we will convert Sale A from the format 14/02/2018 to the same date format as Sale B (i.e.&nbsp;14 February 2018).</p>
<p>We can do this easily with built-in Python functions. To split a string we can use the .split()method:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/353c7c9f-ab42-439a-9304-5faf1e07abb0.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">split_().JPG</figcaption><p></p>
</figure>
</div>
<div class="cell" data-execution_count="82">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the variable for the datetime to convert</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>dt <span class="op">=</span> <span class="st">'14/02/2018'</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the dictionary for the month values</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>mm <span class="op">=</span> {<span class="st">'01'</span>: <span class="st">'January'</span>, <span class="st">'02'</span>: <span class="st">'February'</span>, <span class="st">'03'</span>: <span class="st">'March'</span>}</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Split the dt string into the different parts</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>day, month, year <span class="op">=</span> dt.split(<span class="st">'/'</span>)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the concatenated date string</span></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(day <span class="op">+</span> <span class="st">' '</span> <span class="op">+</span> mm[<span class="st">'02'</span>] <span class="op">+</span> <span class="st">' '</span> <span class="op">+</span> year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>14 February 2018</code></pre>
</div>
</div>
</section>
</section>
<section id="tips-and-tricks-when-working-with-datasets" class="level2">
<h2 class="anchored" data-anchor-id="tips-and-tricks-when-working-with-datasets">5. Tips and tricks when working with datasets</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/a3bb4aee-9eb5-40ab-b130-381ea244b217.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">challenges.JPG</figcaption><p></p>
</figure>
</div>
<section id="working-with-datasets---month-totals" class="level3">
<h3 class="anchored" data-anchor-id="working-with-datasets---month-totals">5.1 Working with datasets - month totals</h3>
<p>In this exercise, we will be exploring a dataset that has multiple sales in one month. We will create a script that will enable us to identify dates within the same month, and combine them into a new month total, and append this to the table.</p>
<p>We will be using the dataset <code>df</code>, which represents data from one of our sales areas. Print it out in the console to have a look at the data. As you can see, there were two sales in March. We will combine these sales into a single month total. We can iterate over the dataset using the <code>.iteritems()</code> method.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/b1035f7f-c3e6-4ea1-98a1-75dcdf826da5.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">iteritems().JPG</figcaption><p></p>
</figure>
</div>
<p>We will also be using the .split() method.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/2947c5e2-ad41-4d8b-b418-6fd56adb9106.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">split_().JPG</figcaption><p></p>
</figure>
</div>
<div class="cell" data-execution_count="94">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a DataFrame to include our sales data</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(columns<span class="op">=</span>[<span class="st">'Description'</span>,<span class="st">'14-Feb'</span>, <span class="st">'19-Mar'</span>, <span class="st">'22-Mar'</span>])</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>df.loc[<span class="dv">0</span>] <span class="op">=</span> [<span class="st">'Sales'</span>, <span class="dv">3000</span>, <span class="dv">1200</span>, <span class="dv">1500</span>]</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="94">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Description</th>
      <th>14-Feb</th>
      <th>19-Mar</th>
      <th>22-Mar</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Sales</td>
      <td>3000</td>
      <td>1200</td>
      <td>1500</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="107">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the index to start at 0</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>index <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the dictionary for the months</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>tt <span class="op">=</span> {<span class="st">'Jan'</span>: <span class="dv">0</span>, <span class="st">'Feb'</span>: <span class="dv">0</span>, <span class="st">'Mar'</span>: <span class="dv">0</span>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="108">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a for loop that will iterate the date and amount values in the dataset</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> date, amount <span class="kw">in</span> df.iteritems():</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create the if statement to split the day and month, then add it to the new tt variable</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> index <span class="op">&gt;</span> <span class="dv">0</span>: </span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>        day, month <span class="op">=</span> date.split(<span class="st">'-'</span>)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>        tt[month] <span class="op">+=</span><span class="bu">float</span>(amount[<span class="dv">0</span>])</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>    index <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>{'Jan': 0, 'Feb': 3000.0, 'Mar': 2700.0}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_127/3317898835.py:2: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for date, amount in df.iteritems():</code></pre>
</div>
</div>
</section>
<section id="working-with-datasets---combining-datasets" class="level3">
<h3 class="anchored" data-anchor-id="working-with-datasets---combining-datasets">5.2 Working with datasets - combining datasets</h3>
<p>In this example, we will be working with two datasets, df1 and df2. You will notice that they contain different date formatting.</p>
<p>More specifically, df1 specifies the month by the name (e.g.&nbsp;02-Feb-18), whereas df2 specifies the month numerically (e.g.&nbsp;06/01/2018). Additionally, df1 uses a hyphen (-) as a separator, whereas df2 uses a forward slash (/) as a separator.</p>
<p>We will be combining these two datasets to form a consolidated forecast for the quarter. To do this, we will need to parse the different date formats of df1 and df2.</p>
<div class="cell" data-execution_count="109">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a DataFrame to include our sales data</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>df1 <span class="op">=</span> pd.DataFrame(columns<span class="op">=</span>[<span class="st">'02-Feb-18'</span>, <span class="st">'15-Mar-18'</span>])</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>df1.loc[<span class="dv">0</span>] <span class="op">=</span> [<span class="dv">3000</span>, <span class="dv">1200</span>]</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>df1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="109">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>02-Feb-18</th>
      <th>15-Mar-18</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>3000</td>
      <td>1200</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="110">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create an empty dictionary containing total sales for each month initialized to 0</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>totals <span class="op">=</span> {<span class="st">'Jan'</span>: <span class="dv">0</span>, <span class="st">'Feb'</span>: <span class="dv">0</span>, <span class="st">'Mar'</span>: <span class="dv">0</span>}</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># create a dictionary containing the months (Jan, Feb, Mar) and corresponding numbers</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>calendar <span class="op">=</span> {<span class="st">'01'</span>: <span class="st">'Jan'</span>, <span class="st">'02'</span>: <span class="st">'Feb'</span>, <span class="st">'03'</span>: <span class="st">'Mar'</span>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="111">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a for loop to iterate over the items in the first dataset df1</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> date, amount <span class="kw">in</span> df1.iteritems():</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>        day, month, year <span class="op">=</span> date.split(<span class="st">'-'</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>        totals[month] <span class="op">+=</span><span class="bu">float</span>(amount[<span class="dv">0</span>]) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_127/1296325721.py:2: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for date, amount in df1.iteritems():</code></pre>
</div>
</div>
<div class="cell" data-execution_count="112">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a DataFrame to include our sales data</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="op">=</span> pd.DataFrame(columns<span class="op">=</span>[<span class="st">'06/01/2018'</span>, <span class="st">'14/02/2018'</span>])</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>df2.loc[<span class="dv">0</span>] <span class="op">=</span> [<span class="dv">1000</span>, <span class="dv">1200</span>]</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>df2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="112">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>06/01/2018</th>
      <th>14/02/2018</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1000</td>
      <td>1200</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="114">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a for loop to iterate over the items in the second dataset df2</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="co"># This time month will yield a a numerical reference, so we will need to use our calendar dictionary to add the amount to our totals dictionary.</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> date, amount <span class="kw">in</span> df2.iteritems():</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>        day, month, year <span class="op">=</span> date.split(<span class="st">'/'</span>)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>        totals[calendar[month]] <span class="op">+=</span> <span class="bu">float</span>(amount[<span class="dv">0</span>])</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(totals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>{'Jan': 1000.0, 'Feb': 4200.0, 'Mar': 1200.0}</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_127/4206160929.py:3: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for date, amount in df2.iteritems():</code></pre>
</div>
</div>
</section>
<section id="exporting-data" class="level3">
<h3 class="anchored" data-anchor-id="exporting-data">5.3 Exporting data</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/f7c32d26-639a-4f8a-8314-48e4b60fbe4b.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">export.JPG</figcaption><p></p>
</figure>
</div>
</section>
</section>
<section id="assumptions-and-variances-in-forecasts" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-and-variances-in-forecasts">6. Assumptions and variances in forecasts</h2>
<section id="building-sensitive-forecast-models" class="level3">
<h3 class="anchored" data-anchor-id="building-sensitive-forecast-models">6.1 Building sensitive forecast models</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/7974da6c-52e6-4054-96d0-b2b7fad5dd65.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">forecasting_considerations.JPG</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/ac3bd82d-b6d1-40e9-8c87-70ffc33aee09.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">assumptions_2.JPG</figcaption><p></p>
</figure>
</div>
</section>
<section id="weighted-probability" class="level3">
<h3 class="anchored" data-anchor-id="weighted-probability">6.2 Weighted probability</h3>
<p>Txs Tools, a company selling hardware tools, is looking to expand out of their home market A into Market B. They have done some market research, and have received the following numeric probabilities:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/e1fb2bf1-e1a2-4058-afe1-bb158e3ffb25.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">weighted_prob.JPG</figcaption><p></p>
</figure>
</div>
<p>Txs Tools will only be motivated to expand if they can have reasonable assurance that they will achieve sales of 400 or more. To manage the different forecast sales probabilities, Txs Tools have asked us to calculate the weighted probability.</p>
<div class="cell" data-execution_count="116">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the combined list for sales and probability</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>sales_probability <span class="op">=</span> [<span class="st">'0|0.05'</span>, <span class="st">'200|0.10'</span>, <span class="st">'300|0.40'</span>, <span class="st">'500|0.2'</span>, <span class="st">'800|0.25'</span>] </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>weighted_probability <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a for loop to calculate the weighted probability</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> pair <span class="kw">in</span> sales_probability:</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>    parts <span class="op">=</span> pair.split(<span class="st">'|'</span>)</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>    weighted_probability <span class="op">+=</span> <span class="bu">float</span>(parts[<span class="dv">0</span>]) <span class="op">*</span> <span class="bu">float</span>(parts[<span class="dv">1</span>]) <span class="co"># float converts to a floating point </span></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the weighted probability result</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The weighted probability is </span><span class="sc">{}</span><span class="st">."</span>.<span class="bu">format</span>(weighted_probability))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The weighted probability is 440.0.</code></pre>
</div>
</div>
<p>Have a look at the calculated weighted probability. We can see it reflects a weighted value between the highest and lowest sales figures. The weighted probability is a technique to manage the uncertainty in Txs Tools sales forecasting, and can give a more balanced view on expected sales numbers as opposed to just going for the lowest or highest number.</p>
</section>
<section id="market-sentiment" class="level3">
<h3 class="anchored" data-anchor-id="market-sentiment">6.3 Market sentiment</h3>
<p>Txs Tools has forecast sales of 500 in January, with an expected increase of 5% per month for the rest of the quarter.</p>
<p>However, this is dependent on the market sentiment. Based on historical trends, the following information has been provided:</p>
<ul>
<li>If the market sentiment drops below 0.6 then the sales will only be realized at an increase of 2% per month.</li>
<li>If market sentiment increases above 0.8. then sales are expected to increase by 7%.</li>
</ul>
<div class="cell" data-execution_count="117">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the computevariance function</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> computevariance(amount, sentiment):</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a> <span class="cf">if</span> (sentiment <span class="op">&lt;</span> <span class="fl">0.6</span>):</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  res <span class="op">=</span> amount <span class="op">+</span> (amount <span class="op">*</span> <span class="fl">0.02</span>)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a> <span class="cf">elif</span> (sentiment <span class="op">&gt;</span> <span class="fl">0.8</span>):</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  res <span class="op">=</span> amount <span class="op">+</span> (amount <span class="op">*</span> <span class="fl">0.07</span>)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a> <span class="cf">else</span>:</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>  res <span class="op">=</span> amount <span class="op">+</span> (amount <span class="op">*</span> <span class="fl">0.05</span>)</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a> <span class="cf">return</span> res</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="118">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the variance for jan, feb and mar</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>jan <span class="op">=</span> computevariance(<span class="dv">500</span>, <span class="fl">0.5</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>feb <span class="op">=</span> computevariance(<span class="dv">500</span>, <span class="fl">0.65</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>mar <span class="op">=</span> computevariance(<span class="dv">500</span>, <span class="fl">0.85</span>)</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The forecast sales considering variance due to market sentiment is </span><span class="sc">{}</span><span class="st"> for Jan, </span><span class="sc">{}</span><span class="st"> for Feb, and </span><span class="sc">{}</span><span class="st"> for Mar."</span>.<span class="bu">format</span>(jan, feb, mar))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The forecast sales considering variance due to market sentiment is 510.0 for Jan, 525.0 for Feb, and 535.0 for Mar.</code></pre>
</div>
</div>
</section>
<section id="dependencies-and-sensitivity" class="level3">
<h3 class="anchored" data-anchor-id="dependencies-and-sensitivity">6.4 Dependencies and sensitivity</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/ad75655e-bde9-49d3-90df-bfbc7044d537.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">dep_sens.JPG</figcaption><p></p>
</figure>
</div>
</section>
<section id="assigning-dependencies-for-sales-and-cogs" class="level3">
<h3 class="anchored" data-anchor-id="assigning-dependencies-for-sales-and-cogs">6.5 Assigning dependencies for sales and COGS</h3>
<p>Txs Tools have built a monthly forecast for their gross profit. This will rely on dependencies for Sales and COGS.</p>
<p>Set the dependencies for <code>sales</code> and <code>cogs</code> based on the information below:</p>
<ul>
<li><p>Sales dependency <code>sales_dep</code>: The sale price is the net price after 1 USD commission. Commissions paid increase from 1 USD per unit to 2 USD per unit for every unit above 350 units sold.</p></li>
<li><p>Cost dependency <code>cost_dep</code>: When sales per unit increase above 500 units, an additional production line needs to be used, causing an increase in the cost per unit above 500 of 2 USD per unit.</p></li>
</ul>
<p>The baseline sale price per unit <code>(base_sales_price)</code> is 15 USD and the baseline cost per unit <code>(base_cost_price)</code> is 7 USD.</p>
<div class="cell" data-execution_count="129">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># instantiate the base sales price</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>base_sales_price <span class="op">=</span> <span class="dv">15</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co"># instantiate the sales </span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>sales <span class="op">=</span> <span class="dv">750</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="130">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the Sales Dependency</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> sales <span class="op">&gt;=</span> <span class="dv">350</span>:</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>    sales_dep <span class="op">=</span> (<span class="dv">350</span> <span class="op">*</span> base_sales_price) <span class="op">+</span> ((sales <span class="op">-</span> <span class="dv">350</span>) <span class="op">*</span> (base_sales_price <span class="op">-</span> <span class="dv">1</span>))</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>    sales_dep <span class="op">=</span> sales <span class="op">*</span> base_sales_price</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The sales dependency is </span><span class="sc">{}</span><span class="st"> USD."</span>.<span class="bu">format</span>(sales_dep))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The sales dependency is 10850 USD.</code></pre>
</div>
</div>
<div class="cell" data-execution_count="131">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># instantiate the bases cost price </span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>base_cost_price <span class="op">=</span> <span class="dv">7</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="132">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the Cost Dependency</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> sales <span class="op">&gt;=</span> <span class="dv">500</span>:</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>    cost_dep <span class="op">=</span> (<span class="dv">500</span> <span class="op">*</span> base_cost_price) <span class="op">+</span> ((sales <span class="op">-</span> <span class="dv">500</span>) <span class="op">*</span> (base_cost_price <span class="op">+</span> <span class="dv">2</span>))</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>    cost_dep <span class="op">=</span> sales <span class="op">*</span> base_cost_price</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The cost dependency is </span><span class="sc">{}</span><span class="st"> USD."</span>.<span class="bu">format</span>(cost_dep))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The cost dependency is 5750 USD.</code></pre>
</div>
</div>
</section>
<section id="building-a-sensitivity-analysis-for-gross-profit" class="level3">
<h3 class="anchored" data-anchor-id="building-a-sensitivity-analysis-for-gross-profit">6.6 Building a sensitivity analysis for gross profit</h3>
<p>xs Tools is now ready to use these dependencies in the gross profit forecast.</p>
<p>The following forecast unit sales have been provided:</p>
<pre><code>Jul = 700 Aug = 350 Sep = 650</code></pre>
<p>The dependencies for <code>sales</code> and <code>cogs</code> are based on the following:</p>
<ul>
<li><p>Sales dependency <code>sales_dep</code>: The sale price is the net price after 1 USD commission. Commissions paid increase from 1 USD per unit to 2 USD per unit for every unit above 350 units sold.</p></li>
<li><p>Cost dependency <code>cost_dep</code>: When sales per unit increase above 500 units, an additional production line needs to be used, causing an increase in the cost per unit above 500 of 2 USD per unit.</p></li>
</ul>
<p>The basic cost price <code>base_cost_price</code> = 7 and basic sales price <code>base_sales_price</code> = 15</p>
<div class="cell" data-execution_count="134">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the sales_usd list</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>sales_usd <span class="op">=</span> [<span class="dv">700</span>, <span class="dv">350</span>, <span class="dv">650</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="135">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the if statement to calculate the forecast_gross_profit</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> sales <span class="kw">in</span> sales_usd:</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> sales <span class="op">&gt;</span> <span class="dv">350</span>:</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>        sales_dep <span class="op">=</span> (<span class="dv">350</span> <span class="op">*</span> base_sales_price) <span class="op">+</span> ((sales <span class="op">-</span> <span class="dv">350</span>) <span class="op">*</span> (base_sales_price <span class="op">-</span> <span class="dv">1</span>))</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>        sales_dep <span class="op">=</span> sales <span class="op">*</span> base_sales_price</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> sales <span class="op">&gt;</span> <span class="dv">500</span>:</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>        cost_dep <span class="op">=</span> (<span class="dv">500</span> <span class="op">*</span> base_cost_price) <span class="op">+</span> ((sales <span class="op">-</span> <span class="dv">500</span>) <span class="op">*</span> (base_cost_price <span class="op">+</span> <span class="dv">2</span>))</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>        cost_dep <span class="op">=</span> sales <span class="op">*</span> base_cost_price</span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>    forecast_gross_profit <span class="op">=</span> sales_dep <span class="op">-</span> cost_dep</span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Print the result</span></span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"The gross profit forecast for a sale unit value of </span><span class="sc">{}</span><span class="st"> is </span><span class="sc">{}</span><span class="st"> USD."</span>.<span class="bu">format</span>(sales, forecast_gross_profit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The gross profit forecast for a sale unit value of 700 is 4850 USD.
The gross profit forecast for a sale unit value of 350 is 2800 USD.
The gross profit forecast for a sale unit value of 650 is 4600 USD.</code></pre>
</div>
</div>
</section>
<section id="assigning-dependencies-for-expenses" class="level3">
<h3 class="anchored" data-anchor-id="assigning-dependencies-for-expenses">6.7 Assigning dependencies for expenses</h3>
<p>Txs Tools wants to assign a dependency for its operating expenses, particularly admin salaries.</p>
<p>The conditions are as follows:</p>
<ul>
<li><p>Admin expenses increase in July and August (<code>Jul</code> and <code>Aug</code>) as temporary workers need to be hired to cover the summer holiday.</p></li>
<li><p>The increase is based on the number of employees taking holidays during that time. For the current year, the value for August is <code>emp_leave</code> = 6 (6 employees expected to take leave).</p></li>
<li><p>The cost is 80 USD per temp employee hired.</p></li>
</ul>
<div class="cell" data-execution_count="136">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># instantiate the emp leave value for August</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>emp_leave <span class="op">=</span> <span class="dv">6</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="137">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the admin dependency</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> emp_leave <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>    admin_dep <span class="op">=</span> emp_leave <span class="op">*</span> <span class="dv">80</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The admin dependency for August is </span><span class="sc">{}</span><span class="st"> USD."</span>.<span class="bu">format</span>(admin_dep))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The admin dependency for August is 480 USD.</code></pre>
</div>
</div>
</section>
<section id="build-a-sensitivity-analysis-for-the-net-profit" class="level3">
<h3 class="anchored" data-anchor-id="build-a-sensitivity-analysis-for-the-net-profit">6.8 Build a sensitivity analysis for the net profit</h3>
<p>Txs Tools has provided the following forecast admin cost in USD based on full-time employees:</p>
<pre><code>Jul = 1500 Aug = 1500 Sep = 1500</code></pre>
<p>Build the forecast net profit <code>forecast_net_profit</code> when <code>emp_leave</code> = [6, 6, 0] and the cost per temp employee is 80 USD.</p>
<div class="cell" data-execution_count="138">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># instantiate our standing data</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>admin_usd <span class="op">=</span> [<span class="dv">1500</span>, <span class="dv">1500</span>, <span class="dv">1500</span>]</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>emp_leave <span class="op">=</span> [<span class="dv">6</span>, <span class="dv">6</span>, <span class="dv">0</span>]</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>forecast_gross_profit <span class="op">=</span> [<span class="dv">4850</span>, <span class="dv">2800</span>, <span class="dv">4600</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="141">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create an index variable and initialize this index to 0</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>index <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the dependency by looping through the admin_usd list, using our index to access the correct month in our lists.</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> admin <span class="kw">in</span> admin_usd:</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>    temp <span class="op">=</span> emp_leave[index]</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> temp <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>        admin_dep <span class="op">=</span> temp <span class="op">*</span> <span class="dv">80</span> <span class="op">+</span> admin</span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>: </span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>         admin_dep <span class="op">=</span> admin</span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>    forecast_net_profit <span class="op">=</span> forecast_gross_profit[index] <span class="op">-</span> admin_dep</span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(forecast_net_profit)</span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a>    index <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The forecast net profit is: </span><span class="sc">{}</span><span class="st"> USD."</span>.<span class="bu">format</span>(forecast_net_profit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2870
820
3100
The forecast net profit is: 3100 USD.</code></pre>
</div>
</div>
</section>
<section id="working-with-variances-in-the-forecast" class="level3">
<h3 class="anchored" data-anchor-id="working-with-variances-in-the-forecast">6.9 Working with variances in the forecast</h3>
<p>Identifying, quantifying, and investigating the difference between an old forecast and the new forecast is often referred to as <code>Gap Analysis</code>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/1600d6ae-6a85-43ea-84e6-09cfbb5a24df.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">gap_analysis.JPG</figcaption><p></p>
</figure>
</div>
<section id="building-an-alternate-forecast" class="level4">
<h4 class="anchored" data-anchor-id="building-an-alternate-forecast">Building an alternate forecast</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Financial%20Forecasting_files/figure-html/08779f61-11ee-44c7-af63-10f2c0767915.JPG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">alternative_forecasts.JPG</figcaption><p></p>
</figure>
</div>
<p>We will now build an alternative forecast for Txs Tools. The new quarter forecast is based off actual data for Jul - Aug as well as adjusted forecast data for September. The data (units sold) is as follows:</p>
<ul>
<li>Jul = 700</li>
<li>Aug = 220</li>
<li>Sep = 520</li>
</ul>
<p>The dependencies calculations have already been completed from the previous exercise. The following information applies:</p>
<ul>
<li>base_cost_price = 7</li>
<li>base_sales_price = 15</li>
</ul>
<div class="cell" data-execution_count="142">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a dependencies() function for sales and costs with the arguments base_cost_price,base_sales_price, and sales_usd</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Pass the arguments into the function in this order.</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> dependencies(base_cost_price, base_sales_price, sales_usd):</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>    res <span class="op">=</span> []</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> sales <span class="kw">in</span> sales_usd:</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> sales <span class="op">&gt;=</span> <span class="dv">350</span>:</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>            sales_dep <span class="op">=</span> (<span class="dv">350</span> <span class="op">*</span> base_sales_price) <span class="op">+</span> ((sales <span class="op">-</span> <span class="dv">350</span>) <span class="op">*</span> (base_sales_price <span class="op">-</span> <span class="dv">1</span>))</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>            sales_dep <span class="op">=</span> sales <span class="op">*</span> base_sales_price</span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> sales <span class="op">&gt;=</span> <span class="dv">500</span>:</span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>            cost_dep <span class="op">=</span> (<span class="dv">500</span> <span class="op">*</span> base_cost_price) <span class="op">+</span> ((sales <span class="op">-</span> <span class="dv">500</span>) <span class="op">*</span> (base_cost_price <span class="op">+</span> <span class="dv">2</span>))</span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>            cost_dep <span class="op">=</span> sales <span class="op">*</span> base_cost_price</span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a>        res.append(sales_dep <span class="op">-</span> cost_dep)</span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> res</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="144">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create scenario forecast1 for the original forecast</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>forecast1 <span class="op">=</span> dependencies(<span class="dv">7</span>, <span class="dv">15</span>, [<span class="dv">700</span>, <span class="dv">350</span>, <span class="dv">650</span>])</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create scenario forecast2 for the alternative forecast. </span></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the data provided above to calculate the alternative forecast</span></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>forecast2 <span class="op">=</span> dependencies(<span class="dv">7</span>, <span class="dv">15</span>, [<span class="dv">700</span>, <span class="dv">220</span>, <span class="dv">520</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="145">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The original forecast scenario is </span><span class="sc">{}</span><span class="st">:"</span>.<span class="bu">format</span>(forecast1))</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The alternative forecast scenario is </span><span class="sc">{}</span><span class="st">:"</span>.<span class="bu">format</span>(forecast2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The original forecast scenario is [4850, 2800, 4600]:
The alternative forecast scenario is [4850, 1760, 3950]:</code></pre>
</div>
</div>
</section>
</section>
<section id="building-a-gap-analysis-between-forecasts" class="level3">
<h3 class="anchored" data-anchor-id="building-a-gap-analysis-between-forecasts">6.10 Building a gap analysis between forecasts</h3>
<p>Txs Tools now has two forecasts, the original forecast <code>forecast1</code> and the adjusted forecast <code>forecast2</code>.</p>
<p>The dependencies have already been defined as <code>def dependencies(base_cost_price, base_sales_price, sales_usd)</code>, where <code>base_cost_price</code> = 7 and <code>base_sales_price</code> = 15, with <code>forecast2</code> based off the following adjusted sales unit values:</p>
<ul>
<li>Jul = 700</li>
<li>Aug = 220</li>
<li>Sep = 520</li>
</ul>
<p>In this exercise, we will look at how to use a for loop to cycle between two different lists, <code>forecast1</code> and <code>forecast2</code> and calculate the difference (“gap”) using an incremented index. It is possible to do this simultaneously as both lists have the same length.</p>
<div class="cell" data-execution_count="147">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the two results</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>forecast1 <span class="op">=</span> dependencies(<span class="dv">7</span>, <span class="dv">15</span>, [<span class="dv">700</span>, <span class="dv">350</span>, <span class="dv">650</span>])</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>forecast2 <span class="op">=</span> dependencies(<span class="dv">7</span>, <span class="dv">15</span>, [<span class="dv">700</span>, <span class="dv">220</span>, <span class="dv">520</span>])</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create an index and the gap analysis for the forecast</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>index <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> value <span class="kw">in</span> forecast2:</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"The gap between forecasts is </span><span class="sc">{}</span><span class="st">"</span>.<span class="bu">format</span>(value <span class="op">-</span> forecast1[index]))</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>    index <span class="op">+=</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The gap between forecasts is 0
The gap between forecasts is -1040
The gap between forecasts is -650</code></pre>
</div>
</div>
<p>You can see how easy it is to use a for loop to compare results across different lists.</p>
<p>Note that the gap between forecasts is driven purely by the difference in sales volume - base sales and cost prices are unchanged.</p>
<ul>
<li><p>In July forecast2 sales are as per forecast 1 - so no gap.</p></li>
<li><p>In August forecast2 sales are 220 units against 350 - resulting in a gap of 130 units x profit per unit of 8 (15 - 7) which is 1040</p></li>
<li><p>In September forecast2 sales are 520 units against 650 - resulting in a gap of 130 units x profit per unit of 8 (15 - 7) which is 1040, but we also have a saving of 3 per unit (sales commission 1 and additional production line cost 2) which reduces the gap by 130 x 3 = 390 to 650.</p></li>
</ul>
</section>
<section id="setting-dependencies-for-netflix" class="level3">
<h3 class="anchored" data-anchor-id="setting-dependencies-for-netflix">6.11 Setting dependencies for Netflix</h3>
<p>Netflix compiled a forecast up to the 2019 financial year <code>netflix_f_is</code>, and has based the sales figures in 2019 on the following dependency:</p>
<ul>
<li>Number of active subscriptions, which are based on the success of Netflix original shows.</li>
</ul>
<p>For 2019, the success of original shows (critical and commercial acclaim) are estimated at 78%. The total amount of subscribers per percentage point is 500, and set to the variable <code>n_subscribers_per_pp</code> (i.e there is a calculated correlation between show success and number of subscribers).</p>
<p>In this exercise, we will calculate how dependent sales are on the number of subscribers in the forecast, which we will use in the next exercise.</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># instantiate subscribers per % point</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>n_subscribers_per_pp <span class="op">=</span> <span class="dv">500</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="co"># load in Netflix financials</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>netflix_f_is <span class="op">=</span> pd.read_csv(<span class="st">'Data/Netflix.csv'</span>)</span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>netflix_f_is</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>metric</th>
      <th>2014_act</th>
      <th>2015_act</th>
      <th>2016_act</th>
      <th>2017_fc</th>
      <th>2018_fc</th>
      <th>2019_fc</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Sales</td>
      <td>5505</td>
      <td>6780</td>
      <td>8831</td>
      <td>11688</td>
      <td>14979</td>
      <td>17994</td>
    </tr>
    <tr>
      <th>1</th>
      <td>EBITDA</td>
      <td>528</td>
      <td>493</td>
      <td>611</td>
      <td>1088</td>
      <td>1899</td>
      <td>2943</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Operating profit&nbsp;(EBIT)</td>
      <td>403</td>
      <td>306</td>
      <td>380</td>
      <td>837</td>
      <td>1660</td>
      <td>2702</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Net income</td>
      <td>267</td>
      <td>123</td>
      <td>187</td>
      <td>559</td>
      <td>1024</td>
      <td>1721</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a filter to select the sales row from the netflix_f_is dataset</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>sales_metric <span class="op">=</span> [<span class="st">'Sales'</span>]</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for rows containing the Sales metric</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>filtered_netflix_f_is <span class="op">=</span> netflix_f_is[netflix_f_is.metric.isin(sales_metric)]</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the 2019 Sales forecast value</span></span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>forecast1 <span class="op">=</span> netflix_f_is[<span class="st">'2019_fc'</span>].iloc[<span class="dv">0</span>]</span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the resulting forecast</span></span>
<span id="cb83-11"><a href="#cb83-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The sales forecast is </span><span class="sc">{}</span><span class="st">."</span>.<span class="bu">format</span>(forecast1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The sales forecast is 17994.</code></pre>
</div>
</div>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the success percentage to 78%</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>pct_success <span class="op">=</span> <span class="fl">0.78</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the dependency for the subscriber base</span></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>n_subscribers <span class="op">=</span> n_subscribers_per_pp <span class="op">*</span> pct_success</span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a><span class="co"># See the result</span></span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The dependency for the subscriber base is </span><span class="sc">{}</span><span class="st">."</span>.<span class="bu">format</span>(n_subscribers))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The dependency for the subscriber base is 390.0.</code></pre>
</div>
</div>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the ratio between forecast sales and subscribers</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>sales_subs_ratio <span class="op">=</span> forecast1 <span class="op">/</span> n_subscribers</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a><span class="co"># See the result</span></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The ratio between subscribers and sales is 1 subscriber equals $</span><span class="sc">{:.2f}</span><span class="st">."</span>.<span class="bu">format</span>(sales_subs_ratio))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The ratio between subscribers and sales is 1 subscriber equals $46.14.</code></pre>
</div>
</div>
</section>
<section id="calculating-an-alternative-forecast-for-netflix" class="level3">
<h3 class="anchored" data-anchor-id="calculating-an-alternative-forecast-for-netflix">6.12 Calculating an alternative forecast for Netflix</h3>
<p>The original assumptions are as follows: the total amount of subscribers at a 78% success rate results in 39,000 subscribers. We used this to build the forecast numbers.</p>
<p>However, the success rate for 2019 has been recalculated to have a probability of 65%, and the management has asked us to make an adjusted forecast based on this value.</p>
<p>The ratio between the subscribers and sales is 1 subscriber to 0.46 USD sales, set to variable <code>sales_subs_ratio</code>.</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># instantiate sales subs ratio</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>sales_subs_ratio <span class="op">=</span> <span class="fl">0.46</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the proportion of successes to 65%</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>pct_success2 <span class="op">=</span> <span class="dv">65</span></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the number of subscribers</span></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>n_subscribers2 <span class="op">=</span> n_subscribers_per_pp <span class="op">*</span> pct_success2 </span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the new forecast</span></span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a>forecast2 <span class="op">=</span> n_subscribers2  <span class="op">*</span> sales_subs_ratio</span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a>forecast2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>14950.0</code></pre>
</div>
</div>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Insert a column named AltForecast, containing forecast2</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>filtered_netflix_f_is.insert(<span class="bu">len</span>(filtered_netflix_f_is.columns), <span class="st">'AltForecast'</span>, forecast2)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Insert a column named Gap, containing the difference</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>filtered_netflix_f_is.insert(<span class="bu">len</span>(filtered_netflix_f_is.columns), <span class="st">'Gap'</span>, forecast1 <span class="op">-</span> forecast2)</span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a><span class="co"># See the result</span></span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a>filtered_netflix_f_is</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>metric</th>
      <th>2014_act</th>
      <th>2015_act</th>
      <th>2016_act</th>
      <th>2017_fc</th>
      <th>2018_fc</th>
      <th>2019_fc</th>
      <th>AltForecast</th>
      <th>Gap</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Sales</td>
      <td>5505</td>
      <td>6780</td>
      <td>8831</td>
      <td>11688</td>
      <td>14979</td>
      <td>17994</td>
      <td>14950.0</td>
      <td>3044.0</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
</section>
<section id="key-takeaways" class="level2">
<h2 class="anchored" data-anchor-id="key-takeaways">Key takeaways</h2>
<p>We learned how to harnass Python, and in particular the <a href="https://pandas.pydata.org/docs/user_guide/index.html"><code>pandas</code></a> library to wrangle raw financial data, and extract relevant information to calculate key <code>metrics</code>.</p>
<p>We also learned how to handle date inconsistencies using the <a href="https://docs.python.org/3/library/datetime.html#module-datetime"><code>datetime</code></a> library, parse dates using the <code>split()</code> method, and how to automate our work by writing functions and using <code>for loops</code> and <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iteritems.html"><code>.iteritems</code></a>.</p>
<p>Automating the financial forecasting process allows fast iterations over different scenarios, saving time and reducing the scope of manual error.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>