<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Stephen Barrie">
<meta name="dcterms.date" content="2022-11-25">

<title>Into the Unknown - FIFA World Cup - Qatar 2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Into the Unknown</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">Stephen Barrie</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"><i class="bi bi-rss" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Stephen137"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/sjbarrie"><i class="bi bi-linkedin" role="img">
</i> 
 </a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">FIFA World Cup - Qatar 2022</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Projects</div>
                <div class="quarto-category">Python</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Stephen Barrie </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">November 25, 2022</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#fifa-world-cup---qatar-2022" id="toc-fifa-world-cup---qatar-2022" class="nav-link active" data-scroll-target="#fifa-world-cup---qatar-2022">FIFA World Cup - Qatar 2022</a>
  <ul class="collapse">
  <li><a href="#data-source" id="toc-data-source" class="nav-link" data-scroll-target="#data-source">Data source</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a></li>
  <li><a href="#numeric-features" id="toc-numeric-features" class="nav-link" data-scroll-target="#numeric-features">Numeric features</a></li>
  <li><a href="#you-cant-win-anything-with-kids" id="toc-you-cant-win-anything-with-kids" class="nav-link" data-scroll-target="#you-cant-win-anything-with-kids">You can’t win anything with kids</a></li>
  <li><a href="#out-with-the-old" id="toc-out-with-the-old" class="nav-link" data-scroll-target="#out-with-the-old">Out with the old</a></li>
  <li><a href="#in-with-the-new" id="toc-in-with-the-new" class="nav-link" data-scroll-target="#in-with-the-new">In with the new</a></li>
  <li><a href="#are-you-experienced" id="toc-are-you-experienced" class="nav-link" data-scroll-target="#are-you-experienced">Are you experienced?</a></li>
  <li><a href="#baptism-of-fire" id="toc-baptism-of-fire" class="nav-link" data-scroll-target="#baptism-of-fire">Baptism of fire?</a></li>
  <li><a href="#categorical-features" id="toc-categorical-features" class="nav-link" data-scroll-target="#categorical-features">Categorical features</a></li>
  <li><a href="#club-v-country" id="toc-club-v-country" class="nav-link" data-scroll-target="#club-v-country">Club v Country</a></li>
  <li><a href="#scotland" id="toc-scotland" class="nav-link" data-scroll-target="#scotland">Scotland</a></li>
  <li><a href="#poland" id="toc-poland" class="nav-link" data-scroll-target="#poland">Poland</a></li>
  <li><a href="#home-and-away" id="toc-home-and-away" class="nav-link" data-scroll-target="#home-and-away">Home and Away</a></li>
  <li><a href="#huddle" id="toc-huddle" class="nav-link" data-scroll-target="#huddle">Huddle</a>
  <ul class="collapse">
  <li><a href="#obtaining-co-ordinates-using-geopy" id="toc-obtaining-co-ordinates-using-geopy" class="nav-link" data-scroll-target="#obtaining-co-ordinates-using-geopy">Obtaining co-ordinates using Geopy</a></li>
  <li><a href="#obtaining-all-possible-city-pair-combinations" id="toc-obtaining-all-possible-city-pair-combinations" class="nav-link" data-scroll-target="#obtaining-all-possible-city-pair-combinations">Obtaining all possible city pair combinations</a></li>
  <li><a href="#going-the-extra-mile" id="toc-going-the-extra-mile" class="nav-link" data-scroll-target="#going-the-extra-mile">Going the extra mile</a></li>
  </ul></li>
  <li><a href="#v-look-up-in-python" id="toc-v-look-up-in-python" class="nav-link" data-scroll-target="#v-look-up-in-python">V look up in Python</a></li>
  <li><a href="#full-time" id="toc-full-time" class="nav-link" data-scroll-target="#full-time">Full time</a></li>
  <li><a href="#key-take-aways" id="toc-key-take-aways" class="nav-link" data-scroll-target="#key-take-aways">Key take-aways</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="fifa-world-cup---qatar-2022" class="level1">
<h1>FIFA World Cup - Qatar 2022</h1>
<p>At the time of writing the 2022 World Cup is already underway, with 32 teams battling it out in Qatar for the famous golden globe. I’ve lost touch a bit in recent years with football, and thought it would be interesting to use Python to get back up to speed.</p>
<p>The main aim of this project is to try and uncover some insights about the 32 teams - who has played it safe, and gone for experience, who has been bold and decided to give youth a chance to flourish. I’m also interested in where the players play their football at club level, and hope to quantify their geographical spread.</p>
<section id="data-source" class="level2">
<h2 class="anchored" data-anchor-id="data-source">Data source</h2>
<p>The data was sourced from <a href="https://www.sportingnews.com/us/soccer/news/world-cup-squads-2022-team-rosters-official-fifa-qatar/kjcagctfesjt0zpjxctbdqha">Sporting News</a> website.</p>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<p>Let’s dive in!</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="World_Cup_2022_files/figure-html/f0df3860-6413-47d9-a77f-4a1ce0f8c753.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">footbal dive.jpg</figcaption><p></p>
</figure>
</div>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">## Import the required packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib <span class="im">as</span> plt</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>pd.options.display.float_format <span class="op">=</span> <span class="st">'</span><span class="sc">{:.2f}</span><span class="st">'</span>.<span class="bu">format</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load in our data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>world_cup <span class="op">=</span> pd.read_csv(<span class="st">'Data/World_Cup_2022.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can automate some of the exploratory data analysis by writing a function:</p>
<div class="cell" data-execution_count="153">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> initial_eda(df):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(df, pd.DataFrame):</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>        total_na <span class="op">=</span> df.isna().<span class="bu">sum</span>().<span class="bu">sum</span>()</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"Dimensions : </span><span class="sc">%d</span><span class="st"> rows, </span><span class="sc">%d</span><span class="st"> columns"</span> <span class="op">%</span> (df.shape[<span class="dv">0</span>], df.shape[<span class="dv">1</span>]))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"Total NA Values : </span><span class="sc">%d</span><span class="st"> "</span> <span class="op">%</span> (total_na))</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"</span><span class="sc">%38s</span><span class="st"> </span><span class="sc">%10s</span><span class="st">     </span><span class="sc">%10s</span><span class="st"> </span><span class="sc">%10s</span><span class="st">"</span> <span class="op">%</span> (<span class="st">"Column Name"</span>, <span class="st">"Data Type"</span>, <span class="st">"#Distinct"</span>, <span class="st">"NA Values"</span>))</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>        col_name <span class="op">=</span> df.columns</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>        dtyp <span class="op">=</span> df.dtypes</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>        uniq <span class="op">=</span> df.nunique()</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>        na_val <span class="op">=</span> df.isna().<span class="bu">sum</span>()</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(df.columns)):</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>            <span class="bu">print</span>(<span class="st">"</span><span class="sc">%38s</span><span class="st"> </span><span class="sc">%10s</span><span class="st">   </span><span class="sc">%10s</span><span class="st"> </span><span class="sc">%10s</span><span class="st">"</span> <span class="op">%</span> (col_name[i], dtyp[i], uniq[i], na_val[i]))</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"Expect a DataFrame but got a </span><span class="sc">%15s</span><span class="st">"</span> <span class="op">%</span> (<span class="bu">type</span>(df)))  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="284">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>initial_eda(world_cup)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dimensions : 830 rows, 11 columns
Total NA Values : 0 
                           Column Name  Data Type      #Distinct  NA Values
                                  Name     object          830          0
                              Position     object            4          0
                                   Age    float64           29          0
                               Country     object           32          0
                              Ctry_cap     object           32          0
                                  Caps      int64          132          0
                                 Group     object            8          0
                                  Club     object          446          0
                             Club_ctry     object           43          0
                         Club_ctry_cap     object           43          0
                             Home_Away     object            2          0</code></pre>
</div>
</div>
<p>Looks like there is no missing data within the dataset. However, there are 8 groups of 4, so 32 teams competing and the maximum permitted squad size is 26, which would be 832 players. We only have 830 observations. Let’s investigate this by grouping the squad numbers by country:</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>world_cup.groupby(<span class="st">"Country"</span>)[<span class="st">"Name"</span>].count().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>Country
Argentina       26
Australia       26
Uruguay         26
USA             26
Tunisia         26
Switzerland     26
Spain           26
South Korea     26
Serbia          26
Senegal         26
Saudi Arabia    26
Qatar           26
Portugal        26
Poland          26
Netherlands     26
Morocco         26
Mexico          26
Japan           26
Ghana           26
Germany         26
England         26
Ecuador         26
Denmark         26
Croatia         26
Costa Rica      26
Canada          26
Cameroon        26
Brazil          26
Belgium         26
Wales           26
Iran            25
France          25
Name: Name, dtype: int64</code></pre>
</div>
</div>
<p>Iran and France only have 25 players in their squad. On follow up this was confirmed to be correct, so we haven’t lost any players! Let’s move on and take a closer look at our data by looking at the first few rows:</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first 5 rows</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>world_cup.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Saad Al-Sheeb</td>
      <td>GK</td>
      <td>32.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>80</td>
      <td>A</td>
      <td>Al-Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Meshaal Barsham</td>
      <td>GK</td>
      <td>24.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>15</td>
      <td>A</td>
      <td>Al-Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Yousuf Hassan</td>
      <td>GK</td>
      <td>26.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>9</td>
      <td>A</td>
      <td>Al-Gharafa</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Pedro Miguel</td>
      <td>DEF</td>
      <td>32.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>78</td>
      <td>A</td>
      <td>Al-Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Musaab Khidir</td>
      <td>DEF</td>
      <td>29.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>29</td>
      <td>A</td>
      <td>Al-Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>….and the last few rows:</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the last 5 rows</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>world_cup.tail()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>825</th>
      <td>Kamaldeen Sulemana</td>
      <td>MID</td>
      <td>20.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>11</td>
      <td>H</td>
      <td>Stade Rennes</td>
      <td>France</td>
      <td>Paris</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>826</th>
      <td>Antoine Semenyo</td>
      <td>FWD</td>
      <td>22.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>1</td>
      <td>H</td>
      <td>Bristol City</td>
      <td>England</td>
      <td>London</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>827</th>
      <td>Andre Ayew</td>
      <td>FWD</td>
      <td>32.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>107</td>
      <td>H</td>
      <td>Al Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>828</th>
      <td>Jordan Ayew</td>
      <td>FWD</td>
      <td>31.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>82</td>
      <td>H</td>
      <td>Crystal Palace</td>
      <td>England</td>
      <td>London</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>829</th>
      <td>Inaki Williams</td>
      <td>FWD</td>
      <td>28.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>1</td>
      <td>H</td>
      <td>Athletic Club</td>
      <td>Spain</td>
      <td>Madrid</td>
      <td>Away</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>OK, so we can see that we have some basic information about each player:</p>
<pre><code>- Name
- Position (GK = Goalkeeper DEF = Defender MID = Midfielder FWD = Forward)
- Age
- Country they represent
- Ctry_cap - capital of country they represent
- Caps (Number of matches played for their country)
- Group (32 teams divided into 8 groups A-H of 4)
- Club (the team that pays the player's wages!)
- Club_ctry (the location of the player's domestic team)
- Club_ctry_cap (capital of their club country)
- Home_Away - where they play their club football</code></pre>
</section>
<section id="numeric-features" class="level2">
<h2 class="anchored" data-anchor-id="numeric-features">Numeric features</h2>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>world_cup.describe(include<span class="op">=</span>(np.number))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Age</th>
      <th>Caps</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>830.00</td>
      <td>830.00</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>26.80</td>
      <td>33.87</td>
    </tr>
    <tr>
      <th>std</th>
      <td>4.59</td>
      <td>33.81</td>
    </tr>
    <tr>
      <th>min</th>
      <td>0.00</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>24.00</td>
      <td>8.00</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>27.00</td>
      <td>23.00</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>30.00</td>
      <td>47.00</td>
    </tr>
    <tr>
      <th>max</th>
      <td>45.00</td>
      <td>191.00</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
<section id="you-cant-win-anything-with-kids" class="level2">
<h2 class="anchored" data-anchor-id="you-cant-win-anything-with-kids">You can’t win anything with kids</h2>
<div>
<p><img src="Kids.jpg" width="300"></p>
</div>
<p>It turned out of course that Alan was wrong - Manchester United went on to win the English Premier league that season. There is no master recipe for success it seems at these tournaments. Some managers like to lean on the old guard, some like to throw the gauntlet down and give the kids a chance. Let’s take a look at the age profile of the players using a <a href="https://en.wikipedia.org/wiki/Histogram"><strong><em>histogram</em></strong></a>:</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>world_cup [<span class="st">'Age'</span>].hist()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="World_Cup_2022_files/figure-html/cell-10-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Something doesn’t look right here, some ages between 0 and 5! Let’s look into this. We can use <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html">.loc</a> to <em>access</em> a group of rows and columns by name or <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html">.iloc</a> to access by index:</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>world_cup.loc[world_cup[<span class="st">'Age'</span>] <span class="op">&lt;</span><span class="dv">5</span> ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>34</th>
      <td>Diego Palacios</td>
      <td>DEF</td>
      <td>2.00</td>
      <td>Ecuador</td>
      <td>Quito</td>
      <td>11</td>
      <td>A</td>
      <td>LAFC</td>
      <td>USA</td>
      <td>Washington, DC</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>520</th>
      <td>Ahmed Reda Tagnaouti</td>
      <td>GK</td>
      <td>3.00</td>
      <td>Morocco</td>
      <td>Rabat</td>
      <td>3</td>
      <td>F</td>
      <td>Wydad Casablanca</td>
      <td>Morocco</td>
      <td>Rabat</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>642</th>
      <td>Fabian Rieder</td>
      <td>MID</td>
      <td>0.00</td>
      <td>Switzerland</td>
      <td>Berne</td>
      <td>0</td>
      <td>G</td>
      <td>Young Boys</td>
      <td>Switzerland</td>
      <td>Berne</td>
      <td>Home</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>On follow up, Diego Palacios Fabian Redier is 23, Ahmed Reda Tagnaouti is 26, and Fabian Rieder is 20 years old. We can correct these errors using <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iat.html">.iat</a>. The values we wish to update are located at rows 34, 520 and 642 of column 2 - watch out, indexing starts at 0 in Python!</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Update Diego Palacios age</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>world_cup.iat[<span class="dv">34</span>,<span class="dv">2</span>]<span class="op">=</span><span class="dv">23</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Update Ahmed Reda Tagnaouti age</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>world_cup.iat[<span class="dv">520</span>,<span class="dv">2</span>]<span class="op">=</span><span class="dv">26</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Update Fabian Rieder age</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>world_cup.iat[<span class="dv">642</span>,<span class="dv">2</span>]<span class="op">=</span><span class="dv">20</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s check that’s worked:</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>world_cup.loc[<span class="dv">34</span>:<span class="dv">34</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>34</th>
      <td>Diego Palacios</td>
      <td>DEF</td>
      <td>23.00</td>
      <td>Ecuador</td>
      <td>Quito</td>
      <td>11</td>
      <td>A</td>
      <td>LAFC</td>
      <td>USA</td>
      <td>Washington, DC</td>
      <td>Away</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>world_cup.loc[<span class="dv">520</span>:<span class="dv">520</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>520</th>
      <td>Ahmed Reda Tagnaouti</td>
      <td>GK</td>
      <td>26.00</td>
      <td>Morocco</td>
      <td>Rabat</td>
      <td>3</td>
      <td>F</td>
      <td>Wydad Casablanca</td>
      <td>Morocco</td>
      <td>Rabat</td>
      <td>Home</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>world_cup.loc[<span class="dv">642</span>:<span class="dv">642</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>642</th>
      <td>Fabian Rieder</td>
      <td>MID</td>
      <td>20.00</td>
      <td>Switzerland</td>
      <td>Berne</td>
      <td>0</td>
      <td>G</td>
      <td>Young Boys</td>
      <td>Switzerland</td>
      <td>Berne</td>
      <td>Home</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Great, the ages have been successfully updated. Let’s now take a look at the age profile of each of the 32 squads:</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>title_string <span class="op">=</span> <span class="st">"FIFA World Cup - Qatar 2022"</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>subtitle_string <span class="op">=</span> <span class="st">"Average age of squad"</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> world_cup.groupby(<span class="st">'Country'</span>)[<span class="st">'Age'</span>].mean().sort_values()</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>x.plot(kind<span class="op">=</span><span class="st">'barh'</span>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>plt.suptitle(title_string, y<span class="op">=</span><span class="fl">1.05</span>, fontsize<span class="op">=</span><span class="dv">18</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>plt.title(subtitle_string, fontsize<span class="op">=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>Text(0.5, 1.0, 'Average age of squad')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="World_Cup_2022_files/figure-html/cell-16-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>ave_age <span class="op">=</span> world_cup.groupby(<span class="st">"Country"</span>)[<span class="st">"Age"</span>].mean()</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>ave_age.sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>Country
Iran           29.08
Mexico         28.58
Tunisia        27.92
Brazil         27.86
Belgium        27.77
South Korea    27.77
Uruguay        27.73
Japan          27.69
Argentina      27.69
Saudi Arabia   27.38
Croatia        27.31
Australia      27.23
Costa Rica     27.15
Poland         27.00
Canada         26.92
Denmark        26.92
Qatar          26.92
Portugal       26.77
Serbia         26.77
Switzerland    26.73
Germany        26.69
Netherlands    26.58
England        26.35
Wales          26.23
Morocco        26.19
Cameroon       26.19
France         26.12
Senegal        26.04
Ecuador        25.54
Spain          25.31
USA            25.00
Ghana          24.73
Name: Age, dtype: float64</code></pre>
</div>
</div>
<p>So Ghana and Ecaudor have the youngest squads (average age 24.73) whilst Iran has the oldest, with an average age of 29.08.</p>
</section>
<section id="out-with-the-old" class="level2">
<h2 class="anchored" data-anchor-id="out-with-the-old">Out with the old</h2>
<div>
<p><img src="added time.jpg" width="300"></p>
</div>
<p>The players below will be looking at the board and hoping for a large number. Players are looking after themselves more and more, extending their playing careers, but realistically, for the players below, this is possibly their last opportunity to appear in a World Cup. So make sure to see catch them while you can!</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>mature <span class="op">=</span> world_cup[world_cup[<span class="st">'Age'</span>] <span class="op">&gt;</span> <span class="dv">33</span>]</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>mature_sorted <span class="op">=</span> mature.sort_values(by<span class="op">=</span><span class="st">"Age"</span>,ascending <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>mature_sorted.head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>143</th>
      <td>Ramin Rezaeian</td>
      <td>DEF</td>
      <td>45.00</td>
      <td>Iran</td>
      <td>Tehran</td>
      <td>2</td>
      <td>B</td>
      <td>Sepahan</td>
      <td>Iran</td>
      <td>Tehran</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>261</th>
      <td>Alfredo Talavera</td>
      <td>GK</td>
      <td>40.00</td>
      <td>Mexico</td>
      <td>Mexico City</td>
      <td>40</td>
      <td>C</td>
      <td>FC Juarez</td>
      <td>Mexico</td>
      <td>Mexico City</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>440</th>
      <td>Eiji Kawashima</td>
      <td>GK</td>
      <td>39.00</td>
      <td>Japan</td>
      <td>Tokyo</td>
      <td>95</td>
      <td>E</td>
      <td>Strasbourg</td>
      <td>France</td>
      <td>Paris</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>781</th>
      <td>Pepe</td>
      <td>DEF</td>
      <td>39.00</td>
      <td>Portugal</td>
      <td>Lisbon</td>
      <td>128</td>
      <td>H</td>
      <td>Porto</td>
      <td>Portugal</td>
      <td>Lisbon</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>608</th>
      <td>Atiba Hutchinson</td>
      <td>MID</td>
      <td>39.00</td>
      <td>Canada</td>
      <td>Ottawa</td>
      <td>98</td>
      <td>F</td>
      <td>Besiktas</td>
      <td>Turkey</td>
      <td>Istanbul</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>682</th>
      <td>Dani Alves</td>
      <td>DEF</td>
      <td>39.00</td>
      <td>Brazil</td>
      <td>Brasilia</td>
      <td>125</td>
      <td>G</td>
      <td>Pumas UNAM</td>
      <td>Mexico</td>
      <td>Mexico City</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>679</th>
      <td>Thiago Silva</td>
      <td>DEF</td>
      <td>38.00</td>
      <td>Brazil</td>
      <td>Brasilia</td>
      <td>108</td>
      <td>G</td>
      <td>Chelsea</td>
      <td>England</td>
      <td>London</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>78</th>
      <td>Remko Pasveer</td>
      <td>GK</td>
      <td>38.00</td>
      <td>Netherlands</td>
      <td>Amsterdam</td>
      <td>2</td>
      <td>A</td>
      <td>Ajax</td>
      <td>Netherlands</td>
      <td>Amsterdam</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>340</th>
      <td>Aymen Mathlouthi</td>
      <td>GK</td>
      <td>38.00</td>
      <td>Tunisia</td>
      <td>Tunis</td>
      <td>73</td>
      <td>D</td>
      <td>Etoile du Sahel</td>
      <td>Tunisia</td>
      <td>Tunis</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>365</th>
      <td>Steve Mandanda</td>
      <td>GK</td>
      <td>37.00</td>
      <td>France</td>
      <td>Paris</td>
      <td>34</td>
      <td>D</td>
      <td>Rennes</td>
      <td>France</td>
      <td>Paris</td>
      <td>Home</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
<section id="in-with-the-new" class="level2">
<h2 class="anchored" data-anchor-id="in-with-the-new">In with the new</h2>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>new <span class="op">=</span> world_cup[world_cup[<span class="st">'Age'</span>] <span class="op">&lt;</span> <span class="dv">20</span>]</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>new_sorted <span class="op">=</span> new.sort_values(by<span class="op">=</span><span class="st">"Age"</span>,ascending <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>new_sorted.head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>435</th>
      <td>Youssoufa Moukoko</td>
      <td>FWD</td>
      <td>17.00</td>
      <td>Germany</td>
      <td>Berlin</td>
      <td>1</td>
      <td>E</td>
      <td>Borussia Dortmund</td>
      <td>Germany</td>
      <td>Berlin</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>820</th>
      <td>Fatawu&nbsp;Issahaku</td>
      <td>MID</td>
      <td>18.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>11</td>
      <td>H</td>
      <td>Sporting</td>
      <td>Portugal</td>
      <td>Lisbon</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>577</th>
      <td>Zeno Debast</td>
      <td>DEF</td>
      <td>18.00</td>
      <td>Belgium</td>
      <td>Brussels</td>
      <td>3</td>
      <td>F</td>
      <td>Anderlecht</td>
      <td>Belgium</td>
      <td>Brussels</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>531</th>
      <td>Bilal El Khannouss</td>
      <td>MID</td>
      <td>18.00</td>
      <td>Morocco</td>
      <td>Rabat</td>
      <td>0</td>
      <td>F</td>
      <td>Racing Genk</td>
      <td>Belgium</td>
      <td>Brussels</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>505</th>
      <td>Jewison Bennette</td>
      <td>MID</td>
      <td>18.00</td>
      <td>Costa Rica</td>
      <td>San Jose</td>
      <td>7</td>
      <td>E</td>
      <td>Sunderland</td>
      <td>England</td>
      <td>London</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>412</th>
      <td>Garang Kuol</td>
      <td>FWD</td>
      <td>18.00</td>
      <td>Australia</td>
      <td>Canberra</td>
      <td>1</td>
      <td>D</td>
      <td>Central Coast Mariners</td>
      <td>Australia</td>
      <td>Canberra</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>478</th>
      <td>Gavi</td>
      <td>MID</td>
      <td>18.00</td>
      <td>Spain</td>
      <td>Madrid</td>
      <td>13</td>
      <td>E</td>
      <td>Barcelona</td>
      <td>Spain</td>
      <td>Madrid</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>784</th>
      <td>Antonio Silva</td>
      <td>DEF</td>
      <td>19.00</td>
      <td>Portugal</td>
      <td>Lisbon</td>
      <td>0</td>
      <td>H</td>
      <td>Benfica</td>
      <td>Portugal</td>
      <td>Lisbon</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>648</th>
      <td>Simon&nbsp;Ngapandouetnbu</td>
      <td>GK</td>
      <td>19.00</td>
      <td>Cameroon</td>
      <td>Yaounde</td>
      <td>0</td>
      <td>G</td>
      <td>Marseille</td>
      <td>France</td>
      <td>Paris</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>504</th>
      <td>Brandon Aguilera</td>
      <td>MID</td>
      <td>19.00</td>
      <td>Costa Rica</td>
      <td>San Jose</td>
      <td>4</td>
      <td>E</td>
      <td>Guanacasteca</td>
      <td>Costa Rica</td>
      <td>San Jose</td>
      <td>Home</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>So it looks like the youngest player at the tournament is Youssoufa Moukoko of Germany at just 17.</p>
</section>
<section id="are-you-experienced" class="level2">
<h2 class="anchored" data-anchor-id="are-you-experienced">Are you experienced?</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="World_Cup_2022_files/figure-html/721b1467-93f6-4d38-ac44-1e1b4f0ff1cc.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">experience.jpg</figcaption><p></p>
</figure>
</div>
<p>Although in some sports physical caps may not now always be given (whether at all or for each appearance) the term cap for an international or other appearance has been retained as an indicator of the number of occasions on which a sportsperson has represented a team in a particular sport. Thus, a “cap” is awarded for each game played and so a player who has played x games for the team is said to have been capped x times or have won x caps.</p>
<p>Let’s first look at the distribution of the number of caps received going into this tournament, using a <a href="https://en.wikipedia.org/wiki/Histogram"><strong><em>histogram</em></strong></a>:</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>world_cup [<span class="st">'Caps'</span>].hist()<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="World_Cup_2022_files/figure-html/cell-20-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>As we can see the majority of players are relatively inexperienced, with less than around 40 appearances, although there are some very experienced players, with over 150 caps. Let’s have a look at who they are:</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>world_cup.loc[world_cup[<span class="st">'Caps'</span>] <span class="op">&gt;</span> <span class="dv">150</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>20</th>
      <td>Hassan Al-Haydos</td>
      <td>MID</td>
      <td>31.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>160</td>
      <td>A</td>
      <td>Al-Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>232</th>
      <td>Lionel Messi</td>
      <td>FWD</td>
      <td>35.00</td>
      <td>Argentina</td>
      <td>Buenos Aires</td>
      <td>165</td>
      <td>C</td>
      <td>PSG</td>
      <td>France</td>
      <td>Paris</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>272</th>
      <td>Andres Guardado</td>
      <td>MID</td>
      <td>36.00</td>
      <td>Mexico</td>
      <td>Mexico City</td>
      <td>180</td>
      <td>C</td>
      <td>Real Betis</td>
      <td>Spain</td>
      <td>Madrid</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>506</th>
      <td>Celso Borges</td>
      <td>MID</td>
      <td>34.00</td>
      <td>Costa Rica</td>
      <td>San Jose</td>
      <td>154</td>
      <td>E</td>
      <td>Alajuelense</td>
      <td>Costa Rica</td>
      <td>San Jose</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>558</th>
      <td>Luka Modric</td>
      <td>MID</td>
      <td>37.00</td>
      <td>Croatia</td>
      <td>Zagreb</td>
      <td>155</td>
      <td>F</td>
      <td>Real Madrid</td>
      <td>Spain</td>
      <td>Madrid</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>733</th>
      <td>Diego Godin</td>
      <td>DEF</td>
      <td>36.00</td>
      <td>Uruguay</td>
      <td>Montevideo</td>
      <td>159</td>
      <td>G</td>
      <td>Velez Sarsfield</td>
      <td>Argentina</td>
      <td>Buenos Aires</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>798</th>
      <td>Cristiano Ronaldo</td>
      <td>FWD</td>
      <td>37.00</td>
      <td>Portugal</td>
      <td>Lisbon</td>
      <td>191</td>
      <td>H</td>
      <td>Manchester United</td>
      <td>England</td>
      <td>London</td>
      <td>Away</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Cristiano Ronaldo is the most capped player at the tournament with 191. The 200 mark is in sight, although at 37 maybe it’s time to make way for some new blood?</p>
</section>
<section id="baptism-of-fire" class="level2">
<h2 class="anchored" data-anchor-id="baptism-of-fire">Baptism of fire?</h2>
<div>
<p><img src="baptism.jpg" width="300"></p>
</div>
<p>The minimum number of caps shown is 0 which means there are players at this tournament who have yet to play for their country - the stage has been set! Let’s find out who they are:</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>world_cup.loc[world_cup[<span class="st">'Caps'</span>] <span class="op">==</span> <span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>12</th>
      <td>Jassim Jabir</td>
      <td>MID</td>
      <td>20.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>0</td>
      <td>A</td>
      <td>Al-Arabi</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>33</th>
      <td>William Pacho</td>
      <td>DEF</td>
      <td>21.00</td>
      <td>Ecuador</td>
      <td>Quito</td>
      <td>0</td>
      <td>A</td>
      <td>Royal Antwerp</td>
      <td>Belgium</td>
      <td>Brussels</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>50</th>
      <td>Kevin Rodriguez</td>
      <td>FWD</td>
      <td>22.00</td>
      <td>Ecuador</td>
      <td>Quito</td>
      <td>0</td>
      <td>A</td>
      <td>Imbabura SC</td>
      <td>Ecuador</td>
      <td>Quito</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>61</th>
      <td>Moussa Ndiaye</td>
      <td>DEF</td>
      <td>20.00</td>
      <td>Senegal</td>
      <td>Dakar</td>
      <td>0</td>
      <td>A</td>
      <td>Anderlecht</td>
      <td>Belgium</td>
      <td>Brussels</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>70</th>
      <td>Pathe Ciss</td>
      <td>MID</td>
      <td>28.00</td>
      <td>Senegal</td>
      <td>Dakar</td>
      <td>0</td>
      <td>A</td>
      <td>Rayo Vallecano</td>
      <td>Spain</td>
      <td>Madrid</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>79</th>
      <td>Andries Noppert</td>
      <td>GK</td>
      <td>28.00</td>
      <td>Netherlands</td>
      <td>Amsterdam</td>
      <td>0</td>
      <td>A</td>
      <td>Heerenveen</td>
      <td>Netherlands</td>
      <td>Amsterdam</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>83</th>
      <td>Jeremie Frimpong</td>
      <td>DEF</td>
      <td>21.00</td>
      <td>Netherlands</td>
      <td>Amsterdam</td>
      <td>0</td>
      <td>A</td>
      <td>Bayer Leverkusen</td>
      <td>Germany</td>
      <td>Berlin</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>92</th>
      <td>Xavi Simons</td>
      <td>MID</td>
      <td>19.00</td>
      <td>Netherlands</td>
      <td>Amsterdam</td>
      <td>0</td>
      <td>A</td>
      <td>PSV Eindhoven</td>
      <td>Netherlands</td>
      <td>Amsterdam</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>234</th>
      <td>Nawaf Al-Aqidi</td>
      <td>GK</td>
      <td>22.00</td>
      <td>Saudi Arabia</td>
      <td>Riyadh</td>
      <td>0</td>
      <td>C</td>
      <td>Al-Nassr FC</td>
      <td>Saudi Arabia</td>
      <td>Riyadh</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>235</th>
      <td>Mohamed Al-Yami</td>
      <td>GK</td>
      <td>25.00</td>
      <td>Saudi Arabia</td>
      <td>Riyadh</td>
      <td>0</td>
      <td>C</td>
      <td>Al-Ahli Saudi FC</td>
      <td>Saudi Arabia</td>
      <td>Riyadh</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>366</th>
      <td>Axel Disasi</td>
      <td>DEF</td>
      <td>24.00</td>
      <td>France</td>
      <td>Paris</td>
      <td>0</td>
      <td>D</td>
      <td>Monaco</td>
      <td>France</td>
      <td>Paris</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>474</th>
      <td>Alejandro Balde</td>
      <td>DEF</td>
      <td>19.00</td>
      <td>Spain</td>
      <td>Madrid</td>
      <td>0</td>
      <td>E</td>
      <td>Barcelona</td>
      <td>Spain</td>
      <td>Madrid</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>531</th>
      <td>Bilal El Khannouss</td>
      <td>MID</td>
      <td>18.00</td>
      <td>Morocco</td>
      <td>Rabat</td>
      <td>0</td>
      <td>F</td>
      <td>Racing Genk</td>
      <td>Belgium</td>
      <td>Brussels</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>597</th>
      <td>James Pantemis</td>
      <td>GK</td>
      <td>25.00</td>
      <td>Canada</td>
      <td>Ottawa</td>
      <td>0</td>
      <td>F</td>
      <td>CF Montreal</td>
      <td>Canada</td>
      <td>Ottawa</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>624</th>
      <td>Philipp Kohn</td>
      <td>GK</td>
      <td>24.00</td>
      <td>Switzerland</td>
      <td>Berne</td>
      <td>0</td>
      <td>G</td>
      <td>RB Salzburg</td>
      <td>Austria</td>
      <td>Vienna</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>642</th>
      <td>Fabian Rieder</td>
      <td>MID</td>
      <td>20.00</td>
      <td>Switzerland</td>
      <td>Berne</td>
      <td>0</td>
      <td>G</td>
      <td>Young Boys</td>
      <td>Switzerland</td>
      <td>Berne</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>648</th>
      <td>Simon&nbsp;Ngapandouetnbu</td>
      <td>GK</td>
      <td>19.00</td>
      <td>Cameroon</td>
      <td>Yaounde</td>
      <td>0</td>
      <td>G</td>
      <td>Marseille</td>
      <td>France</td>
      <td>Paris</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>779</th>
      <td>Jose Sa</td>
      <td>GK</td>
      <td>29.00</td>
      <td>Portugal</td>
      <td>Lisbon</td>
      <td>0</td>
      <td>H</td>
      <td>Wolves</td>
      <td>England</td>
      <td>London</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>784</th>
      <td>Antonio Silva</td>
      <td>DEF</td>
      <td>19.00</td>
      <td>Portugal</td>
      <td>Lisbon</td>
      <td>0</td>
      <td>H</td>
      <td>Benfica</td>
      <td>Portugal</td>
      <td>Lisbon</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>802</th>
      <td>Goncalo Ramos</td>
      <td>FWD</td>
      <td>21.00</td>
      <td>Portugal</td>
      <td>Lisbon</td>
      <td>0</td>
      <td>H</td>
      <td>Benfica</td>
      <td>Portugal</td>
      <td>Lisbon</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>806</th>
      <td>Ibrahim Danlad</td>
      <td>GK</td>
      <td>19.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>0</td>
      <td>H</td>
      <td>Asante Kotoko</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>823</th>
      <td>Salis Abdul Samed</td>
      <td>MID</td>
      <td>22.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>0</td>
      <td>H</td>
      <td>Lens</td>
      <td>France</td>
      <td>Paris</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>824</th>
      <td>Kamal Sowah</td>
      <td>MID</td>
      <td>22.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>0</td>
      <td>H</td>
      <td>Club Brugge</td>
      <td>Belgium</td>
      <td>Brussels</td>
      <td>Away</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>As expected, these players are generally quite young (although Portugal’s Jose Sa is 29 - better late than never) or goalkeepers, where the first choice tends to be difficult to oust! Keep an eye out for these names - they might be the stars of the future.</p>
<p>Let’s take a look at the average number of caps for each squad:</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>title_string <span class="op">=</span> <span class="st">"FIFA World Cup - Qatar 2022"</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>subtitle_string <span class="op">=</span> <span class="st">"Average number of caps per squad"</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> world_cup.groupby(<span class="st">'Country'</span>)[<span class="st">'Caps'</span>].mean().sort_values()</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>x.plot(kind<span class="op">=</span><span class="st">'barh'</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>plt.suptitle(title_string, y<span class="op">=</span><span class="fl">1.05</span>, fontsize<span class="op">=</span><span class="dv">18</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>plt.title(subtitle_string, fontsize<span class="op">=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>Text(0.5, 1.0, 'Average number of caps per squad')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="World_Cup_2022_files/figure-html/cell-23-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>caps <span class="op">=</span> world_cup.groupby(<span class="st">"Country"</span>)[<span class="st">"Caps"</span>].mean()</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>caps.sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>Country
Qatar          53.46
Belgium        52.19
Mexico         51.12
Uruguay        45.85
Costa Rica     43.42
Portugal       40.42
Switzerland    38.58
Wales          37.96
Tunisia        37.88
Croatia        37.65
Iran           36.72
Denmark        36.65
Brazil         36.31
South Korea    35.46
Germany        35.19
Japan          35.15
Argentina      34.12
Poland         33.88
France         31.80
England        31.54
Canada         31.46
Serbia         29.77
Saudi Arabia   28.50
Spain          28.42
Netherlands    26.23
Cameroon       24.73
USA            24.69
Ecuador        23.73
Australia      22.42
Senegal        21.62
Morocco        20.04
Ghana          17.00
Name: Caps, dtype: float64</code></pre>
</div>
</div>
<p>The host nation Quatar have the most experienced squad with an average of 53.46 international apperances per player. The least experienced squad is Ghana, with an average of 17.</p>
<p>To caveat this, it is worth noting that qualification for the World Cup is segregated by region, and there can be a wide disparity between the number of qualifying matches played. This can result in some nations playing a large number of matches, without necessarily playing in a major tournament, which is perhaps a better indicator of experience.</p>
</section>
<section id="categorical-features" class="level2">
<h2 class="anchored" data-anchor-id="categorical-features">Categorical features</h2>
<p>Here’s how we get a quick summary of all the non-numeric columns in the dataset:</p>
<div class="cell" data-execution_count="310">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>world_cup.describe(include<span class="op">=</span>[<span class="bu">object</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="310">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>830</td>
      <td>830</td>
      <td>830</td>
      <td>830</td>
      <td>830</td>
      <td>830</td>
      <td>830</td>
      <td>830</td>
      <td>830</td>
    </tr>
    <tr>
      <th>unique</th>
      <td>830</td>
      <td>4</td>
      <td>32</td>
      <td>32</td>
      <td>8</td>
      <td>446</td>
      <td>43</td>
      <td>43</td>
      <td>2</td>
    </tr>
    <tr>
      <th>top</th>
      <td>Saad Al-Sheeb</td>
      <td>DEF</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>G</td>
      <td>Al-Sadd</td>
      <td>England</td>
      <td>London</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>freq</th>
      <td>1</td>
      <td>274</td>
      <td>26</td>
      <td>26</td>
      <td>130</td>
      <td>13</td>
      <td>159</td>
      <td>159</td>
      <td>551</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> [<span class="st">'Position'</span>, <span class="st">'Group'</span>, <span class="st">'Home_Away'</span>]</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>world_cup[cols] <span class="op">=</span> world_cup[cols].astype(<span class="st">'category'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>world_cup[[<span class="st">'Name'</span>,<span class="st">'Country'</span>,<span class="st">'Ctry_cap'</span>,<span class="st">'Club'</span>,<span class="st">'Club_ctry'</span>,<span class="st">'Club_ctry_cap'</span>]] <span class="op">=</span> world_cup[[<span class="st">'Name'</span>,<span class="st">'Country'</span>,<span class="st">'Ctry_cap'</span>,<span class="st">'Club'</span>,<span class="st">'Club_ctry'</span>,<span class="st">'Club_ctry_cap'</span>]].astype(<span class="bu">str</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="club-v-country" class="level2">
<h2 class="anchored" data-anchor-id="club-v-country">Club v Country</h2>
<p>First of all let’s look at where these 830 players play their club football:</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>title_string <span class="op">=</span> <span class="st">"FIFA World Cup - Qatar 2022"</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>subtitle_string <span class="op">=</span> <span class="st">"Number of players playing in...."</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> world_cup.groupby(<span class="st">'Club_ctry'</span>)[<span class="st">'Club'</span>].count().sort_values(ascending<span class="op">=</span><span class="va">True</span>).tail(<span class="dv">10</span>)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>x.plot(kind<span class="op">=</span><span class="st">'barh'</span>)</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>plt.suptitle(title_string, y<span class="op">=</span><span class="fl">1.05</span>, fontsize<span class="op">=</span><span class="dv">18</span>)</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>plt.title(subtitle_string, fontsize<span class="op">=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>Text(0.5, 1.0, 'Number of players playing in....')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="World_Cup_2022_files/figure-html/cell-28-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>world_cup.groupby(<span class="st">"Club_ctry"</span>)[<span class="st">"Club"</span>].count().sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<pre><code>Club_ctry
England         159
Spain            86
Germany          80
Italy            67
France           58
Saudi Arabia     34
Qatar            33
USA              27
Belgium          25
Mexico           23
Name: Club, dtype: int64</code></pre>
</div>
</div>
<p>So out of 830 players represented at the World Cup, 159 play their football in England. Let’s take a look at the top 10 clubs with the most players playing at this tournament:</p>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>title_string <span class="op">=</span> <span class="st">"FIFA World Cup - Qatar 2022"</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>subtitle_string <span class="op">=</span> <span class="st">"Number of players playing for.."</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> world_cup.groupby(<span class="st">"Club"</span>)[<span class="st">"Club_ctry"</span>].count().sort_values(ascending<span class="op">=</span><span class="va">True</span>).tail(<span class="dv">10</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>x.plot(kind<span class="op">=</span><span class="st">'barh'</span>)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>plt.suptitle(title_string, y<span class="op">=</span><span class="fl">1.05</span>, fontsize<span class="op">=</span><span class="dv">18</span>)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>plt.title(subtitle_string, fontsize<span class="op">=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<pre><code>Text(0.5, 1.0, 'Number of players playing for..')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="World_Cup_2022_files/figure-html/cell-30-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>Al-Sadd, wo play in the Qatar Stars league have 13 players (all playing for Qatar) at the tournament, closely followed by Barcelona with 12, Munich and Manchester City, with 11 and Manchester United having 10. Saudi Arabia’s squad all play within Saudi Arabia, 7 of them for Al_Hilal.</p>
</section>
<section id="scotland" class="level2">
<h2 class="anchored" data-anchor-id="scotland">Scotland</h2>
<div>
<p><img src="scotland_flag.jpg" width="300"></p>
</div>
<p>Sadly, my country didn’t make it, but there are some players who play domestically in Scotland who will be in Qatar representing their country. Let’s have a look and see who they are:</p>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>scotland <span class="op">=</span> world_cup[world_cup[<span class="st">'Club_ctry'</span>] <span class="op">==</span> <span class="st">'Scotland'</span>]</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>scotland</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>159</th>
      <td>Cameron Carter-Vickers</td>
      <td>DEF</td>
      <td>24.00</td>
      <td>USA</td>
      <td>Washington, DC</td>
      <td>10</td>
      <td>B</td>
      <td>Celtic</td>
      <td>Scotland</td>
      <td>Edinburgh</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>200</th>
      <td>Dylan Levitt</td>
      <td>MID</td>
      <td>21.00</td>
      <td>Wales</td>
      <td>Cardiff</td>
      <td>13</td>
      <td>B</td>
      <td>Dundee United</td>
      <td>Scotland</td>
      <td>Edinburgh</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>392</th>
      <td>Aziz Behich</td>
      <td>DEF</td>
      <td>31.00</td>
      <td>Australia</td>
      <td>Canberra</td>
      <td>53</td>
      <td>D</td>
      <td>Dundee United</td>
      <td>Scotland</td>
      <td>Edinburgh</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>394</th>
      <td>Nathaniel Atkinson</td>
      <td>DEF</td>
      <td>23.00</td>
      <td>Australia</td>
      <td>Canberra</td>
      <td>5</td>
      <td>D</td>
      <td>Hearts</td>
      <td>Scotland</td>
      <td>Edinburgh</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>397</th>
      <td>Kye Rowles</td>
      <td>DEF</td>
      <td>24.00</td>
      <td>Australia</td>
      <td>Canberra</td>
      <td>3</td>
      <td>D</td>
      <td>Hearts</td>
      <td>Scotland</td>
      <td>Edinburgh</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>400</th>
      <td>Aaron Mooy</td>
      <td>MID</td>
      <td>32.00</td>
      <td>Australia</td>
      <td>Canberra</td>
      <td>53</td>
      <td>D</td>
      <td>Celtic</td>
      <td>Scotland</td>
      <td>Edinburgh</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>403</th>
      <td>Keanu Baccus</td>
      <td>MID</td>
      <td>29.00</td>
      <td>Australia</td>
      <td>Canberra</td>
      <td>53</td>
      <td>D</td>
      <td>St Mirren</td>
      <td>Scotland</td>
      <td>Edinburgh</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>404</th>
      <td>Cameron Devlin</td>
      <td>MID</td>
      <td>24.00</td>
      <td>Australia</td>
      <td>Canberra</td>
      <td>1</td>
      <td>D</td>
      <td>Hearts</td>
      <td>Scotland</td>
      <td>Edinburgh</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>464</th>
      <td>Daizen Maeda</td>
      <td>FWD</td>
      <td>25.00</td>
      <td>Japan</td>
      <td>Tokyo</td>
      <td>8</td>
      <td>E</td>
      <td>Celtic</td>
      <td>Scotland</td>
      <td>Edinburgh</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>548</th>
      <td>Borna Barisic</td>
      <td>DEF</td>
      <td>29.00</td>
      <td>Croatia</td>
      <td>Zagreb</td>
      <td>28</td>
      <td>F</td>
      <td>Rangers</td>
      <td>Scotland</td>
      <td>Edinburgh</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>554</th>
      <td>Josip Juranovic</td>
      <td>DEF</td>
      <td>27.00</td>
      <td>Croatia</td>
      <td>Zagreb</td>
      <td>21</td>
      <td>F</td>
      <td>Celtic</td>
      <td>Scotland</td>
      <td>Edinburgh</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>614</th>
      <td>David Wotherspoon</td>
      <td>MID</td>
      <td>32.00</td>
      <td>Canada</td>
      <td>Ottawa</td>
      <td>10</td>
      <td>F</td>
      <td>St. Johnstone</td>
      <td>Scotland</td>
      <td>Edinburgh</td>
      <td>Away</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Interestingly, out of the 12 players who play their club football in Scotland, 6 are Australian. The shared language is probably a contributory factor, certainly not the search for warmer weather.</p>
</section>
<section id="poland" class="level2">
<h2 class="anchored" data-anchor-id="poland">Poland</h2>
<div>
<p><img src="poland.jpg" width="200"></p>
</div>
<p>Having recently relocated here, at least I now have a team to follow! Let’s have a look at the players who play their club football in Poland:</p>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>poland_club <span class="op">=</span> world_cup[world_cup[<span class="st">'Club_ctry'</span>] <span class="op">==</span> <span class="st">'Poland'</span>]</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>poland_club</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>295</th>
      <td>Artur Jedrzejczyk</td>
      <td>DEF</td>
      <td>34.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>40</td>
      <td>C</td>
      <td>Legia Warsaw</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>297</th>
      <td>Michal&nbsp;Skoras</td>
      <td>MID</td>
      <td>22.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>1</td>
      <td>C</td>
      <td>Lech Poznan</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>301</th>
      <td>Kamil Grosicki</td>
      <td>MID</td>
      <td>34.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>87</td>
      <td>C</td>
      <td>Pogon Szczecin</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>706</th>
      <td>Filip Mladenovic</td>
      <td>DEF</td>
      <td>31.00</td>
      <td>Serbia</td>
      <td>Belgrade</td>
      <td>20</td>
      <td>G</td>
      <td>Legia Warsaw</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>Away</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Only 4 players, 3 of which are Polish. The lone soldier is Filip Mladenovic of Serbia who plays his club football with Legia Warsaw. Let’s have a look at the Poland squad in general:</p>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>poland <span class="op">=</span> world_cup[world_cup[<span class="st">'Country'</span>] <span class="op">==</span> <span class="st">'Poland'</span>]</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>poland</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="32">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>285</th>
      <td>Wojciech Szczesny</td>
      <td>GK</td>
      <td>32.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>66</td>
      <td>C</td>
      <td>Juventus</td>
      <td>Italy</td>
      <td>Rome</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>286</th>
      <td>Lukasz Skorupski</td>
      <td>GK</td>
      <td>31.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>8</td>
      <td>C</td>
      <td>Bologna</td>
      <td>Italy</td>
      <td>Rome</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>287</th>
      <td>Kamil Grabara</td>
      <td>GK</td>
      <td>23.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>1</td>
      <td>C</td>
      <td>Copenhagen</td>
      <td>Denmark</td>
      <td>Copenhagen</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>288</th>
      <td>Jan Bednarek</td>
      <td>DEF</td>
      <td>26.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>45</td>
      <td>C</td>
      <td>Aston Villa</td>
      <td>England</td>
      <td>London</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>289</th>
      <td>Kamil Glik</td>
      <td>DEF</td>
      <td>34.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>99</td>
      <td>C</td>
      <td>Benevento</td>
      <td>Italy</td>
      <td>Rome</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>290</th>
      <td>Matty Cash</td>
      <td>DEF</td>
      <td>25.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>7</td>
      <td>C</td>
      <td>Aston Villa</td>
      <td>England</td>
      <td>London</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>291</th>
      <td>Jakub Kiwior</td>
      <td>DEF</td>
      <td>22.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>3</td>
      <td>C</td>
      <td>Spezia</td>
      <td>Italy</td>
      <td>Rome</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>292</th>
      <td>Robert Gumny</td>
      <td>DEF</td>
      <td>24.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>5</td>
      <td>C</td>
      <td>FC Augsburg</td>
      <td>Germany</td>
      <td>Berlin</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>293</th>
      <td>Bartosz Bereszynski</td>
      <td>DEF</td>
      <td>30.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>46</td>
      <td>C</td>
      <td>Sampdoria</td>
      <td>Italy</td>
      <td>Rome</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>294</th>
      <td>Mateusz&nbsp;Wieteska</td>
      <td>DEF</td>
      <td>25.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>2</td>
      <td>C</td>
      <td>Clermont</td>
      <td>France</td>
      <td>Paris</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>295</th>
      <td>Artur Jedrzejczyk</td>
      <td>DEF</td>
      <td>34.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>40</td>
      <td>C</td>
      <td>Legia Warsaw</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>296</th>
      <td>Nicola Zalewski</td>
      <td>MID</td>
      <td>20.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>7</td>
      <td>C</td>
      <td>Roma</td>
      <td>Italy</td>
      <td>Rome</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>297</th>
      <td>Michal&nbsp;Skoras</td>
      <td>MID</td>
      <td>22.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>1</td>
      <td>C</td>
      <td>Lech Poznan</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>298</th>
      <td>Grzegorz Krychowiak</td>
      <td>MID</td>
      <td>32.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>94</td>
      <td>C</td>
      <td>Al Shabab</td>
      <td>Saudi Arabia</td>
      <td>Riyadh</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>299</th>
      <td>Piotr Zielinski</td>
      <td>MID</td>
      <td>28.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>74</td>
      <td>C</td>
      <td>Napoli</td>
      <td>Italy</td>
      <td>Rome</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>300</th>
      <td>Krystian Bielik</td>
      <td>MID</td>
      <td>24.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>5</td>
      <td>C</td>
      <td>Birmingham</td>
      <td>England</td>
      <td>London</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>301</th>
      <td>Kamil Grosicki</td>
      <td>MID</td>
      <td>34.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>87</td>
      <td>C</td>
      <td>Pogon Szczecin</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>Home</td>
    </tr>
    <tr>
      <th>302</th>
      <td>Przemyslaw Frankowski</td>
      <td>MID</td>
      <td>27.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>26</td>
      <td>C</td>
      <td>Lens</td>
      <td>France</td>
      <td>Paris</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>303</th>
      <td>Sebastian Szymanski</td>
      <td>MID</td>
      <td>23.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>18</td>
      <td>C</td>
      <td>Feyenoord</td>
      <td>Netherlands</td>
      <td>Amsterdam</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>304</th>
      <td>Damian Szymanski</td>
      <td>MID</td>
      <td>27.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>9</td>
      <td>C</td>
      <td>AEK Athens</td>
      <td>Greece</td>
      <td>Athens</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>305</th>
      <td>Szymon Zurkowski</td>
      <td>MID</td>
      <td>25.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>7</td>
      <td>C</td>
      <td>Fiorentina</td>
      <td>Italy</td>
      <td>Rome</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>306</th>
      <td>Jakub Kaminski</td>
      <td>MID</td>
      <td>20.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>4</td>
      <td>C</td>
      <td>Wolfsburg</td>
      <td>Germany</td>
      <td>Berlin</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>307</th>
      <td>Krzysztof Piatek</td>
      <td>FWD</td>
      <td>27.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>11</td>
      <td>C</td>
      <td>Salernitana</td>
      <td>Italy</td>
      <td>Rome</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>308</th>
      <td>Karol Swiderski</td>
      <td>FWD</td>
      <td>25.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>18</td>
      <td>C</td>
      <td>Charlotte</td>
      <td>USA</td>
      <td>Washington, DC</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>309</th>
      <td>Arkadiusz Milik</td>
      <td>FWD</td>
      <td>28.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>64</td>
      <td>C</td>
      <td>Juventus</td>
      <td>Italy</td>
      <td>Rome</td>
      <td>Away</td>
    </tr>
    <tr>
      <th>310</th>
      <td>Robert Lewandowski</td>
      <td>FWD</td>
      <td>34.00</td>
      <td>Poland</td>
      <td>Warsaw</td>
      <td>134</td>
      <td>C</td>
      <td>Barcelona</td>
      <td>Spain</td>
      <td>Madrid</td>
      <td>Away</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
<section id="home-and-away" class="level2">
<h2 class="anchored" data-anchor-id="home-and-away">Home and Away</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="World_Cup_2022_files/figure-html/1693bed6-de0c-4570-b6e2-e4b440a8abb6.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">home and away.jpg</figcaption><p></p>
</figure>
</div>
<p>These days players travel far and wide to ply their trade. I wondered what the impact of that might be on the tightness of a squad, and thought it would be interesting to take a closer look at where players play domestically.</p>
<p>Let’s take a look at the distribution of where the players play their club football:</p>
<div class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>world_cup[<span class="st">'Home_Away'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="33">
<pre><code>Away    551
Home    279
Name: Home_Away, dtype: int64</code></pre>
</div>
</div>
<p>Most players play their club football outside of their home nation. Let’s illustrate that graphically with a bar plot:</p>
<div class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>home_away_plot <span class="op">=</span> world_cup.groupby([<span class="st">'Home_Away'</span>, <span class="st">'Country'</span>]).size().sort_values(ascending<span class="op">=</span><span class="va">False</span>).reset_index().pivot(columns<span class="op">=</span><span class="st">'Home_Away'</span>, index<span class="op">=</span><span class="st">'Country'</span>, values<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>home_away_plot.plot(kind<span class="op">=</span><span class="st">'barh'</span>, stacked<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="36">
<pre><code>&lt;AxesSubplot: ylabel='Country'&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="World_Cup_2022_files/figure-html/cell-35-output-2.png" class="img-fluid"></p>
</div>
</div>
<p>That’s quite insightful and re-emphasises that most players do play their club football outside of their home nation, exemplified at the extreme by Senegal, where the entire squad are based outside of Senegal. At the other extreme, all of the Qatar and Saudi Arabia squads are based at home. England are the next ‘tightest’ squad. Will this contribute to a successful tournament? All will be revealed over the next few weeks!</p>
</section>
<section id="huddle" class="level2">
<h2 class="anchored" data-anchor-id="huddle">Huddle</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="World_Cup_2022_files/figure-html/e9598d9a-8c82-4ec0-8f58-bde7a1bc8b47.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">huddle.jpg</figcaption><p></p>
</figure>
</div>
<p>We have already established that the total distance for Saudi Arabia and Qatar is zero (their squads all play club football locally), but let’s try to establish just how far flung the other squads are, by calculating the distance for each player from their nation’s capital to the capital of the country where they play their club football.</p>
<p>Apologies for this next section which is not very Pythonic! In hindsight this was probably a tad ambitious for me as someone just starting out, and I ran into all sorts of obstacles, but I got there in the end, and thankfully before the tournament ended!</p>
<section id="obtaining-co-ordinates-using-geopy" class="level3">
<h3 class="anchored" data-anchor-id="obtaining-co-ordinates-using-geopy">Obtaining co-ordinates using Geopy</h3>
<p>We can obtain the co-ordinates of the capital cities of the countries where the players play their club football using the <a href="https://geopy.readthedocs.io/en/stable/">Geopy library</a> in Python. There is a very useful guide available <a href="https://www.geeksforgeeks.org/how-to-get-geolocation-in-python/">here</a>:</p>
<div class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">## Install required package</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>pip install geopy</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># import required module</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> geopy.geocoders <span class="im">import</span> Nominatim</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Requirement already satisfied: geopy in /home/stephen137/mambaforge/lib/python3.10/site-packages (2.2.0)
Requirement already satisfied: geographiclib&lt;2,&gt;=1.49 in /home/stephen137/mambaforge/lib/python3.10/site-packages (from geopy) (1.52)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>countries <span class="op">=</span> (<span class="st">'England'</span>, <span class="st">'Spain'</span>, <span class="st">'Germany'</span>, <span class="st">'Italy'</span>, <span class="st">'France'</span>, <span class="st">'Saudi Arabia'</span>, <span class="st">'Qatar'</span>, <span class="st">'United States'</span>, <span class="st">'Belgium'</span>, <span class="st">'Mexico'</span>, <span class="st">'Turkey'</span>, <span class="st">'Netherlands'</span>, <span class="st">'Portugal'</span>, <span class="st">'Costa Rica'</span>, <span class="st">'South Korea'</span>, <span class="st">'Greece'</span>, <span class="st">'Scotland'</span>, <span class="st">'Japan'</span>,             </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="st">'Canada'</span>, <span class="st">'Switzerland'</span>, <span class="st">'Iran'</span>,  <span class="st">'Denmark'</span>,  <span class="st">'Tunisia'</span>,  <span class="st">'Australia'</span>,  <span class="st">'Croatia'</span> , <span class="st">'Brazil'</span>,  <span class="st">'Argentina'</span>,  <span class="st">'Wales'</span>, <span class="st">'Poland'</span>,  <span class="st">'Morocco'</span>,  <span class="st">'Ecuador'</span>, <span class="st">'Austria'</span>, <span class="st">'Serbia'</span>, <span class="st">'Uruguay'</span>,  <span class="st">'Kuwait'</span>, <span class="st">'Russia'</span>,  <span class="st">'Ghana'</span>, <span class="st">'Egypt'</span>,                                    </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="st">'Cyprus'</span>, <span class="st">'China'</span>, <span class="st">'Cameroon'</span>, <span class="st">'Colombia'</span>,  <span class="st">'United Arab Emirates'</span>, <span class="st">'Senegal'</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>First, we can create a list of capital cities for the above countries, and then create a function to loop through this list, and extract the longitude and latitude for each of the cities:</p>
<div class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># List of capitals</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>capitals <span class="op">=</span> [<span class="st">'London'</span>, <span class="st">'Madrid'</span>, <span class="st">'Berlin'</span>, <span class="st">'Rome'</span>, <span class="st">'Paris'</span>, <span class="st">'Riyadh'</span>, <span class="st">'Doha'</span>, <span class="st">'Washington, DC'</span>, <span class="st">'Brussels'</span>, <span class="st">'Mexico City'</span>, <span class="st">'Ankara'</span>, <span class="st">'Amsterdam'</span>, <span class="st">'Lisbon'</span>, <span class="st">'San Jose'</span>, <span class="st">'Seoul'</span>, <span class="st">'Athens'</span>, <span class="st">'Edinburgh'</span>, <span class="st">'Tokyo'</span>, </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="st">'Ottawa'</span>, <span class="st">'Berne'</span>, <span class="st">'Tehran'</span>, <span class="st">'Copenhagen'</span>, <span class="st">'Tunis'</span>, <span class="st">'Canberra'</span>, <span class="st">'Zagreb'</span>, <span class="st">'Brasilia'</span>, <span class="st">'Buenos Aires'</span>, <span class="st">'Cardiff'</span>, <span class="st">'Warsaw'</span>, <span class="st">'Rabat'</span>, <span class="st">'Quito'</span>, <span class="st">'Vienna'</span>, <span class="st">'Belgrade'</span>, <span class="st">'Montevideo'</span>, <span class="st">'Kuwait City'</span>, <span class="st">'Moscow'</span>, <span class="st">'Accra'</span>, <span class="st">'Cairo'</span>,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="st">'Nicosia'</span>, <span class="st">'Beijing'</span>, <span class="st">'Yaounde'</span>, <span class="st">'Bogota'</span>,<span class="st">'Abu Dhabi'</span>,<span class="st">'Dakar'</span>]</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>geolocator <span class="op">=</span> Nominatim(user_agent<span class="op">=</span><span class="st">"GetLoc"</span>)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a><span class="co"># loop through list of capitals and return their co-ordinates</span></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> capital <span class="kw">in</span> capitals:</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>    location <span class="op">=</span> geolocator.geocode(capital)</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>    lat <span class="op">=</span> location.latitude</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">long</span> <span class="op">=</span> location.longitude </span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(lat,<span class="bu">long</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>51.5073219 -0.1276474
40.4167047 -3.7035825
52.5170365 13.3888599
41.8933203 12.4829321
48.8588897 2.3200410217200766
24.638916 46.7160104
25.2856329 51.5264162
38.8950368 -77.0365427
50.8465573 4.351697
19.4326296 -99.1331785
39.9207886 32.8540482
52.3727598 4.8936041
38.7077507 -9.1365919
37.3361663 -121.890591
37.5666791 126.9782914
37.9839412 23.7283052
55.9533456 -3.1883749
35.6828387 139.7594549
45.4208777 -75.6901106
46.9482713 7.4514512
35.6892523 51.3896004
55.6867243 12.5700724
33.8439408 9.400138
-35.2975906 149.1012676
45.84264135 15.962231476593626
-10.3333333 -53.2
-34.6075682 -58.4370894
51.4816546 -3.1791934
52.2337172 21.071432235636493
34.022405 -6.834543
-0.2201641 -78.5123274
48.2083537 16.3725042
44.8178131 20.4568974
-34.9058916 -56.1913095
29.3796532 47.9734174
55.7504461 37.6174943
5.5571096 -0.2012376
30.0443879 31.2357257
35.1748976 33.3638568
39.906217 116.3912757
3.8689867 11.5213344
4.6534649 -74.0836453
24.4538352 54.3774014
14.693425 -17.447938</code></pre>
</div>
</div>
<p>Now create a list which combines the capitals and their co-ordinates:</p>
<div class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>co_ordinates <span class="op">=</span> [[<span class="st">"London"</span>, <span class="fl">51.5073219</span>, <span class="op">-</span><span class="fl">0.1276474</span>],</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Madrid'</span>, <span class="fl">40.4167047</span>, <span class="op">-</span><span class="fl">3.7035825</span>],</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Berlin'</span>, <span class="fl">52.5170365</span>, <span class="fl">13.3888599</span>],</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Rome'</span>,  <span class="fl">41.8933203</span>, <span class="fl">12.4829321</span>],</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Paris'</span>, <span class="fl">48.8588897</span>, <span class="fl">2.3200410217200766</span>],</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Riyadh'</span>, <span class="fl">24.638916</span>, <span class="fl">46.7160104</span>],</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Doha'</span>, <span class="fl">25.2856329</span>, <span class="fl">51.5264162</span>],</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Washington, DC'</span>, <span class="fl">38.8950368</span>, <span class="op">-</span><span class="fl">77.0365427</span>],</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Brussels'</span>, <span class="fl">50.8465573</span>, <span class="fl">4.351697</span>],</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Mexico City'</span>, <span class="fl">19.4326296</span>, <span class="op">-</span><span class="fl">99.1331785</span>],</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Ankara'</span>, <span class="fl">39.9207886</span>, <span class="fl">32.8540482</span>],</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Amsterdam'</span>, <span class="fl">52.3727598</span>, <span class="fl">4.8936041</span>],</span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Lisbon'</span>, <span class="fl">38.7077507</span>, <span class="op">-</span><span class="fl">9.1365919</span>],</span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>[<span class="st">'San Jose'</span>, <span class="fl">37.3361663</span>, <span class="op">-</span><span class="fl">121.890591</span>],</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Seoul'</span>, <span class="fl">37.5666791</span>, <span class="fl">126.9782914</span>],</span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Athens'</span>, <span class="fl">37.9839412</span>, <span class="fl">23.7283052</span>],</span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Edinburgh'</span>, <span class="fl">55.9533456</span>, <span class="op">-</span><span class="fl">3.1883749</span>],</span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Tokyo'</span>, <span class="fl">35.6828387</span>, <span class="fl">139.7594549</span>],</span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Ottawa'</span>, <span class="fl">45.4208777</span>, <span class="op">-</span><span class="fl">75.6901106</span>],</span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Berne'</span>, <span class="fl">46.9482713</span>, <span class="fl">7.4514512</span>],</span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Tehran'</span>, <span class="fl">35.6892523</span>, <span class="fl">51.3896004</span>],</span>
<span id="cb52-22"><a href="#cb52-22" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Copenhagen'</span>, <span class="fl">55.6867243</span>, <span class="fl">12.5700724</span>],</span>
<span id="cb52-23"><a href="#cb52-23" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Tunis'</span>, <span class="fl">33.8439408</span>, <span class="fl">9.400138</span>],</span>
<span id="cb52-24"><a href="#cb52-24" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Canberra'</span>, <span class="fl">35.2975906</span>, <span class="fl">149.1012676</span>],</span>
<span id="cb52-25"><a href="#cb52-25" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Zagreb'</span>, <span class="fl">45.84264135</span>, <span class="fl">15.962231476593626</span>],</span>
<span id="cb52-26"><a href="#cb52-26" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Brasilia'</span>, <span class="op">-</span><span class="fl">10.3333333</span>, <span class="op">-</span><span class="fl">53.2</span>],</span>
<span id="cb52-27"><a href="#cb52-27" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Buenos Aires'</span>, <span class="op">-</span><span class="fl">34.6075682</span>, <span class="op">-</span><span class="fl">58.4370894</span>],</span>
<span id="cb52-28"><a href="#cb52-28" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Cardiff'</span>, <span class="fl">51.4816546</span>, <span class="op">-</span><span class="fl">3.1791934</span>],</span>
<span id="cb52-29"><a href="#cb52-29" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Warsaw'</span>, <span class="fl">52.2337172</span>, <span class="fl">21.071432235636493</span>],</span>
<span id="cb52-30"><a href="#cb52-30" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Rabat'</span>, <span class="fl">34.022405</span>, <span class="op">-</span><span class="fl">6.834543</span>],</span>
<span id="cb52-31"><a href="#cb52-31" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Quito'</span>, <span class="op">-</span><span class="fl">0.2201641</span>, <span class="op">-</span><span class="fl">78.5123274</span>],</span>
<span id="cb52-32"><a href="#cb52-32" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Vienna'</span>, <span class="fl">48.2083537</span>, <span class="fl">16.3725042</span>],</span>
<span id="cb52-33"><a href="#cb52-33" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Belgrade'</span>, <span class="fl">44.8178131</span>, <span class="fl">20.4568974</span>],</span>
<span id="cb52-34"><a href="#cb52-34" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Montevideo'</span>, <span class="op">-</span><span class="fl">34.9058916</span>, <span class="op">-</span><span class="fl">56.1913095</span>],</span>
<span id="cb52-35"><a href="#cb52-35" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Kuwait City'</span>, <span class="fl">29.3796532</span>, <span class="fl">47.9734174</span>],</span>
<span id="cb52-36"><a href="#cb52-36" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Moscow'</span>, <span class="fl">55.7504461</span>, <span class="fl">37.6174943</span>],</span>
<span id="cb52-37"><a href="#cb52-37" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Accra'</span>, <span class="fl">5.5571096</span>, <span class="op">-</span><span class="fl">0.2012376</span>],</span>
<span id="cb52-38"><a href="#cb52-38" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Cairo'</span>, <span class="fl">30.0443879</span>, <span class="fl">31.2357257</span>],</span>
<span id="cb52-39"><a href="#cb52-39" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Nicosia'</span>, <span class="fl">35.1748976</span>, <span class="fl">33.3638568</span>],</span>
<span id="cb52-40"><a href="#cb52-40" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Beijing'</span>, <span class="fl">39.906217</span>, <span class="fl">116.3912757</span>],</span>
<span id="cb52-41"><a href="#cb52-41" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Yaounde'</span>, <span class="fl">3.8689867</span>, <span class="fl">11.5213344</span>],</span>
<span id="cb52-42"><a href="#cb52-42" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Bogota'</span>, <span class="fl">4.6534649</span>, <span class="op">-</span><span class="fl">74.0836453</span>],</span>
<span id="cb52-43"><a href="#cb52-43" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Abu Dhabi'</span>, <span class="fl">24.4538352</span>, <span class="fl">54.3774014</span>],</span>
<span id="cb52-44"><a href="#cb52-44" aria-hidden="true" tabindex="-1"></a>[<span class="st">'Dakar'</span>, <span class="fl">14.693425</span>, <span class="op">-</span><span class="fl">17.447938</span>]]    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And now create separate DataFrames for our ‘from’ and ‘to’ destinations:</p>
<div class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>from_co_ord <span class="op">=</span> pd.DataFrame(co_ordinates,columns<span class="op">=</span>[<span class="st">'from'</span>, <span class="st">'from_long'</span>, <span class="st">'from_lat'</span>])</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>to_co_ord <span class="op">=</span> pd.DataFrame(co_ordinates,columns<span class="op">=</span>[<span class="st">'to'</span>, <span class="st">'to_long'</span>, <span class="st">'to_lat'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>from_co_ord.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="42">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>from</th>
      <th>from_long</th>
      <th>from_lat</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>London</td>
      <td>51.51</td>
      <td>-0.13</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Madrid</td>
      <td>40.42</td>
      <td>-3.70</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Berlin</td>
      <td>52.52</td>
      <td>13.39</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Rome</td>
      <td>41.89</td>
      <td>12.48</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Paris</td>
      <td>48.86</td>
      <td>2.32</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>to_co_ord.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="43">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>to</th>
      <th>to_long</th>
      <th>to_lat</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>London</td>
      <td>51.51</td>
      <td>-0.13</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Madrid</td>
      <td>40.42</td>
      <td>-3.70</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Berlin</td>
      <td>52.52</td>
      <td>13.39</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Rome</td>
      <td>41.89</td>
      <td>12.48</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Paris</td>
      <td>48.86</td>
      <td>2.32</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
<section id="obtaining-all-possible-city-pair-combinations" class="level3">
<h3 class="anchored" data-anchor-id="obtaining-all-possible-city-pair-combinations">Obtaining all possible city pair combinations</h3>
<p>We need to find all the possible ‘from’ : ‘to’ combinations in order to calculate the distances between the cities. We have 44 cities which gives according to this <a href="https://www.omnicalculator.com/statistics/combination">handy calculator</a> , 946 pairings without repetitions.</p>
<p>After some digging around I found <a href="https://stackoverflow.com/questions/57277290/looping-through-two-separate-dataframes-haversine-function-store-the-values">this post</a> on <strong>stackoverflow</strong> which gave a general overview of how this might be achieved. In order to obtain the pairings and index them, we can use the <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.from_product.html#pandas.MultiIndex.from_product">MultiIndex.from_product</a> pandas class:</p>
<div class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>idx <span class="op">=</span> pd.MultiIndex.from_product([from_co_ord.index, to_co_ord.index], names<span class="op">=</span>[<span class="st">'from'</span>, <span class="st">'to'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a combined DataFrame that joins our from and to DataFrames</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Includes all possible pairings (including duplicates)</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>from_to <span class="op">=</span> pd.DataFrame(index<span class="op">=</span>idx) <span class="op">\</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>        .join(from_co_ord[[<span class="st">'from'</span>,<span class="st">'from_lat'</span>, <span class="st">'from_long'</span>]], on<span class="op">=</span><span class="st">'from'</span>) <span class="op">\</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>        .join(to_co_ord[[<span class="st">'to'</span>,<span class="st">'to_lat'</span>, <span class="st">'to_long'</span>]], on<span class="op">=</span><span class="st">'to'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>from_to</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="46">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>from</th>
      <th>from_lat</th>
      <th>from_long</th>
      <th>to</th>
      <th>to_lat</th>
      <th>to_long</th>
    </tr>
    <tr>
      <th>from</th>
      <th>to</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="5" valign="top">0</th>
      <th>0</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
    </tr>
    <tr>
      <th>1</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>Madrid</td>
      <td>-3.70</td>
      <td>40.42</td>
    </tr>
    <tr>
      <th>2</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>Berlin</td>
      <td>13.39</td>
      <td>52.52</td>
    </tr>
    <tr>
      <th>3</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>Rome</td>
      <td>12.48</td>
      <td>41.89</td>
    </tr>
    <tr>
      <th>4</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>Paris</td>
      <td>2.32</td>
      <td>48.86</td>
    </tr>
    <tr>
      <th>...</th>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th rowspan="5" valign="top">43</th>
      <th>39</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Beijing</td>
      <td>116.39</td>
      <td>39.91</td>
    </tr>
    <tr>
      <th>40</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Yaounde</td>
      <td>11.52</td>
      <td>3.87</td>
    </tr>
    <tr>
      <th>41</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Bogota</td>
      <td>-74.08</td>
      <td>4.65</td>
    </tr>
    <tr>
      <th>42</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Abu Dhabi</td>
      <td>54.38</td>
      <td>24.45</td>
    </tr>
    <tr>
      <th>43</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
    </tr>
  </tbody>
</table>
<p>1936 rows × 6 columns</p>
</div>
</div>
</div>
<p>That’s not quite as concise as we would like - we have 1936 pairings. That’s because <strong><em>MultiIndex.from_prodcut</em></strong> has returned values for London to London, Dakar to Dakar, etc. We also have London to Madrid, and Madrid to London which is also duplication. Let’s move forward.</p>
</section>
<section id="going-the-extra-mile" class="level3">
<h3 class="anchored" data-anchor-id="going-the-extra-mile">Going the extra mile</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="World_Cup_2022_files/figure-html/9d9a872c-ad5b-4cb8-b9be-34a26625721f.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">proclaimers.jpg</figcaption><p></p>
</figure>
</div>
<p>We can calculate the distance between two locations using <a href="https://pypi.org/project/haversine/">Haversine</a>. Let’s create a function that allows us to return values for all our pairings:</p>
<div class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> haversine_np(lon1, lat1, lon2, lat2):</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Calculate the great circle distance between two points</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co">    on the earth (specified in decimal degrees)</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a><span class="co">    All args must be of equal length.    </span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>    lon1, lat1, lon2, lat2 <span class="op">=</span> <span class="bu">map</span>(np.radians, [lon1, lat1, lon2, lat2])</span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>    dlon <span class="op">=</span> lon2 <span class="op">-</span> lon1</span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>    dlat <span class="op">=</span> lat2 <span class="op">-</span> lat1</span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a>    a <span class="op">=</span> np.sin(dlat<span class="op">/</span><span class="fl">2.0</span>)<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> np.cos(lat1) <span class="op">*</span> np.cos(lat2) <span class="op">*</span> np.sin(dlon<span class="op">/</span><span class="fl">2.0</span>)<span class="op">**</span><span class="dv">2</span></span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-16"><a href="#cb59-16" aria-hidden="true" tabindex="-1"></a>    c <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> np.arcsin(np.sqrt(a))</span>
<span id="cb59-17"><a href="#cb59-17" aria-hidden="true" tabindex="-1"></a>    km <span class="op">=</span> <span class="dv">6367</span> <span class="op">*</span> c</span>
<span id="cb59-18"><a href="#cb59-18" aria-hidden="true" tabindex="-1"></a>    miles <span class="op">=</span> km <span class="op">*</span> <span class="fl">0.621371</span></span>
<span id="cb59-19"><a href="#cb59-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> miles</span>
<span id="cb59-20"><a href="#cb59-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-21"><a href="#cb59-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a new column to our from_to DataFrame to include the distance calculations</span></span>
<span id="cb59-22"><a href="#cb59-22" aria-hidden="true" tabindex="-1"></a>from_to[<span class="st">'Distance_miles'</span>] <span class="op">=</span> haversine_np(<span class="op">*</span>from_to[[<span class="st">'from_lat'</span>, <span class="st">'from_long'</span>, <span class="st">'to_lat'</span>, <span class="st">'to_long'</span>]].values.T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s take a look at our completed distances DataFrame:</p>
<div class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>from_to</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="48">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>from</th>
      <th>from_lat</th>
      <th>from_long</th>
      <th>to</th>
      <th>to_lat</th>
      <th>to_long</th>
      <th>Distance_miles</th>
    </tr>
    <tr>
      <th>from</th>
      <th>to</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="5" valign="top">0</th>
      <th>0</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>1</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>Madrid</td>
      <td>-3.70</td>
      <td>40.42</td>
      <td>784.56</td>
    </tr>
    <tr>
      <th>2</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>Berlin</td>
      <td>13.39</td>
      <td>52.52</td>
      <td>577.80</td>
    </tr>
    <tr>
      <th>3</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>Rome</td>
      <td>12.48</td>
      <td>41.89</td>
      <td>890.44</td>
    </tr>
    <tr>
      <th>4</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>Paris</td>
      <td>2.32</td>
      <td>48.86</td>
      <td>212.47</td>
    </tr>
    <tr>
      <th>...</th>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th rowspan="5" valign="top">43</th>
      <th>39</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Beijing</td>
      <td>116.39</td>
      <td>39.91</td>
      <td>7634.29</td>
    </tr>
    <tr>
      <th>40</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Yaounde</td>
      <td>11.52</td>
      <td>3.87</td>
      <td>2107.38</td>
    </tr>
    <tr>
      <th>41</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Bogota</td>
      <td>-74.08</td>
      <td>4.65</td>
      <td>3906.72</td>
    </tr>
    <tr>
      <th>42</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Abu Dhabi</td>
      <td>54.38</td>
      <td>24.45</td>
      <td>4673.86</td>
    </tr>
    <tr>
      <th>43</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>0.00</td>
    </tr>
  </tbody>
</table>
<p>1936 rows × 7 columns</p>
</div>
</div>
</div>
</section>
</section>
<section id="v-look-up-in-python" class="level2">
<h2 class="anchored" data-anchor-id="v-look-up-in-python">V look up in Python</h2>
<p>We now want to include the distance figures in our orginal world_cup DataFrame to allow us to calculate the total distance per squad, which will give us some sort of comaprison of the ‘closeness’ of the 32 teams. I am familiar with this feature in Excel but you can do the same thing in Python. Here is a <a href="https://www.geeksforgeeks.org/how-to-do-a-vlookup-in-python-using-pandas/">useful article</a> on how to do it.</p>
<p>Let’s first get our DataFrames tee’d up by adding a common column for joining on:</p>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>from_to[<span class="st">"from_to"</span>] <span class="op">=</span> from_to[<span class="st">'from'</span>] <span class="op">+</span> <span class="st">" to "</span> <span class="op">+</span> from_to[<span class="st">'to'</span>]</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>from_to</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="49">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th>from</th>
      <th>from_lat</th>
      <th>from_long</th>
      <th>to</th>
      <th>to_lat</th>
      <th>to_long</th>
      <th>Distance_miles</th>
      <th>from_to</th>
    </tr>
    <tr>
      <th>from</th>
      <th>to</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="5" valign="top">0</th>
      <th>0</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>0.00</td>
      <td>London to London</td>
    </tr>
    <tr>
      <th>1</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>Madrid</td>
      <td>-3.70</td>
      <td>40.42</td>
      <td>784.56</td>
      <td>London to Madrid</td>
    </tr>
    <tr>
      <th>2</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>Berlin</td>
      <td>13.39</td>
      <td>52.52</td>
      <td>577.80</td>
      <td>London to Berlin</td>
    </tr>
    <tr>
      <th>3</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>Rome</td>
      <td>12.48</td>
      <td>41.89</td>
      <td>890.44</td>
      <td>London to Rome</td>
    </tr>
    <tr>
      <th>4</th>
      <td>London</td>
      <td>-0.13</td>
      <td>51.51</td>
      <td>Paris</td>
      <td>2.32</td>
      <td>48.86</td>
      <td>212.47</td>
      <td>London to Paris</td>
    </tr>
    <tr>
      <th>...</th>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th rowspan="5" valign="top">43</th>
      <th>39</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Beijing</td>
      <td>116.39</td>
      <td>39.91</td>
      <td>7634.29</td>
      <td>Dakar to Beijing</td>
    </tr>
    <tr>
      <th>40</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Yaounde</td>
      <td>11.52</td>
      <td>3.87</td>
      <td>2107.38</td>
      <td>Dakar to Yaounde</td>
    </tr>
    <tr>
      <th>41</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Bogota</td>
      <td>-74.08</td>
      <td>4.65</td>
      <td>3906.72</td>
      <td>Dakar to Bogota</td>
    </tr>
    <tr>
      <th>42</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Abu Dhabi</td>
      <td>54.38</td>
      <td>24.45</td>
      <td>4673.86</td>
      <td>Dakar to Abu Dhabi</td>
    </tr>
    <tr>
      <th>43</th>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>Dakar</td>
      <td>-17.45</td>
      <td>14.69</td>
      <td>0.00</td>
      <td>Dakar to Dakar</td>
    </tr>
  </tbody>
</table>
<p>1936 rows × 8 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>world_cup[<span class="st">"from_to"</span>] <span class="op">=</span> world_cup[<span class="st">'Ctry_cap'</span>] <span class="op">+</span> <span class="st">" to "</span> <span class="op">+</span> world_cup[<span class="st">'Club_ctry_cap'</span>]</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>world_cup</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="50">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
      <th>from_to</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Saad Al-Sheeb</td>
      <td>GK</td>
      <td>32.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>80</td>
      <td>A</td>
      <td>Al-Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
      <td>Doha to Doha</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Meshaal Barsham</td>
      <td>GK</td>
      <td>24.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>15</td>
      <td>A</td>
      <td>Al-Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
      <td>Doha to Doha</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Yousuf Hassan</td>
      <td>GK</td>
      <td>26.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>9</td>
      <td>A</td>
      <td>Al-Gharafa</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
      <td>Doha to Doha</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Pedro Miguel</td>
      <td>DEF</td>
      <td>32.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>78</td>
      <td>A</td>
      <td>Al-Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
      <td>Doha to Doha</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Musaab Khidir</td>
      <td>DEF</td>
      <td>29.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>29</td>
      <td>A</td>
      <td>Al-Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
      <td>Doha to Doha</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>825</th>
      <td>Kamaldeen Sulemana</td>
      <td>MID</td>
      <td>20.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>11</td>
      <td>H</td>
      <td>Stade Rennes</td>
      <td>France</td>
      <td>Paris</td>
      <td>Away</td>
      <td>Accra to Paris</td>
    </tr>
    <tr>
      <th>826</th>
      <td>Antoine Semenyo</td>
      <td>FWD</td>
      <td>22.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>1</td>
      <td>H</td>
      <td>Bristol City</td>
      <td>England</td>
      <td>London</td>
      <td>Away</td>
      <td>Accra to London</td>
    </tr>
    <tr>
      <th>827</th>
      <td>Andre Ayew</td>
      <td>FWD</td>
      <td>32.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>107</td>
      <td>H</td>
      <td>Al Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Away</td>
      <td>Accra to Doha</td>
    </tr>
    <tr>
      <th>828</th>
      <td>Jordan Ayew</td>
      <td>FWD</td>
      <td>31.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>82</td>
      <td>H</td>
      <td>Crystal Palace</td>
      <td>England</td>
      <td>London</td>
      <td>Away</td>
      <td>Accra to London</td>
    </tr>
    <tr>
      <th>829</th>
      <td>Inaki Williams</td>
      <td>FWD</td>
      <td>28.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>1</td>
      <td>H</td>
      <td>Athletic Club</td>
      <td>Spain</td>
      <td>Madrid</td>
      <td>Away</td>
      <td>Accra to Madrid</td>
    </tr>
  </tbody>
</table>
<p>830 rows × 12 columns</p>
</div>
</div>
</div>
<p>Finally we can join our two DataFrames together which will give us a distance column and value for each player in the tournament:</p>
<div class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>inner_join <span class="op">=</span> pd.merge(world_cup, from_to, on<span class="op">=</span><span class="st">'from_to'</span>,how<span class="op">=</span><span class="st">'inner'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>inner_join</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="52">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Position</th>
      <th>Age</th>
      <th>Country</th>
      <th>Ctry_cap</th>
      <th>Caps</th>
      <th>Group</th>
      <th>Club</th>
      <th>Club_ctry</th>
      <th>Club_ctry_cap</th>
      <th>Home_Away</th>
      <th>from_to</th>
      <th>from</th>
      <th>from_lat</th>
      <th>from_long</th>
      <th>to</th>
      <th>to_lat</th>
      <th>to_long</th>
      <th>Distance_miles</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Saad Al-Sheeb</td>
      <td>GK</td>
      <td>32.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>80</td>
      <td>A</td>
      <td>Al-Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
      <td>Doha to Doha</td>
      <td>Doha</td>
      <td>51.53</td>
      <td>25.29</td>
      <td>Doha</td>
      <td>51.53</td>
      <td>25.29</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Meshaal Barsham</td>
      <td>GK</td>
      <td>24.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>15</td>
      <td>A</td>
      <td>Al-Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
      <td>Doha to Doha</td>
      <td>Doha</td>
      <td>51.53</td>
      <td>25.29</td>
      <td>Doha</td>
      <td>51.53</td>
      <td>25.29</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Yousuf Hassan</td>
      <td>GK</td>
      <td>26.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>9</td>
      <td>A</td>
      <td>Al-Gharafa</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
      <td>Doha to Doha</td>
      <td>Doha</td>
      <td>51.53</td>
      <td>25.29</td>
      <td>Doha</td>
      <td>51.53</td>
      <td>25.29</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Pedro Miguel</td>
      <td>DEF</td>
      <td>32.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>78</td>
      <td>A</td>
      <td>Al-Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
      <td>Doha to Doha</td>
      <td>Doha</td>
      <td>51.53</td>
      <td>25.29</td>
      <td>Doha</td>
      <td>51.53</td>
      <td>25.29</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Musaab Khidir</td>
      <td>DEF</td>
      <td>29.00</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>29</td>
      <td>A</td>
      <td>Al-Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Home</td>
      <td>Doha to Doha</td>
      <td>Doha</td>
      <td>51.53</td>
      <td>25.29</td>
      <td>Doha</td>
      <td>51.53</td>
      <td>25.29</td>
      <td>0.00</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>805</th>
      <td>Mohammed Kudus</td>
      <td>MID</td>
      <td>22.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>16</td>
      <td>H</td>
      <td>Ajax</td>
      <td>Netherlands</td>
      <td>Amsterdam</td>
      <td>Away</td>
      <td>Accra to Amsterdam</td>
      <td>Accra</td>
      <td>-0.20</td>
      <td>5.56</td>
      <td>Amsterdam</td>
      <td>4.89</td>
      <td>52.37</td>
      <td>3245.62</td>
    </tr>
    <tr>
      <th>806</th>
      <td>Daniel Kofi-Kyereh</td>
      <td>MID</td>
      <td>26.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>12</td>
      <td>H</td>
      <td>Freiburg</td>
      <td>Germany</td>
      <td>Berlin</td>
      <td>Away</td>
      <td>Accra to Berlin</td>
      <td>Accra</td>
      <td>-0.20</td>
      <td>5.56</td>
      <td>Berlin</td>
      <td>13.39</td>
      <td>52.52</td>
      <td>3333.41</td>
    </tr>
    <tr>
      <th>807</th>
      <td>Fatawu&nbsp;Issahaku</td>
      <td>MID</td>
      <td>18.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>11</td>
      <td>H</td>
      <td>Sporting</td>
      <td>Portugal</td>
      <td>Lisbon</td>
      <td>Away</td>
      <td>Accra to Lisbon</td>
      <td>Accra</td>
      <td>-0.20</td>
      <td>5.56</td>
      <td>Lisbon</td>
      <td>-9.14</td>
      <td>38.71</td>
      <td>2356.37</td>
    </tr>
    <tr>
      <th>808</th>
      <td>Osman Bukari</td>
      <td>MID</td>
      <td>23.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>5</td>
      <td>H</td>
      <td>Red Star Belgrade</td>
      <td>Serbia</td>
      <td>Belgrade</td>
      <td>Away</td>
      <td>Accra to Belgrade</td>
      <td>Accra</td>
      <td>-0.20</td>
      <td>5.56</td>
      <td>Belgrade</td>
      <td>20.46</td>
      <td>44.82</td>
      <td>2983.47</td>
    </tr>
    <tr>
      <th>809</th>
      <td>Andre Ayew</td>
      <td>FWD</td>
      <td>32.00</td>
      <td>Ghana</td>
      <td>Accra</td>
      <td>107</td>
      <td>H</td>
      <td>Al Sadd</td>
      <td>Qatar</td>
      <td>Doha</td>
      <td>Away</td>
      <td>Accra to Doha</td>
      <td>Accra</td>
      <td>-0.20</td>
      <td>5.56</td>
      <td>Doha</td>
      <td>51.53</td>
      <td>25.29</td>
      <td>3674.63</td>
    </tr>
  </tbody>
</table>
<p>810 rows × 19 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="53">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>title_string <span class="op">=</span> <span class="st">"FIFA World Cup - Qatar 2022"</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>subtitle_string <span class="op">=</span> <span class="st">"Total miles travelled by squad - from their club country capital to their nation capital"</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> inner_join.groupby(<span class="st">'Country'</span>)[<span class="st">'Distance_miles'</span>].<span class="bu">sum</span>().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>x.plot(kind<span class="op">=</span><span class="st">'barh'</span>)</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>plt.suptitle(title_string, y<span class="op">=</span><span class="fl">1.05</span>, fontsize<span class="op">=</span><span class="dv">18</span>)</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>plt.title(subtitle_string, fontsize<span class="op">=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="53">
<pre><code>Text(0.5, 1.0, 'Total miles travelled by squad - from their club country capital to their nation capital')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="World_Cup_2022_files/figure-html/cell-52-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>inner_join.groupby(<span class="st">"Country"</span>)[<span class="st">"Distance_miles"</span>].<span class="bu">sum</span>().sort_values(ascending<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="54">
<pre><code>Country
Saudi Arabia        0.00
Qatar               0.00
England           577.80
Germany          4631.29
Spain            6389.33
Netherlands      6658.89
Wales            7674.01
Belgium          7824.11
France           9663.44
Switzerland     12648.83
Croatia         13322.72
Denmark         15194.21
Portugal        18366.13
Serbia          19948.33
Poland          23557.92
Tunisia         25922.17
Iran            26752.28
Morocco         27042.30
Costa Rica      37651.80
Canada          47922.17
South Korea     53858.03
Mexico          55687.73
USA             61448.54
Senegal         66198.44
Ghana           73052.50
Cameroon        78656.09
Ecuador         80700.85
Uruguay         93702.58
Australia       98441.33
Japan          112062.53
Brazil         118045.02
Argentina      162925.56
Name: Distance_miles, dtype: float64</code></pre>
</div>
</div>
</section>
<section id="full-time" class="level2">
<h2 class="anchored" data-anchor-id="full-time">Full time</h2>
<div>
<p><img src="final_whistle.jpg" width="300"></p>
</div>
<p>Home advantage often counts. If you recall South Korea reached the semi final when they hosted the tournament back in 2002, and if you look back even further to 1966 then… Let’s end that there.</p>
<p>Will this togetherness give Qatar an advantage? Time will tell. They also have the ‘tightest’ squad (along with Saudi Arabia) in terms of the fact that all of their players play their club football at home. Outside of those two, England are the ‘closest’ squad, with only Jude Bellingham (Borussia Dortmund) playing his club football outside of England.</p>
<p>The Argentina squad are the most scattered, followed by Brazil, Argentina, and Japan. This makes sense, as most of their squads play in Europe, which is a long way from home!</p>
</section>
<section id="key-take-aways" class="level2">
<h2 class="anchored" data-anchor-id="key-take-aways">Key take-aways</h2>
<p>This has been a rewarding project overall for me. I achieved what I set out to do, which began with a vague idea of the ‘tightness’ of the World Cup squads, and how I might quantify this, perhaps by looking at where the players play their club football, and how far they would have to travel to begin preparations back in their home nation.</p>
<p>There were many obstacles along the way, the main one was working out how to calculate the distance between two points, and this gave me a first introduction to working with geospatial data, including the <a href="https://geopy.readthedocs.io/en/stable/">Geopy library</a> and <a href="https://pypi.org/project/haversine/">Haversine</a>. I also managed to create one or two functions to automate the extraction of co-ordinate data and distance calculations and found about one of the more advanced panda classes, <a href="https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.from_product.html#pandas.MultiIndex.from_product">MultiIndex.from_product</a>.</p>
<p>I was familiar with the <a href="https://support.microsoft.com/en-us/office/vlookup-function-0bbc8083-26fe-4963-8ab8-93a18ad188a1">VLOOKUP fuction</a> in Excel, and the various <a href="https://en.wikipedia.org/wiki/Join_(SQL)">join clauses</a> in SQL, but I now know how to achieve the same end result using pandas <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html">merge</a>.</p>
<p>I’m looking forward to seeing how this Tournament unfolds - may the best team win!</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>