<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Stephen Barrie">
<meta name="dcterms.date" content="2023-05-25">

<title>Into the Unknown - mlops-zoomcamp | Module 2: Experiment tracking and model management</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Into the Unknown</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">Stephen Barrie</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"><i class="bi bi-rss" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Stephen137"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/sjbarrie"><i class="bi bi-linkedin" role="img">
</i> 
 </a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">mlops-zoomcamp | Module 2: Experiment tracking and model management</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">MLOps</div>
                <div class="quarto-category">DataTalksClub</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Stephen Barrie </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 25, 2023</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#experiment-tracking-and-model-management" id="toc-experiment-tracking-and-model-management" class="nav-link active" data-scroll-target="#experiment-tracking-and-model-management">2. Experiment tracking and model management</a>
  <ul class="collapse">
  <li><a href="#experiment-tracking-intro" id="toc-experiment-tracking-intro" class="nav-link" data-scroll-target="#experiment-tracking-intro">2.1 Experiment tracking intro</a></li>
  <li><a href="#getting-started-with-mlflow" id="toc-getting-started-with-mlflow" class="nav-link" data-scroll-target="#getting-started-with-mlflow">2.2 Getting started with MLflow</a></li>
  <li><a href="#experiment-tracking-with-mlflow" id="toc-experiment-tracking-with-mlflow" class="nav-link" data-scroll-target="#experiment-tracking-with-mlflow">2.3 Experiment tracking with MLflow</a></li>
  <li><a href="#model-management" id="toc-model-management" class="nav-link" data-scroll-target="#model-management">2.4 Model management</a></li>
  <li><a href="#model-registry" id="toc-model-registry" class="nav-link" data-scroll-target="#model-registry">2.5 Model Registry</a></li>
  <li><a href="#mlflow-in-practice" id="toc-mlflow-in-practice" class="nav-link" data-scroll-target="#mlflow-in-practice">2.6 MLflow in practice</a></li>
  <li><a href="#setting-up-an-aws-account" id="toc-setting-up-an-aws-account" class="nav-link" data-scroll-target="#setting-up-an-aws-account">2.6.4 Setting up an AWS account</a></li>
  <li><a href="#mlflow-benefits-limitations-and-alternatives" id="toc-mlflow-benefits-limitations-and-alternatives" class="nav-link" data-scroll-target="#mlflow-benefits-limitations-and-alternatives">2.7 MLflow: benefits, limitations and alternatives</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="experiment-tracking-and-model-management" class="level2">
<h2 class="anchored" data-anchor-id="experiment-tracking-and-model-management">2. Experiment tracking and model management</h2>
<p>Spreadsheets are a familiar tool and widely used across different industries. Many people are already familiar with spreadsheet software like Microsoft Excel or Google Sheets, making it easier to adopt and use for experiment tracking without requiring additional learning or training.</p>
<p>However, as the complexity and scale of your experiments increase, and your experiment tracking needs evolve, dedicated experiment tracking platforms may provide more advanced features and better support for reproducibility, collaboration, and scalability.</p>
<section id="experiment-tracking-intro" class="level3">
<h3 class="anchored" data-anchor-id="experiment-tracking-intro">2.1 Experiment tracking intro</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/7d24aa18-1419-48b2-bdbb-ce053a31cd2d.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">experiment_tracking.PNG</figcaption><p></p>
</figure>
</div>
<p>Experiment tracking in machine learning refers to the practice of systematically recording and organizing information about machine learning experiments. It involves capturing various aspects of an experiment, such as hyperparameters, datasets, model architecture, evaluation metrics, and results. Experiment tracking platforms or tools are often used to facilitate this process.</p>
<p>The purpose of experiment tracking is to enable reproducibility, collaboration, and optimization of machine learning workflows. By keeping a detailed record of experiments, researchers and data scientists can easily revisit and reproduce previous experiments, compare different approaches, and make informed decisions about model improvements. Experiment tracking also helps in identifying patterns, understanding the impact of various factors on model performance, and sharing findings with colleagues.</p>
</section>
<section id="getting-started-with-mlflow" class="level3">
<h3 class="anchored" data-anchor-id="getting-started-with-mlflow">2.2 Getting started with MLflow</h3>
<p><a href="https://mlflow.org/">MLflow</a> is an open-source platform for managing the machine learning lifecycle. It provides a comprehensive set of tools and APIs to help data scientists and machine learning engineers track, manage, and deploy machine learning experiments and models. MLflow aims to simplify the process of building, sharing, and reproducing machine learning projects.</p>
<p>The main components of MLflow are:</p>
<ul>
<li><p><code>Tracking:</code> MLflow Tracking allows users to log and organize experiments. It captures parameters, metrics, and artifacts (such as models or visualizations) associated with each run. The tracking component enables easy comparison and reproducibility of experiments, as well as visualization of experiment results.</p></li>
<li><p><code>Projects:</code> MLflow Projects provide a standard format for organizing and packaging code in a machine learning project. It allows you to define dependencies, specify the entry point for running the project, and easily reproduce and share the project with others.</p></li>
<li><p><code>Models:</code> MLflow Models provides a way to manage and deploy machine learning models in a standardized manner. It supports various model formats and allows easy deployment to different execution environments, such as local deployment or serving through REST APIs.</p></li>
<li><p><code>Model Registry (Enterprise Edition):</code> MLflow Model Registry (available in the Enterprise Edition) offers model versioning, stage management, and collaboration features. It allows teams to manage and track the lifecycle of models, including transitioning models between development stages, approving and promoting models, and enabling collaboration among team members.</p></li>
</ul>
<p>MLflow supports multiple programming languages and integrates with popular machine learning libraries and frameworks like TensorFlow, PyTorch, and scikit-learn. It can be used both locally and in distributed computing environments like Apache Spark.</p>
<p>Overall, MLflow simplifies the process of managing and tracking machine learning experiments, facilitating collaboration, reproducibility, and deployment of machine learning models. It provides a unified interface and toolset to help data scientists and machine learning practitioners manage the entire lifecycle of their projects.</p>
<section id="installing-mlflow" class="level4">
<h4 class="anchored" data-anchor-id="installing-mlflow">2.2.1 Installing MLflow</h4>
<p>First, let’s set up a virtual environment by running the following from the command line:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>conda create <span class="op">-</span>n exp<span class="op">-</span>tracking<span class="op">-</span>env python<span class="op">=</span><span class="fl">3.9</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/07613277-e566-44c8-a210-44b6cc9b382a.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">environment.PNG</figcaption><p></p>
</figure>
</div>
<p>And then activate the environment :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>conda activate exp<span class="op">-</span>tracking<span class="op">-</span>env</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And install the following dependencies :</p>
<p><code>requirements.txt</code><br>
mlflow<br>
jupyter<br>
scikit-learn<br>
pandas<br>
seaborn<br>
hyperopt<br>
xgboost<br>
fastparquet<br>
boto3</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pip install <span class="op">-</span>r requirements.txt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/94fbd9c5-2de6-4e14-b32f-85ff6481497e.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">requirements.PNG</figcaption><p></p>
</figure>
</div>
<p>With all the dependencies intalled, we are ready to roll. To initiate MLllow and get access to the CLI just type the following in your terminal :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mlflow</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/0cd45870-c5c4-4649-a6ab-2db92ca9d6cd.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">mlflow_cli.PNG</figcaption><p></p>
</figure>
</div>
</section>
<section id="the-mlflow-ui" class="level4">
<h4 class="anchored" data-anchor-id="the-mlflow-ui">2.2.2 The MLFlow UI</h4>
<p>To launch the MLflow UI enter the following from the command line :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mlflow ui <span class="op">--</span>backend<span class="op">-</span>store<span class="op">-</span>uri sqlite:<span class="op">///</span>mlflow.db</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Make sure you launch the mlflow UI from the same directory as the scripts/jupyter notebook that is running the experiments (same directory that has the mlflow directory and the database that stores the experiments).</p>
</div>
</div>
<p>I found that running:</p>
<pre><code>mlflow server</code></pre>
<p>worked without any problems.</p>
<p>And we can view by copying the highlighted link <code>http://127.0.0.1:5000</code> into your browser :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/542ba2b7-5d25-42de-85b9-a69644047ba8.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">mlflow_ui.PNG</figcaption><p></p>
</figure>
</div>
<p>Note, if you get an error message along the lines of <code>Connection in use: ('127.0.0.1', 5000)</code> this means you already have something running on port 5000, and you need to kill it.</p>
<p>Run the following command on the terminal :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ps <span class="op">-</span>A <span class="op">|</span> grep gunicorn</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and then look for the number process id which is the 1st number after running the command. Then kill it using :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>kill <span class="op">&lt;</span>process_id<span class="op">&gt;</span> <span class="co"># replace with the 1st number after running ps -A | grep gunicorn</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/094d0a91-e293-42aa-aaa1-4e8d439f93b2.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">ml_flow.PNG</figcaption><p></p>
</figure>
</div>
<p>We have no experiments at the moment. Let’s create one following the Linear Regression model we built in the previous module to predict the duration of a taxi trip.</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check Python version</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>python <span class="op">-</span>V</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Python 3.9.16</code></pre>
</div>
</div>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd <span class="co"># working with tabular data</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pickle <span class="co"># for machine learning models</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns <span class="co"># visualization</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt <span class="co"># visualization</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.feature_extraction <span class="im">import</span> DictVectorizer <span class="co"># Machine Learning</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression <span class="co"># Machine Learning</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> Lasso <span class="co"># Regularization</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> Ridge <span class="co"># Regularization</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error <span class="co"># Loss Function</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> mlflow</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># to hook up with MLFlow UI</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>mlflow.set_tracking_uri(<span class="st">"sqlite:///mlflow.db"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>mlflow.set_experiment(<span class="st">"mlops_nyc_taxi"</span>) <span class="co"># choose a name for your experiment</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>&lt;Experiment: artifact_location='/home/stephen137/Blog/posts/MLOps_Zoomcamp_Module_2/mlruns/3', creation_time=1684439443423, experiment_id='3', last_update_time=1684439443423, lifecycle_stage='active', name='mlops_nyc_taxi', tags={}&gt;</code></pre>
</div>
</div>
<p>If we return to the MLflow UI we can see that our experiment nyc_taxi_experiment has been successfully initiated.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/mlops_nyc_taxi.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">mlops_nyc_taxi.PNG</figcaption><p></p>
</figure>
</div>
<p>If you recall in <a href="https://stephen137.github.io/posts/MLOps_Zoomcamp_Week_1/MLOps_Zoomcamp_Week_1.html#training-a-ride-duration-prediction-model">Module 1</a> the code was scattered, and at times difficult to follow. Let’s replicate it here to at least get a baseline for improvement using MLflow.</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>wget https:<span class="op">//</span>d37ci6vzurychx.cloudfront.net<span class="op">/</span>trip<span class="op">-</span>data<span class="op">/</span>yellow_tripdata_2022<span class="op">-</span><span class="fl">01.</span><span class="er">parquet</span> https:<span class="op">//</span>d37ci6vzurychx.cloudfront.net<span class="op">/</span>trip<span class="op">-</span>data<span class="op">/</span>yellow_tripdata_2022<span class="op">-</span><span class="fl">02.</span><span class="er">parquet</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>--2023-05-18 20:52:44--  https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-01.parquet
Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 18.244.96.218, 18.244.96.180, 18.244.96.25, ...
Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|18.244.96.218|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38139949 (36M) [application/x-www-form-urlencoded]
Saving to: ‘yellow_tripdata_2022-01.parquet’

yellow_tripdata_202 100%[===================&gt;]  36.37M  52.2MB/s    in 0.7s    

2023-05-18 20:52:45 (52.2 MB/s) - ‘yellow_tripdata_2022-01.parquet’ saved [38139949/38139949]

--2023-05-18 20:52:45--  https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-02.parquet
Reusing existing connection to d37ci6vzurychx.cloudfront.net:443.
HTTP request sent, awaiting response... 200 OK
Length: 45616512 (44M) [application/x-www-form-urlencoded]
Saving to: ‘yellow_tripdata_2022-02.parquet’

yellow_tripdata_202 100%[===================&gt;]  43.50M  56.0MB/s    in 0.8s    

2023-05-18 20:52:45 (56.0 MB/s) - ‘yellow_tripdata_2022-02.parquet’ saved [45616512/45616512]

FINISHED --2023-05-18 20:52:45--
Total wall clock time: 1.7s
Downloaded: 2 files, 80M in 1.5s (54.2 MB/s)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> read_dataframe(filename):</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> filename.endswith(<span class="st">'.csv'</span>):</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>        df <span class="op">=</span> pd.read_csv(filename)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>        df.tpep_dropoff_datetime <span class="op">=</span> pd.to_datetime(df.tpep_dropoff_datetime)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>        df.tpep_pickup_datetime <span class="op">=</span> pd.to_datetime(df.tpep_pickup_datetime)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> filename.endswith(<span class="st">'.parquet'</span>):</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>        df <span class="op">=</span> pd.read_parquet(filename)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'duration'</span>] <span class="op">=</span> df.tpep_dropoff_datetime <span class="op">-</span> df.tpep_pickup_datetime</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    df.duration <span class="op">=</span> df.duration.<span class="bu">apply</span>(<span class="kw">lambda</span> td: td.total_seconds() <span class="op">/</span> <span class="dv">60</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> df[(df.duration <span class="op">&gt;=</span> <span class="dv">1</span>) <span class="op">&amp;</span> (df.duration <span class="op">&lt;=</span> <span class="dv">60</span>)]</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    categorical <span class="op">=</span> [<span class="st">'PULocationID'</span>, <span class="st">'DOLocationID'</span>]</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    df[categorical] <span class="op">=</span> df[categorical].astype(<span class="bu">str</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>df_train <span class="op">=</span> read_dataframe(<span class="st">'yellow_tripdata_2022-01.parquet'</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>df_val <span class="op">=</span> read_dataframe(<span class="st">'yellow_tripdata_2022-02.parquet'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(df_train), <span class="bu">len</span>(df_val)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>(2421440, 2918187)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df_train[<span class="st">'PU_DO'</span>] <span class="op">=</span> df_train[<span class="st">'PULocationID'</span>] <span class="op">+</span> <span class="st">'_'</span> <span class="op">+</span> df_train[<span class="st">'DOLocationID'</span>]</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>df_val[<span class="st">'PU_DO'</span>] <span class="op">=</span> df_val[<span class="st">'PULocationID'</span>] <span class="op">+</span> <span class="st">'_'</span> <span class="op">+</span> df_val[<span class="st">'DOLocationID'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>categorical <span class="op">=</span> [<span class="st">'PU_DO'</span>] <span class="co">#'PULocationID', 'DOLocationID']</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>numerical <span class="op">=</span> [<span class="st">'trip_distance'</span>]</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>dv <span class="op">=</span> DictVectorizer()</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>train_dicts <span class="op">=</span> df_train[categorical <span class="op">+</span> numerical].to_dict(orient<span class="op">=</span><span class="st">'records'</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> dv.fit_transform(train_dicts)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>val_dicts <span class="op">=</span> df_val[categorical <span class="op">+</span> numerical].to_dict(orient<span class="op">=</span><span class="st">'records'</span>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>X_val <span class="op">=</span> dv.transform(val_dicts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> <span class="st">'duration'</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>y_train <span class="op">=</span> df_train[target].values</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>y_val <span class="op">=</span> df_val[target].values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> LinearRegression()</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>lr.fit(X_train, y_train)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> lr.predict(X_val)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>mean_squared_error(y_val, y_pred, squared<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>5.530468126047705</code></pre>
</div>
</div>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">'./models/lin_reg.bin'</span>, <span class="st">'wb'</span>) <span class="im">as</span> f_out: <span class="co"># wb means write binary mlops-zoomcamp/week_1/models</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Pickle both the dictionary vectorizer and the linear regression model</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>        pickle.dump((dv, lr), f_out)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"Model successfully pickled."</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"Error occurred while pickling the model:"</span>, <span class="bu">str</span>(e))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model successfully pickled.</code></pre>
</div>
</div>
<p>Let’s harness MLFlow to incorporate some structure into our flow, making it easier to follow, easier to iterate over different models and parameters, and easier to track changes.</p>
<p>A code snippet is included below to demonstrate how we can achieve this :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> mlflow.start_run():</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    mlflow.set_tag(<span class="st">"developer"</span>, <span class="st">"stephen"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    mlflow.log_param(<span class="st">"train-data-path"</span>, <span class="st">"./data/green_tripdata_2021-01.csv"</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    mlflow.log_param(<span class="st">"valid-data-path"</span>, <span class="st">"./data/green_tripdata_2021-02.csv"</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    alpha <span class="op">=</span> <span class="fl">0.1</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    mlflow.log_param(<span class="st">"alpha"</span>, alpha)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    lr <span class="op">=</span> Lasso(alpha)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    lr.fit(X_train, y_train)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    y_pred <span class="op">=</span> lr.predict(X_val)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    rmse <span class="op">=</span> mean_squared_error(y_val, y_pred, squared<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>    mlflow.log_metric(<span class="st">"rmse"</span>, rmse)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>    mlflow.log_artifact(local_path<span class="op">=</span><span class="st">"models/lin_reg.bin"</span>, artifact_path<span class="op">=</span><span class="st">"models_pickle"</span>) <span class="co"># where model saved</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>mlflow.log_artifact()</code> logs a local file or directory as an artifact, optionally taking an <code>artifact_path</code> to place it in within the run’s artifact URI. Run artifacts can be organized into directories, so you can place the artifact in a directory this way.</p>
<p>If we now revisit the Mlflow UI we can see that the run status is <code>FINISHED</code> and has completed successfully. We have a note of our <code>Tag</code>, <code>Parmaeters</code>, <code>Metrics</code> and <code>Artifacts</code> as specified above in <code>with mlflow.start_run():</code>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/baseline_mlflow.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">baseline_mlflow.PNG</figcaption><p></p>
</figure>
</div>
</section>
</section>
<section id="experiment-tracking-with-mlflow" class="level3">
<h3 class="anchored" data-anchor-id="experiment-tracking-with-mlflow">2.3 Experiment tracking with MLflow</h3>
<section id="xgboost" class="level4">
<h4 class="anchored" data-anchor-id="xgboost">2.3.1 XGBoost</h4>
<p>In order to demonstrate MLflow’s capabilities more fully, let’s look at a more complex model which uses <a href="https://xgboost.readthedocs.io/en/stable/">XGBoost</a>.</p>
<p>XGBoost, short for “Extreme Gradient Boosting,” is a popular machine learning algorithm known for its effectiveness in predictive modeling and data analysis tasks. It belongs to the family of gradient boosting methods, which are ensemble learning techniques that combine multiple weak prediction models, typically decision trees, to create a strong predictive model.</p>
<p>XGBoost is particularly renowned for its scalability, efficiency, and accuracy. It incorporates advanced techniques such as gradient boosting, regularization, and parallel processing to enhance model performance. It can handle a wide range of data types and is often used for both regression and classification problems.</p>
<p>The algorithm works by iteratively building decision trees to minimize a specified loss function. Each subsequent tree focuses on correcting the errors made by the previous trees, resulting in a highly accurate ensemble model. Additionally, XGBoost allows for custom optimization objectives and evaluation metrics, providing flexibility to address various problem domains.</p>
<p>Due to its exceptional performance and versatility, XGBoost has gained popularity in various fields, including finance, healthcare, marketing, and more. It has been widely adopted in data science competitions and is a favored choice among practitioners when tackling complex machine learning problems.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import required modules</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> xgboost <span class="im">as</span> xgb</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> hyperopt <span class="im">import</span> fmin, tpe, hp, STATUS_OK, Trials <span class="co"># some methods to optimize hyperparameters</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> hyperopt.pyll <span class="im">import</span> scope</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>FMin</code></p>
<p>https://github.com/hyperopt/hyperopt/wiki/FMin</p>
<p><code>Tree-structured Parzen Estimator Approach (TPE)</code></p>
<p>The Tree-structured Parzen Estimator Approach (TPE) is a Bayesian optimization algorithm used for hyperparameter tuning in machine learning models. It is a popular alternative to traditional grid search and random search methods. TPE aims to efficiently search the hyperparameter space by iteratively exploring and exploiting the most promising regions based on previous evaluations.</p>
<p>TPE divides the search space into two parts: the “prior” and the “posterior.” The prior represents the probability distribution of hyperparameters, while the posterior reflects the conditional probability distribution of hyperparameters given their corresponding objective function values.</p>
<p>The algorithm operates in a two-step process. First, it builds a probabilistic model to estimate the posterior distribution of the hyperparameters using a set of previously evaluated points. This model is typically constructed using a tree structure called a “density ratio” that captures the relative densities of better-performing hyperparameters compared to worse-performing ones.</p>
<p>In the second step, TPE generates a new set of candidate hyperparameters by sampling from the estimated posterior distribution. The selection of candidates is biased towards regions with higher probability of improving the objective function, leveraging the knowledge gained from previous evaluations.</p>
<p>By iteratively repeating these steps, TPE explores and refines the hyperparameter search space, gradually converging towards the optimal configuration. It focuses on exploring promising regions during the early stages of optimization and exploits those regions as the optimization progresses.</p>
<p>TPE has gained popularity due to its ability to efficiently search high-dimensional and complex hyperparameter spaces. It has been successfully applied in various domains, including deep learning, machine learning model selection, and reinforcement learning.</p>
<p><code>hp</code><br>
In Hyperopt, hyperparameters are defined using the “hp” module provided by the library. This module offers a set of functions to define different types of hyperparameters, including continuous, discrete, and conditional hyperparameters. These functions enable the creation of a search space over which the optimization algorithm can explore to find the optimal hyperparameter values.</p>
<p><code>Trials</code><br>
By passing in a trials object directly, we can inspect all of the return values that were calculated during the experiment.</p>
<p>So for example:</p>
<ul>
<li><code>trials.trials</code> - a list of dictionaries representing everything about the search</li>
<li><code>trials.results</code> - a list of dictionaries returned by ‘objective’ during the search</li>
<li><code>trials.losses()</code> - a list of losses (float for each ‘ok’ trial)</li>
<li><code>trials.statuses()</code> - a list of status strings</li>
</ul>
<p>This trials object can be saved, passed on to the built-in plotting routines, or analyzed with your own custom code.</p>
<p>Let’s now define our training and validation datasets and configure our MLflow run :</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>train <span class="op">=</span> xgb.DMatrix(X_train, label<span class="op">=</span>y_train)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>valid <span class="op">=</span> xgb.DMatrix(X_val, label<span class="op">=</span>y_val)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Objective function - set the parameters for this specific run</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> objective(params): </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> mlflow.start_run():</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>        mlflow.set_tag(<span class="st">"model"</span>, <span class="st">"xgboost"</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>        mlflow.log_params(params) </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>        booster <span class="op">=</span> xgb.train(</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>            params<span class="op">=</span>params,</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>            dtrain<span class="op">=</span>train, <span class="co"># model trained on training set</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>            num_boost_round<span class="op">=</span><span class="dv">3</span>, <span class="co"># restricted due to time constraints - a value of 1000 iterations is common</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>            evals<span class="op">=</span>[(valid, <span class="st">'validation'</span>)], <span class="co"># model evaluated on validation set</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>            early_stopping_rounds<span class="op">=</span><span class="dv">3</span> <span class="co"># if no improvements after 3 iterations, stop running # restricted, time constraints</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>        y_pred <span class="op">=</span> booster.predict(valid)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>        rmse <span class="op">=</span> mean_squared_error(y_val, y_pred, squared<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>        mlflow.log_metric(<span class="st">"rmse"</span>, rmse)</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">'loss'</span>: rmse, <span class="st">'status'</span>: STATUS_OK}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="setting-the-hyperparamter-optimization-search-range" class="level4">
<h4 class="anchored" data-anchor-id="setting-the-hyperparamter-optimization-search-range">2.3.2 Setting the Hyperparamter optimization search range</h4>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the range of the hyperparameter optimization search</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>search_space <span class="op">=</span> {</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'max_depth'</span>: scope.<span class="bu">int</span>(hp.quniform(<span class="st">'max_depth'</span>, <span class="dv">4</span>, <span class="dv">100</span>, <span class="dv">1</span>)), <span class="co"># tree depth 4 to 100. Returns float, so convert to integer</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'learning_rate'</span>: hp.loguniform(<span class="st">'learning_rate'</span>, <span class="op">-</span><span class="dv">3</span>, <span class="dv">0</span>), <span class="co"># range exp(-3), exp(0) which is (0.049787, 1.0)</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'reg_alpha'</span>: hp.loguniform(<span class="st">'reg_alpha'</span>, <span class="op">-</span><span class="dv">5</span>, <span class="op">-</span><span class="dv">1</span>), <span class="co"># range exp(-5), exp(-1) which is (0.006738, 0.367879)</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'reg_lambda'</span>: hp.loguniform(<span class="st">'reg_lambda'</span>, <span class="op">-</span><span class="dv">6</span>, <span class="op">-</span><span class="dv">1</span>), <span class="co"># range exp(-6), exp(-1) which is (0.002479, 0.367879)</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'min_child_weight'</span>: hp.loguniform(<span class="st">'min_child_weight'</span>, <span class="op">-</span><span class="dv">1</span>, <span class="dv">3</span>), <span class="co"># range exp(-1), exp(3) which is (0.367879, 20.085537)</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'objective'</span>: <span class="st">'reg:linear'</span>,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'seed'</span>: <span class="dv">42</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>best_result <span class="op">=</span> fmin( <span class="co"># imported above</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>    fn<span class="op">=</span>objective,</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>    space<span class="op">=</span>search_space, <span class="co"># as defined above</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>    algo<span class="op">=</span>tpe.suggest, <span class="co"># tpe is the algorithm used for optimization</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>    max_evals<span class="op">=</span><span class="dv">3</span>, <span class="co">#restricted, time constraints</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>    trials<span class="op">=</span>Trials()</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[22:45:26] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[0] validation-rmse:15.30102                                                                           
[1] validation-rmse:14.27922                                                                           
[2] validation-rmse:13.34956                                                                           
[22:45:43] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[0] validation-rmse:10.51801                                                                           
[1] validation-rmse:7.55540                                                                            
[2] validation-rmse:6.17083                                                                            
[22:45:57] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[0] validation-rmse:13.82562                                                                           
[1] validation-rmse:11.78374                                                                           
[2] validation-rmse:10.19087                                                                           
100%|███████████████████████████████████| 3/3 [00:33&lt;00:00, 11.15s/trial, best loss: 6.170828197460482]</code></pre>
</div>
</div>
<p><code>hp.quniform(label, low, high, q)</code></p>
<ul>
<li>Returns a value like round(uniform(low, high) / q) * q</li>
<li>Suitable for a discrete value with respect to which the objective is still somewhat “smooth”, but which should be bounded both above and below.</li>
</ul>
<p><code>hp.loguniform(label, low, high)</code></p>
<ul>
<li>Returns a value drawn according to exp(uniform(low, high)) so that the logarithm of the return value is uniformly distributed.</li>
<li>When optimizing, this variable is constrained to the interval [exp(low), exp(high)]</li>
</ul>
<p>A detailed guide on setting the search space is included within the official <a href="https://hyperopt.github.io/hyperopt/getting-started/search_spaces/">Hyperopt documentation</a>.</p>
</section>
<section id="visualizations" class="level4">
<h4 class="anchored" data-anchor-id="visualizations">2.3.3 Visualizations</h4>
<p><code>Table View</code></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/xgboot_mlflow.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">xgboot_mlflow.PNG</figcaption><p></p>
</figure>
</div>
<p>The <code>Table View</code> allows a basic comparison to be made. You can specify which colums to display. In my case we can see that the <code>brawny-donkey-463</code> model returns the lowest RMSE, <code>6.171</code> an improvement over our baseline figure of <code>9.71</code>.</p>
<p><code>Chart View</code></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/chart_view.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">chart_view.PNG</figcaption><p></p>
</figure>
</div>
<p>The <code>Chart View</code> offers a slightly better visualization - a horizontal bar chart. However if we want to fully understand our models then we need a more complex visualization which deals with the inter-relationships between the various parameters, and their impact on the RMSE.</p>
<p><code>Compare</code></p>
<p>You can filter the models you want to compare using <code>tags.model=&lt;model_name&gt;</code> select them all by ticking the boxes, and then hit <code>Compare</code>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/compare.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">compare.PNG</figcaption><p></p>
</figure>
</div>
<p><code>Parallel Coordinates Plot</code></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/parallell_coordinates.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">parallell_coordinates.PNG</figcaption><p></p>
</figure>
</div>
<p><code>Scatter Plot</code></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/scatter_plot.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">scatter_plot.PNG</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/box_plot.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">box_plot.PNG</figcaption><p></p>
</figure>
</div>
<p><code>Contour Plot</code></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/contour_plot.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">contour_plot.PNG</figcaption><p></p>
</figure>
</div>
</section>
<section id="selecting-the-best-model" class="level4">
<h4 class="anchored" data-anchor-id="selecting-the-best-model">2.3.4 Selecting the best model</h4>
<p>The easisest way to rank the models is to sort the <code>Metrics</code> column of the <code>Table View</code> however it is not all about the metric.</p>
<p>Speed is also something to consider. In my simple example, although the <code>brawny-donkey-463</code> model returned the lowest <code>RMSE</code>, the <code>youthful-hen-151</code> model was the fastest <code>2.1s</code>. The old addage, time is money is very much true in a production environment, and so we need to factor in how long it takes to train our models.</p>
<p>Model complexity is another factor. The <code>brawny-donkey-463</code> is quite complex with <code>max_depth=81</code>, whilst the <code>youthful-hen-151</code> model is less so with <code>max_depth=11</code>. The higher the complexity the lower the interpretability. We need to understand what our model is doing ‘under the hood’ before we can explain it.</p>
</section>
<section id="training-the-model-selected-as-the-best" class="level4">
<h4 class="anchored" data-anchor-id="training-the-model-selected-as-the-best">2.3.5 Training the model selected as the best</h4>
<p>So, let’s say after careful consideration of metrics, time, and complexity we decide to go with the <code>brawn-donkey-463</code> model. We can grab its pararmeters and copy them into a <code>params</code> dictionary:</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>params <span class="op">=</span> {</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'learning_rate'</span>: <span class="fl">0.4434065752589766</span>,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'max_depth'</span>: <span class="dv">81</span>,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'min_child_weight'</span>: <span class="fl">10.423237853746643</span>,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'objective'</span>: <span class="st">'reg:linear'</span>,</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'reg_alpha'</span>: <span class="fl">0.2630756846813668</span>,</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'reg_lambda'</span>: <span class="fl">0.1220536223877784</span>,</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'seed'</span>: <span class="dv">42</span>   </span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can then make use of <a href="https://mlflow.org/docs/latest/tracking.html#automatic-logging">Automatic Logging</a>.</p>
</section>
<section id="automatic-logging" class="level4">
<h4 class="anchored" data-anchor-id="automatic-logging">2.3.6 Automatic Logging</h4>
<p>Automatic logging allows you to log metrics, parameters, and models without the need for explicit log statements.</p>
<p>There are two ways to use autologging:</p>
<ol type="1">
<li><p>Call <code>mlflow.autolog()</code> before your training code. This will enable autologging for each supported library you have installed as soon as you import it.</p></li>
<li><p>Use library-specific autolog calls for each library you use in your code.</p></li>
</ol>
<p>The following libraries support autologging:</p>
<ul>
<li>Scikit-learn</li>
<li>Keras</li>
<li>Gluon</li>
<li>XGBoost</li>
<li>LightGBM</li>
<li>Statsmodels</li>
<li>Spark</li>
<li>Fastai</li>
<li>Pytorch</li>
</ul>
<p>We can then run the model training, in our case using the <a href="https://mlflow.org/docs/latest/tracking.html#xgboost">XGBoost library</a> prompt :</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>mlflow.xgboost.autolog()</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>booster <span class="op">=</span> xgb.train(</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    params<span class="op">=</span>params,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    dtrain<span class="op">=</span>train, <span class="co"># model trained on training set</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    num_boost_round<span class="op">=</span><span class="dv">3</span>, <span class="co"># restricted due to time constraints - a value of 1000 iterations is common</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    evals<span class="op">=</span>[(valid, <span class="st">'validation'</span>)], <span class="co"># model evaluated on validation set</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    early_stopping_rounds<span class="op">=</span><span class="dv">3</span> <span class="co"># if no improvements after 3 iterations, stop running # restricted, time constraints</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>2023/05/19 09:37:00 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '3294af67608c45ca96e3d9f56e61edd4', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current xgboost workflow</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[09:37:00] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[0] validation-rmse:10.51801
[1] validation-rmse:7.55540
[2] validation-rmse:6.17083</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>2023/05/19 09:37:23 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "/home/stephen137/mambaforge/envs/exp-tracking-env/lib/python3.9/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils."</code></pre>
</div>
</div>
<p>If we go to the UI we can see that a new run has been logged with much more information:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/resilient_turtle_199.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">resilient_turtle_199.PNG</figcaption><p></p>
</figure>
</div>
<p>If we look at the <code>Metrics</code> we can visualize the evolution of the <code>RMSE</code>:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/metric_evolution.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">metric_evolution.PNG</figcaption><p></p>
</figure>
</div>
<p>We also have the model details if we wish to reproduce this :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/MLmodel.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">MLmodel.PNG</figcaption><p></p>
</figure>
</div>
</section>
</section>
<section id="model-management" class="level3">
<h3 class="anchored" data-anchor-id="model-management">2.4 Model management</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/experiment_tracking.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">experiment_tracking.PNG</figcaption><p></p>
</figure>
</div>
<p>In the previous section we looked at <code>Experiment Tracking</code>, but model management also encompasses :</p>
<ul>
<li>Model Versioning</li>
<li>Model Deployment</li>
<li>Scaling Hardware</li>
</ul>
<section id="model-versioning" class="level4">
<h4 class="anchored" data-anchor-id="model-versioning">2.4.1 Model Versioning</h4>
<p>We could use a folders system as a very basic way to manage our model versions, but this has a number of shortcomings. <img src="MLOps_Zoomcamp_Module_2_files/figure-html/folders.PNG" class="img-fluid" alt="folders.PNG"></p>
<p>Let’s see how we can leverage MLflow to handle version control.</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>mlflow.xgboost.autolog(disable<span class="op">=</span><span class="va">True</span>) <span class="co"># MLflow will not store parameters automatically - these will have to be requested</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> mlflow.start_run():</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    train <span class="op">=</span> xgb.DMatrix(X_train, label<span class="op">=</span>y_train)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    valid <span class="op">=</span> xgb.DMatrix(X_val, label<span class="op">=</span>y_val)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    best_params <span class="op">=</span> {</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">'learning_rate'</span>: <span class="fl">0.4434065752589766</span>,</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">'max_depth'</span>: <span class="dv">81</span>,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">'min_child_weight'</span>: <span class="fl">10.423237853746643</span>,</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">'objective'</span>: <span class="st">'reg:linear'</span>,</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">'reg_alpha'</span>: <span class="fl">0.2630756846813668</span>,</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">'reg_lambda'</span>: <span class="fl">0.1220536223877784</span>,</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">'seed'</span>: <span class="dv">42</span>    </span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>    mlflow.log_params(best_params)</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>    booster <span class="op">=</span> xgb.train(</span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>        params<span class="op">=</span>params,</span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>        dtrain<span class="op">=</span>train, <span class="co"># model trained on training set</span></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>        num_boost_round<span class="op">=</span><span class="dv">3</span>, <span class="co"># restricted due to time constraints - a value of 1000 iterations is common</span></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>        evals<span class="op">=</span>[(valid, <span class="st">'validation'</span>)], <span class="co"># model evaluated on validation set</span></span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a>        early_stopping_rounds<span class="op">=</span><span class="dv">3</span> <span class="co"># if no improvements after 3 iterations, stop running # restricted, time constraints</span></span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a>    y_pred <span class="op">=</span> booster.predict(valid)</span>
<span id="cb39-27"><a href="#cb39-27" aria-hidden="true" tabindex="-1"></a>    rmse <span class="op">=</span> mean_squared_error(y_val, y_pred, squared<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb39-28"><a href="#cb39-28" aria-hidden="true" tabindex="-1"></a>    mlflow.log_metric(<span class="st">"rmse"</span>, rmse)</span>
<span id="cb39-29"><a href="#cb39-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-30"><a href="#cb39-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> <span class="bu">open</span>(<span class="st">"models/preprocessor.b"</span>, <span class="st">"wb"</span>) <span class="im">as</span> f_out: <span class="co"># save pre-processing as a model</span></span>
<span id="cb39-31"><a href="#cb39-31" aria-hidden="true" tabindex="-1"></a>        pickle.dump(dv, f_out)</span>
<span id="cb39-32"><a href="#cb39-32" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb39-33"><a href="#cb39-33" aria-hidden="true" tabindex="-1"></a>    mlflow.log_artifact(<span class="st">"models/preprocessor.b"</span>, artifact_path<span class="op">=</span><span class="st">"preprocessor"</span>) <span class="co"># we can isolate the pre-processing from raw data</span></span>
<span id="cb39-34"><a href="#cb39-34" aria-hidden="true" tabindex="-1"></a>    mlflow.xgboost.log_model(booster, artifact_path<span class="op">=</span><span class="st">"models_mlflow"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[10:44:08] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
[0] validation-rmse:10.51801
[1] validation-rmse:7.55540
[2] validation-rmse:6.17083</code></pre>
</div>
</div>
<p>On running this we can see from the UI that both the XGB model and a pre-processing model have been saved. Later this can be loaded to preprocess the prediction data and then pass it through the XGBoost model.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/whimsical_shad_190.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">whimsical_shad_190.PNG</figcaption><p></p>
</figure>
</div>
</section>
<section id="making-predictions" class="level4">
<h4 class="anchored" data-anchor-id="making-predictions">2.4.2 Making Predictions</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/predictions.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">predictions.PNG</figcaption><p></p>
</figure>
</div>
<p>MLflow provides handy code snippets for predicting on a Spark or pandas Dataframe.</p>
<p>Let’s grab the pandas snippet and make a prediction. First let’s load the model. There are two flavors available, <code>python_function</code> or alternatively <code>xgboost</code>.</p>
<p><code>python_function</code></p>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>logged_model <span class="op">=</span> <span class="st">'runs:/fd2b3236374d4d0c933cad45678251fe/models_mlflow'</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load model as a PyFuncModel.</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>loaded_model <span class="op">=</span> mlflow.pyfunc.load_model(logged_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>2023/05/19 10:55:45 WARNING mlflow.pyfunc: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - mlflow (current: 2.3.2, required: mlflow==2.3)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[10:55:45] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.</code></pre>
</div>
</div>
<p>We can check the type of <code>loaded_model</code> :</p>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>loaded_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<pre><code>mlflow.pyfunc.loaded_model:
  artifact_path: models_mlflow
  flavor: mlflow.xgboost
  run_id: fd2b3236374d4d0c933cad45678251fe</code></pre>
</div>
</div>
<p><code>xgboost</code></p>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>xgboost_model <span class="op">=</span> mlflow.xgboost.load_model(logged_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[11:01:09] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.</code></pre>
</div>
</div>
<p>We can check the type of <code>xgboost_model</code> :</p>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>xgboost_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>&lt;xgboost.core.Booster at 0x7f06ebbc9340&gt;</code></pre>
</div>
</div>
<p>Finally, we can make predictions with this model.</p>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> xgboost_model.predict(valid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check the first 10</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>y_pred[:<span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="32">
<pre><code>array([12.633282 , 16.895218 , 27.585228 , 20.118687 , 26.492146 ,
       11.089786 , 20.731995 ,  4.2313485, 14.710851 , 14.201264 ],
      dtype=float32)</code></pre>
</div>
</div>
<p>Summing up this section we have seen that it is possible to take a model trained using a host of different libraries, and log that model in MLflow. You can then access that model using different <code>flavors</code> e.g.&nbsp;as a python function, or a <a href="https://scikit-learn.org/stable/">scikit-learn</a> model. It then becomes very easy to make predictions and later deploy the model, for example, as a Python function, in a <a href="https://www.docker.com/">docker</a> container, in a Jupyter NoteBook, or maybe as a batch job in <a href="https://spark.apache.org/">Spark</a>. Furthermore you can deploy to a <a href="https://kubernetes.io/">kubernetes</a> cluster or different cloud environments such as <a href="https://aws.amazon.com/pm/sagemaker/?trk=3ea5c9d1-0497-4ab3-92e6-c583f43ac2f9&amp;sc_channel=ps&amp;ef_id=%7Bgclid%7D:G:s&amp;s_kwcid=AL!4422!3!645186192649!e!!g!!amazon%20sagemaker!19571721771!146073031580">Amazon SageMaker</a> or <a href="https://azure.microsoft.com/en-us/free/search/?ef_id=_k_%7Bgclid%7D_k_&amp;OCID=AIDcmm4rphvbww_SEM__k_%7Bgclid%7D_k_">Microsoft Azure</a>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/model_format.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">model_format.PNG</figcaption><p></p>
</figure>
</div>
</section>
</section>
<section id="model-registry" class="level3">
<h3 class="anchored" data-anchor-id="model-registry">2.5 Model Registry</h3>
<section id="motivation" class="level4">
<h4 class="anchored" data-anchor-id="motivation">2.5.1 Motivation</h4>
<p>Imagine you are a machine learning or MLOps engineer and you receive the following email from a data scientist :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/model_registry.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">model_registry.PNG</figcaption><p></p>
</figure>
</div>
<p>There are a number of unanswered questions that need to be answered before you would feel comfortable about deploying the model, such as :</p>
<ul>
<li>what has changed from previous version ?</li>
<li>do hyperparameters require updating ?</li>
<li>any pre-processing needed ?</li>
<li>which dependencies needed to run model ?</li>
</ul>
<p>In order to avoid any delay in model deployment due to lengthy email correspondence, or ambiguity we can harness <a href="https://mlflow.org/docs/latest/model-registry.html">MLflow Model Registry</a>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/register_model.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">register_model.PNG</figcaption><p></p>
</figure>
</div>
<p>Note that model registry does <strong>not</strong> equate to deployment. It is a “waiting room” of models to be allocated to <code>staging</code>, <code>production</code>, or <code>archive</code>. In order to actually deploy a model we would need some CI/CD (continuous integration and continuous delivery) code.</p>
</section>
<section id="registering-a-model" class="level4">
<h4 class="anchored" data-anchor-id="registering-a-model">2.5.2 Registering a model</h4>
<p>Ok, let’s say we are happy with our <code>whimsical-shad-190</code> run which was a XGBoost model, and would now like to move it to <code>staging</code>. To do this click <code>Register Model</code> and give the model a name :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/register_xgb_model.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">register_xgb_model.PNG</figcaption><p></p>
</figure>
</div>
<p>When we go to the <code>Models</code> tab we can now see our registered model :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/model_registered.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">model_registered.PNG</figcaption><p></p>
</figure>
</div>
</section>
<section id="stage-transition" class="level4">
<h4 class="anchored" data-anchor-id="stage-transition">2.5.3 Stage transition</h4>
<p>We mentioned earlier that there are three stages <code>Staging</code>, <code>Production</code> and <code>Archive</code>. As you can see from above, our model is newly registered, and so it has not yet been transitioned. We can do this by first clicking on the version we wish to stage, which takes us to this screen :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/staging.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">staging.PNG</figcaption><p></p>
</figure>
</div>
<p>Click on <code>Transition to -&gt; Staging</code> and if we return to our models tab, we can see it is now shown in the <code>Staging</code> column :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/transition_to_staging.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">transition_to_staging.PNG</figcaption><p></p>
</figure>
</div>
</section>
<section id="interacting-with-the-mlflow-tracking-server" class="level4">
<h4 class="anchored" data-anchor-id="interacting-with-the-mlflow-tracking-server">2.5.4 Interacting with the MLflow tracking server</h4>
<p>The <a href="https://mlflow.org/docs/latest/python_api/mlflow.client.html">mlflow.client</a> module provides a Python CRUD interface to MLflow Experiments, Runs, Model Versions, and Registered Models. This is a lower level API that directly translates to MLflow REST API calls. For a higher level API for managing an “active run”, use the mlflow module.</p>
<p>Essentially this allows us to interact with the MLflow UI and access the same information using Python :</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> mlflow.tracking <span class="im">import</span> MlflowClient</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>MLFLOW_TRACKING_URI <span class="op">=</span> <span class="st">"sqlite:///mlflow.db"</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>client <span class="op">=</span> MlflowClient(tracking_uri<span class="op">=</span>MLFLOW_TRACKING_URI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a new experiment</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>client.create_experiment(name<span class="op">=</span><span class="st">"my_137_experiment"</span>) <span class="co"># returns the experiment ID</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>'4'</code></pre>
</div>
</div>
<p>Imagine that we are trying to understand for a given experiment, what are the best models or runs :</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> mlflow.entities <span class="im">import</span> ViewType</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>runs <span class="op">=</span> client.search_runs(</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>    experiment_ids<span class="op">=</span><span class="st">'3'</span>, <span class="co"># mlops_nyc_taxi</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>    filter_string<span class="op">=</span><span class="st">"metrics.rmse &lt; 10"</span>, <span class="co"># grab only the runs with an RMSE below 10</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>    run_view_type<span class="op">=</span>ViewType.ACTIVE_ONLY,</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>    max_results<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>    order_by<span class="op">=</span>[<span class="st">"metrics.rmse ASC"</span>] <span class="co"># Ascending</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> run <span class="kw">in</span> runs:</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"run id: </span><span class="sc">{</span>run<span class="sc">.</span>info<span class="sc">.</span>run_id<span class="sc">}</span><span class="ss">, rmse: </span><span class="sc">{</span>run<span class="sc">.</span>data<span class="sc">.</span>metrics[<span class="st">'rmse'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>) <span class="co"># round to 4 d.p</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>run id: fd2b3236374d4d0c933cad45678251fe, rmse: 6.1708
run id: 471d0a98d029426588698b8caed0ffc0, rmse: 6.1708
run id: 225560b7938a4bb280b64593c5db884d, rmse: 9.7080</code></pre>
</div>
</div>
</section>
<section id="interacting-with-the-model-registry" class="level4">
<h4 class="anchored" data-anchor-id="interacting-with-the-model-registry">2.5.5 Interacting with the Model Registry</h4>
<p>In this section We will use the MlflowClient instance to:</p>
<ul>
<li>Register a new version for the experiment <code>mlops_nyc_taxi</code></li>
<li>Retrieve the latest versions of the model <code>nyc_taxi_xgb</code> and check that a new version was created</li>
<li>Transition the new version 2 to “Staging”</li>
<li>Add annotations</li>
</ul>
<p><code>Register a new version for the experiment mlops_nyc_taxi</code></p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> mlflow</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># register the top performing model(run) from the mlops_nyc_taxi experiment</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>run_id <span class="op">=</span> <span class="st">"fd2b3236374d4d0c933cad45678251fe"</span> <span class="co"># </span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>model_uri <span class="op">=</span> <span class="ss">f"runs:/</span><span class="sc">{</span>run_id<span class="sc">}</span><span class="ss">/model"</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>mlflow.register_model(model_uri<span class="op">=</span>model_uri, name<span class="op">=</span><span class="st">"nyc_taxi_xgb"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered model 'nyc_taxi_xgb' already exists. Creating a new version of this model...
2023/05/19 15:30:38 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation. Model name: nyc_taxi_xgb, version 2
Created version '2' of model 'nyc_taxi_xgb'.</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="17">
<pre><code>&lt;ModelVersion: aliases=[], creation_timestamp=1684503038967, current_stage='None', description=None, last_updated_timestamp=1684503038967, name='nyc_taxi_xgb', run_id='fd2b3236374d4d0c933cad45678251fe', run_link=None, source='/home/stephen137/Blog/posts/MLOps_Zoomcamp_Module_2/mlruns/3/fd2b3236374d4d0c933cad45678251fe/artifacts/model', status='READY', status_message=None, tags={}, user_id=None, version=2&gt;</code></pre>
</div>
</div>
<p>We can see that we now have <code>Version 2</code> of our model :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/version_2-2.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">version_2-2.PNG</figcaption><p></p>
</figure>
</div>
<p><code>Retrieve the latest versions of the model nyc_taxi_xgb and check that a new version was created</code></p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>model_name <span class="op">=</span> <span class="st">"nyc_taxi_xgb"</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>latest_versions <span class="op">=</span> client.get_latest_versions(name<span class="op">=</span>model_name)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> version <span class="kw">in</span> latest_versions:</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"version: </span><span class="sc">{</span>version<span class="sc">.</span>version<span class="sc">}</span><span class="ss">, stage: </span><span class="sc">{</span>version<span class="sc">.</span>current_stage<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>version: 1, stage: Staging
version: 2, stage: None</code></pre>
</div>
</div>
<p><code>Transition the new version 2 to "Staging"</code></p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>model_version <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>new_stage <span class="op">=</span> <span class="st">"Staging"</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>client.transition_model_version_stage(</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>    name<span class="op">=</span>model_name,</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>    version<span class="op">=</span>model_version,</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>    stage<span class="op">=</span>new_stage,</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>    archive_existing_versions<span class="op">=</span><span class="va">False</span> <span class="co"># so version 1 will remain in Staging</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>&lt;ModelVersion: aliases=[], creation_timestamp=1684503038967, current_stage='Staging', description=None, last_updated_timestamp=1684503630353, name='nyc_taxi_xgb', run_id='fd2b3236374d4d0c933cad45678251fe', run_link=None, source='/home/stephen137/Blog/posts/MLOps_Zoomcamp_Module_2/mlruns/3/fd2b3236374d4d0c933cad45678251fe/artifacts/model', status='READY', status_message=None, tags={}, user_id=None, version=2&gt;</code></pre>
</div>
</div>
<p>We can see that this has been actioned sucessfully :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/version_2_staging.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">version_2_staging.PNG</figcaption><p></p>
</figure>
</div>
<p><code>Add annotations</code></p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> datetime <span class="im">import</span> datetime</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>date <span class="op">=</span> datetime.today().date()</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>client.update_model_version(</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>    name<span class="op">=</span>model_name,</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>    version<span class="op">=</span>model_version,</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>    description<span class="op">=</span><span class="ss">f"The model version </span><span class="sc">{</span>model_version<span class="sc">}</span><span class="ss"> was transitioned to </span><span class="sc">{</span>new_stage<span class="sc">}</span><span class="ss"> on </span><span class="sc">{</span>date<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>&lt;ModelVersion: aliases=[], creation_timestamp=1684503038967, current_stage='Staging', description='The model version 2 was transitioned to Staging on 2023-05-19', last_updated_timestamp=1684504091974, name='nyc_taxi_xgb', run_id='fd2b3236374d4d0c933cad45678251fe', run_link=None, source='/home/stephen137/Blog/posts/MLOps_Zoomcamp_Module_2/mlruns/3/fd2b3236374d4d0c933cad45678251fe/artifacts/model', status='READY', status_message=None, tags={}, user_id=None, version=2&gt;</code></pre>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/annotate.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">annotate.PNG</figcaption><p></p>
</figure>
</div>
<p>Let’s add Version 1 to <code>Production</code> for use in the illustration that follows in the next section.</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>model_version <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>new_stage <span class="op">=</span> <span class="st">"Production"</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>client.transition_model_version_stage(</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>    name<span class="op">=</span>model_name,</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>    version<span class="op">=</span>model_version,</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>    stage<span class="op">=</span>new_stage,</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>    archive_existing_versions<span class="op">=</span><span class="va">False</span> <span class="co"># </span></span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> datetime <span class="im">import</span> datetime</span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a>date <span class="op">=</span> datetime.today().date()</span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>client.update_model_version(</span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a>    name<span class="op">=</span>model_name,</span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a>    version<span class="op">=</span>model_version,</span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a>    description<span class="op">=</span><span class="ss">f"The model version </span><span class="sc">{</span>model_version<span class="sc">}</span><span class="ss"> was transitioned to </span><span class="sc">{</span>new_stage<span class="sc">}</span><span class="ss"> on </span><span class="sc">{</span>date<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>&lt;ModelVersion: aliases=[], creation_timestamp=1684491417632, current_stage='Production', description='The model version 1 was transitioned to Production on 2023-05-19', last_updated_timestamp=1684505743784, name='nyc_taxi_xgb', run_id='fd2b3236374d4d0c933cad45678251fe', run_link='', source='/home/stephen137/Blog/posts/MLOps_Zoomcamp_Module_2/mlruns/3/fd2b3236374d4d0c933cad45678251fe/artifacts/models_mlflow', status='READY', status_message=None, tags={}, user_id=None, version=1&gt;</code></pre>
</div>
</div>
</section>
<section id="comparing-versions-and-selecting-the-new-production-model" class="level4">
<h4 class="anchored" data-anchor-id="comparing-versions-and-selecting-the-new-production-model">2.5.6 Comparing versions and selecting the new “Production” model</h4>
<p>In this last section, we will retrieve models registered in the model registry and compare their performance on an unseen test set. The idea is to simulate the scenario in which a deployment engineer has to interact with the model registry to decide whether to update the model version that is in production or not.</p>
<p>These are the steps:</p>
<ul>
<li>Load the test dataset, which corresponds to the NYC Yellow Taxi data from the month of March 2022.</li>
<li>Download the DictVectorizer that was fitted using the training data and saved to MLflow as an artifact, and load it with pickle.</li>
<li>Preprocess the test set using the DictVectorizer</li>
<li>Make predictions on the test set using the model version that is currently in the “Production” stage</li>
<li>Based on the results, update the “Production” model version accordingly</li>
</ul>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Model registry
</div>
</div>
<div class="callout-body-container callout-body">
<p>The model registry doesn’t actually deploy the model to production when you transition a model to the “Production” stage, it just assign a label to that model version. You should complement the registry with some CI/CD code that does the actual deployment.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import packages</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># download March 2022 yellow taxi data as `test` dataset</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="co"># we used Feb 2022 for validation (which is sometimes also effectively the 'test' set)</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>wget https:<span class="op">//</span>d37ci6vzurychx.cloudfront.net<span class="op">/</span>trip<span class="op">-</span>data<span class="op">/</span>yellow_tripdata_2022<span class="op">-</span><span class="fl">03.</span><span class="er">parquet</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>--2023-05-19 16:20:39--  https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2022-03.parquet
Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 18.244.96.103, 18.244.96.218, 18.244.96.180, ...
Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|18.244.96.103|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 55682369 (53M) [application/x-www-form-urlencoded]
Saving to: ‘yellow_tripdata_2022-03.parquet’

yellow_tripdata_202 100%[===================&gt;]  53.10M  53.9MB/s    in 1.0s    

2023-05-19 16:20:40 (53.9 MB/s) - ‘yellow_tripdata_2022-03.parquet’ saved [55682369/55682369]
</code></pre>
</div>
</div>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create our functions</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> read_dataframe(filename):</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> filename.endswith(<span class="st">'.csv'</span>):</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>        df <span class="op">=</span> pd.read_csv(filename)</span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>        df.tpep_dropoff_datetime <span class="op">=</span> pd.to_datetime(df.tpep_dropoff_datetime)</span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>        df.tpep_pickup_datetime <span class="op">=</span> pd.to_datetime(df.tpep_pickup_datetime)</span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> filename.endswith(<span class="st">'.parquet'</span>):</span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>        df <span class="op">=</span> pd.read_parquet(filename)</span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'duration'</span>] <span class="op">=</span> df.tpep_dropoff_datetime <span class="op">-</span> df.tpep_pickup_datetime</span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a>    df.duration <span class="op">=</span> df.duration.<span class="bu">apply</span>(<span class="kw">lambda</span> td: td.total_seconds() <span class="op">/</span> <span class="dv">60</span>)</span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-15"><a href="#cb75-15" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> df[(df.duration <span class="op">&gt;=</span> <span class="dv">1</span>) <span class="op">&amp;</span> (df.duration <span class="op">&lt;=</span> <span class="dv">60</span>)]</span>
<span id="cb75-16"><a href="#cb75-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-17"><a href="#cb75-17" aria-hidden="true" tabindex="-1"></a>    categorical <span class="op">=</span> [<span class="st">'PULocationID'</span>, <span class="st">'DOLocationID'</span>]</span>
<span id="cb75-18"><a href="#cb75-18" aria-hidden="true" tabindex="-1"></a>    df[categorical] <span class="op">=</span> df[categorical].astype(<span class="bu">str</span>)</span>
<span id="cb75-19"><a href="#cb75-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb75-20"><a href="#cb75-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df</span>
<span id="cb75-21"><a href="#cb75-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-22"><a href="#cb75-22" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> preprocess(df, dv):</span>
<span id="cb75-23"><a href="#cb75-23" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'PU_DO'</span>] <span class="op">=</span> df[<span class="st">'PULocationID'</span>] <span class="op">+</span> <span class="st">'_'</span> <span class="op">+</span> df[<span class="st">'DOLocationID'</span>]</span>
<span id="cb75-24"><a href="#cb75-24" aria-hidden="true" tabindex="-1"></a>    categorical <span class="op">=</span> [<span class="st">'PU_DO'</span>]</span>
<span id="cb75-25"><a href="#cb75-25" aria-hidden="true" tabindex="-1"></a>    numerical <span class="op">=</span> [<span class="st">'trip_distance'</span>]</span>
<span id="cb75-26"><a href="#cb75-26" aria-hidden="true" tabindex="-1"></a>    train_dicts <span class="op">=</span> df[categorical <span class="op">+</span> numerical].to_dict(orient<span class="op">=</span><span class="st">'records'</span>)</span>
<span id="cb75-27"><a href="#cb75-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> dv.transform(train_dicts) <span class="co"># not fitting the pre-processor again</span></span>
<span id="cb75-28"><a href="#cb75-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-29"><a href="#cb75-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-30"><a href="#cb75-30" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> test_model(name, stage, X_test, y_test):</span>
<span id="cb75-31"><a href="#cb75-31" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> mlflow.pyfunc.load_model(<span class="ss">f"models:/</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">/</span><span class="sc">{</span>stage<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb75-32"><a href="#cb75-32" aria-hidden="true" tabindex="-1"></a>    y_pred <span class="op">=</span> model.predict(X_test)</span>
<span id="cb75-33"><a href="#cb75-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">"rmse"</span>: mean_squared_error(y_test, y_pred, squared<span class="op">=</span><span class="va">False</span>)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>Load the test dataset, which corresponds to the NYC Yellow Taxi data from the month of March 2022</code></p>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> read_dataframe(<span class="st">"yellow_tripdata_2022-03.parquet"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>Download the DictVectorizer that was fitted using the training data and saved to MLflow as an artifact, and load it with pickle</code></p>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>client.download_artifacts(run_id<span class="op">=</span>run_id, path<span class="op">=</span><span class="st">'preprocessor'</span>, dst_path<span class="op">=</span><span class="st">'.'</span>) <span class="co"># downloaded locally</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_611/2852634549.py:1: FutureWarning: ``mlflow.tracking.client.MlflowClient.download_artifacts`` is deprecated since 2.0. This method will be removed in a future release. Use ``mlflow.artifacts.download_artifacts`` instead.
  client.download_artifacts(run_id=run_id, path='preprocessor', dst_path='.')</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="28">
<pre><code>'/home/stephen137/Blog/posts/MLOps_Zoomcamp_Module_2/preprocessor'</code></pre>
</div>
</div>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pickle</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">"preprocessor/preprocessor.b"</span>, <span class="st">"rb"</span>) <span class="im">as</span> f_in:</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>    dv <span class="op">=</span> pickle.load(f_in)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>Preprocess the test set using the DictVectorizer</code></p>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>X_test <span class="op">=</span> preprocess(df, dv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>Make predictions on the test set - model in Production</code></p>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> <span class="st">"duration"</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>y_test <span class="op">=</span> df[target].values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>time test_model(name<span class="op">=</span>model_name, stage<span class="op">=</span><span class="st">"Production"</span>, X_test<span class="op">=</span>X_test, y_test<span class="op">=</span>y_test) <span class="co"># magic command % to clock the test</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>2023/05/19 16:29:14 WARNING mlflow.pyfunc: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - mlflow (current: 2.3.2, required: mlflow==2.3)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[16:29:14] WARNING: ../src/objective/regression_obj.cu:213: reg:linear is now deprecated in favor of reg:squarederror.
CPU times: user 10.3 s, sys: 25.5 ms, total: 10.3 s
Wall time: 809 ms</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="33">
<pre><code>{'rmse': 6.505082976506096}</code></pre>
</div>
</div>
<p>So the RMSE is only slightly higher <code>6.505</code> (and performace slightly worse) when tested on the unseen March 2022 data, than the validation set metric of <code>6.171</code>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/model_management.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">model_management.PNG</figcaption><p></p>
</figure>
</div>
</section>
</section>
<section id="mlflow-in-practice" class="level3">
<h3 class="anchored" data-anchor-id="mlflow-in-practice">2.6 MLflow in practice</h3>
<p>Let’s consider three scenarios:</p>
<ol type="1">
<li>A <em>single</em> data scientist participating in an ML competition</li>
<li>A cross-functional <em>team</em> with <em>one</em> data scientist working on an ML model</li>
<li><em>Multiple</em> data scientists working on <em>multiple</em> ML models</li>
</ol>
<section id="a-single-data-scientist-participating-in-an-ml-competition" class="level4">
<h4 class="anchored" data-anchor-id="a-single-data-scientist-participating-in-an-ml-competition">2.6.1 A single data scientist participating in an ML competition</h4>
<p>In this use case, having a remote tracking server would be overkill. Sharing information with others is not a requirement and using a model registry would be useless, because there is no likelihood of model deployment to production.</p>
<p>MLflow setup:</p>
<ul>
<li>Tracking server: no</li>
<li>Backend store: local filesystem</li>
<li>Artifacts store: local filesystem</li>
</ul>
<p>The experiments can be explored locally by launching the MLflow UI.</p>
</section>
<section id="a-cross-functional-team-with-one-data-scientist-working-on-an-ml-model" class="level4">
<h4 class="anchored" data-anchor-id="a-cross-functional-team-with-one-data-scientist-working-on-an-ml-model">2.6.2 A cross-functional team with one data scientist working on an ML model</h4>
<p>Information will require to be shared with the cross-functional team, but there is not necessarily a necessity to run a tracking server remotely - locally may well be enough. Using the model registry might be a good idea to manage the life cycle of the models, but it is not clear whether we need to run it remotely or on the local host.</p>
<p>MLflow setup:</p>
<ul>
<li>Tracking server: yes, local server</li>
<li>Backend store: sqlite database</li>
<li>Artifacts store: local filesystem</li>
</ul>
<p>The experiments can be explored locally by accessing the local tracking server.</p>
<p>To run this example you need to launch the mlflow server locally by running the following command in your terminal:</p>
<pre><code>mlflow server --backend-store-uri sqlite:///backend.db</code></pre>
</section>
<section id="multiple-data-scientists-working-on-multiple-ml-models" class="level4">
<h4 class="anchored" data-anchor-id="multiple-data-scientists-working-on-multiple-ml-models">2.6.3 Multiple data scientists working on multiple ML models</h4>
<p>Sharing information is <strong>very</strong> important in this scenario. There is collaboration between scientists to build models and so they need a remote tracking server, and they should make use of model registry.</p>
<p>MLflow setup:</p>
<ul>
<li>Tracking server: yes, remote server (EC2).</li>
<li>Backend store: postgresql database.</li>
<li>Artifacts store: s3 bucket.</li>
</ul>
<p>The experiments can be explored by accessing the remote server.</p>
<p>The exampe uses AWS to host a remote server. In order to run the example you’ll need an AWS account. Follow the steps described below to create a new AWS account and launch the tracking server.</p>
</section>
</section>
<section id="setting-up-an-aws-account" class="level3">
<h3 class="anchored" data-anchor-id="setting-up-an-aws-account">2.6.4 Setting up an AWS account</h3>
<p><code>Basic AWS setup</code><br>
This tutorial explains how to configure a remote tracking server on AWS. We will use an RDS database as the backend store and an s3 bucket as the artifact store.</p>
<ol type="1">
<li><p>First, you need to <a href="https://aws.amazon.com/free">create an AWS account</a>. If you open a new account, AWS allows you to use some of their products for free but take into account that you may be charged for using the AWS services. More information <a href="https://youtu.be/rkKvzCskpLE">here</a> and <a href="https://aws.amazon.com/premiumsupport/knowledge-center/free-tier-charges/">here</a>.</p></li>
<li><p>Launch a new EC2 instance.</p></li>
</ol>
<p>For this, you can select one of the instance types that are free tier eligible. For example, we will select an Amazon Linux OS (<code>Amazon Linux 2 AMI (HVM) - Kernel 5.10, SSD Volume Type</code>) and a <code>t2.micro</code> instance type, which are free tier eligible.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/ec2_os.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">ec2_os.png</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/ec2_instance_type.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">ec2_instance_type.png</figcaption><p></p>
</figure>
</div>
<p>You’ll also need to create a new key pair so later you can connect to the new instance using SSH. Click on “Create new key pair” and complete the details like in the image below:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/key_pair.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">key_pair.png</figcaption><p></p>
</figure>
</div>
<p>Select the new key pair and then click on “Launch Instance” :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/select_key_pair.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">select_key_pair.png</figcaption><p></p>
</figure>
</div>
<p>Finally, you have to edit the security group so the EC2 instance accepts SSH (port 22) and HTTP connections (port 5000):</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/security_group.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">security_group.png</figcaption><p></p>
</figure>
</div>
<ol start="3" type="1">
<li>Create an s3 bucket to be used as the artifact store.</li>
</ol>
<p>Go to s3 and click on “Create bucket”. Fill in the bucket name as in the image below and let all the other configurations with their default values.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/s3_bucket.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">s3_bucket.png</figcaption><p></p>
</figure>
</div>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
s3 bucket names
</div>
</div>
<div class="callout-body-container callout-body">
<p>s3 bucket names must be unique across all AWS account in all the AWS Regions within a partition, that means that once a bucket is created, the name of that bucket cannot be used by another AWS account within the same region. If you get an error saying that the bucket name was already taken you can fix it easily by just changing the name to something like mlflow-artifacts-remote-2 or another name.</p>
</div>
</div>
<ol start="4" type="1">
<li>Create a new PostgreSQL database to be used as the backend store</li>
</ol>
<p>Go to the RDS Console and click on “Create database”. Make sure to select “PostgreSQL” engine type and the “Free tier” template.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/postgresql.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">postgresql.png</figcaption><p></p>
</figure>
</div>
<p>Select a name for your DB instance, set the master username as “mlflow” and tick the option “Auto generate a password” so Amazon RDS generate a password automatically.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/db_settings.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">db_settings.png</figcaption><p></p>
</figure>
</div>
<p>Finally, on the section “Additional configuration” specify a database name so RDS automatically creates an initial database for you :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/db_configuration.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">db_configuration.png</figcaption><p></p>
</figure>
</div>
<p>You can use the default values for all the other configurations.</p>
<p>Take note of the following information:</p>
<ul>
<li>master username</li>
<li>password</li>
<li>initial database name</li>
<li>endpoint</li>
</ul>
<p>Once the DB instance is created, go to the RDS console, select the new db and under “Connectivity &amp; security” select the VPC security group. Modify the security group by adding a new inbound rule that allows postgreSQL connections on the port 5432 from the security group of the EC2 instance. This way, the server will be able to connect to the postgres database :</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/postgresql_inbound_rule.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">postgresql_inbound_rule.png</figcaption><p></p>
</figure>
</div>
<ol start="5" type="1">
<li>Connect to the EC2 instance and launch the tracking server.</li>
</ol>
<p>Go to the EC2 Console and find the instance launched on the step 2. Click on “Connect” and then follow the steps described in the tab “SSH”.</p>
<p>Run the following commands to install the dependencies, configure the environment and launch the server:</p>
<ul>
<li>sudo yum update</li>
<li>pip3 install mlflow boto3 psycopg2-binary</li>
<li>aws configure # you’ll need to input your AWS credentials here</li>
<li>mlflow server -h 0.0.0.0 -p 5000 –backend-store-uri postgresql://DB_USER:DB_PASSWORD@DB_ENDPOINT:5432/DB_NAME –default-artifact-root s3://S3_BUCKET_NAME</li>
</ul>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Before launching server
</div>
</div>
<div class="callout-body-container callout-body">
<p>Before launching the server, check that the instance can access the s3 bucket created in the step number 3. To do that, just run this command from the EC2 instance: <code>aws s3 ls</code>. You should see the bucket listed in the result.</p>
</div>
</div>
<ol start="6" type="1">
<li>Access the remote tracking server from your local machine.</li>
</ol>
<p>Open a new tab on your web browser and go to this address: <code>http://&lt;EC2_PUBLIC_DNS&gt;:5000</code> (you can find the instance’s public DNS by checking the details of your instance in the EC2 Console).</p>
<section id="configuring-ml-flow" class="level4">
<h4 class="anchored" data-anchor-id="configuring-ml-flow">2.6.5 Configuring ML Flow</h4>
<p>Configuration will be different depending on the context. The three main aspects to consider are :</p>
<p><code>Backend store</code> - local filesystem - SQLAlchemy compatible DB (e.g.&nbsp;SQLite)</p>
<p><code>Artifacts store</code> - local filesystem - remote (e.g.&nbsp;s3 bucket)</p>
<p><code>Tracking server</code> - no tracking server - localhost - remote</p>
</section>
</section>
<section id="mlflow-benefits-limitations-and-alternatives" class="level3">
<h3 class="anchored" data-anchor-id="mlflow-benefits-limitations-and-alternatives">2.7 MLflow: benefits, limitations and alternatives</h3>
<section id="remote-tracking-server" class="level4">
<h4 class="anchored" data-anchor-id="remote-tracking-server">2.7.1 Remote tracking server</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/d61aa2e0-2b72-43f8-92b0-a4adefb802fc.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">remote_tracking_server.PNG</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/a0428aa3-e43e-4d82-9424-c8e85d673276.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">remote_server_issues.PNG</figcaption><p></p>
</figure>
</div>
</section>
<section id="mlflow-limitations" class="level4">
<h4 class="anchored" data-anchor-id="mlflow-limitations">2.7.2 MLflow limitations</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/189e3c94-ab0c-4f16-9420-5401f55b062b.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">limitations.PNG</figcaption><p></p>
</figure>
</div>
</section>
<section id="mlflow-alternatives" class="level4">
<h4 class="anchored" data-anchor-id="mlflow-alternatives">2.7.3 MLflow alternatives</h4>
<p>There are some paid alternatives to MLflow, each with a free tier and offering a free trial:</p>
<p><a href="https://neptune.ai/">Neptune</a><img src="MLOps_Zoomcamp_Module_2_files/figure-html/62c6128f-5f29-47ec-994c-1517e4124000.PNG" class="img-fluid" alt="neptune.PNG"></p>
<p><a href="https://www.comet.com/site/">Comet</a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/2650f65d-0c01-4df1-ba3e-2b5ece20239f.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">comet.PNG</figcaption><p></p>
</figure>
</div>
<p><a href="https://wandb.ai/site/pricing">Weights &amp; Biases</a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/bec58c99-0139-4ad4-be98-342f413307c8.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">weights_n_biases.PNG</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Module_2_files/figure-html/69571158-dfb6-426a-905b-6174eb0b4907.PNG" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">many_more.PNG</figcaption><p></p>
</figure>
</div>
<p>and <a href="https://neptune.ai/blog/best-ml-experiment-tracking-tools">many more</a>.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>