<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Stephen Barrie">
<meta name="dcterms.date" content="2023-05-17">

<title>Into the Unknown - mlops-zoomcamp | Module 1: Introduction</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Into the Unknown</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">Stephen Barrie</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml" rel="" target=""><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Stephen137" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/sjbarrie" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">mlops-zoomcamp | Module 1: Introduction</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">MLOps</div>
                <div class="quarto-category">DataTalksClub</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Stephen Barrie </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 17, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#course-overview" id="toc-course-overview" class="nav-link active" data-scroll-target="#course-overview">Course Overview</a>
  <ul class="collapse">
  <li><a href="#target-audience" id="toc-target-audience" class="nav-link" data-scroll-target="#target-audience">Target audience</a></li>
  <li><a href="#pre-requisites" id="toc-pre-requisites" class="nav-link" data-scroll-target="#pre-requisites">Pre-requisites</a></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset">Dataset</a></li>
  <li><a href="#what-is-mlops" id="toc-what-is-mlops" class="nav-link" data-scroll-target="#what-is-mlops">1.1 What is MLOps</a></li>
  <li><a href="#environment-preparation" id="toc-environment-preparation" class="nav-link" data-scroll-target="#environment-preparation">1.2 Environment preparation</a></li>
  <li><a href="#training-a-ride-duration-prediction-model" id="toc-training-a-ride-duration-prediction-model" class="nav-link" data-scroll-target="#training-a-ride-duration-prediction-model">1.3 Training a ride duration prediction model</a>
  <ul class="collapse">
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda">1.3.1 Exploratory Data Analysis (EDA)</a></li>
  <li><a href="#distribution-of-our-data" id="toc-distribution-of-our-data" class="nav-link" data-scroll-target="#distribution-of-our-data">1.3.2 Distribution of our data</a></li>
  <li><a href="#potential-outliers" id="toc-potential-outliers" class="nav-link" data-scroll-target="#potential-outliers">1.3.3 Potential outliers</a></li>
  <li><a href="#dealing-with-outliers" id="toc-dealing-with-outliers" class="nav-link" data-scroll-target="#dealing-with-outliers">1.3.4 Dealing with outliers</a></li>
  <li><a href="#one-hot-encoding" id="toc-one-hot-encoding" class="nav-link" data-scroll-target="#one-hot-encoding">1.3.5 One Hot Encoding</a></li>
  <li><a href="#customized-pre-processing-function" id="toc-customized-pre-processing-function" class="nav-link" data-scroll-target="#customized-pre-processing-function">1.3.6 Customized pre-processing function</a></li>
  <li><a href="#training-a-model" id="toc-training-a-model" class="nav-link" data-scroll-target="#training-a-model">1.3.7 Training a model</a></li>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression">1.3.8 Linear Regression</a></li>
  <li><a href="#get-predictions" id="toc-get-predictions" class="nav-link" data-scroll-target="#get-predictions">1.3.9 Get predictions</a></li>
  <li><a href="#loss-function---rmse" id="toc-loss-function---rmse" class="nav-link" data-scroll-target="#loss-function---rmse">1.3.10 Loss function - RMSE</a></li>
  <li><a href="#evaluating-our-model---validation-set" id="toc-evaluating-our-model---validation-set" class="nav-link" data-scroll-target="#evaluating-our-model---validation-set">1.3.11 Evaluating our model - validation set</a></li>
  <li><a href="#visualization" id="toc-visualization" class="nav-link" data-scroll-target="#visualization">1.3.12 Visualization</a></li>
  <li><a href="#other-models" id="toc-other-models" class="nav-link" data-scroll-target="#other-models">1.3.13 Other models</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering">1.3.14 Feature engineering</a></li>
  <li><a href="#saving-our-model" id="toc-saving-our-model" class="nav-link" data-scroll-target="#saving-our-model">1.3.15 Saving our model</a></li>
  </ul></li>
  <li><a href="#mlops-maturity-model" id="toc-mlops-maturity-model" class="nav-link" data-scroll-target="#mlops-maturity-model">1.4 MLOps maturity model</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="course-overview" class="level1">
<h1>Course Overview</h1>
<p>Jupyter Notebooks offer a convenient and interactive environment for experimentation, prototyping, and data exploration in machine learning projects. However, when it comes to production-level code, scalability, collaboration, and reproducibility, it is often recommended to transition to more robust development environments and workflows.</p>
<p>Some of the shotcomings of working using Jupyter Notebooks include:</p>
<ul>
<li><p><code>Lack of scalability:</code> Jupyter Notebooks are not ideal for handling large datasets or computationally intensive tasks. As notebooks run on a single kernel, they may struggle with memory limitations and slow execution times for complex machine learning models or big datasets.</p></li>
<li><p><code>Version control issues:</code> Jupyter Notebooks are not designed for seamless integration with version control systems like Git. This can make it challenging to track changes, collaborate with team members, or revert to previous versions of the code.</p></li>
<li><p><code>Reproducibility challenges:</code> While Jupyter Notebooks allow code intermingled with narrative and visualizations, this can make reproducing experiments difficult. Reproducing results from a notebook may require manually executing each cell in the correct order, leading to potential errors or inconsistencies.</p></li>
<li><p><code>Lack of code modularity:</code> Notebooks often encourage a linear and exploratory coding style, which can lead to unorganized and unmaintainable code. Extracting modular functions and reusing code becomes harder, as code snippets tend to be scattered throughout the notebook.</p></li>
<li><p><code>Debugging complexities:</code> Debugging code in Jupyter Notebooks can be more challenging compared to traditional code editors. Errors may not be displayed immediately, making it harder to identify and fix issues, especially when dealing with complex machine learning workflows.</p></li>
<li><p><code>Security risks:</code> Sharing Jupyter Notebooks can pose security risks, as they may contain sensitive information such as API keys or access tokens. If precautions are not taken, there is a potential risk of exposing confidential data when sharing notebooks.</p></li>
<li><p><code>Lack of performance optimization:</code> Jupyter Notebooks do not provide extensive profiling and optimization tools. Optimizing code performance may require additional steps and tools outside of the notebook environment.</p></li>
</ul>
<p>This course aims to address the above shortcomings, by teaching the practical aspects of productionizing ML services — from training and experimenting to model deployment and monitoring.</p>
<section id="target-audience" class="level2">
<h2 class="anchored" data-anchor-id="target-audience">Target audience</h2>
<p>Data scientists and ML engineers. Also software engineers and data engineers interested in learning about putting ML in production.</p>
</section>
<section id="pre-requisites" class="level2">
<h2 class="anchored" data-anchor-id="pre-requisites">Pre-requisites</h2>
<ul>
<li>Python</li>
<li>Docker</li>
<li>Being comfortable with command line</li>
<li>Prior exposure to machine learning (at work or from other courses, e.g.&nbsp;from ML Zoomcamp)</li>
<li>Prior programming experience (at least 1+ year)</li>
</ul>
</section>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">Dataset</h2>
<p>The <a href="https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page">NYC Taxi and Limousine Commission(TLC)</a> open dataset. Throughout this course we will be referencing this dataset to build, train, experiment, deploy, and monitor (a process collectovely known as MLOps) a linear regression model that predicts the duration of a taxi ride.</p>
</section>
<section id="what-is-mlops" class="level2">
<h2 class="anchored" data-anchor-id="what-is-mlops">1.1 What is MLOps</h2>
<p><code>MLOps</code>, short for Machine Learning Operations, refers to the practices, methodologies, and tools used to streamline and operationalize the lifecycle of machine learning (ML) models. It aims to bridge the gap between data scientists, who develop and train models, and production environments, where models are deployed and maintained.</p>
<p>Traditionally, the development and deployment of ML models have been treated as separate stages, leading to challenges when transitioning from experimentation to production. MLOps seeks to address these challenges by introducing a set of best practices for managing ML workflows, collaboration, and automation.</p>
<p>Here are some key components and concepts associated with MLOps:</p>
<ul>
<li><p><code>Version control:</code> Applying version control systems (e.g., Git) to ML models, code, and data, enabling easy tracking of changes and reproducibility.</p></li>
<li><p><code>Automation and orchestration:</code> Using automation tools to streamline repetitive tasks, such as data preprocessing, model training, evaluation, and deployment. Orchestration frameworks, like Kubeflow or Apache Airflow, help manage complex workflows.</p></li>
<li><p><code>Continuous Integration and Continuous Deployment (CI/CD):</code> Adapting CI/CD principles from software development to ML, allowing for frequent and automated model updates and deployments.</p></li>
<li><p><code>Infrastructure and environment management:</code> Utilizing tools like Docker and Kubernetes to containerize ML models and manage scalable and reproducible environments across different stages, from development to production.</p></li>
<li><p><code>Model monitoring and management:</code> Implementing monitoring solutions to track model performance, detect anomalies, and ensure models remain effective over time. This includes logging relevant metrics and retraining models when necessary.</p></li>
<li><p><code>Collaboration and reproducibility:</code> Establishing practices for sharing code, data, and experiment results, enabling collaboration among data scientists and ensuring reproducibility of ML workflows.</p></li>
<li><p><code>Governance and compliance:</code> Addressing ethical and legal considerations, such as data privacy, bias mitigation, and regulatory compliance, throughout the ML lifecycle.</p></li>
</ul>
<p>By adopting MLOps practices, organizations can enhance the efficiency, scalability, and reliability of their ML deployments. It promotes a systematic approach to managing ML models, accelerates time to market, and facilitates collaboration between different stakeholders involved in ML development and deployment.</p>
</section>
<section id="environment-preparation" class="level2">
<h2 class="anchored" data-anchor-id="environment-preparation">1.2 Environment preparation</h2>
<p><code>Step 1</code><br>
Download and install the Anaconda distribution of Python</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>wget https:<span class="op">//</span>repo.anaconda.com<span class="op">/</span>archive<span class="op">/</span>Anaconda3<span class="op">-</span><span class="fl">2022.05</span><span class="op">-</span>Linux<span class="op">-</span>x86_64.sh</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>bash Anaconda3<span class="op">-</span><span class="fl">2022.05</span><span class="op">-</span>Linux<span class="op">-</span>x86_64.sh</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>Step 2</code><br>
Update existing packages</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>sudo apt update</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>Step 3</code><br>
Install Docker</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>sudo apt install docker.io</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>Step 4</code><br>
Create a separate directory for the installation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>mkdir soft</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>cd soft</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To get the latest release of Docker Compose, go to https://github.com/docker/compose and download the release for your OS.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>wget https:<span class="op">//</span>github.com<span class="op">/</span>docker<span class="op">/</span>compose<span class="op">/</span>releases<span class="op">/</span>download<span class="op">/</span>v2<span class="fl">.18.0</span><span class="op">/</span>docker<span class="op">-</span>compose<span class="op">-</span>linux<span class="op">-</span>x86_64 <span class="op">-</span>O docker<span class="op">-</span>compose</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Make it executable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>chmod <span class="op">+</span>x docker<span class="op">-</span>compose</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Add to the <code>soft</code> directory to PATH. Open the <code>.bashrc</code> file with <code>nano</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>nano <span class="op">~/</span>.bashrc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In <code>.bashrc</code>, add the following line:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>export PATH<span class="op">=</span><span class="st">"$</span><span class="sc">{HOME}</span><span class="st">/soft:$</span><span class="sc">{PATH}</span><span class="st">"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Week_1_files/figure-html/79b285b1-6a3b-40a6-b5d6-6f8d03b51563-1-34f69f9d-da18-47cb-98ad-4228a7942840.PNG" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">nano.PNG</figcaption>
</figure>
</div>
<p>Save it using <code>ctrl + O</code> , hit <code>enter</code> at the <code>File Name to Write</code> prompt, and then exit using <code>ctrl + Z</code></p>
<p>Run the following to make sure the changes are applied:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>source <span class="op">~/</span>.bashrc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>Step 5</code><br>
Run Docker</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>docker run hello<span class="op">-</span>world</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Week_1_files/figure-html/5d61a46c-f79e-463f-ad2f-651f7b0815c8-1-dae46866-a236-45df-a516-22d242a7fe2d.PNG" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">hello_world.PNG</figcaption>
</figure>
</div>
</section>
<section id="training-a-ride-duration-prediction-model" class="level2">
<h2 class="anchored" data-anchor-id="training-a-ride-duration-prediction-model">1.3 Training a ride duration prediction model</h2>
<section id="exploratory-data-analysis-eda" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis-eda">1.3.1 Exploratory Data Analysis (EDA)</h3>
<p>Let’s download <a href="https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page">Yellow Trips taxi records for January and February 2022</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>wget https:<span class="op">//</span>d37ci6vzurychx.cloudfront.net<span class="op">/</span>trip<span class="op">-</span>data<span class="op">/</span>yellow_tripdata_2022<span class="op">-</span><span class="fl">01.</span><span class="er">parquet</span> https:<span class="op">//</span>d37ci6vzurychx.cloudfront.net<span class="op">/</span>trip<span class="op">-</span>data<span class="op">/</span>yellow_tripdata_2022<span class="op">-</span><span class="fl">02.</span><span class="er">parquet</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And import the required packages :</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd <span class="co"># working with tabular data</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pickle <span class="co"># for machine learning models</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns <span class="co"># visualization</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt <span class="co"># visualization</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.feature_extraction <span class="im">import</span> DictVectorizer <span class="co"># Machine Learning</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression <span class="co"># Machine Learning</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> Lasso <span class="co"># Regularization</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> Ridge <span class="co"># Regularization</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error <span class="co"># Loss Function</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Read the data for January 2022:</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>yellow_jan_22 <span class="op">=</span> pd.read_parquet(<span class="st">'yellow_tripdata_2022-01.parquet'</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>yellow_jan_22</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">VendorID</th>
<th data-quarto-table-cell-role="th">tpep_pickup_datetime</th>
<th data-quarto-table-cell-role="th">tpep_dropoff_datetime</th>
<th data-quarto-table-cell-role="th">passenger_count</th>
<th data-quarto-table-cell-role="th">trip_distance</th>
<th data-quarto-table-cell-role="th">RatecodeID</th>
<th data-quarto-table-cell-role="th">store_and_fwd_flag</th>
<th data-quarto-table-cell-role="th">PULocationID</th>
<th data-quarto-table-cell-role="th">DOLocationID</th>
<th data-quarto-table-cell-role="th">payment_type</th>
<th data-quarto-table-cell-role="th">fare_amount</th>
<th data-quarto-table-cell-role="th">extra</th>
<th data-quarto-table-cell-role="th">mta_tax</th>
<th data-quarto-table-cell-role="th">tip_amount</th>
<th data-quarto-table-cell-role="th">tolls_amount</th>
<th data-quarto-table-cell-role="th">improvement_surcharge</th>
<th data-quarto-table-cell-role="th">total_amount</th>
<th data-quarto-table-cell-role="th">congestion_surcharge</th>
<th data-quarto-table-cell-role="th">airport_fee</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>2022-01-01 00:35:40</td>
<td>2022-01-01 00:53:29</td>
<td>2.0</td>
<td>3.80</td>
<td>1.0</td>
<td>N</td>
<td>142</td>
<td>236</td>
<td>1</td>
<td>14.50</td>
<td>3.0</td>
<td>0.5</td>
<td>3.65</td>
<td>0.0</td>
<td>0.3</td>
<td>21.95</td>
<td>2.5</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1</td>
<td>2022-01-01 00:33:43</td>
<td>2022-01-01 00:42:07</td>
<td>1.0</td>
<td>2.10</td>
<td>1.0</td>
<td>N</td>
<td>236</td>
<td>42</td>
<td>1</td>
<td>8.00</td>
<td>0.5</td>
<td>0.5</td>
<td>4.00</td>
<td>0.0</td>
<td>0.3</td>
<td>13.30</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2</td>
<td>2022-01-01 00:53:21</td>
<td>2022-01-01 01:02:19</td>
<td>1.0</td>
<td>0.97</td>
<td>1.0</td>
<td>N</td>
<td>166</td>
<td>166</td>
<td>1</td>
<td>7.50</td>
<td>0.5</td>
<td>0.5</td>
<td>1.76</td>
<td>0.0</td>
<td>0.3</td>
<td>10.56</td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2</td>
<td>2022-01-01 00:25:21</td>
<td>2022-01-01 00:35:23</td>
<td>1.0</td>
<td>1.09</td>
<td>1.0</td>
<td>N</td>
<td>114</td>
<td>68</td>
<td>2</td>
<td>8.00</td>
<td>0.5</td>
<td>0.5</td>
<td>0.00</td>
<td>0.0</td>
<td>0.3</td>
<td>11.80</td>
<td>2.5</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2</td>
<td>2022-01-01 00:36:48</td>
<td>2022-01-01 01:14:20</td>
<td>1.0</td>
<td>4.30</td>
<td>1.0</td>
<td>N</td>
<td>68</td>
<td>163</td>
<td>1</td>
<td>23.50</td>
<td>0.5</td>
<td>0.5</td>
<td>3.00</td>
<td>0.0</td>
<td>0.3</td>
<td>30.30</td>
<td>2.5</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2463926</td>
<td>2</td>
<td>2022-01-31 23:36:53</td>
<td>2022-01-31 23:42:51</td>
<td>NaN</td>
<td>1.32</td>
<td>NaN</td>
<td>None</td>
<td>90</td>
<td>170</td>
<td>0</td>
<td>8.00</td>
<td>0.0</td>
<td>0.5</td>
<td>2.39</td>
<td>0.0</td>
<td>0.3</td>
<td>13.69</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2463927</td>
<td>2</td>
<td>2022-01-31 23:44:22</td>
<td>2022-01-31 23:55:01</td>
<td>NaN</td>
<td>4.19</td>
<td>NaN</td>
<td>None</td>
<td>107</td>
<td>75</td>
<td>0</td>
<td>16.80</td>
<td>0.0</td>
<td>0.5</td>
<td>4.35</td>
<td>0.0</td>
<td>0.3</td>
<td>24.45</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2463928</td>
<td>2</td>
<td>2022-01-31 23:39:00</td>
<td>2022-01-31 23:50:00</td>
<td>NaN</td>
<td>2.10</td>
<td>NaN</td>
<td>None</td>
<td>113</td>
<td>246</td>
<td>0</td>
<td>11.22</td>
<td>0.0</td>
<td>0.5</td>
<td>2.00</td>
<td>0.0</td>
<td>0.3</td>
<td>16.52</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2463929</td>
<td>2</td>
<td>2022-01-31 23:36:42</td>
<td>2022-01-31 23:48:45</td>
<td>NaN</td>
<td>2.92</td>
<td>NaN</td>
<td>None</td>
<td>148</td>
<td>164</td>
<td>0</td>
<td>12.40</td>
<td>0.0</td>
<td>0.5</td>
<td>0.00</td>
<td>0.0</td>
<td>0.3</td>
<td>15.70</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2463930</td>
<td>2</td>
<td>2022-01-31 23:46:00</td>
<td>2022-02-01 00:13:00</td>
<td>NaN</td>
<td>8.94</td>
<td>NaN</td>
<td>None</td>
<td>186</td>
<td>181</td>
<td>0</td>
<td>25.48</td>
<td>0.0</td>
<td>0.5</td>
<td>6.28</td>
<td>0.0</td>
<td>0.3</td>
<td>35.06</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>2463931 rows × 19 columns</p>
</div>
</div>
</div>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>yellow_jan_22.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 2463931 entries, 0 to 2463930
Data columns (total 19 columns):
 #   Column                 Dtype         
---  ------                 -----         
 0   VendorID               int64         
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64       
 4   trip_distance          float64       
 5   RatecodeID             float64       
 6   store_and_fwd_flag     object        
 7   PULocationID           int64         
 8   DOLocationID           int64         
 9   payment_type           int64         
 10  fare_amount            float64       
 11  extra                  float64       
 12  mta_tax                float64       
 13  tip_amount             float64       
 14  tolls_amount           float64       
 15  improvement_surcharge  float64       
 16  total_amount           float64       
 17  congestion_surcharge   float64       
 18  airport_fee            float64       
dtypes: datetime64[ns](2), float64(12), int64(4), object(1)
memory usage: 357.2+ MB</code></pre>
</div>
</div>
<p>Let’s create a new column <code>duration</code> which calculates the length of each ride :</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>yellow_jan_22[<span class="st">'duration'</span>] <span class="op">=</span> yellow_jan_22.tpep_dropoff_datetime <span class="op">-</span> yellow_jan_22.tpep_pickup_datetime</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>yellow_jan_22.duration <span class="op">=</span> yellow_jan_22.duration.<span class="bu">apply</span>(<span class="kw">lambda</span> td: td.total_seconds()<span class="op">/</span><span class="dv">60</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s also convert the <code>PULocationID</code>, <code>DOLocationID</code> columns from <code>int64</code> to strings :</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>categorical <span class="op">=</span> [<span class="st">'PULocationID'</span>, <span class="st">'DOLocationID'</span>]</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>numerical <span class="op">=</span> [<span class="st">'trip_distance'</span>]</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>yellow_jan_22[categorical] <span class="op">=</span> yellow_jan_22[categorical].astype(<span class="bu">str</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And look at our updated dataframe :</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>yellow_jan_22.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 2463931 entries, 0 to 2463930
Data columns (total 20 columns):
 #   Column                 Dtype         
---  ------                 -----         
 0   VendorID               int64         
 1   tpep_pickup_datetime   datetime64[ns]
 2   tpep_dropoff_datetime  datetime64[ns]
 3   passenger_count        float64       
 4   trip_distance          float64       
 5   RatecodeID             float64       
 6   store_and_fwd_flag     object        
 7   PULocationID           object        
 8   DOLocationID           object        
 9   payment_type           int64         
 10  fare_amount            float64       
 11  extra                  float64       
 12  mta_tax                float64       
 13  tip_amount             float64       
 14  tolls_amount           float64       
 15  improvement_surcharge  float64       
 16  total_amount           float64       
 17  congestion_surcharge   float64       
 18  airport_fee            float64       
 19  duration               float64       
dtypes: datetime64[ns](2), float64(13), int64(2), object(3)
memory usage: 376.0+ MB</code></pre>
</div>
</div>
<p>Great, we now have a <code>duration</code> column and <code>PULocationID</code> and <code>DOLocationID</code> are now correctly showing as datatype <code>object</code> (categorical data, which includes strings).</p>
</section>
<section id="distribution-of-our-data" class="level3">
<h3 class="anchored" data-anchor-id="distribution-of-our-data">1.3.2 Distribution of our data</h3>
<p>It’s often useful to get an idea of the distribution of our data. We can get a quick overview :</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>yellow_jan_22.describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">VendorID</th>
<th data-quarto-table-cell-role="th">passenger_count</th>
<th data-quarto-table-cell-role="th">trip_distance</th>
<th data-quarto-table-cell-role="th">RatecodeID</th>
<th data-quarto-table-cell-role="th">payment_type</th>
<th data-quarto-table-cell-role="th">fare_amount</th>
<th data-quarto-table-cell-role="th">extra</th>
<th data-quarto-table-cell-role="th">mta_tax</th>
<th data-quarto-table-cell-role="th">tip_amount</th>
<th data-quarto-table-cell-role="th">tolls_amount</th>
<th data-quarto-table-cell-role="th">improvement_surcharge</th>
<th data-quarto-table-cell-role="th">total_amount</th>
<th data-quarto-table-cell-role="th">congestion_surcharge</th>
<th data-quarto-table-cell-role="th">airport_fee</th>
<th data-quarto-table-cell-role="th">duration</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>2.463931e+06</td>
<td>2.392428e+06</td>
<td>2.463931e+06</td>
<td>2.392428e+06</td>
<td>2.463931e+06</td>
<td>2.463931e+06</td>
<td>2.463931e+06</td>
<td>2.463931e+06</td>
<td>2.463931e+06</td>
<td>2.463931e+06</td>
<td>2.463931e+06</td>
<td>2.463931e+06</td>
<td>2.392428e+06</td>
<td>2.392428e+06</td>
<td>2.463931e+06</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>1.707819e+00</td>
<td>1.389453e+00</td>
<td>5.372751e+00</td>
<td>1.415507e+00</td>
<td>1.194449e+00</td>
<td>1.294648e+01</td>
<td>1.006710e+00</td>
<td>4.914539e-01</td>
<td>2.385696e+00</td>
<td>3.749773e-01</td>
<td>2.967234e-01</td>
<td>1.916937e+01</td>
<td>2.282322e+00</td>
<td>8.249935e-02</td>
<td>1.421220e+01</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>5.021375e-01</td>
<td>9.829686e-01</td>
<td>5.478714e+02</td>
<td>5.917573e+00</td>
<td>5.001778e-01</td>
<td>2.558149e+02</td>
<td>1.236226e+00</td>
<td>8.291560e-02</td>
<td>2.830698e+00</td>
<td>1.680538e+00</td>
<td>4.374741e-02</td>
<td>2.559641e+02</td>
<td>7.432040e-01</td>
<td>3.125554e-01</td>
<td>4.644531e+01</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>1.000000e+00</td>
<td>0.000000e+00</td>
<td>0.000000e+00</td>
<td>1.000000e+00</td>
<td>0.000000e+00</td>
<td>-4.800000e+02</td>
<td>-4.500000e+00</td>
<td>-5.000000e-01</td>
<td>-1.252200e+02</td>
<td>-3.140000e+01</td>
<td>-3.000000e-01</td>
<td>-4.803000e+02</td>
<td>-2.500000e+00</td>
<td>-1.250000e+00</td>
<td>-3.442400e+03</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>1.000000e+00</td>
<td>1.000000e+00</td>
<td>1.040000e+00</td>
<td>1.000000e+00</td>
<td>1.000000e+00</td>
<td>6.500000e+00</td>
<td>0.000000e+00</td>
<td>5.000000e-01</td>
<td>7.200000e-01</td>
<td>0.000000e+00</td>
<td>3.000000e-01</td>
<td>1.130000e+01</td>
<td>2.500000e+00</td>
<td>0.000000e+00</td>
<td>6.316667e+00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>2.000000e+00</td>
<td>1.000000e+00</td>
<td>1.740000e+00</td>
<td>1.000000e+00</td>
<td>1.000000e+00</td>
<td>9.000000e+00</td>
<td>5.000000e-01</td>
<td>5.000000e-01</td>
<td>2.000000e+00</td>
<td>0.000000e+00</td>
<td>3.000000e-01</td>
<td>1.469000e+01</td>
<td>2.500000e+00</td>
<td>0.000000e+00</td>
<td>1.018333e+01</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>2.000000e+00</td>
<td>1.000000e+00</td>
<td>3.130000e+00</td>
<td>1.000000e+00</td>
<td>1.000000e+00</td>
<td>1.400000e+01</td>
<td>2.500000e+00</td>
<td>5.000000e-01</td>
<td>3.000000e+00</td>
<td>0.000000e+00</td>
<td>3.000000e-01</td>
<td>2.002000e+01</td>
<td>2.500000e+00</td>
<td>0.000000e+00</td>
<td>1.616667e+01</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>6.000000e+00</td>
<td>9.000000e+00</td>
<td>3.061593e+05</td>
<td>9.900000e+01</td>
<td>5.000000e+00</td>
<td>4.010923e+05</td>
<td>3.350000e+01</td>
<td>1.659000e+01</td>
<td>8.888800e+02</td>
<td>1.933000e+02</td>
<td>3.000000e-01</td>
<td>4.010956e+05</td>
<td>2.500000e+00</td>
<td>1.250000e+00</td>
<td>8.513183e+03</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="potential-outliers" class="level3">
<h3 class="anchored" data-anchor-id="potential-outliers">1.3.3 Potential outliers</h3>
<p>Outliers are data points that significantly deviate from the general pattern or distribution of the rest of the data. They are observations that are extremely different or unusual compared to the majority of the dataset. Outliers can occur due to various reasons, such as measurement errors, data entry mistakes, or genuinely rare events.</p>
<p>Outliers can have a substantial impact on statistical analyses and machine learning models. They can skew summary statistics, such as the mean and standard deviation, leading to biased estimations. Outliers can also influence the fitting of models, affecting the coefficients or parameters estimated.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Week_1_files/figure-html/9408e8b3-da34-4dfd-88b0-ea9672c59bc3-1-499e5089-6454-4d42-b82d-03e03c317641.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">back_to_the_future.jpg</figcaption>
</figure>
</div>
<p>It looks as if we have some outliers in our dataset. For example the minimum duration is negative! Unless the DeLorean from Back to the Future is in the NYC taxi fleet then that’s an error! On the other end of the scale the maximum trip duration is 8513 minutes which is over 50 days - Route 66? Probably not.</p>
</section>
<section id="dealing-with-outliers" class="level3">
<h3 class="anchored" data-anchor-id="dealing-with-outliers">1.3.4 Dealing with outliers</h3>
<p>Outliers can be dealt with in different ways depending on the context and goals of the analysis. Some common strategies include:</p>
<ul>
<li><p>Removing outliers: In certain cases, outliers can be removed from the dataset if they are determined to be due to data entry errors or measurement issues. However, caution must be exercised, as removing outliers indiscriminately can lead to the loss of valuable information.</p></li>
<li><p>Transforming the data: Applying data transformations, such as logarithmic or power transformations, can help mitigate the impact of outliers and make the data more normally distributed.</p></li>
<li><p>Winsorizing or capping: Winsorizing involves replacing extreme values with less extreme values, such as replacing values above a certain threshold with the value at that threshold. This approach reduces the impact of outliers without entirely removing them from the dataset.</p></li>
<li><p>Robust statistical methods: Utilizing robust statistical techniques, such as median and median absolute deviation, instead of mean and standard deviation, can provide more resistant estimators that are less influenced by outliers.</p></li>
</ul>
<p>It’s important to note that the appropriate treatment of outliers depends on the specific context, domain knowledge, and the goals of the analysis. Careful consideration and understanding of the data and its characteristics are crucial in handling outliers effectively.</p>
<p>We will remove these outliers as it looks as if they are due to measurement issues. Let’s keep only the records where the duration was between 1 and 60 minutes (inclusive).</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>yellow_jan_22 <span class="op">=</span> yellow_jan_22[(yellow_jan_22.duration <span class="op">&gt;=</span> <span class="dv">1</span>) <span class="op">&amp;</span> (yellow_jan_22.duration <span class="op">&lt;=</span> <span class="dv">60</span>)]</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>yellow_jan_22 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">VendorID</th>
<th data-quarto-table-cell-role="th">tpep_pickup_datetime</th>
<th data-quarto-table-cell-role="th">tpep_dropoff_datetime</th>
<th data-quarto-table-cell-role="th">passenger_count</th>
<th data-quarto-table-cell-role="th">trip_distance</th>
<th data-quarto-table-cell-role="th">RatecodeID</th>
<th data-quarto-table-cell-role="th">store_and_fwd_flag</th>
<th data-quarto-table-cell-role="th">PULocationID</th>
<th data-quarto-table-cell-role="th">DOLocationID</th>
<th data-quarto-table-cell-role="th">payment_type</th>
<th data-quarto-table-cell-role="th">fare_amount</th>
<th data-quarto-table-cell-role="th">extra</th>
<th data-quarto-table-cell-role="th">mta_tax</th>
<th data-quarto-table-cell-role="th">tip_amount</th>
<th data-quarto-table-cell-role="th">tolls_amount</th>
<th data-quarto-table-cell-role="th">improvement_surcharge</th>
<th data-quarto-table-cell-role="th">total_amount</th>
<th data-quarto-table-cell-role="th">congestion_surcharge</th>
<th data-quarto-table-cell-role="th">airport_fee</th>
<th data-quarto-table-cell-role="th">duration</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>2022-01-01 00:35:40</td>
<td>2022-01-01 00:53:29</td>
<td>2.0</td>
<td>3.80</td>
<td>1.0</td>
<td>N</td>
<td>142</td>
<td>236</td>
<td>1</td>
<td>14.50</td>
<td>3.0</td>
<td>0.5</td>
<td>3.65</td>
<td>0.0</td>
<td>0.3</td>
<td>21.95</td>
<td>2.5</td>
<td>0.0</td>
<td>17.816667</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1</td>
<td>2022-01-01 00:33:43</td>
<td>2022-01-01 00:42:07</td>
<td>1.0</td>
<td>2.10</td>
<td>1.0</td>
<td>N</td>
<td>236</td>
<td>42</td>
<td>1</td>
<td>8.00</td>
<td>0.5</td>
<td>0.5</td>
<td>4.00</td>
<td>0.0</td>
<td>0.3</td>
<td>13.30</td>
<td>0.0</td>
<td>0.0</td>
<td>8.400000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>2</td>
<td>2022-01-01 00:53:21</td>
<td>2022-01-01 01:02:19</td>
<td>1.0</td>
<td>0.97</td>
<td>1.0</td>
<td>N</td>
<td>166</td>
<td>166</td>
<td>1</td>
<td>7.50</td>
<td>0.5</td>
<td>0.5</td>
<td>1.76</td>
<td>0.0</td>
<td>0.3</td>
<td>10.56</td>
<td>0.0</td>
<td>0.0</td>
<td>8.966667</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>2</td>
<td>2022-01-01 00:25:21</td>
<td>2022-01-01 00:35:23</td>
<td>1.0</td>
<td>1.09</td>
<td>1.0</td>
<td>N</td>
<td>114</td>
<td>68</td>
<td>2</td>
<td>8.00</td>
<td>0.5</td>
<td>0.5</td>
<td>0.00</td>
<td>0.0</td>
<td>0.3</td>
<td>11.80</td>
<td>2.5</td>
<td>0.0</td>
<td>10.033333</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2</td>
<td>2022-01-01 00:36:48</td>
<td>2022-01-01 01:14:20</td>
<td>1.0</td>
<td>4.30</td>
<td>1.0</td>
<td>N</td>
<td>68</td>
<td>163</td>
<td>1</td>
<td>23.50</td>
<td>0.5</td>
<td>0.5</td>
<td>3.00</td>
<td>0.0</td>
<td>0.3</td>
<td>30.30</td>
<td>2.5</td>
<td>0.0</td>
<td>37.533333</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2463926</td>
<td>2</td>
<td>2022-01-31 23:36:53</td>
<td>2022-01-31 23:42:51</td>
<td>NaN</td>
<td>1.32</td>
<td>NaN</td>
<td>None</td>
<td>90</td>
<td>170</td>
<td>0</td>
<td>8.00</td>
<td>0.0</td>
<td>0.5</td>
<td>2.39</td>
<td>0.0</td>
<td>0.3</td>
<td>13.69</td>
<td>NaN</td>
<td>NaN</td>
<td>5.966667</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2463927</td>
<td>2</td>
<td>2022-01-31 23:44:22</td>
<td>2022-01-31 23:55:01</td>
<td>NaN</td>
<td>4.19</td>
<td>NaN</td>
<td>None</td>
<td>107</td>
<td>75</td>
<td>0</td>
<td>16.80</td>
<td>0.0</td>
<td>0.5</td>
<td>4.35</td>
<td>0.0</td>
<td>0.3</td>
<td>24.45</td>
<td>NaN</td>
<td>NaN</td>
<td>10.650000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2463928</td>
<td>2</td>
<td>2022-01-31 23:39:00</td>
<td>2022-01-31 23:50:00</td>
<td>NaN</td>
<td>2.10</td>
<td>NaN</td>
<td>None</td>
<td>113</td>
<td>246</td>
<td>0</td>
<td>11.22</td>
<td>0.0</td>
<td>0.5</td>
<td>2.00</td>
<td>0.0</td>
<td>0.3</td>
<td>16.52</td>
<td>NaN</td>
<td>NaN</td>
<td>11.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2463929</td>
<td>2</td>
<td>2022-01-31 23:36:42</td>
<td>2022-01-31 23:48:45</td>
<td>NaN</td>
<td>2.92</td>
<td>NaN</td>
<td>None</td>
<td>148</td>
<td>164</td>
<td>0</td>
<td>12.40</td>
<td>0.0</td>
<td>0.5</td>
<td>0.00</td>
<td>0.0</td>
<td>0.3</td>
<td>15.70</td>
<td>NaN</td>
<td>NaN</td>
<td>12.050000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2463930</td>
<td>2</td>
<td>2022-01-31 23:46:00</td>
<td>2022-02-01 00:13:00</td>
<td>NaN</td>
<td>8.94</td>
<td>NaN</td>
<td>None</td>
<td>186</td>
<td>181</td>
<td>0</td>
<td>25.48</td>
<td>0.0</td>
<td>0.5</td>
<td>6.28</td>
<td>0.0</td>
<td>0.3</td>
<td>35.06</td>
<td>NaN</td>
<td>NaN</td>
<td>27.000000</td>
</tr>
</tbody>
</table>

<p>2421440 rows × 20 columns</p>
</div>
</div>
</div>
<p>Our original dataset had <code>2,463,931</code> rows. After removing the outliers we now have <code>2,421,440</code> rows.</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2421440</span><span class="op">/</span><span class="dv">2463931</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>0.9827547930522406</code></pre>
</div>
</div>
<p>So we still have 98.3% of our original dataset. Removing the outliers hasn’t reduced our dataset significantly.</p>
</section>
<section id="one-hot-encoding" class="level3">
<h3 class="anchored" data-anchor-id="one-hot-encoding">1.3.5 One Hot Encoding</h3>
<p>One-hot encoding is a technique used to convert categorical variables into a numerical representation that can be used by machine learning algorithms. It is a common preprocessing step in data preparation.</p>
<p>In many machine learning algorithms, categorical variables cannot be directly used as input, as these algorithms typically operate on numerical data. One-hot encoding transforms each categorical value into a binary vector, where each vector has a length equal to the number of unique categories in the variable. The vector contains all zeros except for a single one at the index corresponding to the category of the original value.</p>
<p>One-hot encoding allows machine learning models to effectively capture categorical information and handle it as numerical input. However, it increases the dimensionality of the data, especially when dealing with variables with many unique categories. This can impact computational efficiency and model performance, especially in cases where the number of categories is large relative to the number of observations.</p>
<p>To illustrate, let’s apply one-hot encoding to the pickup and dropoff location IDs. We’ll use only these two features for our model.</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># turn the categorical columns into a list of dictionaries</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>list_of_dicts <span class="op">=</span> yellow_jan_22[categorical].to_dict(orient<span class="op">=</span><span class="st">'records'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Instantiate a dictionary vectorizer</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>dv <span class="op">=</span> DictVectorizer()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the vectorizer and transform the data into a feature matrix</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>fm <span class="op">=</span> dv.fit_transform(list_of_dicts)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the feature matrix to an array</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>fm_array <span class="op">=</span> fm.toarray()</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the dimensionality of the feature matrix</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>dimensionality <span class="op">=</span> fm_array.shape</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Dimensionality:"</span>, dimensionality)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dimensionality: (2421440, 515)</code></pre>
</div>
</div>
<p>So our feature matrix has <code>2,421,440</code> rows and <code>515</code> columns (originally 20 prior to one hot encoding).</p>
</section>
<section id="customized-pre-processing-function" class="level3">
<h3 class="anchored" data-anchor-id="customized-pre-processing-function">1.3.6 Customized pre-processing function</h3>
<p>We have carried out a lot of steps to get our data fit for training. We could automate this by creating a customized function :</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> read_dataframe(filename):</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> filename.endswith(<span class="st">'.csv'</span>):</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>        df <span class="op">=</span> pd.read_csv(filename)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>        df.tpep_dropoff_datetime <span class="op">=</span> pd.to_datetime(df.tpep_dropoff_datetime)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>        df.tpep_pickup_datetime <span class="op">=</span> pd.to_datetime(df.tpep_pickup_datetime)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> filename.endswith(<span class="st">'.parquet'</span>):</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>        df <span class="op">=</span> pd.read_parquet(filename)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'duration'</span>] <span class="op">=</span> df.tpep_dropoff_datetime <span class="op">-</span> df.tpep_pickup_datetime</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>    df.duration <span class="op">=</span> df.duration.<span class="bu">apply</span>(<span class="kw">lambda</span> td: td.total_seconds() <span class="op">/</span> <span class="dv">60</span>)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> df[(df.duration <span class="op">&gt;=</span> <span class="dv">1</span>) <span class="op">&amp;</span> (df.duration <span class="op">&lt;=</span> <span class="dv">60</span>)]</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>    categorical <span class="op">=</span> [<span class="st">'PULocationID'</span>, <span class="st">'DOLocationID'</span>]</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>    df[categorical] <span class="op">=</span> df[categorical].astype(<span class="bu">str</span>)</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="training-a-model" class="level3">
<h3 class="anchored" data-anchor-id="training-a-model">1.3.7 Training a model</h3>
<p>Let’s now let’s use the feature matrix from the previous step to train a Linear Regression model :</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert categorical columns to a dictionary</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>train_dicts <span class="op">=</span> yellow_jan_22[categorical].to_dict(orient<span class="op">=</span><span class="st">'records'</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Instantiate a dictionary vectorizer</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>dv <span class="op">=</span> DictVectorizer()</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up trainign set</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> dv.fit_transform(train_dicts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define target variable and assign to y_train</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> <span class="st">'duration'</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>y_train <span class="op">=</span> yellow_jan_22[target].values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression">1.3.8 Linear Regression</h3>
<p>A linear regression model is a statistical approach used to model the relationship between a dependent variable and one or more independent variables. It assumes a linear relationship between the variables and aims to find the best-fitting line that minimizes the differences between the predicted and actual values.</p>
<p>The model assumes that the dependent variable can be expressed as a linear combination of the independent variables, where each independent variable is multiplied by a coefficient and summed together with an intercept term. The coefficients represent the effect of each independent variable on the dependent variable, and the intercept term represents the expected value of the dependent variable when all independent variables are zero.</p>
<p>Linear regression models are widely used for various purposes, such as predicting sales based on advertising expenditure, analyzing the impact of independent variables on a dependent variable, and making forecasts.</p>
<p>In our case we are going to used linear regression to predict the duration of taxi rides.</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># instantiate linear regression model with default parameters</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> LinearRegression()</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># fit model to training data</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>lr.fit(X_train, y_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<style>#sk-container-id-1 {color: black;background-color: white;}#sk-container-id-1 pre{padding: 0;}#sk-container-id-1 div.sk-toggleable {background-color: white;}#sk-container-id-1 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-1 label.sk-toggleable__label-arrow:before {content: "▸";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-1 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-1 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-1 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: "▾";}#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-1 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-1 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-1 div.sk-parallel-item::after {content: "";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-serial::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-1 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-1 div.sk-item {position: relative;z-index: 1;}#sk-container-id-1 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-1 div.sk-item::before, #sk-container-id-1 div.sk-parallel-item::before {content: "";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-1 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-1 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-1 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-1 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-1 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-1 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-1 div.sk-label-container {text-align: center;}#sk-container-id-1 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-1 div.sk-text-repr-fallback {display: none;}</style><div id="sk-container-id-1" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>LinearRegression()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item"><div class="sk-estimator sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-1" type="checkbox" checked=""><label for="sk-estimator-id-1" class="sk-toggleable__label sk-toggleable__label-arrow">LinearRegression</label><div class="sk-toggleable__content"><pre>LinearRegression()</pre></div></div></div></div></div>
</div>
</div>
</section>
<section id="get-predictions" class="level3">
<h3 class="anchored" data-anchor-id="get-predictions">1.3.9 Get predictions</h3>
<p>Once the model is trained, it can be used to make predictions by plugging in new values for the independent variables. The model assumes that the relationship between the variables remains linear and that the underlying assumptions, such as linearity, independence, and homoscedasticity, hold true.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get predictions</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> lr.predict(X_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="loss-function---rmse" class="level3">
<h3 class="anchored" data-anchor-id="loss-function---rmse">1.3.10 Loss function - RMSE</h3>
<p>The process of building a linear regression model involves estimating the coefficients that minimize a chosen error metric, such as the <code>mean squared error (MSE)</code>. This is typically done using a technique called ordinary least squares (OLS), which finds the coefficients that minimize the sum of squared differences between the predicted and actual values.</p>
<p>The <code>RMSE</code> is the square root of the <code>mean squared error (MSE)</code>.</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate RMSE</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>mean_squared_error(y_train, y_pred, squared<span class="op">=</span><span class="va">False</span>) <span class="co"># squared = False so this is root MSE (RMSE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>6.986190845634642</code></pre>
</div>
</div>
</section>
<section id="evaluating-our-model---validation-set" class="level3">
<h3 class="anchored" data-anchor-id="evaluating-our-model---validation-set">1.3.11 Evaluating our model - validation set</h3>
<p>After training the model on the training set, the model’s performance is evaluated on the <code>validation set</code>.</p>
<p>A validation set, also known as a validation dataset, is a subset of data used to assess the performance and generalization ability of a machine learning model. It is important to note that the validation set should be kept separate from the training set and not be used for model training. Mixing the training and validation data may lead to biased performance estimates and ineffective model evaluation</p>
<p>The purpose of a validation set is to provide an unbiased estimate of how well the model will perform on new, unseen data. It helps in assessing whether the model has learned the underlying patterns and relationships in the data or if it has overfit or underfit the training data.</p>
<p>Once the model’s hyperparameters are optimized, a final evaluation on a separate test set, which represents completely unseen data, provides a more accurate assessment of the model’s performance and generalization ability.</p>
<p>Let’s evaluate our model on the unseen Yellow Taxi <code>February 2022</code> dataset that we downloaded earlier :</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read in the validation set</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>yellow_feb_22 <span class="op">=</span> pd.read_parquet(<span class="st">'yellow_tripdata_2022-02.parquet'</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># create a new column 'duration' in minutes</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>yellow_feb_22[<span class="st">'duration'</span>] <span class="op">=</span> yellow_feb_22.tpep_dropoff_datetime <span class="op">-</span> yellow_feb_22.tpep_pickup_datetime</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="co"># convert duration to seconds</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>yellow_feb_22.duration <span class="op">=</span> yellow_feb_22.duration.<span class="bu">apply</span>(<span class="kw">lambda</span> td: td.total_seconds()<span class="op">/</span><span class="dv">60</span>)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="co"># define categorical and numerical columns</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>categorical <span class="op">=</span> [<span class="st">'PULocationID'</span>, <span class="st">'DOLocationID'</span>]</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>numerical <span class="op">=</span> [<span class="st">'trip_distance'</span>]</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a><span class="co"># convert categorical columns to strings</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>yellow_feb_22[categorical] <span class="op">=</span> yellow_feb_22[categorical].astype(<span class="bu">str</span>)</span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a><span class="co"># remove outliers by clipping duration between 1 and 60 mins</span></span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>yellow_feb_22 <span class="op">=</span> yellow_feb_22[(yellow_feb_22.duration <span class="op">&gt;=</span> <span class="dv">1</span>) <span class="op">&amp;</span> (yellow_feb_22.duration <span class="op">&lt;=</span> <span class="dv">60</span>)]</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Instantiate a dictionary vectorizer</span></span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>dv <span class="op">=</span> DictVectorizer()</span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a><span class="co"># reinstate our training set</span></span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>train_dicts <span class="op">=</span> yellow_jan_22[categorical].to_dict(orient<span class="op">=</span><span class="st">'records'</span>)</span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> dv.fit_transform(train_dicts)</span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a><span class="co"># turn the categorical columns into a list of dictionaries</span></span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>val_dicts <span class="op">=</span> yellow_feb_22[categorical].to_dict(orient<span class="op">=</span><span class="st">'records'</span>)</span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a>X_val <span class="op">=</span> dv.transform(val_dicts)</span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-30"><a href="#cb35-30" aria-hidden="true" tabindex="-1"></a><span class="co"># define target variable and assign to y_val</span></span>
<span id="cb35-31"><a href="#cb35-31" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> <span class="st">'duration'</span></span>
<span id="cb35-32"><a href="#cb35-32" aria-hidden="true" tabindex="-1"></a>y_train <span class="op">=</span> yellow_jan_22[target].values</span>
<span id="cb35-33"><a href="#cb35-33" aria-hidden="true" tabindex="-1"></a>y_val <span class="op">=</span> yellow_feb_22[target].values</span>
<span id="cb35-34"><a href="#cb35-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-35"><a href="#cb35-35" aria-hidden="true" tabindex="-1"></a><span class="co"># instantiate &amp; fit our model to the TRAINING set</span></span>
<span id="cb35-36"><a href="#cb35-36" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> LinearRegression()</span>
<span id="cb35-37"><a href="#cb35-37" aria-hidden="true" tabindex="-1"></a>lr.fit(X_train,y_train)</span>
<span id="cb35-38"><a href="#cb35-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-39"><a href="#cb35-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Get predictions for the VALIDATION set</span></span>
<span id="cb35-40"><a href="#cb35-40" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> lr.predict(X_val)</span>
<span id="cb35-41"><a href="#cb35-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-42"><a href="#cb35-42" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate RMSE</span></span>
<span id="cb35-43"><a href="#cb35-43" aria-hidden="true" tabindex="-1"></a>mean_squared_error(y_val, y_pred, squared<span class="op">=</span><span class="va">False</span>) <span class="co"># squared = False so this is root MSE (RMSE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>7.7864132069521945</code></pre>
</div>
</div>
<p>So the RMSE on the validation set is <code>7.79</code> against <code>6.99</code> on the test set. This means that our predictions on the duration of taxi trips are wrong on average by 8 minutes. This is a starting baseline for improvement.</p>
</section>
<section id="visualization" class="level3">
<h3 class="anchored" data-anchor-id="visualization">1.3.12 Visualization</h3>
<p>We can visualize our predictions versus actuals using the <a href="https://seaborn.pydata.org/">Seaborn</a> library :</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>sns.distplot(y_pred, label<span class="op">=</span><span class="st">'prediction'</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>sns.distplot(y_train, label<span class="op">=</span><span class="st">'actual'</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>plt.legend()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_374/1672306066.py:1: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  sns.distplot(y_pred, label='prediction')
/tmp/ipykernel_374/1672306066.py:2: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  sns.distplot(y_train, label='actual')</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>&lt;matplotlib.legend.Legend at 0x7f316d9d4400&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="MLOps_Zoomcamp_Week_1_files/figure-html/cell-32-output-3.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="other-models" class="level3">
<h3 class="anchored" data-anchor-id="other-models">1.3.13 Other models</h3>
<p><code>Least Absolute Shrinkage and Selection Operator(Lasso)</code></p>
<p>Lasso regularization adds the absolute value of the coefficients multiplied by a constant, called the regularization parameter or alpha, to the loss function. The main characteristic of Lasso is that it can shrink coefficients all the way to zero, effectively performing feature selection by eliminating irrelevant or less important features. This property makes Lasso useful when dealing with high-dimensional datasets or when trying to identify the most significant predictors.</p>
<p>Lasso tends to perform well when there are many irrelevant features or a need for feature selection. However, it can struggle with highly correlated features or situations where there are more predictors than observations.</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> Lasso() <span class="co"># default parameters</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>lr.fit(X_train, y_train)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">-</span> lr.predict(X_val)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>mean_squared_error(y_val, y_pred, squared<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>7.7864132069521945</code></pre>
</div>
</div>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> Lasso(alpha<span class="op">=</span><span class="fl">0.01</span>) <span class="co"># try using different values for alpha - this controls the speed of gradient descent</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>lr.fit(X_train, y_train)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">-</span> lr.predict(X_val)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>mean_squared_error(y_val, y_pred, squared<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>7.7864132069521945</code></pre>
</div>
</div>
<p><code>Ridge (Tikhonov regularization or L2 regularization)</code></p>
<p>Ridge regularization adds the squared value of the coefficients multiplied by the regularization parameter to the loss function. Unlike Lasso, Ridge does not eliminate coefficients entirely but shrinks them towards zero without reaching zero. This leads to a reduction in the magnitude of the coefficients, effectively reducing model complexity. Ridge regularization is particularly useful when dealing with multicollinearity, a situation where predictor variables are highly correlated.</p>
<p>The choice between Lasso and Ridge regularization depends on the specific characteristics of the dataset and the goals of the analysis. In practice, it’s common to try both techniques and select the one that yields the best results or combine them in a hybrid approach called Elastic Net regularization.</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> Ridge(alpha<span class="op">=</span><span class="fl">0.01</span>) <span class="co"># try using different values for alpha - this controls the speed of gradient descent</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>lr.fit(X_train, y_train)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">-</span> lr.predict(X_val)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>mean_squared_error(y_val, y_pred, squared<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>7.7864132069521945</code></pre>
</div>
</div>
<p>Both the Lasso and Ridge models produce the same results as our standard Linear Regresssion model. This is hardly surprising as our model is only looking at two features, <code>PULocationID</code> and <code>DOLocationID</code>. Let’s include more features.</p>
</section>
<section id="feature-engineering" class="level3">
<h3 class="anchored" data-anchor-id="feature-engineering">1.3.14 Feature engineering</h3>
<p>Feature engineering is the process of transforming raw data into meaningful and informative features that can be used by machine learning algorithms. It involves selecting, extracting, and manipulating data attributes to enhance the performance of a model. The goal is to create features that capture relevant patterns, relationships, and insights from the data, leading to better predictive power.</p>
<p>Feature engineering techniques include handling missing values, scaling or normalizing numerical features, encoding categorical variables, creating new features through mathematical operations or domain knowledge, and reducing dimensionality through techniques like principal component analysis (PCA).</p>
<p>Effective feature engineering can significantly impact the performance of machine learning models by improving their accuracy, robustness, and interpretability.</p>
<p>Let’s try Linear Regression again with our categorical columns updated for this new feature:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>df_train <span class="op">=</span> read_dataframe(<span class="st">'yellow_tripdata_2022-01.parquet'</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>df_val <span class="op">=</span> read_dataframe(<span class="st">'yellow_tripdata_2022-02.parquet'</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>df_train[<span class="st">'PU_DO'</span>] <span class="op">=</span> df_train[<span class="st">'PULocationID'</span>] <span class="op">+</span> <span class="st">'_'</span> <span class="op">+</span> df_train[<span class="st">'DOLocationID'</span>]</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>df_val[<span class="st">'PU_DO'</span>] <span class="op">=</span> df_val[<span class="st">'PULocationID'</span>] <span class="op">+</span> <span class="st">'_'</span> <span class="op">+</span> df_val[<span class="st">'DOLocationID'</span>]</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>categorical <span class="op">=</span> [<span class="st">'PU_DO'</span>] <span class="co">#'PULocationID', 'DOLocationID']</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>numerical <span class="op">=</span> [<span class="st">'trip_distance'</span>]</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>dv <span class="op">=</span> DictVectorizer()</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>train_dicts <span class="op">=</span> df_train[categorical].to_dict(orient<span class="op">=</span><span class="st">'records'</span>)</span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> dv.fit_transform(train_dicts)</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>val_dicts <span class="op">=</span> df_val[categorical].to_dict(orient<span class="op">=</span><span class="st">'records'</span>)</span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a>X_val <span class="op">=</span> dv.transform(val_dicts)</span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> <span class="st">'duration'</span></span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a>y_train <span class="op">=</span> df_train[target].values</span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a>y_val <span class="op">=</span> df_val[target].values</span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> LinearRegression()</span>
<span id="cb46-23"><a href="#cb46-23" aria-hidden="true" tabindex="-1"></a>lr.fit(X_train, y_train)</span>
<span id="cb46-24"><a href="#cb46-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-25"><a href="#cb46-25" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> lr.predict(X_val)</span>
<span id="cb46-26"><a href="#cb46-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-27"><a href="#cb46-27" aria-hidden="true" tabindex="-1"></a>mean_squared_error(y_val, y_pred, squared<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="45">
<pre><code>5.41511157865009</code></pre>
</div>
</div>
<p>That is a significant improvement. The average prediction error is now down to 5.42 minutes, from 7.79.</p>
</section>
<section id="saving-our-model" class="level3">
<h3 class="anchored" data-anchor-id="saving-our-model">1.3.15 Saving our model</h3>
<p>Pickling is a process in Python that allows you to serialize (convert into a byte stream) and store objects, such as machine learning models, in a file. This serialized object can be saved to disk and later loaded back into memory, allowing you to preserve the model’s state for future use.</p>
<p>The pickle module in Python provides functions for pickling and unpickling objects. When you pickle a model, it saves the model’s parameters, internal state, and other necessary information required for its operation. This allows you to save trained models and use them later without needing to retrain them every time.</p>
<p>Pickling a model is useful for various purposes, such as:</p>
<ul>
<li><p><code>Saving trained models:</code> You can pickle your trained model and store it as a file. Later, you can load the model from the file and use it for making predictions without the need to retrain the model.</p></li>
<li><p><code>Sharing models:</code> Pickling enables you to share models with others, allowing them to use your trained model without requiring access to the original training data or retraining the model.</p></li>
<li><p><code>Deploying models</code> in production: You can pickle a trained model and load it into a production environment for making real-time predictions.</p></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="MLOps_Zoomcamp_Week_1_files/figure-html/f6bc8223-300a-40c7-857e-86d2e227ec94-1-cc92412b-e5b6-4283-9781-448f83ce02ee.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">pickle.jpg</figcaption>
</figure>
</div>
<p>First, let’s create a new directory to store our model :</p>
<div class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="op">!</span>mkdir models</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And save our model :</p>
<div class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">'./models/lin_reg.bin'</span>, <span class="st">'wb'</span>) <span class="im">as</span> f_out: <span class="co"># wb means write binary mlops-zoomcamp/week_1/models</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Pickle both the dictionary vectorizer and the linear regression model</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>        pickle.dump((dv, lr), f_out)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"Model successfully pickled."</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"Error occurred while pickling the model:"</span>, <span class="bu">str</span>(e))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model successfully pickled.</code></pre>
</div>
</div>
</section>
</section>
<section id="mlops-maturity-model" class="level2">
<h2 class="anchored" data-anchor-id="mlops-maturity-model">1.4 MLOps maturity model</h2>
<p>MLOps (Machine Learning Operations) maturity refers to the level of sophistication and effectiveness in managing and operationalizing machine learning (ML) systems within an organization. It represents the organization’s ability to develop, deploy, monitor, and maintain ML models in a reliable and scalable manner. MLOps maturity typically evolves through different stages, which can vary depending on the framework or model used. Here is a general overview of the stages:</p>
<p><code>Ad hoc:</code> In the early stages, ML development is ad hoc and lacks a systematic approach. Models are developed and deployed manually without standardized processes or version control. There is limited collaboration between data scientists and IT/DevOps teams.</p>
<p><code>Managed:</code> As organizations recognize the importance of ML, they start implementing basic management practices. Version control is introduced, and models are tracked. However, there might still be manual steps involved, and deployment processes may not be well-defined.</p>
<p><code>Automated:</code> At this stage, automation plays a crucial role in MLOps. Organizations adopt continuous integration and deployment (CI/CD) pipelines to automate model training, evaluation, and deployment. Infrastructure provisioning, testing, and monitoring become more streamlined. There is a stronger collaboration between data scientists, software engineers, and IT/DevOps teams.</p>
<p><code>Orchestrated:</code> MLOps processes are integrated and orchestrated across the entire ML lifecycle. Advanced automation tools and frameworks are employed to manage the complexity of ML workflows. There is a focus on reproducibility, model versioning, and experiment tracking. ML models are deployed in a scalable and efficient manner, making use of containerization and orchestration platforms.</p>
<p><code>Governed:</code> MLOps is fully integrated into the organization’s governance framework. Compliance, security, and regulatory considerations are taken into account throughout the ML lifecycle. Model performance and monitoring are monitored continuously, and feedback loops are established to improve models over time. Model explainability and interpretability are given importance.</p>
<p>Achieving higher levels of MLOps maturity requires investment in infrastructure, tooling, and establishing best practices. It also involves fostering collaboration and communication between different teams involved in ML development and deployment. Organizations with higher MLOps maturity are better equipped to handle the challenges of scaling ML projects, ensuring model reliability, and maximizing the value derived from ML initiatives.</p>
<p>A detailed overview is provided <a href="https://learn.microsoft.com/en-us/azure/architecture/example-scenario/mlops/mlops-maturity-model">here</a> by Microsoft Azure.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>