<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Stephen Barrie">
<meta name="dcterms.date" content="2022-12-09">

<title>Into the Unknown - Name that Genre</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Into the Unknown</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">Stephen Barrie</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Stephen137" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/sjbarrie" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Name that Genre</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Projects</div>
                <div class="quarto-category">Python</div>
                <div class="quarto-category">DataCamp</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Stephen Barrie </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">December 9, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#project-overview" id="toc-project-overview" class="nav-link active" data-scroll-target="#project-overview">Project overview</a>
  <ul class="collapse">
  <li><a href="#project-tasks" id="toc-project-tasks" class="nav-link" data-scroll-target="#project-tasks">Project Tasks</a></li>
  </ul></li>
  <li><a href="#preparing-our-dataset" id="toc-preparing-our-dataset" class="nav-link" data-scroll-target="#preparing-our-dataset">1. Preparing our dataset</a></li>
  <li><a href="#pairwise-relationships-between-continuous-variables" id="toc-pairwise-relationships-between-continuous-variables" class="nav-link" data-scroll-target="#pairwise-relationships-between-continuous-variables">2. Pairwise relationships between continuous variables</a></li>
  <li><a href="#splitting-our-data" id="toc-splitting-our-data" class="nav-link" data-scroll-target="#splitting-our-data">3. Splitting our data</a></li>
  <li><a href="#normalizing-the-feature-data" id="toc-normalizing-the-feature-data" class="nav-link" data-scroll-target="#normalizing-the-feature-data">4. Normalizing the feature data</a></li>
  <li><a href="#principal-component-analysis-on-our-scaled-data" id="toc-principal-component-analysis-on-our-scaled-data" class="nav-link" data-scroll-target="#principal-component-analysis-on-our-scaled-data">5. Principal Component Analysis on our scaled data</a></li>
  <li><a href="#further-visualization-of-pca" id="toc-further-visualization-of-pca" class="nav-link" data-scroll-target="#further-visualization-of-pca">6. Further visualization of PCA</a></li>
  <li><a href="#projecting-on-to-our-features" id="toc-projecting-on-to-our-features" class="nav-link" data-scroll-target="#projecting-on-to-our-features">7. Projecting on to our features</a></li>
  <li><a href="#train-a-decision-tree-to-classify-genre" id="toc-train-a-decision-tree-to-classify-genre" class="nav-link" data-scroll-target="#train-a-decision-tree-to-classify-genre">8. Train a decision tree to classify genre</a></li>
  <li><a href="#compare-our-decision-tree-to-a-logistic-regression" id="toc-compare-our-decision-tree-to-a-logistic-regression" class="nav-link" data-scroll-target="#compare-our-decision-tree-to-a-logistic-regression">9. Compare our decision tree to a logistic regression</a></li>
  <li><a href="#balance-our-data-for-greater-performance" id="toc-balance-our-data-for-greater-performance" class="nav-link" data-scroll-target="#balance-our-data-for-greater-performance">10. Balance our data for greater performance</a></li>
  <li><a href="#does-balancing-our-dataset-improve-model-bias" id="toc-does-balancing-our-dataset-improve-model-bias" class="nav-link" data-scroll-target="#does-balancing-our-dataset-improve-model-bias">11. Does balancing our dataset improve model bias?</a></li>
  <li><a href="#using-cross-validation-to-evaluate-our-models" id="toc-using-cross-validation-to-evaluate-our-models" class="nav-link" data-scroll-target="#using-cross-validation-to-evaluate-our-models">12. Using cross-validation to evaluate our models</a></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways">Key takeaways</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="project-overview" class="level2">
<h2 class="anchored" data-anchor-id="project-overview">Project overview</h2>
<p>Using a dataset comprised of songs of two music genres (Hip-Hop and Rock), we will train a classifier to distinguish between the two genres based only on track information derived from <a href="https://music.us/supporters/echo-nest/">Echonest</a> (now part of Spotify). We will first make use of pandas packages in Python for subsetting the data, aggregating information, and creating plots when exploring the data for obvious trends or factors we should be aware of when doing machine learning.</p>
<p>Next, we will use the scikit-learn package to predict whether we can correctly classify a song’s genre based on features such as danceability, energy, acousticness, tempo, etc. We will go over implementations of common algorithms such as PCA, logistic regression, decision trees, and so forth.</p>
<p><img src="hip_hop.jpg" width="450" height="250"> <img src="rock.jpg" width="450" height="250"></p>
<section id="project-tasks" class="level3">
<h3 class="anchored" data-anchor-id="project-tasks">Project Tasks</h3>
<ol type="1">
<li>Preparing our dataset</li>
<li>Pairwise relationships between continuous variables</li>
<li>Splitting our data</li>
<li>Normalizing the feature data</li>
<li>Principal Component Analysis on our scaled data</li>
<li>Further visualization of PCA</li>
<li>Projecting on to our features</li>
<li>Train a decision tree to classify genre</li>
<li>Compare our decision tree to a logistic regression</li>
<li>Balance our data for greater performance</li>
<li>Does balancing our dataset improve model bias?</li>
<li>Using cross-validation to evaluate our models</li>
</ol>
</section>
</section>
<section id="preparing-our-dataset" class="level2">
<h2 class="anchored" data-anchor-id="preparing-our-dataset">1. Preparing our dataset</h2>
<p>Over the past few years, streaming services with huge catalogs have become the primary means through which most people listen to their favorite music. But at the same time, the sheer amount of music on offer can mean users might be a bit overwhelmed when trying to look for newer music that suits their tastes.</p>
<p>For this reason, streaming services have looked into means of categorizing music to allow for personalized recommendations. One method involves direct analysis of the raw audio information in a given song, scoring the raw data on a variety of metrics. Today, we’ll be examining data compiled by a research group known as The Echo Nest. Our goal is to look through this dataset and classify songs as being either ‘Hip-Hop’ or ‘Rock’ - all without listening to a single one ourselves. In doing so, we will learn how to clean our data, do some exploratory data visualization, and use feature reduction towards the goal of feeding our data through some simple machine learning algorithms, such as decision trees and logistic regression.</p>
<p>To begin with, let’s load the metadata about our tracks alongside the track metrics compiled by The Echo Nest. A song is about more than its title, artist, and number of listens. We have another dataset that has musical features of each track such as danceability and acousticness on a scale from -1 to 1. These exist in two different files, which are in different formats - CSV and JSON. While CSV is a popular file format for denoting tabular data, <strong><a href="https://www.json.org/json-en.html">JSON</a></strong> (JavaScript Object Notation) is another common file format in which databases often return the results of a given query.</p>
<p>Let’s start by creating two pandas DataFrames out of these files that we can merge so we have features and labels (often also referred to as X and y) for the classification later on.</p>
<div class="cell" data-execution_count="116">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in the file with the track metadata </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>tracks <span class="op">=</span> pd.read_csv(<span class="st">'Data/fma-rock-vs-hiphop.csv'</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in JSON file with track metrics with the track acoustic metrics</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>echonest_metrics <span class="op">=</span> pd.read_json(<span class="st">'Data/echonest-metrics.json'</span>,precise_float<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the DataFrames on matching track_id values </span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Only retain genre_top columns of tracks (in addition to the key column that we are matching on</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>echo_tracks <span class="op">=</span> echonest_metrics.merge(tracks[[<span class="st">'genre_top'</span>,<span class="st">'track_id'</span>]],on<span class="op">=</span><span class="st">'track_id'</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect the resultant dataframe</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>echo_tracks.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
Int64Index: 4802 entries, 0 to 4801
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   track_id          4802 non-null   int64  
 1   acousticness      4802 non-null   float64
 2   danceability      4802 non-null   float64
 3   energy            4802 non-null   float64
 4   instrumentalness  4802 non-null   float64
 5   liveness          4802 non-null   float64
 6   speechiness       4802 non-null   float64
 7   tempo             4802 non-null   float64
 8   valence           4802 non-null   float64
 9   genre_top         4802 non-null   object 
dtypes: float64(8), int64(1), object(1)
memory usage: 412.7+ KB</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Pandas documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html">read_csv</a><br>
<a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html">read_json</a><br>
<a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html">pd.merge</a></p>
</div>
</div>
<p>So our <strong>dependent variable</strong> or <strong><em>target</em></strong> is <em>genre_top</em> and our 8 <strong>independent variables</strong> or <strong><em>features</em></strong> are:</p>
<pre><code>- acousticness
- danceability
- energy
- instrumentalness
- liveness
- speechiness
- tempo
- valence</code></pre>
<p>The <em>track_id</em> is not really a feature and so we will drop that in due course.</p>
</section>
<section id="pairwise-relationships-between-continuous-variables" class="level2">
<h2 class="anchored" data-anchor-id="pairwise-relationships-between-continuous-variables">2. Pairwise relationships between continuous variables</h2>
<p>We typically want to avoid using variables that have strong correlations with each other – hence avoiding feature redundancy – for a few reasons:</p>
<ul>
<li>To keep the model simple and improve interpretability (with many features, we run the risk of overfitting).</li>
<li>When our datasets are very large, using fewer features can drastically speed up our computation time.</li>
</ul>
<p>We can visually inspect the correlation between the features by creating a correlation matrix using pandas.</p>
<div class="cell" data-execution_count="117">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>corr_metrics <span class="op">=</span> echo_tracks.corr()</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>corr_metrics.style.background_gradient()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_116/408970472.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr_metrics = echo_tracks.corr()</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="117">
<style type="text/css">
#T_e360a_row0_col0, #T_e360a_row1_col1, #T_e360a_row2_col2, #T_e360a_row3_col3, #T_e360a_row4_col4, #T_e360a_row5_col5, #T_e360a_row6_col6, #T_e360a_row7_col7, #T_e360a_row8_col8 {
  background-color: #023858;
  color: #f1f1f1;
}
#T_e360a_row0_col1, #T_e360a_row1_col0, #T_e360a_row1_col3, #T_e360a_row2_col5, #T_e360a_row2_col7, #T_e360a_row4_col2, #T_e360a_row4_col6, #T_e360a_row4_col8, #T_e360a_row6_col4 {
  background-color: #fff7fb;
  color: #000000;
}
#T_e360a_row0_col2 {
  background-color: #d2d2e7;
  color: #000000;
}
#T_e360a_row0_col3 {
  background-color: #b5c4df;
  color: #000000;
}
#T_e360a_row0_col4 {
  background-color: #f5eef6;
  color: #000000;
}
#T_e360a_row0_col5 {
  background-color: #e9e5f1;
  color: #000000;
}
#T_e360a_row0_col6, #T_e360a_row8_col3 {
  background-color: #d1d2e6;
  color: #000000;
}
#T_e360a_row0_col7, #T_e360a_row1_col7 {
  background-color: #e1dfed;
  color: #000000;
}
#T_e360a_row0_col8, #T_e360a_row3_col6 {
  background-color: #dedcec;
  color: #000000;
}
#T_e360a_row1_col2 {
  background-color: #e0dded;
  color: #000000;
}
#T_e360a_row1_col4, #T_e360a_row4_col1 {
  background-color: #97b7d7;
  color: #000000;
}
#T_e360a_row1_col5, #T_e360a_row2_col4 {
  background-color: #f3edf5;
  color: #000000;
}
#T_e360a_row1_col6, #T_e360a_row6_col1 {
  background-color: #b8c6e0;
  color: #000000;
}
#T_e360a_row1_col8 {
  background-color: #e2dfee;
  color: #000000;
}
#T_e360a_row2_col0, #T_e360a_row5_col0, #T_e360a_row5_col3 {
  background-color: #bdc8e1;
  color: #000000;
}
#T_e360a_row2_col1, #T_e360a_row6_col0, #T_e360a_row7_col0, #T_e360a_row7_col1 {
  background-color: #d0d1e6;
  color: #000000;
}
#T_e360a_row2_col3 {
  background-color: #fbf3f9;
  color: #000000;
}
#T_e360a_row2_col6 {
  background-color: #80aed2;
  color: #f1f1f1;
}
#T_e360a_row2_col8 {
  background-color: #529bc7;
  color: #f1f1f1;
}
#T_e360a_row3_col0, #T_e360a_row7_col3 {
  background-color: #a7bddb;
  color: #000000;
}
#T_e360a_row3_col1 {
  background-color: #f5eff6;
  color: #000000;
}
#T_e360a_row3_col2, #T_e360a_row7_col2 {
  background-color: #fef6fa;
  color: #000000;
}
#T_e360a_row3_col4 {
  background-color: #c4cbe3;
  color: #000000;
}
#T_e360a_row3_col5, #T_e360a_row5_col7 {
  background-color: #dcdaeb;
  color: #000000;
}
#T_e360a_row3_col7 {
  background-color: #adc1dd;
  color: #000000;
}
#T_e360a_row3_col8, #T_e360a_row4_col7 {
  background-color: #d9d8ea;
  color: #000000;
}
#T_e360a_row4_col0 {
  background-color: #f4eef6;
  color: #000000;
}
#T_e360a_row4_col3 {
  background-color: #d2d3e7;
  color: #000000;
}
#T_e360a_row4_col5 {
  background-color: #fdf5fa;
  color: #000000;
}
#T_e360a_row5_col1 {
  background-color: #ced0e6;
  color: #000000;
}
#T_e360a_row5_col2 {
  background-color: #ede8f3;
  color: #000000;
}
#T_e360a_row5_col4, #T_e360a_row6_col7 {
  background-color: #dbdaeb;
  color: #000000;
}
#T_e360a_row5_col6 {
  background-color: #c0c9e2;
  color: #000000;
}
#T_e360a_row5_col8 {
  background-color: #e8e4f0;
  color: #000000;
}
#T_e360a_row6_col2 {
  background-color: #93b5d6;
  color: #000000;
}
#T_e360a_row6_col3, #T_e360a_row6_col5 {
  background-color: #eae6f1;
  color: #000000;
}
#T_e360a_row6_col8 {
  background-color: #bfc9e1;
  color: #000000;
}
#T_e360a_row7_col4 {
  background-color: #c5cce3;
  color: #000000;
}
#T_e360a_row7_col5 {
  background-color: #f0eaf4;
  color: #000000;
}
#T_e360a_row7_col6 {
  background-color: #c8cde4;
  color: #000000;
}
#T_e360a_row7_col8 {
  background-color: #d6d6e9;
  color: #000000;
}
#T_e360a_row8_col0 {
  background-color: #c6cce3;
  color: #000000;
}
#T_e360a_row8_col1 {
  background-color: #cdd0e5;
  color: #000000;
}
#T_e360a_row8_col2 {
  background-color: #4c99c5;
  color: #f1f1f1;
}
#T_e360a_row8_col4 {
  background-color: #efe9f3;
  color: #000000;
}
#T_e360a_row8_col5 {
  background-color: #f7f0f7;
  color: #000000;
}
#T_e360a_row8_col6 {
  background-color: #a5bddb;
  color: #000000;
}
#T_e360a_row8_col7 {
  background-color: #d3d4e7;
  color: #000000;
}
</style>

<table id="T_e360a" data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_e360a_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">track_id</th>
<th id="T_e360a_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">acousticness</th>
<th id="T_e360a_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">danceability</th>
<th id="T_e360a_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">energy</th>
<th id="T_e360a_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">instrumentalness</th>
<th id="T_e360a_level0_col5" class="col_heading level0 col5" data-quarto-table-cell-role="th">liveness</th>
<th id="T_e360a_level0_col6" class="col_heading level0 col6" data-quarto-table-cell-role="th">speechiness</th>
<th id="T_e360a_level0_col7" class="col_heading level0 col7" data-quarto-table-cell-role="th">tempo</th>
<th id="T_e360a_level0_col8" class="col_heading level0 col8" data-quarto-table-cell-role="th">valence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_e360a_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">track_id</td>
<td id="T_e360a_row0_col0" class="data row0 col0">1.000000</td>
<td id="T_e360a_row0_col1" class="data row0 col1">-0.372282</td>
<td id="T_e360a_row0_col2" class="data row0 col2">0.049454</td>
<td id="T_e360a_row0_col3" class="data row0 col3">0.140703</td>
<td id="T_e360a_row0_col4" class="data row0 col4">-0.275623</td>
<td id="T_e360a_row0_col5" class="data row0 col5">0.048231</td>
<td id="T_e360a_row0_col6" class="data row0 col6">-0.026995</td>
<td id="T_e360a_row0_col7" class="data row0 col7">-0.025392</td>
<td id="T_e360a_row0_col8" class="data row0 col8">0.010070</td>
</tr>
<tr class="even">
<td id="T_e360a_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">acousticness</td>
<td id="T_e360a_row1_col0" class="data row1 col0">-0.372282</td>
<td id="T_e360a_row1_col1" class="data row1 col1">1.000000</td>
<td id="T_e360a_row1_col2" class="data row1 col2">-0.028954</td>
<td id="T_e360a_row1_col3" class="data row1 col3">-0.281619</td>
<td id="T_e360a_row1_col4" class="data row1 col4">0.194780</td>
<td id="T_e360a_row1_col5" class="data row1 col5">-0.019991</td>
<td id="T_e360a_row1_col6" class="data row1 col6">0.072204</td>
<td id="T_e360a_row1_col7" class="data row1 col7">-0.026310</td>
<td id="T_e360a_row1_col8" class="data row1 col8">-0.013841</td>
</tr>
<tr class="odd">
<td id="T_e360a_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">danceability</td>
<td id="T_e360a_row2_col0" class="data row2 col0">0.049454</td>
<td id="T_e360a_row2_col1" class="data row2 col1">-0.028954</td>
<td id="T_e360a_row2_col2" class="data row2 col2">1.000000</td>
<td id="T_e360a_row2_col3" class="data row2 col3">-0.242032</td>
<td id="T_e360a_row2_col4" class="data row2 col4">-0.255217</td>
<td id="T_e360a_row2_col5" class="data row2 col5">-0.106584</td>
<td id="T_e360a_row2_col6" class="data row2 col6">0.276206</td>
<td id="T_e360a_row2_col7" class="data row2 col7">-0.242089</td>
<td id="T_e360a_row2_col8" class="data row2 col8">0.473165</td>
</tr>
<tr class="even">
<td id="T_e360a_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">energy</td>
<td id="T_e360a_row3_col0" class="data row3 col0">0.140703</td>
<td id="T_e360a_row3_col1" class="data row3 col1">-0.281619</td>
<td id="T_e360a_row3_col2" class="data row3 col2">-0.242032</td>
<td id="T_e360a_row3_col3" class="data row3 col3">1.000000</td>
<td id="T_e360a_row3_col4" class="data row3 col4">0.028238</td>
<td id="T_e360a_row3_col5" class="data row3 col5">0.113331</td>
<td id="T_e360a_row3_col6" class="data row3 col6">-0.109983</td>
<td id="T_e360a_row3_col7" class="data row3 col7">0.195227</td>
<td id="T_e360a_row3_col8" class="data row3 col8">0.038603</td>
</tr>
<tr class="odd">
<td id="T_e360a_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">instrumentalness</td>
<td id="T_e360a_row4_col0" class="data row4 col0">-0.275623</td>
<td id="T_e360a_row4_col1" class="data row4 col1">0.194780</td>
<td id="T_e360a_row4_col2" class="data row4 col2">-0.255217</td>
<td id="T_e360a_row4_col3" class="data row4 col3">0.028238</td>
<td id="T_e360a_row4_col4" class="data row4 col4">1.000000</td>
<td id="T_e360a_row4_col5" class="data row4 col5">-0.091022</td>
<td id="T_e360a_row4_col6" class="data row4 col6">-0.366762</td>
<td id="T_e360a_row4_col7" class="data row4 col7">0.022215</td>
<td id="T_e360a_row4_col8" class="data row4 col8">-0.219967</td>
</tr>
<tr class="even">
<td id="T_e360a_level0_row5" class="row_heading level0 row5" data-quarto-table-cell-role="th">liveness</td>
<td id="T_e360a_row5_col0" class="data row5 col0">0.048231</td>
<td id="T_e360a_row5_col1" class="data row5 col1">-0.019991</td>
<td id="T_e360a_row5_col2" class="data row5 col2">-0.106584</td>
<td id="T_e360a_row5_col3" class="data row5 col3">0.113331</td>
<td id="T_e360a_row5_col4" class="data row5 col4">-0.091022</td>
<td id="T_e360a_row5_col5" class="data row5 col5">1.000000</td>
<td id="T_e360a_row5_col6" class="data row5 col6">0.041173</td>
<td id="T_e360a_row5_col7" class="data row5 col7">0.002732</td>
<td id="T_e360a_row5_col8" class="data row5 col8">-0.045093</td>
</tr>
<tr class="odd">
<td id="T_e360a_level0_row6" class="row_heading level0 row6" data-quarto-table-cell-role="th">speechiness</td>
<td id="T_e360a_row6_col0" class="data row6 col0">-0.026995</td>
<td id="T_e360a_row6_col1" class="data row6 col1">0.072204</td>
<td id="T_e360a_row6_col2" class="data row6 col2">0.276206</td>
<td id="T_e360a_row6_col3" class="data row6 col3">-0.109983</td>
<td id="T_e360a_row6_col4" class="data row6 col4">-0.366762</td>
<td id="T_e360a_row6_col5" class="data row6 col5">0.041173</td>
<td id="T_e360a_row6_col6" class="data row6 col6">1.000000</td>
<td id="T_e360a_row6_col7" class="data row6 col7">0.008241</td>
<td id="T_e360a_row6_col8" class="data row6 col8">0.149894</td>
</tr>
<tr class="even">
<td id="T_e360a_level0_row7" class="row_heading level0 row7" data-quarto-table-cell-role="th">tempo</td>
<td id="T_e360a_row7_col0" class="data row7 col0">-0.025392</td>
<td id="T_e360a_row7_col1" class="data row7 col1">-0.026310</td>
<td id="T_e360a_row7_col2" class="data row7 col2">-0.242089</td>
<td id="T_e360a_row7_col3" class="data row7 col3">0.195227</td>
<td id="T_e360a_row7_col4" class="data row7 col4">0.022215</td>
<td id="T_e360a_row7_col5" class="data row7 col5">0.002732</td>
<td id="T_e360a_row7_col6" class="data row7 col6">0.008241</td>
<td id="T_e360a_row7_col7" class="data row7 col7">1.000000</td>
<td id="T_e360a_row7_col8" class="data row7 col8">0.052221</td>
</tr>
<tr class="odd">
<td id="T_e360a_level0_row8" class="row_heading level0 row8" data-quarto-table-cell-role="th">valence</td>
<td id="T_e360a_row8_col0" class="data row8 col0">0.010070</td>
<td id="T_e360a_row8_col1" class="data row8 col1">-0.013841</td>
<td id="T_e360a_row8_col2" class="data row8 col2">0.473165</td>
<td id="T_e360a_row8_col3" class="data row8 col3">0.038603</td>
<td id="T_e360a_row8_col4" class="data row8 col4">-0.219967</td>
<td id="T_e360a_row8_col5" class="data row8 col5">-0.045093</td>
<td id="T_e360a_row8_col6" class="data row8 col6">0.149894</td>
<td id="T_e360a_row8_col7" class="data row8 col7">0.052221</td>
<td id="T_e360a_row8_col8" class="data row8 col8">1.000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Pandas documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html">DataFrame.corr</a></p>
</div>
</div>
</section>
<section id="splitting-our-data" class="level2">
<h2 class="anchored" data-anchor-id="splitting-our-data">3. Splitting our data</h2>
<p>As mentioned earlier, it can be particularly useful to simplify our models and use as few features as necessary to achieve the best result. Since we didn’t find any particularly strong correlations between our features, we can now split our data into an array containing our features, and another containing the labels - the genre of the track.</p>
<p>Once we have split the data into these arrays, we will perform some preprocessing steps to optimize our model development.</p>
<div class="cell" data-execution_count="118">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import train_test_split function</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create features by storing all values of the echo_tracks DataFrame except for the "genre_top" and "track_id" columns.</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>features <span class="op">=</span> echo_tracks.drop([<span class="st">"genre_top"</span>,<span class="st">"track_id"</span>],axis<span class="op">=</span><span class="dv">1</span>).values</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create labels</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> echo_tracks[<span class="st">"genre_top"</span>].values</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Split our data</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>train_features, test_features, train_labels, test_labels <span class="op">=</span> train_test_split(features, labels, random_state<span class="op">=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
sci-kit learn documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html">train_test_split</a></p>
</div>
</div>
<p>Let’s take a look at the shape of our features:</p>
<div class="cell" data-execution_count="119">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>train_features.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="119">
<pre><code>(3601, 8)</code></pre>
</div>
</div>
<p>So we have 3,601 rows which represent the individual tracks, and 8 columns which are our features. Let’s have a look at a few of the values for our training features and associated labels:</p>
<div class="cell" data-execution_count="120">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the first 5 train_features</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>train_features[:<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="120">
<pre><code>array([[9.48677459e-01, 1.37199242e-01, 2.47403596e-02, 3.06704890e-03,
        1.20902996e-01, 4.94376494e-02, 2.11283000e+02, 3.81535017e-02],
       [1.02727000e-05, 1.18115308e-01, 7.50281301e-01, 4.93739963e-01,
        1.57670577e-01, 4.45210657e-02, 9.51060000e+01, 3.59604392e-01],
       [3.12262570e-02, 6.28698289e-01, 8.31143855e-01, 1.11037480e-03,
        1.82296940e-01, 6.79014582e-02, 9.70140000e+01, 6.53131979e-01],
       [1.67591241e-02, 3.61955450e-01, 8.72379042e-01, 9.22775365e-01,
        1.51773090e-01, 3.86009300e-02, 1.46546000e+02, 5.32632464e-01],
       [7.52748738e-01, 4.53939425e-01, 4.90570217e-01, 9.66552918e-01,
        8.74566097e-02, 2.58750898e-02, 1.50057000e+02, 3.09709828e-01]])</code></pre>
</div>
</div>
<div class="cell" data-execution_count="121">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the first 5 train_lables</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>train_labels[:<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="121">
<pre><code>array(['Rock', 'Rock', 'Hip-Hop', 'Rock', 'Rock'], dtype=object)</code></pre>
</div>
</div>
<p>Let’s check the mean and standard deviation of our training features dataset:</p>
<div class="cell" data-execution_count="123">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>np.mean(train_features),np.std(train_features)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="123">
<pre><code>(16.185663138852977, 43.42267453551983)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Our training features have a large standard deviation (broad range of values). The danger here is that the larger value features will dominate our model and smaller, but potentially influential features may be disregarded.
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can address this through <strong>normalizing</strong> which in simple terms squeezes the values so that they are more centred around zero. The normalized data will have a mean of zero and a standard deviation of one.</p>
</div>
</div>
</section>
<section id="normalizing-the-feature-data" class="level2">
<h2 class="anchored" data-anchor-id="normalizing-the-feature-data">4. Normalizing the feature data</h2>
<p>As mentioned earlier, it can be particularly useful to simplify our models and use as few features as necessary to achieve the best result. Since we didn’t find any particular strong correlations between our features, we can instead use a common approach to reduce the number of features called <strong><em>principal component analysis (PCA)</em></strong>. A comprehensive coverage of PCA can be found in <a href="https://towardsdatascience.com/a-one-stop-shop-for-principal-component-analysis-5582fb7e0a9c">this article</a> by Matt Brems.</p>
<p>It is possible that the variance between genres can be explained by just a few features in the dataset. PCA rotates the data along the axis of highest variance, thus allowing us to determine the relative contribution of each feature of our data towards the variance between classes. However, since PCA uses the absolute variance of a feature to rotate the data, a feature with a broader range of values will overpower and bias the algorithm relative to the other features. To avoid this, we must first <strong>normalize</strong> our train and test features. There are a few methods to do this, but a common way is through <strong>standardization</strong>, such that all features have a mean = 0 and standard deviation = 1 (the resultant is a <a href="https://en.wikipedia.org/wiki/Standard_score">z-score</a>).</p>
<div class="cell" data-execution_count="124">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import the StandardScaler</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Instantiate the Scaler without passign any agruments</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the fit_transform method to scale train_features and test_features</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>scaled_train_features <span class="op">=</span> scaler.fit_transform(train_features)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>scaled_test_features <span class="op">=</span> scaler.transform(test_features)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
sci-kit learn documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html">StandardScaler</a></p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
To transform test features test it is important to use StandardScaler’s tranform method, <strong><em>after</em></strong> it has been fit to the training features (and potentially transformed them), rather than using fit_transform directly on the test features.
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>Now that we have normalized our data, let’s take a look and see the impact on the feature values:</p>
<div class="cell" data-execution_count="125">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>scaled_train_features[:<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="125">
<pre><code>array([[ 1.24994743, -1.64927931, -2.45820448, -1.60032105, -0.44360329,
        -0.37842314,  2.49377868, -1.55894527],
       [-1.33744998, -1.75457157,  0.5134387 , -0.29343727, -0.19705986,
        -0.41242335, -0.9269891 , -0.34245846],
       [-1.25231142,  1.06248053,  0.8446325 , -1.60553256, -0.03192884,
        -0.25073824, -0.87080909,  0.76835644],
       [-1.29176911, -0.40922633,  1.01352202,  0.84927796, -0.23660521,
        -0.45336354,  0.58763337,  0.31234255],
       [ 0.71557091,  0.09827913, -0.55027614,  0.96587738, -0.6678766 ,
        -0.54136801,  0.69101283, -0.53127759]])</code></pre>
</div>
</div>
<p>Let’s check the mean and standard deviation of our normalized data:</p>
<div class="cell" data-execution_count="126">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>np.mean(scaled_train_features),np.std(scaled_train_features)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="126">
<pre><code>(-6.010804800914205e-16, 1.0)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
That’s much better. Our normalized feature values are all centred around zero (mean is basically zero, and standard deviation is one), thus reducing the risk of a particular feature dominating our model.
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
</section>
<section id="principal-component-analysis-on-our-scaled-data" class="level2">
<h2 class="anchored" data-anchor-id="principal-component-analysis-on-our-scaled-data">5. Principal Component Analysis on our scaled data</h2>
<p><img src="scree.jpg" width="350" height="350"></p>
<p>Now that we have preprocessed our data, we are ready to use PCA to determine by how much we can reduce the dimensionality of our data. We can use <strong><em><a href="https://en.wikipedia.org/wiki/Scree_plot#:~:text=In%20multivariate%20statistics%2C%20a%20scree,principal%20component%20analysis%20(PCA).">scree-plots</a></em></strong> and <strong><em>cumulative explained ratio plots</em></strong> to find the number of components to use in further analyses.</p>
<p>Scree-plots display the number of components against the variance explained by each component, sorted in descending order of variance. Scree-plots help us get a better sense of which components explain a sufficient amount of variance in our data. When using scree plots, an ‘elbow’ (a steep drop from one data point to the next) in the plot is typically used to decide on an appropriate cutoff.</p>
<div class="cell" data-execution_count="127">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This is just to make plots appear in the notebook</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Import our plotting module, and PCA class</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.decomposition <span class="im">import</span> PCA</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Instantiate our PCA class</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>pca <span class="op">=</span> PCA()</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model on our scaled_train_features</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>pca.fit(scaled_train_features)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the number of components</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>components <span class="op">=</span> pca.n_components_</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Retrieve the explained variance ratio</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>exp_variance <span class="op">=</span> pca.explained_variance_ratio_</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the explained variance using a barplot</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>ax.bar(<span class="bu">range</span>(components), exp_variance)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Principal Component #'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="127">
<pre><code>Text(0.5, 0, 'Principal Component #')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Song Genre Classifier_files/figure-html/cell-12-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
sci-kit learn documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html">Principal component analysis</a><br>
</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
matplotlib documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.bar.html">bar plot</a></p>
</div>
</div>
</section>
<section id="further-visualization-of-pca" class="level2">
<h2 class="anchored" data-anchor-id="further-visualization-of-pca">6. Further visualization of PCA</h2>
<p>Unfortunately, there does not appear to be a clear elbow in this scree plot, which means it is not straightforward to find the number of intrinsic dimensions using this method.</p>
<p>But all is not lost! Instead, we can also look at the <strong><em>cumulative explained variance plot</em></strong> to determine how many features are required to explain, say, about 85% of the variance (cutoffs are somewhat arbitrary here, and usually decided upon by ‘rules of thumb’). Once we determine the appropriate number of components, we can perform PCA with that many components, ideally reducing the dimensionality of our data.</p>
<div class="cell" data-execution_count="128">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import numpy</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the cumulative sums of our explained variance</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>cum_exp_variance <span class="op">=</span> np.cumsum(exp_variance)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the cumulative explained variances and look for the no. of components at which we can account for &gt;85% of our variance</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots()</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>ax.plot(<span class="bu">range</span>(components), cum_exp_variance)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw a dashed line at 0.85</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>ax.axhline(y<span class="op">=</span><span class="fl">0.85</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="128">
<pre><code>&lt;matplotlib.lines.Line2D at 0x7f59f340c220&gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Song Genre Classifier_files/figure-html/cell-13-output-2.png" class="img-fluid"></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
numpy documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html">cumsum()</a></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
sklean documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html">PCA</a></p>
</div>
</div>
</section>
<section id="projecting-on-to-our-features" class="level2">
<h2 class="anchored" data-anchor-id="projecting-on-to-our-features">7. Projecting on to our features</h2>
<p>We saw from the plot that 6 features (remember indexing starts at 0) can explain 85% of the variance! Therefore, we can use 6 components to perform PCA and reduce the dimensionality of our train and test features.</p>
<div class="cell" data-execution_count="129">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform PCA with the optimal no. of components from our cumulative explained variance plot</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>pca <span class="op">=</span> PCA(n_components<span class="op">=</span><span class="dv">6</span>,random_state<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit and transform the scaled training features using pca</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>train_pca <span class="op">=</span> pca.fit_transform(scaled_train_features)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit and transform the scaled test features using pca</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>test_pca <span class="op">=</span> pca.fit_transform(scaled_test_features)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="130">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>train_pca.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="130">
<pre><code>(3601, 6)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="131">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the first 5 train_pca</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>train_pca[:<span class="dv">5</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="131">
<pre><code>array([[-0.94683521, -0.98726024,  2.09691406,  1.82221026, -1.88745714,
         2.63086297],
       [-1.16474503,  0.81643176, -0.29364819, -1.2819193 , -0.85195312,
        -0.22963785],
       [ 1.52161734,  1.4246482 , -0.92071409, -1.25676649, -0.10178816,
        -0.07969312],
       [-0.97593229,  1.23672376, -1.10458784,  0.1487983 ,  0.02900411,
        -0.0715869 ],
       [-0.78621628, -1.10767364, -0.34725279,  0.89060792, -0.1259162 ,
         0.3696838 ]])</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Following our Principal Component Analysis and dimensionality reduction, the train and test datasets now only include values for 6 features, reduced from our original 8.
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
</section>
<section id="train-a-decision-tree-to-classify-genre" class="level2">
<h2 class="anchored" data-anchor-id="train-a-decision-tree-to-classify-genre">8. Train a decision tree to classify genre</h2>
<p>Now we can use the lower dimensional PCA projection of the data to classify songs into genres.</p>
<p>Here, we will be using a simple algorithm known as a decision tree. Decision trees are rule-based classifiers that take in features and follow a ‘tree structure’ of binary decisions to ultimately classify a data point into one of two or more categories. In addition to being easy to both use and interpret, decision trees allow us to visualize the ‘logic flowchart’ that the model generates from the training data.</p>
<p>Here is an example of a decision tree that demonstrates the process by which an input image (in this case, of a shape) might be classified based on the number of sides it has and whether it is rotated.</p>
<p><img src="simple_decision_tree.png" width="500" height="300"></p>
<div class="cell" data-execution_count="132">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import Decision tree classifier</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> DecisionTreeClassifier</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Instantiate our DecisionTreeClassifier</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>tree <span class="op">=</span> DecisionTreeClassifier(random_state<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                              </span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit our DecisionTreeClassifier to the training data</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>tree.fit(train_pca, train_labels)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the predicted labels of the test set</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>pred_labels_tree <span class="op">=</span> tree.predict(test_pca)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the first 10 labels</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>pred_labels_tree[:<span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="132">
<pre><code>array(['Rock', 'Hip-Hop', 'Rock', 'Hip-Hop', 'Hip-Hop', 'Rock', 'Hip-Hop',
       'Rock', 'Hip-Hop', 'Rock'], dtype=object)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
scikit-learn documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html">DecisionTreeClassifier</a></p>
</div>
</div>
</section>
<section id="compare-our-decision-tree-to-a-logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="compare-our-decision-tree-to-a-logistic-regression">9. Compare our decision tree to a logistic regression</h2>
<p>Although our tree’s performance is decent, it’s a bad idea to immediately assume that it’s therefore the perfect tool for this job – there’s always the possibility of other models that will perform even better! It’s always a worthwhile idea to at least test a few other algorithms and find the one that’s best for our data.</p>
<p>Sometimes simplest is best, and so we will start by applying <strong><em><a href="https://en.wikipedia.org/wiki/Logistic_regression">logistic regression</a></em></strong>. Logistic regression makes use of what’s called the logistic function to calculate the odds that a given data point belongs to a given class. Once we have both models, we can compare them on a few performance metrics, such as false positive and false negative rate (or how many points are inaccurately classified).</p>
<div class="cell" data-execution_count="133">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import LogisticRegression</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Instantiate our LogisticRegression </span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>logreg <span class="op">=</span> LogisticRegression(random_state<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit our Logistic Regression model to the training data</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>logreg.fit(train_pca, train_labels)</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the predicted labels of the test set</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>pred_labels_logit <span class="op">=</span> logreg.predict(test_pca)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the classification report for both models</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> classification_report</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>class_rep_tree <span class="op">=</span> classification_report(test_labels,pred_labels_tree)</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>class_rep_log <span class="op">=</span> classification_report(test_labels,pred_labels_logit)</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Decision Tree: </span><span class="ch">\n</span><span class="st">"</span>, class_rep_tree)</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Logistic Regression: </span><span class="ch">\n</span><span class="st">"</span>, class_rep_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Decision Tree: 
               precision    recall  f1-score   support

     Hip-Hop       0.52      0.59      0.55       235
        Rock       0.90      0.87      0.88       966

    accuracy                           0.81      1201
   macro avg       0.71      0.73      0.72      1201
weighted avg       0.82      0.81      0.82      1201

Logistic Regression: 
               precision    recall  f1-score   support

     Hip-Hop       0.75      0.55      0.63       235
        Rock       0.90      0.96      0.93       966

    accuracy                           0.88      1201
   macro avg       0.82      0.75      0.78      1201
weighted avg       0.87      0.88      0.87      1201
</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
scikit-learn documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html">LogisticRegression()</a></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
scikit-learn documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html">classification_report()</a></p>
</div>
</div>
</section>
<section id="balance-our-data-for-greater-performance" class="level2">
<h2 class="anchored" data-anchor-id="balance-our-data-for-greater-performance">10. Balance our data for greater performance</h2>
<p>Both our models do well, with the Decision Tree scoring average precision of 82% and Logistic Regression scoring average precision of 87%. However, looking at our classification report, we can see that rock songs are fairly well classified, but hip-hop songs are disproportionately misclassified as rock songs.</p>
<p>Why might this be the case? Well, just by looking at the number of data points we have for each class (966 for rock, 235 for hip-hop) we can see that our data is imbalanced, potentially skewing our model’s ability to distinguish between classes. This also tells us that most of our model’s accuracy is driven by its ability to classify just rock songs, which is less than ideal.</p>
<p>To account for this, we can weight the value of a correct classification in each class inversely to the occurrence of data points for each class. Since a correct classification for “Rock” is not more important than a correct classification for “Hip-Hop” (and vice versa), we only need to account for differences in sample size of our data points when weighting our classes here, and not relative importance of each class.</p>
<div class="cell" data-execution_count="134">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset only the hip-hop tracks, and then only the rock tracks</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>hop_only <span class="op">=</span> echo_tracks.loc[echo_tracks[<span class="st">'genre_top'</span>] <span class="op">==</span> <span class="st">'Hip-Hop'</span>]</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>rock_only <span class="op">=</span> echo_tracks.loc[echo_tracks[<span class="st">'genre_top'</span>] <span class="op">==</span> <span class="st">'Rock'</span>]</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># sample the rocks songs to be the same number as there are hip-hop songs</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>rock_only <span class="op">=</span> rock_only.sample(hop_only.shape[<span class="dv">0</span>],random_state<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="co"># concatenate the dataframes rock_only and hop_only</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>rock_hop_bal <span class="op">=</span> pd.concat([rock_only,hop_only])</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="co"># The features, labels, and pca projection are created for the balanced dataframe</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>features <span class="op">=</span> rock_hop_bal.drop([<span class="st">'genre_top'</span>, <span class="st">'track_id'</span>], axis<span class="op">=</span><span class="dv">1</span>) </span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> rock_hop_bal[<span class="st">'genre_top'</span>]</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Redefine the train and test set with the pca_projection from the balanced data</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>train_features, test_features, train_labels, test_labels <span class="op">=</span> train_test_split(features,labels, random_state<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>train_pca <span class="op">=</span> pca.fit_transform(scaler.fit_transform(train_features))</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>test_pca <span class="op">=</span> pca.transform(scaler.transform(test_features))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
pandas documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html">DataFrame.loc[]</a></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
pandas documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html">concat()</a></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
pandas documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html">DataFrame.sample()</a></p>
</div>
</div>
</section>
<section id="does-balancing-our-dataset-improve-model-bias" class="level2">
<h2 class="anchored" data-anchor-id="does-balancing-our-dataset-improve-model-bias">11. Does balancing our dataset improve model bias?</h2>
<p>We’ve now balanced our dataset, but in doing so, we’ve removed a lot of data points that might have been crucial to training our models. Let’s test to see if balancing our data improves model bias towards the “Rock” classification while retaining overall classification performance. Note that we have already reduced the size of our dataset and will go forward without applying any dimensionality reduction. In practice, we would consider dimensionality reduction more rigorously when dealing with vastly large datasets and when computation times become prohibitively large.</p>
<div class="cell" data-execution_count="135">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Instantiate our DecisionTreeClassifier</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>tree <span class="op">=</span> DecisionTreeClassifier(random_state<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit our DecisionTree Classifier model to the balanced training set</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>tree.fit(train_pca, train_labels)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the predicted labels of the test set</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>pred_labels_tree <span class="op">=</span> tree.predict(test_pca)</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Instantiate our LogisticRegression </span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>logreg <span class="op">=</span> LogisticRegression(random_state<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit our Logistic Regression model to the balanced training set</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>logreg.fit(train_pca, train_labels)</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the predicted labels of the test set</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>pred_labels_logit <span class="op">=</span> logreg.predict(test_pca)</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare the models</span></span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Decision Tree: </span><span class="ch">\n</span><span class="st">"</span>, classification_report(test_labels,pred_labels_tree))</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Logistic Regression: </span><span class="ch">\n</span><span class="st">"</span>, classification_report(test_labels,pred_labels_logit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Decision Tree: 
               precision    recall  f1-score   support

     Hip-Hop       0.82      0.77      0.79       230
        Rock       0.78      0.82      0.80       225

    accuracy                           0.80       455
   macro avg       0.80      0.80      0.80       455
weighted avg       0.80      0.80      0.80       455

Logistic Regression: 
               precision    recall  f1-score   support

     Hip-Hop       0.84      0.80      0.82       230
        Rock       0.81      0.85      0.83       225

    accuracy                           0.82       455
   macro avg       0.82      0.82      0.82       455
weighted avg       0.83      0.82      0.82       455
</code></pre>
</div>
</div>
<p>Success! Balancing our data has removed bias towards the more prevalent class - the precision scores for Hip-Hop and rock are now similar. To get a good sense of how well our models are actually performing, we can apply what’s called <strong><em>cross-validation (CV)</em></strong>. This step allows us to compare models in a more rigorous fashion.</p>
</section>
<section id="using-cross-validation-to-evaluate-our-models" class="level2">
<h2 class="anchored" data-anchor-id="using-cross-validation-to-evaluate-our-models">12. Using cross-validation to evaluate our models</h2>
<p>Before we can perform cross-validation we will need to create pipelines to scale our data, perform PCA, and instantiate our model of choice - DecisionTreeClassifier or LogisticRegression.</p>
<p>Since the way our data is split into train and test sets can impact model performance, CV attempts to split the data multiple ways and test the model on each of the splits. Although there are many different CV methods, all with their own advantages and disadvantages, we will use what’s known as <strong><em>K-fold CV</em></strong> here. K-fold first splits the data into K different, equally sized subsets. Then, it iteratively uses each subset as a test set while using the remainder of the data as train sets. Finally, we can then aggregate the results from each fold for a final model performance score.</p>
<div class="cell" data-execution_count="136">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> KFold, cross_val_score</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.pipeline <span class="im">import</span> Pipeline</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>tree_pipe <span class="op">=</span> Pipeline([(<span class="st">"scaler"</span>, StandardScaler()), (<span class="st">"pca"</span>, PCA(n_components<span class="op">=</span><span class="dv">5</span>)), </span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>                      (<span class="st">"tree"</span>, DecisionTreeClassifier(random_state<span class="op">=</span><span class="dv">10</span>))])</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>logreg_pipe <span class="op">=</span> Pipeline([(<span class="st">"scaler"</span>, StandardScaler()), (<span class="st">"pca"</span>, PCA(n_components<span class="op">=</span><span class="dv">5</span>)), </span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>                        (<span class="st">"logreg"</span>, LogisticRegression(random_state<span class="op">=</span><span class="dv">10</span>))])</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up our K-fold cross-validation with 10 folds</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>kf <span class="op">=</span> KFold(n_splits<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Train our models using KFold cv</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>tree_score <span class="op">=</span> cross_val_score(tree_pipe, features,labels,cv<span class="op">=</span>kf)</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>logit_score <span class="op">=</span> cross_val_score(logreg_pipe, features,labels,cv<span class="op">=</span>kf)</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the mean of each array of scores</span></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Decision Tree:"</span>, np.mean(tree_score), <span class="st">"Logistic Regression:"</span>, np.mean(logit_score))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Decision Tree: 0.7417582417582418 Logistic Regression: 0.7835164835164835</code></pre>
</div>
</div>
<p>So our final performance scores are:</p>
<pre><code>- Decision Tree 74.2%
- Logistic Regression 78.4%</code></pre>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
sklearn documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html">KFold()</a></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
sklearn documentation
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html#sklearn.model_selection.cross_val_score">cross_val_score()</a></p>
</div>
</div>
</section>
<section id="key-takeaways" class="level2">
<h2 class="anchored" data-anchor-id="key-takeaways">Key takeaways</h2>
<p>In this project we learned how to:</p>
<ul>
<li>load in two different file types, csv and json, using pandas <strong>pd.read</strong></li>
<li>merge two datasets using pandas <strong>.merge</strong></li>
<li>explore and visulaize the relationship between continuous variables using pandas <strong>.corr()</strong></li>
<li>split our data into a training and test set using scikit-learn <strong>train_test_split</strong></li>
<li>normalize our data using <strong>StandardScaler</strong> from scikit-learn</li>
<li>improve model performance by reducing the dimensionality of our data via <strong>Principle Component Analysis</strong></li>
<li>visualize feature importance using <strong>scree</strong> and <strong>cumulative explained variance</strong> plots</li>
<li>train a Decison Tree and Logistic Regression model</li>
<li>enhance model performance by <strong>balancing</strong> our data</li>
<li>evaluate model performance using <strong>cross-validation</strong></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>